/**
 * EatVera — Comprehensive Alcohol Guide Database
 *
 * Covers spirits, wines, beers, and cocktails with quality ratings based on:
 * - ABV (alcohol by volume)
 * - Sugar content
 * - Additives & artificial ingredients
 * - Calorie density
 * - Health impact score (1–100)
 *
 * Quality Score Tiers:
 * - 80–100: Premium/clean (minimal additives, lower sugar)
 * - 60–79: Good (moderate quality, some additives)
 * - 40–59: Fair (higher sugar/additives, less ideal)
 * - 1–39: Poor (high sugar, many additives, artificial sweeteners)
 */

export interface AlcoholProduct {
  id: string;
  imageUrl?: string;
  name: string;
  type: "spirit" | "wine" | "beer" | "cocktail" | "cider" | "liqueur";
  category: string;
  brand?: string;
  abv: number;
  servingSize: string;
  caloriesPerServing: number;
  sugarPerServing: number;
  carbs: number;
  hasArtificialSweeteners: boolean;
  additives: string[];
  qualityScore: number;
  scoreLabel: "Poor" | "Fair" | "Good" | "Premium";
  healthNotes: string;
  averagePrice?: number;
  bestFor?: string;
  alternatives?: string[];
}

export const ALL_SPIRITS: AlcoholProduct[] = [
  {
    id: "vodka-grey-goose",
    name: "Grey Goose Vodka",
    imageUrl: "/manus-storage/grey_goose_vodka_170bab19.jpg",
    type: "spirit",
    category: "Vodka",
    brand: "Grey Goose",
    abv: 40,
    servingSize: "1.5 oz",
    caloriesPerServing: 97,
    sugarPerServing: 0,
    carbs: 0,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 85,
    scoreLabel: "Premium",
    healthNotes: "Clean, no sugar. Moderate calories. Best mixed with sugar-free mixers.",
  },
  {
    id: "vodka-smirnoff",
    name: "Smirnoff Vodka",
    imageUrl: "/manus-storage/smirnoff_vodka_ae0cb3f5.jpg",
    type: "spirit",
    category: "Vodka",
    brand: "Smirnoff",
    abv: 40,
    servingSize: "1.5 oz",
    caloriesPerServing: 97,
    sugarPerServing: 0,
    carbs: 0,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 75,
    scoreLabel: "Good",
    healthNotes: "No sugar, but less premium than Grey Goose. Good budget option.",
  },
  {
    id: "rum-bacardi",
    name: "Bacardi Superior Rum",
    imageUrl: "/manus-storage/bacardi_superior_rum_aa898b1a.jpg",
    type: "spirit",
    category: "Rum",
    brand: "Bacardi",
    abv: 40,
    servingSize: "1.5 oz",
    caloriesPerServing: 97,
    sugarPerServing: 0,
    carbs: 0,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 70,
    scoreLabel: "Good",
    healthNotes: "Clean rum, no sugar. Good for mojitos with fresh lime and minimal sugar.",
  },
  {
    id: "rum-captain-morgan",
    name: "Captain Morgan Spiced Rum",
    imageUrl: "/manus-storage/captain_morgan_spiced_rum_e6d6655c.jpg",
    type: "spirit",
    category: "Rum",
    brand: "Captain Morgan",
    abv: 35,
    servingSize: "1.5 oz",
    caloriesPerServing: 86,
    sugarPerServing: 2.5,
    carbs: 2.5,
    hasArtificialSweeteners: false,
    additives: ["caramel coloring", "spice extracts"],
    qualityScore: 55,
    scoreLabel: "Fair",
    healthNotes: "Added sugar and spice extracts. Less ideal than white rum.",
  },
  {
    id: "gin-tanqueray",
    name: "Tanqueray Gin",
    imageUrl: "/manus-storage/tanqueray_gin_93042022.jpg",
    type: "spirit",
    category: "Gin",
    brand: "Tanqueray",
    abv: 47.3,
    servingSize: "1.5 oz",
    caloriesPerServing: 110,
    sugarPerServing: 0,
    carbs: 0,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 82,
    scoreLabel: "Premium",
    healthNotes: "Clean, no sugar. Higher ABV means fewer drinks needed.",
  },
  {
    id: "whiskey-jack-daniels",
    name: "Jack Daniel's Tennessee Whiskey",
    imageUrl: "/manus-storage/jack_daniel_s_tennessee_whiskey_bottle_953c5d58.png",
    type: "spirit",
    category: "Whiskey",
    brand: "Jack Daniel's",
    abv: 40,
    servingSize: "1.5 oz",
    caloriesPerServing: 97,
    sugarPerServing: 0.1,
    carbs: 0.1,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 78,
    scoreLabel: "Good",
    healthNotes: "Minimal sugar, good for neat or on rocks.",
  },
  {
    id: "whiskey-makers-mark",
    name: "Maker's Mark Bourbon",
    imageUrl: "/manus-storage/maker_s_mark_bourbon_55595c1a.jpg",
    type: "spirit",
    category: "Whiskey",
    brand: "Maker's Mark",
    abv: 45,
    servingSize: "1.5 oz",
    caloriesPerServing: 105,
    sugarPerServing: 0,
    carbs: 0,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 80,
    scoreLabel: "Premium",
    healthNotes: "Clean bourbon, no sugar. Smooth and balanced.",
  },
  {
    id: "tequila-patron",
    name: "Patrón Silver Tequila",
    imageUrl: "/manus-storage/patr_n_silver_tequila_70354500.jpg",
    type: "spirit",
    category: "Tequila",
    brand: "Patrón",
    abv: 40,
    servingSize: "1.5 oz",
    caloriesPerServing: 97,
    sugarPerServing: 0,
    carbs: 0,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 85,
    scoreLabel: "Premium",
    healthNotes: "100% agave, no additives. Excellent quality.",
  },
  {
    id: "tequila-jose-cuervo",
    name: "José Cuervo Gold Tequila",
    imageUrl: "/manus-storage/jos_cuervo_gold_tequila_d5458924.jpg",
    type: "spirit",
    category: "Tequila",
    brand: "José Cuervo",
    abv: 38,
    servingSize: "1.5 oz",
    caloriesPerServing: 91,
    sugarPerServing: 1.2,
    carbs: 1.2,
    hasArtificialSweeteners: false,
    additives: ["caramel coloring"],
    qualityScore: 50,
    scoreLabel: "Fair",
    healthNotes: "Not 100% agave, added sugar and coloring. Choose silver instead.",
  },
];

export const ALL_WINES: AlcoholProduct[] = [
  {
    id: "wine-red-cabernet",
    name: "Cabernet Sauvignon (Red Wine)",
    imageUrl: "/manus-storage/cabernet_sauvignon_red_wine_fec57cff.png",
    type: "wine",
    category: "Red Wine",
    abv: 13.5,
    servingSize: "5 oz",
    caloriesPerServing: 120,
    sugarPerServing: 0.9,
    carbs: 3.7,
    hasArtificialSweeteners: false,
    additives: ["sulfites"],
    qualityScore: 78,
    scoreLabel: "Good",
    healthNotes: "Moderate sugar, rich in resveratrol. Sulfites are natural preservatives.",
  },
  {
    id: "wine-red-pinot",
    name: "Pinot Noir (Red Wine)",
    imageUrl: "/manus-storage/pinot_noir_red_wine_9be13dd0.jpg",
    type: "wine",
    category: "Red Wine",
    abv: 13,
    servingSize: "5 oz",
    caloriesPerServing: 115,
    sugarPerServing: 0.7,
    carbs: 3.4,
    hasArtificialSweeteners: false,
    additives: ["sulfites"],
    qualityScore: 80,
    scoreLabel: "Premium",
    healthNotes: "Lower sugar than Cabernet. Light and elegant.",
  },
  {
    id: "wine-white-chardonnay",
    name: "Chardonnay (White Wine)",
    imageUrl: "/manus-storage/chardonnay_white_wine_2ee691e9.jpg",
    type: "wine",
    category: "White Wine",
    abv: 13.5,
    servingSize: "5 oz",
    caloriesPerServing: 120,
    sugarPerServing: 1.4,
    carbs: 3.9,
    hasArtificialSweeteners: false,
    additives: ["sulfites"],
    qualityScore: 75,
    scoreLabel: "Good",
    healthNotes: "Slightly higher sugar than red wine. Crisp and versatile.",
  },
  {
    id: "wine-white-sauvignon-blanc",
    name: "Sauvignon Blanc (White Wine)",
    imageUrl: "/manus-storage/sauvignon_blanc_white_wine_1406d646.jpg",
    type: "wine",
    category: "White Wine",
    abv: 12.5,
    servingSize: "5 oz",
    caloriesPerServing: 110,
    sugarPerServing: 1.5,
    carbs: 3.8,
    hasArtificialSweeteners: false,
    additives: ["sulfites"],
    qualityScore: 76,
    scoreLabel: "Good",
    healthNotes: "Crisp, lower alcohol. Good for daytime drinking.",
  },
  {
    id: "wine-sparkling-prosecco",
    name: "Prosecco (Sparkling Wine)",
    imageUrl: "/manus-storage/prosecco_sparkling_wine_832d86e0.jpg",
    type: "wine",
    category: "Sparkling Wine",
    abv: 11,
    servingSize: "5 oz",
    caloriesPerServing: 95,
    sugarPerServing: 1.5,
    carbs: 2.6,
    hasArtificialSweeteners: false,
    additives: ["sulfites"],
    qualityScore: 72,
    scoreLabel: "Good",
    healthNotes: "Lower alcohol and calories. Good for celebrations.",
  },
  {
    id: "wine-dessert-port",
    name: "Port Wine (Dessert)",
    imageUrl: "/manus-storage/port_wine_dessert_de8c71fc.jpg",
    type: "wine",
    category: "Dessert Wine",
    abv: 20,
    servingSize: "3 oz",
    caloriesPerServing: 130,
    sugarPerServing: 7,
    carbs: 7,
    hasArtificialSweeteners: false,
    additives: ["sulfites"],
    qualityScore: 45,
    scoreLabel: "Fair",
    healthNotes: "High sugar and alcohol. Use as occasional dessert drink only.",
  },
];

export const ALL_BEERS: AlcoholProduct[] = [
  {
    id: "beer-ipa-sierra-nevada",
    name: "Sierra Nevada IPA",
    imageUrl: "/manus-storage/sierra_nevada_ipa_550c77da.jpg",
    type: "beer",
    category: "IPA",
    brand: "Sierra Nevada",
    abv: 6.7,
    servingSize: "12 oz",
    caloriesPerServing: 175,
    sugarPerServing: 0,
    carbs: 14,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 75,
    scoreLabel: "Good",
    healthNotes: "Craft beer, no added sugars. Moderate calories.",
  },
  {
    id: "beer-lager-corona",
    name: "Corona Extra",
    imageUrl: "/manus-storage/corona_extra_dd6d856a.jpg",
    type: "beer",
    category: "Lager",
    brand: "Corona",
    abv: 4.6,
    servingSize: "12 oz",
    caloriesPerServing: 148,
    sugarPerServing: 0,
    carbs: 13,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 70,
    scoreLabel: "Good",
    healthNotes: "Light lager, lower calories. Good for warm weather.",
  },
  {
    id: "beer-lager-bud-light",
    name: "Bud Light",
    imageUrl: "/manus-storage/bud_light_5a593872.png",
    type: "beer",
    category: "Light Lager",
    brand: "Budweiser",
    abv: 4.2,
    servingSize: "12 oz",
    caloriesPerServing: 110,
    sugarPerServing: 0,
    carbs: 6.6,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 55,
    scoreLabel: "Fair",
    healthNotes: "Low calories but less flavor. Highly processed.",
  },
  {
    id: "beer-stout-guinness",
    name: "Guinness Draught",
    imageUrl: "/manus-storage/guinness_draught_c406a6f7.png",
    type: "beer",
    category: "Stout",
    brand: "Guinness",
    abv: 4.2,
    servingSize: "12 oz",
    caloriesPerServing: 125,
    sugarPerServing: 0,
    carbs: 10,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 72,
    scoreLabel: "Good",
    healthNotes: "Rich flavor, moderate calories. Contains antioxidants.",
  },
  {
    id: "beer-pilsner-stella-artois",
    name: "Stella Artois",
    imageUrl: "/manus-storage/stella_artois_c3371d48.jpg",
    type: "beer",
    category: "Pilsner",
    brand: "Stella Artois",
    abv: 5.2,
    servingSize: "12 oz",
    caloriesPerServing: 152,
    sugarPerServing: 0,
    carbs: 10.6,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 73,
    scoreLabel: "Good",
    healthNotes: "Premium pilsner, clean taste. Moderate calories.",
  },
];

export const ALL_COCKTAILS: AlcoholProduct[] = [
  {
    id: "cocktail-margarita-classic",
    name: "Classic Margarita",
    imageUrl: "/manus-storage/classic_margarita_0a6f2ed6.jpg",
    type: "cocktail",
    category: "Margarita",
    abv: 33,
    servingSize: "5.5 oz",
    caloriesPerServing: 168,
    sugarPerServing: 6,
    carbs: 6,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 70,
    scoreLabel: "Good",
    healthNotes: "Made with tequila, lime, and triple sec. Request less simple syrup.",
  },
  {
    id: "cocktail-mojito",
    name: "Mojito",
    imageUrl: "/manus-storage/mojito_df3b4ad9.png",
    type: "cocktail",
    category: "Mojito",
    abv: 14,
    servingSize: "8 oz",
    caloriesPerServing: 143,
    sugarPerServing: 12,
    carbs: 12,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 65,
    scoreLabel: "Good",
    healthNotes: "Fresh mint and lime. Request minimal simple syrup.",
  },
  {
    id: "cocktail-daiquiri-frozen",
    name: "Frozen Daiquiri",
    imageUrl: "/manus-storage/frozen_daiquiri_d99fdada.jpg",
    type: "cocktail",
    category: "Daiquiri",
    abv: 12,
    servingSize: "8 oz",
    caloriesPerServing: 225,
    sugarPerServing: 28,
    carbs: 28,
    hasArtificialSweeteners: false,
    additives: ["high fructose corn syrup (typical bar mix)"],
    qualityScore: 35,
    scoreLabel: "Poor",
    healthNotes: "Very high sugar from mix. Request fresh lime juice instead.",
  },
  {
    id: "cocktail-cosmopolitan",
    name: "Cosmopolitan",
    imageUrl: "/manus-storage/cosmopolitan_8c2bb05c.jpg",
    type: "cocktail",
    category: "Cosmopolitan",
    abv: 32,
    servingSize: "4 oz",
    caloriesPerServing: 146,
    sugarPerServing: 4,
    carbs: 4,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 68,
    scoreLabel: "Good",
    healthNotes: "Vodka-based with cranberry juice. Moderate sugar.",
  },
  {
    id: "cocktail-old-fashioned",
    name: "Old Fashioned",
    imageUrl: "/manus-storage/old_fashioned_8f6480ee.jpg",
    type: "cocktail",
    category: "Old Fashioned",
    abv: 43,
    servingSize: "2 oz",
    caloriesPerServing: 154,
    sugarPerServing: 0.5,
    carbs: 0.5,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 82,
    scoreLabel: "Premium",
    healthNotes: "Whiskey, bitters, minimal sugar. Classic and clean.",
  },
  {
    id: "cocktail-pina-colada",
    name: "Piña Colada",
    imageUrl: "/manus-storage/pi_a_colada_c30c954a.jpg",
    type: "cocktail",
    category: "Piña Colada",
    abv: 12,
    servingSize: "6 oz",
    caloriesPerServing: 280,
    sugarPerServing: 32,
    carbs: 32,
    hasArtificialSweeteners: false,
    additives: ["coconut cream (high saturated fat)"],
    qualityScore: 30,
    scoreLabel: "Poor",
    healthNotes: "Very high sugar and fat. Tropical vacation drink only.",
  },
];

export const ALL_CIDERS: AlcoholProduct[] = [
  {
    id: "cider-angry-orchard",
    name: "Angry Orchard Hard Cider",
    imageUrl: "/manus-storage/angry_orchard_hard_cider_8e6f41df.jpg",
    type: "cider",
    category: "Apple Cider",
    brand: "Angry Orchard",
    abv: 5,
    servingSize: "12 oz",
    caloriesPerServing: 180,
    sugarPerServing: 16,
    carbs: 16,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 55,
    scoreLabel: "Fair",
    healthNotes: "Higher sugar than beer. Good for occasional consumption.",
  },
  {
    id: "cider-stella-cidre",
    name: "Stella Artois Cidre",
    imageUrl: "/manus-storage/stella_artois_cidre_cb3cf324.jpg",
    type: "cider",
    category: "Apple Cider",
    brand: "Stella Artois",
    abv: 4.5,
    servingSize: "12 oz",
    caloriesPerServing: 210,
    sugarPerServing: 24,
    carbs: 24,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 50,
    scoreLabel: "Fair",
    healthNotes: "Sweeter than beer. More of a dessert drink.",
  },
];

export const ALL_LIQUEURS: AlcoholProduct[] = [
  {
    id: "liqueur-baileys",
    name: "Baileys Irish Cream",
    imageUrl: "/manus-storage/baileys_irish_cream_7cf0a1cc.jpg",
    type: "liqueur",
    category: "Cream Liqueur",
    brand: "Baileys",
    abv: 17,
    servingSize: "1.5 oz",
    caloriesPerServing: 147,
    sugarPerServing: 11,
    carbs: 11,
    hasArtificialSweeteners: false,
    additives: ["cream", "cocoa"],
    qualityScore: 40,
    scoreLabel: "Poor",
    healthNotes: "High sugar and fat. Treat as dessert, not a drink.",
  },
  {
    id: "liqueur-amaretto",
    name: "Amaretto",
    imageUrl: "/manus-storage/amaretto_620b0d65.jpg",
    type: "liqueur",
    category: "Almond Liqueur",
    brand: "Disaronno",
    abv: 28,
    servingSize: "1.5 oz",
    caloriesPerServing: 129,
    sugarPerServing: 11,
    carbs: 11,
    hasArtificialSweeteners: false,
    additives: [],
    qualityScore: 45,
    scoreLabel: "Fair",
    healthNotes: "Sweet almond flavor, high sugar. Use sparingly.",
  },
];

export const ALL_ALCOHOL = [
  ...ALL_SPIRITS,
  ...ALL_WINES,
  ...ALL_BEERS,
  ...ALL_COCKTAILS,
  ...ALL_CIDERS,
  ...ALL_LIQUEURS,
];

export function getAlcoholById(id: string): AlcoholProduct | undefined {
  return ALL_ALCOHOL.find((a) => a.id === id);
}

export function searchAlcohol(query: string): AlcoholProduct[] {
  const q = query.toLowerCase();
  return ALL_ALCOHOL.filter(
    (a) =>
      a.name.toLowerCase().includes(q) ||
      a.category.toLowerCase().includes(q) ||
      a.brand?.toLowerCase().includes(q)
  );
}

export function filterByType(type: AlcoholProduct["type"]): AlcoholProduct[] {
  return ALL_ALCOHOL.filter((a) => a.type === type);
}

export function filterByQualityScore(minScore: number): AlcoholProduct[] {
  return ALL_ALCOHOL.filter((a) => a.qualityScore >= minScore).sort(
    (a, b) => b.qualityScore - a.qualityScore
  );
}
