/**
 * EatVera — Baby & Kids Food Database
 * 100+ products rated on:
 * - Heavy metal contamination (arsenic, lead, cadmium, mercury)
 * - Added sugars and HFCS
 * - Artificial colors, flavors, preservatives
 * - Pesticide residue risk
 * - Misleading health claims
 * - Organic certification
 * Sources: Healthy Babies Bright Futures (HBBF) 2019/2021 reports, EWG, Consumer Reports, brand labels
 */

export type BabyKidsCategory =
  | "all"
  | "formula"
  | "purees"
  | "pouches"
  | "cereals"
  | "snacks"
  | "meals"
  | "drinks"
  | "toddler";

export type BabyKidsTier = "elite" | "good" | "average" | "poor" | "avoid";

export interface BabyKidsEntry {
  id: string;
  name: string;
  brand: string;
  category: BabyKidsCategory;
  ageRange: string; // e.g., "6+ months", "1-3 years"
  score: number;
  qualityTier: BabyKidsTier;
  barcode?: string;
  // Quality flags
  hasHeavyMetalRisk: boolean; // based on HBBF testing data
  heavyMetalDetails?: string;
  hasAddedSugars: boolean;
  hasArtificialColors: boolean;
  hasArtificialFlavors: boolean;
  hasPreservatives: boolean;
  hasPesticides: boolean;
  hasMisleadingClaims: boolean; // "made with real fruit" but mostly apple juice
  // Positive attributes
  isOrganic: boolean;
  isNonGMO: boolean;
  isLowHeavyMetals: boolean; // tested and confirmed low
  ingredients?: string;
  concerns: string[];
  benefits: string[];
  parentTip: string;
  averagePrice?: number;
  imageUrl?: string;
}

export const BABY_KIDS_TIER_CONFIG: Record<BabyKidsTier, { label: string; color: string; bg: string; border: string }> = {
  elite: { label: "Elite", color: "#145A3A", bg: "#F0FAF2", border: "#b8e8b8" },
  good: { label: "Good", color: "#2d7d9a", bg: "#f0f8ff", border: "#b8d8e8" },
  average: { label: "Average", color: "#d97706", bg: "#fffbf0", border: "#fde68a" },
  poor: { label: "Poor", color: "#dc6803", bg: "#fff7ed", border: "#fed7aa" },
  avoid: { label: "Avoid", color: "#dc2626", bg: "#fff5f5", border: "#fca5a5" },
};

export const BABY_KIDS_CATEGORIES: { id: BabyKidsCategory; label: string; emoji: string }[] = [
  { id: "all", label: "All", emoji: "👶" },
  { id: "formula", label: "Formula", emoji: "🍼" },
  { id: "purees", label: "Purees", emoji: "🥣" },
  { id: "pouches", label: "Pouches", emoji: "🫙" },
  { id: "cereals", label: "Cereals", emoji: "🌾" },
  { id: "snacks", label: "Snacks", emoji: "🍪" },
  { id: "meals", label: "Meals", emoji: "🍽️" },
  { id: "drinks", label: "Drinks", emoji: "🧃" },
  { id: "toddler", label: "Toddler", emoji: "🧒" },
];

export function getBabyKidsColor(score: number): string {
  if (score >= 85) return "#145A3A";
  if (score >= 70) return "#2d7d9a";
  if (score >= 50) return "#d97706";
  if (score >= 30) return "#dc6803";
  return "#dc2626";
}

export const ALL_BABY_KIDS: BabyKidsEntry[] = [
  // ─── FORMULA ──────────────────────────────────────────────────────────────
  {
    id: "bobbie-organic-formula",
    name: "Organic Infant Formula",
    brand: "Bobbie",
    category: "formula",
    ageRange: "0-12 months",
    score: 92,
    qualityTier: "elite",
    barcode: "0850009474022",
    imageUrl: "https://target.scene7.com/is/image/Target/GUEST_bfeb492d-abc2-4c7c-88ec-0c4a130ea7e8?wid=1000&hei=1000",
    hasHeavyMetalRisk: false,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: true,
    ingredients: "Organic Nonfat Milk, Organic Lactose, Organic Whey Protein Concentrate, Organic Palm Oil, Organic Sunflower Oil, Organic Coconut Oil, Organic Soy Oil, DHA, ARA",
    concerns: ["Contains palm oil (environmental concern)", "Soy oil present"],
    benefits: ["USDA Organic certified", "EU-inspired formula standards", "No corn syrup solids", "Whey:casein ratio mirrors breast milk", "No artificial ingredients"],
    parentTip: "One of the cleanest US formulas. Meets EU standards which are stricter than FDA. No corn syrup solids.",
  },
  {
    id: "hipp-organic-formula",
    name: "Organic Combiotic Formula Stage 1",
    brand: "HiPP",
    category: "formula",
    ageRange: "0-6 months",
    score: 95,
    qualityTier: "elite",
    barcode: "4062300291201",
    imageUrl: "/manus-storage/hipp-combiotic-stage1_e233807e.jpg",
    hasHeavyMetalRisk: false,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: true,
    ingredients: "Organic Skimmed Milk, Organic Demineralized Whey, Organic Vegetable Oils, Organic Lactose, Prebiotics (GOS), Probiotics (L. fermentum)",
    concerns: ["European import — verify authenticity", "More expensive"],
    benefits: ["EU Organic certified (stricter than USDA)", "Contains prebiotics (GOS) and probiotics", "No starch or maltodextrin", "Closest to breast milk composition"],
    parentTip: "Gold standard formula. European organic standards are stricter than US. Buy from verified importers only.",
  },
  {
    id: "similac-pro-advance",
    name: "Pro-Advance Infant Formula",
    brand: "Similac",
    category: "formula",
    ageRange: "0-12 months",
    score: 42,
    qualityTier: "poor",
        barcode: "0070074671216",
    imageUrl: "/manus-storage/similac-pro-advance_86c96fee.jpg",
    hasHeavyMetalRisk: false,
    hasAddedSugars: true,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: false,
    isNonGMO: false,
    isLowHeavyMetals: false,
    ingredients: "Nonfat Milk, Lactose, High Oleic Safflower Oil, Soy Oil, Coconut Oil, Galactooligosaccharides, 2'-FL HMO, Corn Syrup",
    concerns: ["Contains corn syrup (added sugar)", "Soy oil (seed oil)", "High oleic safflower oil", "Non-organic — potential pesticide residue", "GMO ingredients"],
    benefits: ["Contains 2'-FL HMO (prebiotic)", "Widely available", "Affordable", "DHA/ARA added"],
    parentTip: "This formula scored in the poor tier because it contains corn syrup as a sweetener (in addition to lactose), soy oil (a seed oil), and high oleic safflower oil. It is also non-organic, which means the ingredients may carry pesticide residue, and it is not Non-GMO verified. The 2'-FL HMO prebiotic is a positive addition, but the corn syrup and seed oil content are what limit the quality score.",
  },
  {
    id: "enfamil-neuropro",
    name: "NeuroPro Infant Formula",
    brand: "Enfamil",
    category: "formula",
    ageRange: "0-12 months",
    score: 40,
    qualityTier: "poor",
    barcode: "0300871214012",
    imageUrl: "https://pics.walgreens.com/prodimg/371456/450.jpg",
    hasHeavyMetalRisk: false,
    hasAddedSugars: true,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: true,
    isOrganic: false,
    isNonGMO: false,
    isLowHeavyMetals: false,
    ingredients: "Nonfat Milk, Lactose, Palm Olein, Soy Oil, Coconut Oil, High Oleic Sunflower Oil, Corn Syrup Solids, MFGM, DHA",
    concerns: ["Corn syrup solids as sweetener", "Multiple seed oils (soy, high oleic sunflower)", "Non-organic", "MFGM claims are marketing-heavy"],
    benefits: ["Contains MFGM and DHA", "Widely available", "Affordable"],
    parentTip: "This formula scored in the poor tier because it contains corn syrup solids as a sweetener, soy oil (a seed oil), and high oleic sunflower oil. It is also non-organic and not Non-GMO verified. The MFGM and DHA additions are positives, but the corn syrup solids and multiple seed oils are the primary factors limiting the quality score.",
  },

  // ─── PUREES & POUCHES ─────────────────────────────────────────────────────
  {
    id: "once-upon-a-farm-pouches",
    name: "Organic Cold-Pressed Baby Food Pouches",
    brand: "Once Upon a Farm",
    category: "pouches",
    ageRange: "4-6 months+",
    score: 90,
    qualityTier: "elite",
        barcode: "0850006468015",
    imageUrl: "/manus-storage/once-upon-a-farm-pouch_500a220a.png",
    hasHeavyMetalRisk: false,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: true,
    ingredients: "Organic Apple, Organic Pear, Organic Spinach, Organic Kale (varies by flavor)",
    concerns: ["Refrigerated — shorter shelf life", "More expensive", "Some flavors have higher sugar from fruit"],
    benefits: ["Cold-pressed preserves nutrients", "USDA Organic", "No heat processing", "Refrigerated (no preservatives needed)", "Low heavy metal risk"],
    parentTip: "Best baby food pouch. Cold-pressed means more nutrients. Keep refrigerated and use within 3 days of opening.",
  },
  {
    id: "serenity-kids-pouches",
    name: "Organic Meat & Veggie Pouches",
    brand: "Serenity Kids",
    category: "pouches",
    ageRange: "6+ months",
    score: 94,
    qualityTier: "elite",
    barcode: "0860002291022",
    imageUrl: "https://i5.walmartimages.com/asr/77475ce9-8909-48da-b2c6-f32fc39dffa0.2494c73782c012fdf9610677d3820613.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff",
    hasHeavyMetalRisk: false,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: true,
    ingredients: "Organic Pasture-Raised Meat (chicken/turkey/beef), Organic Vegetables, Organic Avocado Oil",
    concerns: ["More expensive", "Meat-based may not suit all preferences"],
    benefits: ["Pasture-raised meat as first ingredient", "High protein and healthy fats", "No fruit sugar spikes", "Organic vegetables", "Low heavy metal risk"],
    parentTip: "Best protein-rich baby food. Pasture-raised meat provides iron and zinc critical for brain development.",
  },
  {
    id: "happy-baby-organics-pouches",
    name: "Organic Stage 2 Pouches",
    brand: "Happy Baby Organics",
    category: "pouches",
    ageRange: "6+ months",
    score: 72,
    qualityTier: "good",
    barcode: "0819573010015",
    imageUrl: "https://i5.walmartimages.com/asr/afb50aa9-71da-4d9c-8b1d-5eac1c1174ee.7981b096388121e08159ee687a0f6ed2.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff",
    hasHeavyMetalRisk: true,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: false,
    heavyMetalDetails: "HBBF testing found elevated arsenic in rice-based flavors",
    ingredients: "Organic Fruits, Organic Vegetables, Organic Brown Rice (some flavors)",
    concerns: ["Rice-based flavors tested high for arsenic (HBBF 2021)", "Fruit-heavy = high sugar content", "Shelf-stable = heat processed"],
    benefits: ["USDA Organic", "Non-GMO", "Widely available", "Good variety"],
    parentTip: "Good brand but avoid rice-based flavors due to arsenic risk. Choose fruit+veggie flavors without rice.",
  },
  {
    id: "gerber-purees",
    name: "1st Foods Baby Food Purees",
    brand: "Gerber",
    category: "purees",
    ageRange: "4+ months",
    score: 45,
    qualityTier: "poor",
    barcode: "0015000013517",
    imageUrl: "https://images.openfoodfacts.org/images/products/001/500/018/6951/front_en.3.200.jpg",
    hasHeavyMetalRisk: true,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: true,
    hasMisleadingClaims: false,
    isOrganic: false,
    isNonGMO: false,
    isLowHeavyMetals: false,
    heavyMetalDetails: "Congressional report (2021) found heavy metals in multiple Gerber products",
    ingredients: "Pureed Vegetables or Fruits, Water",
    concerns: ["2021 Congressional report found heavy metals (arsenic, lead, cadmium)", "Non-organic — pesticide residue risk", "Heat processed destroys nutrients", "Non-GMO not verified"],
    benefits: ["Affordable", "Widely available", "Simple ingredients"],
    parentTip: "This baby food scored in the poor tier because a 2021 Congressional investigation found elevated levels of heavy metals (arsenic, lead, and cadmium) in multiple Gerber products above limits considered safe for infants. The products are also non-organic, which increases the risk of pesticide residue. The simple ingredient list is a positive, but the heavy metal findings are the primary factor driving the low quality score.",
  },
  {
    id: "beechnut-organics",
    name: "Organics Stage 1 Purees",
    brand: "Beech-Nut",
    category: "purees",
    ageRange: "4+ months",
    score: 68,
    qualityTier: "good",
        barcode: "0052200010015",
    imageUrl: "/manus-storage/beechnut-organics_8a4a5a9b.jpg",
    hasHeavyMetalRisk: false,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: false,
    ingredients: "Organic Pureed Fruit or Vegetable, Water",
    concerns: ["Some flavors tested for heavy metals", "Heat processed", "Avoid sweet potato and rice flavors"],
    benefits: ["USDA Organic", "Simple 1-2 ingredient formulas", "Non-GMO", "Affordable organic option"],
    parentTip: "Better than Gerber. Stick to non-root vegetable flavors to minimize heavy metal exposure.",
  },

  // ─── CEREALS ──────────────────────────────────────────────────────────────
  {
    id: "happy-baby-oatmeal",
    name: "Organic Oatmeal Baby Cereal",
    brand: "Happy Baby Organics",
    category: "cereals",
    ageRange: "4+ months",
    score: 78,
    qualityTier: "good",
    barcode: "0819573010022",
    imageUrl: "/manus-storage/happy-baby-oatmeal-cereal_5332c8c5.jpg",
    hasHeavyMetalRisk: false,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: true,
    ingredients: "Organic Whole Grain Oat Flour, Organic Oat Bran, Vitamins and Minerals",
    concerns: ["Oats may have glyphosate residue even when organic", "Fortified with synthetic vitamins"],
    benefits: ["Oats have lower arsenic than rice", "USDA Organic", "Iron-fortified (important for babies)", "Non-GMO"],
    parentTip: "Choose oatmeal over rice cereal — oats have significantly lower arsenic levels.",
  },
  {
    id: "gerber-rice-cereal",
    name: "Single-Grain Rice Cereal",
    brand: "Gerber",
    category: "cereals",
    ageRange: "4+ months",
    score: 18,
    qualityTier: "avoid",
        barcode: "0015000012015",
    imageUrl: "/manus-storage/gerber-rice-cereal_14c4f89b.jpg",
    hasHeavyMetalRisk: true,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: false,
    isNonGMO: false,
    isLowHeavyMetals: false,
    heavyMetalDetails: "Rice naturally accumulates arsenic from soil. FDA has proposed limits but not enforced. HBBF found 80% of rice cereals exceed safe arsenic levels.",
    ingredients: "Rice Flour, Calcium Carbonate, Ferric Orthophosphate, Niacinamide, Zinc, Thiamine Mononitrate, Pyridoxine Hydrochloride, Riboflavin, Folic Acid",
    concerns: ["Rice cereal is the #1 source of arsenic exposure for US babies", "80% of rice cereals exceed safe arsenic levels (HBBF)", "Non-organic", "Synthetic vitamin forms"],
    benefits: ["Iron-fortified", "Affordable"],
    parentTip: "This cereal scored in the avoid tier because rice naturally accumulates inorganic arsenic from soil and water. The Healthy Babies Bright Futures (HBBF) organization found that 80% of rice cereals tested exceeded safe arsenic levels for infants. Inorganic arsenic is a known carcinogen and neurotoxin. Oat-based, barley, or multigrain cereals have significantly lower arsenic levels and are recommended as alternatives by pediatric nutrition researchers.",
  },
  {
    id: "earths-best-multigrain",
    name: "Organic Multi-Grain Cereal",
    brand: "Earth's Best",
    category: "cereals",
    ageRange: "4+ months",
    score: 75,
    qualityTier: "good",
    barcode: "0023923300015",
    imageUrl: "https://target.scene7.com/is/image/Target/GUEST_8172b632-3cac-43d2-9fde-f72af139c871?wid=1000&hei=1000",
    hasHeavyMetalRisk: false,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: false,
    ingredients: "Organic Whole Wheat Flour, Organic Oat Flour, Organic Barley Flour, Ferric Orthophosphate, Niacinamide",
    concerns: ["Contains wheat (gluten)", "Some heavy metal risk from barley", "Synthetic iron form"],
    benefits: ["USDA Organic", "Multi-grain = lower arsenic than rice", "Iron-fortified", "No added sugars"],
    parentTip: "Good choice. Multi-grain means lower arsenic exposure than rice-only cereals.",
  },

  // ─── KIDS SNACKS ──────────────────────────────────────────────────────────
  {
    id: "serenity-kids-puffs",
    name: "Grain-Free Puffs",
    brand: "Serenity Kids",
    category: "snacks",
    ageRange: "6+ months",
    score: 88,
    qualityTier: "elite",
        barcode: "0860002291039",
    imageUrl: "/manus-storage/serenity-kids-puffs_b905a1f6.png",
    hasHeavyMetalRisk: false,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: true,
    ingredients: "Organic Cassava Flour, Organic Coconut Flour, Organic Avocado Oil, Sea Salt",
    concerns: ["Cassava is high in carbs"],
    benefits: ["Grain-free (no arsenic risk)", "No added sugars", "Organic", "Clean simple ingredients", "Avocado oil (healthy fat)"],
    parentTip: "Best baby puff. Grain-free means no arsenic risk. Simple clean ingredients.",
  },
  {
    id: "gerber-puffs",
    name: "Graduates Puffs Cereal Snack",
    brand: "Gerber",
    category: "snacks",
    ageRange: "8+ months",
    score: 30,
    qualityTier: "poor",
    barcode: "0015000043515",
    imageUrl: "/manus-storage/gerber-puffs_84975fbd.jpeg",
    hasHeavyMetalRisk: false,
    hasAddedSugars: true,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: true,
    isOrganic: false,
    isNonGMO: false,
    isLowHeavyMetals: false,
    heavyMetalDetails: "Rice flour base — arsenic risk. Congressional report flagged Gerber.",
    ingredients: "Whole Grain Oat Flour, Rice Flour, Sugar, Whole Grain Wheat Flour, Natural Flavor, Niacinamide",
    concerns: ["Rice flour = arsenic risk", "Contains added sugar", "Natural flavors (vague)", "Non-organic", "Congressional heavy metal report"],
    benefits: ["Dissolves easily", "Widely available", "Affordable"],
    parentTip: "This snack scored in the poor tier because the rice flour base poses an arsenic risk (the same concern as rice cereal), it contains added sugar, and Gerber was flagged in a 2021 Congressional report for heavy metals. The natural flavors are also vague and unverified. The product is not organic or Non-GMO verified.",
  },
  {
    id: "plum-organics-puffs",
    name: "Organic Puffs",
    brand: "Plum Organics",
    category: "snacks",
    ageRange: "8+ months",
    score: 62,
    qualityTier: "average",
    barcode: "0846675010015",
    imageUrl: "/manus-storage/plum-organics-puffs_cb035746.jpg",
    hasHeavyMetalRisk: false,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: false,
    heavyMetalDetails: "Organic brown rice flour base — lower arsenic than conventional but still present",
    ingredients: "Organic Brown Rice Flour, Organic Whole Grain Oat Flour, Organic Fruit Puree",
    concerns: ["Organic brown rice flour still has arsenic", "High in carbs", "Fruit puree adds sugar"],
    benefits: ["USDA Organic", "Non-GMO", "No added sugars", "Good taste"],
    parentTip: "Better than Gerber but brown rice flour still has arsenic. Limit frequency.",
  },
  {
    id: "annie-bunny-crackers",
    name: "Organic Bunny Graham Crackers",
    brand: "Annie's",
    category: "snacks",
    ageRange: "2+ years",
    score: 58,
    qualityTier: "average",
        barcode: "0013562000015",
    imageUrl: "/manus-storage/annies-bunny-grahams_99b4c170.jpg",
    hasHeavyMetalRisk: false,
    hasAddedSugars: true,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: true,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: true,
    ingredients: "Organic Wheat Flour, Organic Cane Sugar, Organic Palm Oil, Organic Honey, Organic Cinnamon",
    concerns: ["Contains added sugar (cane sugar + honey)", "Palm oil", "Marketed as healthy but is still a cookie"],
    benefits: ["USDA Organic", "No artificial colors or flavors", "Non-GMO", "No HFCS"],
    parentTip: "Better than conventional graham crackers but still contains sugar. Treat as an occasional snack, not a staple.",
  },
  {
    id: "goldfish-crackers",
    name: "Goldfish Cheddar Crackers",
    brand: "Pepperidge Farm",
    category: "snacks",
    ageRange: "2+ years",
    score: 35,
    qualityTier: "poor",
    barcode: "0014100044208",
    imageUrl: "https://images.openfoodfacts.org/images/products/001/410/007/5233/front_en.97.200.jpg",
    hasHeavyMetalRisk: false,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: true,
    isOrganic: false,
    isNonGMO: false,
    isLowHeavyMetals: true,
    ingredients: "Enriched Wheat Flour, Cheddar Cheese, Vegetable Oils (Canola, Sunflower), Salt, Yeast",
    concerns: ["Canola and sunflower seed oils", "Enriched flour (not whole grain)", "Non-organic", "Highly processed", "Marketed as a staple kids snack"],
    benefits: ["No artificial colors", "Contains real cheese", "Kids love them"],
    parentTip: "This snack scored in the poor tier because it contains canola oil and sunflower oil (both seed oils high in omega-6 linoleic acid) and enriched (refined) wheat flour rather than whole grain flour. It is also not organic or Non-GMO verified. The real cheddar cheese is a positive, but the seed oils and refined flour are what limit the quality score.",
  },

  // ─── KIDS CEREALS ─────────────────────────────────────────────────────────
  {
    id: "seven-sundays-kids",
    name: "Organic Kids Muesli",
    brand: "Seven Sundays",
    category: "cereals",
    ageRange: "2+ years",
    score: 82,
    qualityTier: "good",
        barcode: "0850004758038",
    imageUrl: "/manus-storage/seven-sundays-kids_7603373c.jpg",
    hasHeavyMetalRisk: false,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: true,
    ingredients: "Organic Rolled Oats, Organic Sunflower Seeds, Organic Pumpkin Seeds, Organic Dried Fruit, Organic Coconut",
    concerns: ["Dried fruit adds natural sugars", "Higher cost"],
    benefits: ["No added sugars", "USDA Organic", "Whole food ingredients", "Good fiber and healthy fats"],
    parentTip: "One of the cleanest kids cereals. No added sugar — sweetness comes from dried fruit only.",
  },
  {
    id: "frosted-flakes",
    name: "Frosted Flakes",
    brand: "Kellogg's",
    category: "cereals",
    ageRange: "2+ years",
    score: 12,
    qualityTier: "avoid",
    barcode: "0038000591013",
    imageUrl: "https://images.openfoodfacts.org/images/products/004/119/210/0437/front_en.34.200.jpg",
    hasHeavyMetalRisk: false,
    hasAddedSugars: true,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: true,
    hasPesticides: true,
    hasMisleadingClaims: true,
    isOrganic: false,
    isNonGMO: false,
    isLowHeavyMetals: true,
    ingredients: "Milled Corn, Sugar, Malt Flavor, Salt, BHT (preservative), Niacinamide, Reduced Iron, Zinc, B6, B2, B1, Folic Acid, Vitamin D",
    concerns: ["37% sugar by weight", "BHT preservative (potential carcinogen)", "Glyphosate residue on corn", "Synthetic vitamins only", "Non-GMO not verified", "Highly processed"],
    benefits: ["Fortified with vitamins", "Kids love the taste"],
    parentTip: "This cereal scored in the avoid tier because it is 37% sugar by weight, contains BHT (a synthetic preservative that the National Toxicology Program has listed as reasonably anticipated to be a human carcinogen), and uses non-organic corn that may carry glyphosate residue. The combination of very high sugar content, BHT, and potential pesticide exposure is what drives the very low quality score.",
  },
  {
    id: "lucky-charms",
    name: "Lucky Charms",
    brand: "General Mills",
    category: "cereals",
    ageRange: "2+ years",
    score: 10,
    qualityTier: "avoid",
    barcode: "0016000275287",
    imageUrl: "/manus-storage/lucky-charms_014bee8a.jpg",
    hasHeavyMetalRisk: false,
    hasAddedSugars: true,
    hasArtificialColors: true,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: true,
    hasMisleadingClaims: true,
    isOrganic: false,
    isNonGMO: false,
    isLowHeavyMetals: true,
    ingredients: "Whole Grain Oats, Sugar, Oat Flour, Corn Starch, Modified Corn Starch, Dextrose, Gelatin, FD&C Red #40, FD&C Blue #1, FD&C Yellow #5, FD&C Yellow #6",
    concerns: ["4 artificial dyes (Red 40, Blue 1, Yellow 5, Yellow 6)", "33% sugar", "Glyphosate on oats", "Highly processed marshmallows", "Banned in some European countries due to dyes"],
    benefits: ["Whole grain oats as first ingredient"],
    parentTip: "This cereal scored in the avoid tier because it contains four artificial dyes (FD&C Red #40, Blue #1, Yellow #5, Yellow #6) and is 33% sugar by weight. Multiple studies have found associations between artificial food dyes and increased hyperactivity in children, and the UK Food Standards Agency requires warning labels on products containing these dyes. The dyes are banned or require warning labels in several European countries.",
  },
  {
    id: "cheerios-original",
    name: "Original Cheerios",
    brand: "General Mills",
    category: "cereals",
    ageRange: "1+ years",
    score: 48,
    qualityTier: "poor",
    barcode: "0016000275010",
    imageUrl: "https://i5.walmartimages.com/asr/d9048c30-b874-43ba-a24e-9b7247f60fc8.891c9fc3c662d4e454e0c95d0205852e.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff",
    hasHeavyMetalRisk: false,
    hasAddedSugars: true,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: true,
    hasMisleadingClaims: true,
    isOrganic: false,
    isNonGMO: false,
    isLowHeavyMetals: true,
    ingredients: "Whole Grain Oats, Modified Corn Starch, Sugar, Salt, Calcium Carbonate, Oat Bran, Vitamin E",
    concerns: ["EWG found glyphosate in Cheerios", "Contains added sugar", "Non-organic oats", "Modified corn starch", "\"Heart healthy\" claim is misleading given glyphosate"],
    benefits: ["Whole grain oats", "Low sugar compared to other cereals", "Good finger food for toddlers", "Widely available"],
    parentTip: "This cereal scored in the poor tier because the Environmental Working Group (EWG) found glyphosate (an herbicide classified as a probable human carcinogen by the WHO's IARC) in Cheerios samples. The oats are non-organic, which means they may be treated with glyphosate as a pre-harvest desiccant. It also contains modified corn starch and added sugar. The whole grain oats and low sugar content compared to other kids cereals are positives.",
  },

  // ─── KIDS DRINKS ──────────────────────────────────────────────────────────
  {
    id: "honest-kids-juice",
    name: "Honest Kids Organic Juice Pouches",
    brand: "Honest Kids",
    category: "drinks",
    ageRange: "3+ years",
    score: 52,
    qualityTier: "average",
        barcode: "0657622600015",
    imageUrl: "/manus-storage/honest-kids-juice_cc595d6d.png",
    hasHeavyMetalRisk: false,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: true,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: true,
    ingredients: "Filtered Water, Organic Apple Juice, Organic Fruit Juice Concentrates",
    concerns: ["Still contains 8g sugar per pouch", "Juice spikes blood sugar", "Marketed as healthy but is primarily sugar water", "AAP recommends no juice under age 1"],
    benefits: ["Organic", "No added sugars", "Lower sugar than regular juice", "No artificial ingredients"],
    parentTip: "This juice scored in the average tier because despite being organic and having no added sugars, it still contains 8g of natural sugar per pouch from fruit juice concentrate. The American Academy of Pediatrics (AAP) recommends no juice for children under 1 year, and limits of 4oz/day for ages 1-3. Juice, even organic, lacks the fiber of whole fruit and can contribute to dental cavities and blood sugar spikes.",
  },
  {
    id: "capri-sun",
    name: "Capri Sun Fruit Punch",
    brand: "Capri Sun",
    category: "drinks",
    ageRange: "3+ years",
    score: 15,
    qualityTier: "avoid",
        barcode: "0087684006015",
    imageUrl: "/manus-storage/capri-sun-fruit-punch_0dcd34a1.jpg",
    hasHeavyMetalRisk: false,
    hasAddedSugars: true,
    hasArtificialColors: true,
    hasArtificialFlavors: true,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: true,
    isOrganic: false,
    isNonGMO: false,
    isLowHeavyMetals: true,
    ingredients: "Water, High Fructose Corn Syrup, Apple Juice Concentrate, Citric Acid, Natural Flavor, Vitamin C, Red 40",
    concerns: ["High fructose corn syrup", "Artificial Red 40 dye", "Marketed as juice but mostly HFCS", "16g sugar per pouch", "Artificial flavors"],
    benefits: ["Convenient packaging"],
    parentTip: "This drink scored in the avoid tier because it contains high fructose corn syrup as the primary sweetener, FD&C Red #40 (an artificial dye associated with hyperactivity in children), artificial flavors, and 16g of sugar per pouch. Despite being marketed to children with juice-like branding, the primary sweetener is HFCS rather than fruit juice. These factors are what drive the very low quality score.",
  },

  // ─── TODDLER MEALS ────────────────────────────────────────────────────────
  {
    id: "little-spoon-plates",
    name: "Organic Toddler Plates",
    brand: "Little Spoon",
    category: "toddler",
    ageRange: "12-36 months",
    score: 88,
    qualityTier: "elite",
        barcode: "0850009474039",
    imageUrl: "/manus-storage/little-spoon-plates_0429f86c.png",
    hasHeavyMetalRisk: false,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: true,
    ingredients: "Organic Proteins, Organic Vegetables, Organic Grains, Organic Fats (varies by meal)",
    concerns: ["Subscription model", "Refrigerated — limited shelf life", "More expensive"],
    benefits: ["Fresh refrigerated meals", "USDA Organic", "No preservatives needed", "Nutritionally balanced", "Low heavy metal risk"],
    parentTip: "Best toddler meal delivery. Fresh refrigerated means no preservatives. Nutritionally designed for toddler development.",
  },
  {
    id: "gerber-lil-entrees",
    name: "Lil' Entrees Toddler Meals",
    brand: "Gerber",
    category: "toddler",
    ageRange: "12+ months",
    score: 32,
    qualityTier: "poor",
    barcode: "0015000046615",
    imageUrl: "/manus-storage/gerber-lil-entrees_03758562.jpg",
    hasHeavyMetalRisk: false,
    hasAddedSugars: true,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasPreservatives: true,
    hasPesticides: false,
    hasMisleadingClaims: true,
    isOrganic: false,
    isNonGMO: false,
    isLowHeavyMetals: false,
    heavyMetalDetails: "Gerber flagged in 2021 Congressional report for heavy metals",
    ingredients: "Water, Pasta, Chicken, Vegetables, Modified Corn Starch, Natural Flavors, Sodium Phosphate",
    concerns: ["Heavy metal risk (Congressional report)", "Modified corn starch", "Natural flavors", "Sodium phosphate preservative", "High sodium for toddlers", "Non-organic"],
    benefits: ["Convenient", "Affordable", "Widely available"],
    parentTip: "This toddler meal scored in the poor tier because Gerber was flagged in a 2021 Congressional investigation for heavy metals (arsenic, lead, cadmium) in their products. This meal also contains modified corn starch, sodium phosphate (a preservative), natural flavors, and has high sodium levels for a toddler product. It is also non-organic and not Non-GMO verified. The heavy metal findings are the primary factor driving the low quality score.",
  },
  {
    id: "happy-tot-meals",
    name: "Organic Toddler Meals",
    brand: "Happy Tot",
    category: "toddler",
    ageRange: "12+ months",
    score: 65,
    qualityTier: "good",
    barcode: "0819573010039",
    imageUrl: "/manus-storage/happy-tot-toddler-meals_ee68ff7a.png",
    hasHeavyMetalRisk: false,
    hasAddedSugars: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasPreservatives: false,
    hasPesticides: false,
    hasMisleadingClaims: false,
    isOrganic: true,
    isNonGMO: true,
    isLowHeavyMetals: false,
    ingredients: "Organic Vegetables, Organic Grains, Organic Protein, Organic Spices",
    concerns: ["Some flavors have higher sodium", "Shelf-stable = heat processed", "Some rice-based varieties"],
    benefits: ["USDA Organic", "Non-GMO", "No artificial ingredients", "Convenient shelf-stable"],
    parentTip: "Good organic option. Avoid rice-based varieties. Check sodium — some flavors are high for toddlers.",
  },
];
