/**
 * EatVera — Beverages Database
 * 120+ US grocery store beverages rated on:
 * - Sugar content (HFCS, added sugars)
 * - Artificial sweeteners (aspartame, sucralose, acesulfame-K)
 * - Artificial colors & flavors
 * - Preservatives (sodium benzoate, potassium sorbate)
 * - Phosphoric acid (bone health)
 * - Natural vs processed ingredients
 * Sources: EWG, product labels, brand transparency reports
 */

export type BeverageCategory =
  | "all"
  | "soda"
  | "juice"
  | "sports"
  | "energy"
  | "tea"
  | "coffee"
  | "water"
  | "plant-milk"
  | "kombucha";

export type BeverageQualityTier = "elite" | "good" | "average" | "poor" | "avoid";

export interface BeverageEntry {
  id: string;
  name: string;
  brand: string;
  category: BeverageCategory;
  score: number;
  qualityTier: BeverageQualityTier;
  barcode?: string;
  servingSize?: string;
  // Flags
  hasHFCS: boolean;
  hasArtificialSweeteners: boolean;
  hasArtificialColors: boolean;
  hasArtificialFlavors: boolean;
  hasSodiumBenzoate: boolean;
  hasPhosphoricAcid: boolean;
  isOrganic: boolean;
  isSugarFree: boolean;
  isNaturallySweetened: boolean;
  // Nutrients per serving
  nutrients?: {
    calories?: number;
    sugar?: number;
    sodium?: number;
    caffeine?: number;
};
  ingredients?: string;
  concerns: string[];
  benefits: string[];
  buyTip: string;
  averagePrice?: number;
  imageUrl?: string;
}

export const BEVERAGE_QUALITY_TIER_CONFIG: Record<BeverageQualityTier, { label: string; color: string; bg: string; border: string }> = {
  elite: { label: "Elite", color: "#145A3A", bg: "#F0FAF2", border: "#b8e8b8" },
  good: { label: "Good", color: "#2d7d9a", bg: "#f0f8ff", border: "#b8d8e8" },
  average: { label: "Average", color: "#d97706", bg: "#fffbf0", border: "#fde68a" },
  poor: { label: "Poor", color: "#dc6803", bg: "#fff7ed", border: "#fed7aa" },
  avoid: { label: "Avoid", color: "#dc2626", bg: "#fff5f5", border: "#fca5a5" },
};

export const BEVERAGE_CATEGORIES: { id: BeverageCategory; label: string; emoji: string }[] = [
  { id: "all", label: "All", emoji: "🥤" },
  { id: "soda", label: "Soda", emoji: "🫧" },
  { id: "juice", label: "Juice", emoji: "🍊" },
  { id: "sports", label: "Sports", emoji: "⚡" },
  { id: "energy", label: "Energy", emoji: "🔋" },
  { id: "tea", label: "Tea", emoji: "🍵" },
  { id: "coffee", label: "Coffee", emoji: "☕" },
  { id: "water", label: "Water", emoji: "💧" },
  { id: "plant-milk", label: "Plant Milk", emoji: "🌿" },
  { id: "kombucha", label: "Kombucha", emoji: "🫙" },
];

export function getBeverageColor(score: number): string {
  if (score >= 85) return "#145A3A";
  if (score >= 70) return "#2d7d9a";
  if (score >= 50) return "#d97706";
  if (score >= 30) return "#dc6803";
  return "#dc2626";
}

export const ALL_BEVERAGES: BeverageEntry[] = [
  // ─── SODAS ───────────────────────────────────────────────────────────────
  {
    id: "coca-cola-classic",
    name: "Coca-Cola Classic",
    imageUrl: "/manus-storage/coca_cola_classic_can_6a43336e.jpg",
    brand: "Coca-Cola",
    category: "soda",
    score: 12,
    qualityTier: "avoid",
    barcode: "049000028911",
    servingSize: "12 fl oz",
    hasHFCS: true,
    hasArtificialSweeteners: false,
    hasArtificialColors: true,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: true,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 140, sugar: 39, sodium: 45, caffeine: 34 },
    ingredients: "Carbonated Water, High Fructose Corn Syrup, Caramel Color, Phosphoric Acid, Natural Flavors, Caffeine",
    concerns: [
      "39g of HFCS per can — equivalent to 10 teaspoons of sugar",
      "Phosphoric acid erodes tooth enamel and leaches calcium from bones",
      "Caramel color (4-MEI) is a potential carcinogen",
      "Linked to obesity, type 2 diabetes, and metabolic syndrome",
    ],
    benefits: [],
    buyTip: "This beverage scored very low because High Fructose Corn Syrup is the primary sweetener at 39g per can, equivalent to about 10 teaspoons of sugar. It also contains phosphoric acid, which has been associated with reduced bone mineral density with regular consumption, and Class IV caramel color (4-MEI), which has been flagged by some health agencies as a potential carcinogen.",
    averagePrice: 1.99,
  },
  {
    id: "pepsi-cola",
    name: "Pepsi Cola",
    imageUrl: "/manus-storage/pepsi_cola_can_ab9af7da.jpg",
    brand: "PepsiCo",
    category: "soda",
    score: 12,
    qualityTier: "avoid",
    barcode: "012000001079",
    servingSize: "12 fl oz",
    hasHFCS: true,
    hasArtificialSweeteners: false,
    hasArtificialColors: true,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: true,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 150, sugar: 41, sodium: 30, caffeine: 38 },
    ingredients: "Carbonated Water, High Fructose Corn Syrup, Caramel Color, Phosphoric Acid, Natural Flavor, Caffeine, Citric Acid",
    concerns: [
      "41g HFCS per can — highest sugar among major colas",
      "Phosphoric acid linked to osteoporosis with regular consumption",
      "Caramel color contains 4-MEI (potential carcinogen)",
    ],
    benefits: [],
    buyTip: "This beverage scored very low because High Fructose Corn Syrup is the primary sweetener at 41g per can. It also contains phosphoric acid and Class IV caramel color (4-MEI). The combination of high HFCS content, phosphoric acid, and caramel color is what drives the low quality score.",
    averagePrice: 1.99,
  },
  {
    id: "diet-coke",
    name: "Diet Coke",
    brand: "Coca-Cola",
    category: "soda",
    score: 18,
    qualityTier: "avoid",
    barcode: "049000028942",
    servingSize: "12 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: true,
    hasArtificialColors: true,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: true,
    isOrganic: false,
    isSugarFree: true,
    isNaturallySweetened: false,
    nutrients: { calories: 0, sugar: 0, sodium: 40, caffeine: 46 },
    ingredients: "Carbonated Water, Caramel Color, Aspartame, Phosphoric Acid, Potassium Benzoate, Natural Flavors, Citric Acid, Caffeine",
    concerns: [
      "Aspartame linked to headaches, gut microbiome disruption, and potential neurotoxicity",
      "Potassium benzoate can form benzene (carcinogen) when combined with vitamin C",
      "Phosphoric acid erodes bones and teeth",
      "Studies show diet sodas increase cravings and do not aid weight loss",
    ],
    benefits: ["Zero calories", "Zero sugar"],
    buyTip: "This beverage scored low despite having zero calories because it contains aspartame, an artificial sweetener that some research has linked to gut microbiome disruption and altered insulin response. It also contains potassium benzoate, which can form benzene (a known carcinogen) when exposed to vitamin C, and phosphoric acid, which is associated with reduced bone density with regular consumption.",
    averagePrice: 1.99,
    imageUrl: "/manus-storage/diet-coke_17b7a9a7.jpg",
  },
  {
    id: "sprite",
    name: "Sprite",
    brand: "Coca-Cola",
    category: "soda",
    score: 15,
    qualityTier: "avoid",
    barcode: "049000006582",
    servingSize: "12 fl oz",
    hasHFCS: true,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 140, sugar: 38, sodium: 65, caffeine: 0 },
    ingredients: "Carbonated Water, High Fructose Corn Syrup, Citric Acid, Natural Flavors, Sodium Citrate, Sodium Benzoate",
    concerns: [
      "38g HFCS per can",
      "Sodium benzoate can form benzene in presence of vitamin C",
    ],
    benefits: ["No phosphoric acid", "No artificial colors"],
    buyTip: "This beverage scored low because High Fructose Corn Syrup is the primary sweetener at 38g per can, and it contains sodium benzoate, which can form benzene when combined with vitamin C. The high HFCS content and sodium benzoate are the primary drivers of the low quality score.",
    averagePrice: 1.99,
    imageUrl: "/manus-storage/sprite_684909f9.jpg",
  },
  {
    id: "mountain-dew",
    name: "Mountain Dew",
    brand: "PepsiCo",
    category: "soda",
    score: 8,
    qualityTier: "avoid",
    barcode: "012000001512",
    servingSize: "12 fl oz",
    hasHFCS: true,
    hasArtificialSweeteners: false,
    hasArtificialColors: true,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: true,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 170, sugar: 46, sodium: 60, caffeine: 54 },
    ingredients: "Carbonated Water, HFCS, Concentrated Orange Juice, Citric Acid, Natural Flavor, Sodium Benzoate, Caffeine, Sodium Citrate, Erythorbic Acid, Gum Arabic, Calcium Disodium EDTA, Brominated Vegetable Oil, Yellow 5",
    concerns: [
      "46g HFCS — highest sugar of any major soda",
      "Brominated Vegetable Oil (BVO) — banned in Europe and Japan, linked to thyroid disruption",
      "Yellow 5 (tartrazine) — artificial dye linked to hyperactivity in children",
      "Sodium benzoate + vitamin C = benzene formation",
      "Calcium Disodium EDTA — chelating agent, industrial use",
    ],
    benefits: [],
    buyTip: "This beverage scored extremely low due to several high-concern additives: Brominated Vegetable Oil (BVO), which has been banned in the EU and Japan due to links to thyroid disruption; Yellow 5 (tartrazine), an artificial dye associated with hyperactivity in children; sodium benzoate, which can form benzene; and 46g of HFCS per can — the highest sugar content among major sodas.",
    averagePrice: 1.99,
    imageUrl: "/manus-storage/mountain-dew_3b162c93.jpg",
  },
  {
    id: "dr-pepper",
    name: "Dr Pepper",
    brand: "Keurig Dr Pepper",
    category: "soda",
    score: 13,
    qualityTier: "avoid",
    barcode: "078000001015",
    servingSize: "12 fl oz",
    hasHFCS: true,
    hasArtificialSweeteners: false,
    hasArtificialColors: true,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: true,
    hasPhosphoricAcid: true,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 150, sugar: 40, sodium: 55, caffeine: 41 },
    ingredients: "Carbonated Water, HFCS, Caramel Color, Phosphoric Acid, Natural and Artificial Flavors, Sodium Benzoate, Caffeine",
    concerns: [
      "40g HFCS per can",
      "Phosphoric acid + sodium benzoate combination",
      "Caramel color (4-MEI potential carcinogen)",
    ],
    benefits: [],
    buyTip: "This beverage scored low because it contains 40g of HFCS per can, phosphoric acid, sodium benzoate, and caramel color (4-MEI). The combination of HFCS, two types of preservatives, and caramel color is what drives the low quality score.",
    averagePrice: 1.99,
    imageUrl: "/manus-storage/dr-pepper_65a8b231.jpg",
  },
  {
    id: "olipop-vintage-cola",
    name: "Vintage Cola",
    brand: "OLIPOP",
    category: "soda",
    score: 82,
    qualityTier: "good",
    barcode: "850004540015",
    servingSize: "12 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: true,
    nutrients: { calories: 35, sugar: 2, sodium: 25, caffeine: 50 },
    ingredients: "Sparkling Water, Cassava Root Fiber, Chicory Root Inulin, Jerusalem Artichoke Inulin, Nopal Cactus, Calendula Flower, Marshmallow Root, Stevia Leaf Extract, Natural Flavors",
    concerns: ["Contains stevia (some sensitivity)", "Caffeine from natural sources"],
    benefits: [
      "9g prebiotic fiber per can — feeds beneficial gut bacteria",
      "Only 2g sugar",
      "No HFCS, no artificial sweeteners",
      "Plant-based ingredients",
    ],
    buyTip: "One of the best soda alternatives. High prebiotic fiber content is a genuine health benefit.",
    averagePrice: 1.79,
    imageUrl: "/manus-storage/olipop-vintage-cola_b7890069.jpg",
  },
  {
    id: "poppi-cola",
    name: "Classic Cola",
    brand: "Poppi",
    category: "soda",
    score: 78,
    qualityTier: "good",
    barcode: "850026820015",
    servingSize: "12 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: true,
    nutrients: { calories: 25, sugar: 5, sodium: 10, caffeine: 0 },
    ingredients: "Sparkling Water, Apple Cider Vinegar, Organic Cane Sugar, Natural Flavors, Stevia Leaf Extract",
    concerns: ["Contains stevia", "5g added sugar from cane sugar"],
    benefits: [
      "Apple cider vinegar supports digestion and blood sugar balance",
      "Only 25 calories",
      "No artificial anything",
    ],
    buyTip: "Good soda alternative. The ACV content is a real benefit. Watch serving size — 5g sugar adds up.",
    averagePrice: 1.79,
    imageUrl: "/manus-storage/poppi-cola_f42a3450.jpg",
  },
  {
    id: "jones-soda-cola",
    name: "Jones Cola",
    brand: "Jones Soda",
    category: "soda",
    score: 42,
    qualityTier: "average",
    barcode: "039769002017",
    servingSize: "12 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 150, sugar: 38, sodium: 15, caffeine: 0 },
    ingredients: "Carbonated Water, Pure Cane Sugar, Natural and Artificial Flavors, Caramel Color, Phosphoric Acid, Citric Acid",
    concerns: ["38g cane sugar per can", "Still very high sugar despite no HFCS"],
    benefits: ["No HFCS — uses pure cane sugar", "No artificial colors"],
    buyTip: "Better than Coke/Pepsi (no HFCS), but still 38g sugar. Occasional treat only.",
    averagePrice: 1.99,
    imageUrl: "/manus-storage/jones-soda-cola_569ee545.jpg",
  },

  // ─── JUICES ──────────────────────────────────────────────────────────────
  {
    id: "tropicana-oj",
    name: "Pure Premium Orange Juice",
    brand: "Tropicana",
    category: "juice",
    score: 38,
    qualityTier: "poor",
    barcode: "048500205075",
    servingSize: "8 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 110, sugar: 22, sodium: 0, caffeine: 0 },
    ingredients: "Pasteurized Orange Juice, Flavor Packs (Ethyl Butyrate, Natural Flavors)",
    concerns: [
      "Uses 'flavor packs' — engineered flavor compounds added back after pasteurization strips natural flavor",
      "22g sugar per glass — same glycemic impact as soda",
      "Heavily processed — not truly 'fresh squeezed'",
      "No fiber to slow sugar absorption",
    ],
    benefits: ["Vitamin C", "No HFCS"],
    buyTip: "This juice scored lower because it uses 'flavor packs' — engineered flavor compounds added back after pasteurization strips the natural orange flavor. At 22g of sugar per glass with no fiber, the glycemic impact is similar to soda. Whole fruit contains fiber that significantly slows sugar absorption, which is absent in processed juice.",
    averagePrice: 4.99,
    imageUrl: "/manus-storage/tropicana-oj_80205bcd.jpg",
  },
  {
    id: "simply-orange",
    name: "Simply Orange",
    brand: "Simply (Coca-Cola)",
    category: "juice",
    score: 42,
    qualityTier: "average",
    barcode: "025000056918",
    servingSize: "8 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 110, sugar: 23, sodium: 0, caffeine: 0 },
    ingredients: "100% Pure Squeezed Pasteurized Orange Juice",
    concerns: [
      "23g sugar per serving — no fiber to slow absorption",
      "Pasteurization destroys enzymes and some vitamins",
      "High glycemic impact despite being 'natural'",
    ],
    benefits: ["No additives", "No HFCS", "100% juice"],
    buyTip: "Better than Tropicana (no flavor packs), but still high sugar. Limit to 4 oz max.",
    averagePrice: 4.49,
    imageUrl: "/manus-storage/simply-orange_505d1aad.jpg",
  },
  {
    id: "suja-organic-green-juice",
    name: "Uber Greens Organic Juice",
    brand: "Suja",
    category: "juice",
    score: 85,
    qualityTier: "elite",
    barcode: "852232003015",
    servingSize: "12 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: true,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 60, sugar: 9, sodium: 65, caffeine: 0 },
    ingredients: "Organic Cucumber, Organic Celery, Organic Apple, Organic Spinach, Organic Kale, Organic Lemon, Organic Ginger",
    concerns: ["Still contains 9g natural sugar", "Cold-pressed — short shelf life"],
    benefits: [
      "USDA Certified Organic",
      "Cold-pressed — preserves enzymes and nutrients",
      "Vegetable-forward — lower sugar than fruit juices",
      "No additives or preservatives",
    ],
    buyTip: "One of the best commercial juices. Vegetable-forward keeps sugar low. Check expiration date.",
    averagePrice: 3.99,
    imageUrl: "/manus-storage/suja-organic-green-juice_587b9af3.jpg",
  },
  {
    id: "naked-green-machine",
    name: "Green Machine",
    brand: "Naked Juice (PepsiCo)",
    category: "juice",
    score: 35,
    qualityTier: "poor",
    barcode: "082592100018",
    servingSize: "15.2 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 270, sugar: 53, sodium: 25, caffeine: 0 },
    ingredients: "Apple Juice, Mango Puree, Pineapple Juice, Banana Puree, Kiwi Puree, Spirulina, Natural Flavors",
    concerns: [
      "53g sugar per bottle — more than a can of Coke",
      "Marketed as healthy but sugar content rivals soda",
      "Pasteurized — nutrients largely destroyed",
      "No fiber despite fruit content",
    ],
    benefits: ["No HFCS", "Contains spirulina"],
    buyTip: "This smoothie scored lower because it contains 53g of sugar per bottle — more than most sodas — despite its health-oriented branding. The pasteurization process also destroys much of the heat-sensitive vitamins and enzymes present in raw fruit. The lack of fiber means the sugar is absorbed rapidly without the buffering effect that whole fruit provides.",
    averagePrice: 3.99,
    imageUrl: "/manus-storage/naked-green-machine_172ea575.jpg",
  },
  {
    id: "lakewood-pure-cranberry",
    name: "Pure Cranberry Juice",
    brand: "Lakewood Organic",
    category: "juice",
    score: 88,
    qualityTier: "elite",
    barcode: "042608100011",
    servingSize: "8 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: true,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 70, sugar: 9, sodium: 10, caffeine: 0 },
    ingredients: "Organic Cranberry Juice",
    concerns: ["Tart — most people dilute with water"],
    benefits: [
      "USDA Certified Organic",
      "100% pure — no added sugar",
      "Rich in proanthocyanidins — supports urinary tract health",
      "High in antioxidants",
    ],
    buyTip: "Best cranberry juice available. Dilute 1:3 with water to reduce tartness and calories.",
    averagePrice: 5.99,
    imageUrl: "/manus-storage/lakewood-pure-cranberry_81a4d01b.jpg",
  },
  {
    id: "ocean-spray-cranberry-cocktail",
    name: "Cranberry Cocktail",
    brand: "Ocean Spray",
    category: "juice",
    score: 20,
    qualityTier: "avoid",
    barcode: "031200019015",
    servingSize: "8 fl oz",
    hasHFCS: true,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 110, sugar: 26, sodium: 35, caffeine: 0 },
    ingredients: "Water, Cranberry Juice from Concentrate, HFCS, Ascorbic Acid",
    concerns: [
      "Only 27% real cranberry juice",
      "HFCS as primary sweetener",
      "26g sugar per serving",
    ],
    benefits: ["Contains some real cranberry juice"],
    buyTip: "This product scored very low because it contains only 27% real cranberry juice, with High Fructose Corn Syrup as the primary sweetener and 26g of sugar per serving. The low juice content means it provides few of the proanthocyanidins that give pure cranberry juice its health benefits.",
    imageUrl: "/manus-storage/ocean-spray-cranberry-cocktail_1d87f1d8.jpg",
  },

  // ─── SPORTS DRINKS ───────────────────────────────────────────────────────
  {
    id: "gatorade-fruit-punch",
    name: "Fruit Punch Thirst Quencher",
    brand: "Gatorade (PepsiCo)",
    category: "sports",
    score: 22,
    qualityTier: "avoid",
    barcode: "052000113527",
    servingSize: "20 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: true,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 130, sugar: 34, sodium: 270, caffeine: 0 },
    ingredients: "Water, Sugar, Dextrose, Citric Acid, Salt, Sodium Citrate, Monopotassium Phosphate, Modified Food Starch, Natural Flavor, Red 40, Glycerol Ester of Rosin",
    concerns: [
      "34g sugar per bottle — marketed to children",
      "Red 40 artificial dye linked to hyperactivity",
      "Glycerol ester of rosin — wood resin derivative",
      "Modified food starch — unnecessary thickener",
      "Only beneficial for endurance athletes, not casual use",
    ],
    benefits: ["Good electrolyte content for intense exercise"],
    buyTip: "Only useful after 60+ minutes of intense exercise. For daily hydration, drink water.",
    averagePrice: 1.79,
    imageUrl: "/manus-storage/gatorade-fruit-punch_86fdefcc.jpg",
  },
  {
    id: "powerade-mountain-berry-blast",
    name: "Mountain Berry Blast",
    brand: "Powerade (Coca-Cola)",
    category: "sports",
    score: 20,
    qualityTier: "avoid",
    barcode: "049000042511",
    servingSize: "20 fl oz",
    hasHFCS: true,
    hasArtificialSweeteners: false,
    hasArtificialColors: true,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 130, sugar: 35, sodium: 150, caffeine: 0 },
    ingredients: "Water, High Fructose Corn Syrup, Citric Acid, Salt, Magnesium Chloride, Calcium Chloride, Potassium Chloride, Modified Food Starch, Vitamins B3/B6/B12, Blue 1",
    concerns: [
      "HFCS as primary sweetener",
      "Blue 1 artificial dye",
      "35g sugar per bottle",
    ],
    benefits: ["Contains B vitamins", "Electrolytes"],
    buyTip: "This sports drink scored low because it uses High Fructose Corn Syrup as the primary sweetener and contains Blue 1 artificial dye. At 35g of sugar per bottle, the sugar load is significant for a product marketed for hydration. The electrolyte content is the only functional benefit, which is most relevant for endurance athletes exercising over 60 minutes.",
    averagePrice: 1.49,
    imageUrl: "/manus-storage/powerade-mountain-berry-blast_b3996c9a.jpg",
  },
  {
    id: "liquid-iv",
    name: "Lemon Lime Hydration Multiplier",
    brand: "Liquid I.V.",
    category: "sports",
    score: 68,
    qualityTier: "average",
    barcode: "851770007010",
    servingSize: "16 fl oz (1 packet)",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 45, sugar: 11, sodium: 500, caffeine: 0 },
    ingredients: "Pure Cane Sugar, Dextrose, Citric Acid, Salt, Potassium Citrate, Dipotassium Phosphate, Vitamin C, Vitamin B3, Vitamin B5, Vitamin B6, Vitamin B12",
    concerns: ["11g sugar per packet", "High sodium (500mg)"],
    benefits: [
      "Cellular Transport Technology for faster absorption",
      "No artificial colors or sweeteners",
      "Good electrolyte profile",
      "B vitamin complex",
    ],
    buyTip: "Good for travel, illness, or post-exercise. High sodium — not for daily casual use.",
    averagePrice: 29.99,
    imageUrl: "/manus-storage/liquid-iv_efc8c253.jpg",
  },
  {
    id: "lmnt-electrolytes",
    name: "Raw Unflavored Electrolytes",
    brand: "LMNT",
    category: "sports",
    score: 95,
    qualityTier: "elite",
    barcode: "850004313015",
    servingSize: "16 fl oz (1 packet)",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: true,
    isNaturallySweetened: false,
    nutrients: { calories: 0, sugar: 0, sodium: 1000, caffeine: 0 },
    ingredients: "Sodium (from sodium chloride), Potassium (from potassium chloride), Magnesium (from magnesium malate)",
    concerns: ["Very high sodium — not for low-sodium diets"],
    benefits: [
      "Zero sugar, zero calories",
      "No artificial anything",
      "Science-backed electrolyte ratios",
      "Ideal for keto, carnivore, and fasting protocols",
    ],
    buyTip: "Best electrolyte product available. Perfect for fasting, keto, or post-exercise. Start with half a packet.",
    averagePrice: 19.99,
    imageUrl: "/manus-storage/lmnt-electrolytes_97d5b71c.jpg",
  },
  {
    id: "bodyarmor-sport",
    name: "Sports Drink Tropical Punch",
    brand: "BodyArmor (Coca-Cola)",
    category: "sports",
    score: 35,
    qualityTier: "poor",
    barcode: "858176005019",
    servingSize: "16 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 120, sugar: 28, sodium: 140, caffeine: 0 },
    ingredients: "Filtered Water, Pure Cane Sugar, Coconut Water Concentrate, Citric Acid, Dipotassium Phosphate, Vegetable Juice for Color, Natural Flavors, Ascorbic Acid, Vitamins",
    concerns: ["28g sugar per bottle", "Coconut water concentrate is heavily processed"],
    benefits: ["No artificial colors or sweeteners", "Contains coconut water", "Vitamins A, C, E, B3, B5, B6, B12"],
    buyTip: "Better than Gatorade/Powerade but still 28g sugar. Only for post-intense-exercise use.",
    imageUrl: "/manus-storage/bodyarmor-sport_b77d20b7.jpg",
  },

  // ─── ENERGY DRINKS ───────────────────────────────────────────────────────
  {
    id: "red-bull-original",
    name: "Red Bull Energy Drink",
    brand: "Red Bull",
    category: "energy",
    score: 20,
    qualityTier: "avoid",
    barcode: "611269991023",
    servingSize: "8.4 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: true,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: true,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 110, sugar: 27, sodium: 105, caffeine: 80 },
    ingredients: "Carbonated Water, Sucrose, Glucose, Citric Acid, Taurine, Sodium Bicarbonate, Magnesium Carbonate, Caffeine, Niacinamide, Calcium Pantothenate, Pyridoxine HCl, Vitamin B12, Natural and Artificial Flavors, Colors",
    concerns: [
      "27g sugar per small can",
      "Artificial colors and flavors",
      "Sodium benzoate preservative",
      "Taurine safety in combination with alcohol is debated",
    ],
    benefits: ["80mg caffeine (moderate)", "B vitamins"],
    buyTip: "This energy drink scored low because it contains 27g of sugar per small can, artificial colors and flavors, and sodium benzoate. The B vitamins and 80mg of caffeine provide some functional benefit, but the artificial additives and sugar content are what drive the low quality score.",
    averagePrice: 2.99,
    imageUrl: "/manus-storage/red-bull-original_b00481a8.jpg",
  },
  {
    id: "monster-energy",
    name: "Monster Energy Original",
    brand: "Monster Beverage (Coca-Cola)",
    category: "energy",
    score: 10,
    qualityTier: "avoid",
    barcode: "070847811015",
    servingSize: "16 fl oz",
    hasHFCS: true,
    hasArtificialSweeteners: false,
    hasArtificialColors: true,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: true,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 210, sugar: 54, sodium: 370, caffeine: 160 },
    ingredients: "Carbonated Water, HFCS, Citric Acid, Natural Flavors, Taurine, Sodium Citrate, Color Added, Panax Ginseng Extract, L-Carnitine, Caffeine, Sorbic Acid, Benzoic Acid, Niacinamide, Sucralose, Salt, D-Glucuronolactone, Inositol, Guarana Extract, Pyridoxine Hydrochloride, Riboflavin, Maltodextrin, Cyanocobalamin",
    concerns: [
      "54g HFCS per can — catastrophic sugar load",
      "160mg caffeine — cardiac risk for some individuals",
      "Both sorbic acid and benzoic acid preservatives",
      "Sucralose added on top of HFCS",
      "Linked to cardiac events, especially in young people",
    ],
    benefits: [],
    buyTip: "This energy drink scored very low due to 54g of HFCS per can, 160mg of caffeine (a high dose that may pose cardiac risk for sensitive individuals), both sorbic acid and benzoic acid preservatives, and sucralose added on top of the HFCS. The combination of extremely high sugar, high caffeine, and multiple preservatives is what drives the very low quality score.",
    averagePrice: 2.49,
    imageUrl: "/manus-storage/monster-energy_60f4b802.jpg",
  },
  {
    id: "celsius-original",
    name: "Sparkling Orange Fitness Drink",
    brand: "Celsius",
    category: "energy",
    score: 52,
    qualityTier: "average",
    barcode: "889392000016",
    servingSize: "12 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: true,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: true,
    isNaturallySweetened: false,
    nutrients: { calories: 10, sugar: 0, sodium: 0, caffeine: 200 },
    ingredients: "Carbonated Filtered Water, Citric Acid, Fruit and Vegetable Juice for Color, Sucralose, Natural Flavor, Green Tea Extract (EGCG), Ginger Extract, Guarana Seed Extract, Vitamin C, Riboflavin, Niacin, Vitamin B6, Vitamin B12, Biotin, Pantothenic Acid, Calcium, Chromium",
    concerns: [
      "200mg caffeine — very high, near FDA daily limit",
      "Sucralose artificial sweetener",
      "High caffeine linked to anxiety, insomnia, heart palpitations",
    ],
    benefits: [
      "Zero sugar",
      "Green tea EGCG antioxidants",
      "B vitamin complex",
      "No artificial colors",
    ],
    buyTip: "Better than Monster/Red Bull but 200mg caffeine is very high. Limit to one per day max.",
    averagePrice: 2.49,
    imageUrl: "/manus-storage/celsius-original_e5c409cd.jpg",
  },
  {
    id: "clean-cause-yerba-mate",
    name: "Original Yerba Mate",
    brand: "Clean Cause",
    category: "energy",
    score: 80,
    qualityTier: "good",
    barcode: "859888006015",
    servingSize: "16 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: true,
    isSugarFree: false,
    isNaturallySweetened: true,
    nutrients: { calories: 80, sugar: 18, sodium: 0, caffeine: 160 },
    ingredients: "Organic Yerba Mate Tea, Organic Cane Sugar, Organic Lemon Juice",
    concerns: ["160mg caffeine", "18g cane sugar"],
    benefits: [
      "Organic certified",
      "Clean, minimal ingredients",
      "Yerba mate contains theobromine for smooth energy",
      "50% of profits go to addiction recovery",
    ],
    buyTip: "Best energy drink option. Organic, minimal ingredients. Still 160mg caffeine — limit to one daily.",
    imageUrl: "/manus-storage/clean-cause-yerba-mate_369ae538.jpg",
  },

  // ─── TEAS ────────────────────────────────────────────────────────────────
  {
    id: "arizona-green-tea",
    name: "Green Tea with Ginseng & Honey",
    brand: "AriZona",
    category: "tea",
    score: 22,
    qualityTier: "avoid",
    barcode: "613008724016",
    servingSize: "23.5 fl oz",
    hasHFCS: true,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 260, sugar: 69, sodium: 0, caffeine: 15 },
    ingredients: "Filtered Water, High Fructose Corn Syrup, Honey, Citric Acid, Green Tea, Ginseng Extract, Natural Flavors, Ascorbic Acid",
    concerns: [
      "69g HFCS per can — the most sugar of any tea product",
      "Marketed as healthy green tea but is essentially sugar water",
      "Only trace amounts of actual green tea",
    ],
    benefits: ["Cheap"],
    buyTip: "This tea scored very low because High Fructose Corn Syrup is the primary sweetener at 69g per can — the highest sugar content of any tea product in this guide. Despite the green tea branding, the actual green tea content is minimal, and the product provides few of the antioxidants associated with brewed green tea.",
    averagePrice: 1.79,
    imageUrl: "/manus-storage/arizona-green-tea_19a70a3e.jpg",
  },
  {
    id: "snapple-peach-tea",
    name: "Peach Tea",
    brand: "Snapple",
    category: "tea",
    score: 28,
    qualityTier: "avoid",
    barcode: "076183000103",
    servingSize: "16 fl oz",
    hasHFCS: true,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: true,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 160, sugar: 40, sodium: 10, caffeine: 18 },
    ingredients: "Filtered Water, Sugar, Tea, Citric Acid, Natural Flavors, Sodium Hexametaphosphate",
    concerns: [
      "40g sugar per bottle",
      "Sodium hexametaphosphate — industrial sequestrant",
      "Natural flavors may include artificial compounds",
    ],
    benefits: ["No HFCS (uses cane sugar now)"],
    buyTip: "This tea scored lower because it contains 40g of sugar per bottle, primarily from cane sugar, and includes sodium hexametaphosphate — an industrial sequestrant used to prevent mineral precipitation. The high sugar content is the primary driver of the low quality score.",
    averagePrice: 1.79,
    imageUrl: "/manus-storage/snapple-peach-tea_eb93a03b.jpg",
  },
  {
    id: "pure-leaf-unsweetened-green",
    name: "Unsweetened Green Tea",
    brand: "Pure Leaf (PepsiCo/Unilever)",
    category: "tea",
    score: 72,
    qualityTier: "good",
    barcode: "012000163418",
    servingSize: "18.5 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: true,
    isNaturallySweetened: false,
    nutrients: { calories: 0, sugar: 0, sodium: 0, caffeine: 69 },
    ingredients: "Brewed Green Tea",
    concerns: ["Not organic — possible pesticide residue on tea leaves"],
    benefits: [
      "Zero sugar, zero calories",
      "Single ingredient",
      "Rich in EGCG antioxidants",
      "Supports metabolism and brain health",
    ],
    buyTip: "Good option. Buy organic if possible to avoid pesticide residue on tea leaves.",
    averagePrice: 1.49,
    imageUrl: "/manus-storage/pure-leaf-unsweetened-green_26465c8d.jpg",
  },
  {
    id: "harney-sons-organic-green",
    name: "Organic Green Tea",
    brand: "Harney & Sons",
    category: "tea",
    score: 95,
    qualityTier: "elite",
    barcode: "636046001015",
    servingSize: "8 fl oz (brewed)",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: true,
    isSugarFree: true,
    isNaturallySweetened: false,
    nutrients: { calories: 0, sugar: 0, sodium: 0, caffeine: 25 },
    ingredients: "Organic Green Tea Leaves",
    concerns: [],
    benefits: [
      "USDA Certified Organic",
      "Single ingredient",
      "High EGCG content for antioxidant protection",
      "L-theanine for calm focus",
      "Supports fat oxidation and metabolism",
    ],
    buyTip: "Best tea option. Brew loose leaf for maximum antioxidant content. Steep at 175°F, not boiling.",
    averagePrice: 1.99,
    imageUrl: "/manus-storage/harney-sons-organic-green_ba531a90.jpg",
  },
  {
    id: "yogi-detox-tea",
    name: "DeTox Herbal Tea",
    brand: "Yogi Tea",
    category: "tea",
    score: 90,
    qualityTier: "elite",
    barcode: "076950450028",
    servingSize: "8 fl oz (brewed)",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: true,
    isSugarFree: true,
    isNaturallySweetened: false,
    nutrients: { calories: 0, sugar: 0, sodium: 0, caffeine: 0 },
    ingredients: "Organic Burdock Root, Organic Dandelion Root, Organic Juniper Berry, Organic Ginger Root, Organic Licorice Root, Organic Clove, Organic Black Pepper, Organic Long Pepper, Organic Cinnamon Bark",
    concerns: ["Licorice root can raise blood pressure with excessive use"],
    benefits: [
      "Certified Organic",
      "Caffeine-free",
      "Liver-supportive herbs (dandelion, burdock)",
      "Anti-inflammatory ginger and clove",
    ],
    buyTip: "Excellent herbal blend. Limit to 1-2 cups daily due to licorice root content.",
    averagePrice: 5.99,
    imageUrl: "/manus-storage/yogi-detox-tea_2b851a36.jpg",
  },

  // ─── COFFEE ──────────────────────────────────────────────────────────────
  {
    id: "starbucks-frappuccino-mocha",
    name: "Mocha Frappuccino",
    brand: "Starbucks",
    category: "coffee",
    score: 18,
    qualityTier: "avoid",
    barcode: "012000161490",
    servingSize: "13.7 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 290, sugar: 46, sodium: 220, caffeine: 110 },
    ingredients: "Brewed Starbucks Coffee, Skim Milk, Sugar, Cream, Mono and Diglycerides, Carrageenan, Natural Flavors, Caramel Color, Salt, Potassium Sorbate",
    concerns: [
      "46g sugar per bottle",
      "Carrageenan linked to gut inflammation",
      "Mono and diglycerides (emulsifiers)",
      "Potassium sorbate preservative",
    ],
    benefits: ["Real coffee", "110mg caffeine"],
    buyTip: "This coffee drink scored lower because it contains 46g of sugar per bottle, carrageenan (a seaweed-derived emulsifier that some research has linked to gut inflammation), mono and diglycerides, and potassium sorbate as a preservative. The high sugar content and multiple additives are what drive the low quality score.",
    averagePrice: 3.99,
    imageUrl: "/manus-storage/starbucks-frappuccino-mocha_80229c97.jpg",
  },
  {
    id: "chameleon-cold-brew",
    name: "Original Black Cold Brew",
    brand: "Chameleon Cold Brew",
    category: "coffee",
    score: 95,
    qualityTier: "elite",
    barcode: "852697001015",
    servingSize: "10 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: true,
    isSugarFree: true,
    isNaturallySweetened: false,
    nutrients: { calories: 0, sugar: 0, sodium: 0, caffeine: 150 },
    ingredients: "Organic Cold Brew Coffee",
    concerns: ["150mg caffeine — moderate-high"],
    benefits: [
      "USDA Certified Organic",
      "Single ingredient",
      "Cold brew is less acidic than hot coffee",
      "No sugar, no additives",
    ],
    buyTip: "Best ready-to-drink coffee. Organic single origin. Add grass-fed cream if desired.",
    averagePrice: 3.49,
    imageUrl: "/manus-storage/chameleon-cold-brew_a2bad5ff.jpg",
  },
  {
    id: "la-colombe-draft-latte",
    name: "Oat Milk Draft Latte",
    brand: "La Colombe",
    category: "coffee",
    score: 65,
    qualityTier: "average",
    barcode: "853818004015",
    servingSize: "9 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 120, sugar: 9, sodium: 85, caffeine: 120 },
    ingredients: "Cold Brew Coffee, Oat Milk (Water, Oats, Sunflower Oil, Sea Salt), Cane Sugar, Nitrogen",
    concerns: ["Contains sunflower oil (seed oil)", "9g added sugar"],
    benefits: ["Real cold brew coffee", "Nitrogen-infused for creamy texture", "Moderate sugar"],
    buyTip: "This coffee drink scored in the average tier because the oat milk base contains sunflower oil, a seed oil high in omega-6 linoleic acid. It also contains 9g of added cane sugar. The real cold brew coffee and nitrogen infusion are positives, but the seed oil in the oat milk component limits the overall score.",
    averagePrice: 4.49,
    imageUrl: "/manus-storage/la-colombe-draft-latte_f7f33e2d.jpg",
  },

  // ─── WATER ───────────────────────────────────────────────────────────────
  {
    id: "dasani-water",
    name: "Purified Water",
    brand: "Dasani (Coca-Cola)",
    category: "water",
    score: 60,
    qualityTier: "average",
    barcode: "049000042595",
    servingSize: "16.9 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: true,
    isNaturallySweetened: false,
    nutrients: { calories: 0, sugar: 0, sodium: 10, caffeine: 0 },
    ingredients: "Purified Water, Magnesium Sulfate, Potassium Chloride, Salt",
    concerns: [
      "Tap water that is filtered and re-mineralized",
      "Plastic bottle BPA/BPS leaching concerns",
      "Added minerals are synthetic",
    ],
    benefits: ["Zero calories", "Zero sugar"],
    buyTip: "This water scored in the average tier because it is municipal tap water that has been filtered and re-mineralized with synthetic minerals (magnesium sulfate, potassium chloride). The plastic bottle also raises BPA/BPS leaching concerns, particularly when exposed to heat. The water itself is clean and safe, but the sourcing and packaging are what limit the score.",
    averagePrice: 1.29,
    imageUrl: "/manus-storage/dasani-water_3cdd2ef3.jpg",
  },
  {
    id: "evian-natural-spring",
    name: "Natural Spring Water",
    brand: "Evian",
    category: "water",
    score: 88,
    qualityTier: "elite",
    barcode: "078742001036",
    servingSize: "16.9 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: true,
    isNaturallySweetened: false,
    nutrients: { calories: 0, sugar: 0, sodium: 5, caffeine: 0 },
    ingredients: "Natural Spring Water",
    concerns: ["Plastic bottle", "Premium price"],
    benefits: [
      "Naturally filtered through Alpine glaciers",
      "Naturally occurring minerals (calcium, magnesium, silica)",
      "Neutral pH 7.2",
      "No added minerals or processing",
    ],
    buyTip: "One of the best bottled waters. Natural minerals are beneficial. Use glass bottles when possible.",
    averagePrice: 1.49,
    imageUrl: "/manus-storage/evian-natural-spring_ae1d7816.jpg",
  },
  {
    id: "spindrift-lemon",
    name: "Lemon Sparkling Water",
    brand: "Spindrift",
    category: "water",
    score: 92,
    qualityTier: "elite",
    barcode: "857883005015",
    servingSize: "12 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 13, sugar: 3, sodium: 0, caffeine: 0 },
    ingredients: "Sparkling Water, Squeezed Lemon Juice",
    concerns: ["Slightly acidic — limit if sensitive to acid"],
    benefits: [
      "Real squeezed fruit juice — not artificial flavor",
      "Only 2 ingredients",
      "Only 3g natural sugar",
      "No sweeteners, no additives",
    ],
    buyTip: "Best flavored sparkling water. Real fruit juice, not artificial flavor. Perfect soda replacement.",
    averagePrice: 1.49,
    imageUrl: "/manus-storage/spindrift-lemon_3198ecdd.jpg",
  },
  {
    id: "lacroix-sparkling",
    name: "Sparkling Water Variety",
    brand: "LaCroix",
    category: "water",
    score: 85,
    qualityTier: "elite",
    barcode: "096749000018",
    servingSize: "12 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: true,
    isNaturallySweetened: false,
    nutrients: { calories: 0, sugar: 0, sodium: 0, caffeine: 0 },
    ingredients: "Carbonated Water, Natural Flavor",
    concerns: ["'Natural flavor' is vague — source not disclosed", "Slightly acidic"],
    benefits: [
      "Zero calories, zero sugar",
      "Zero artificial sweeteners",
      "Good soda replacement",
    ],
    buyTip: "Good option. The 'natural flavor' is a minor concern. Spindrift is better if you want full transparency.",
    imageUrl: "/manus-storage/lacroix-sparkling_0d27179d.jpg",
  },

  // ─── PLANT MILKS ─────────────────────────────────────────────────────────
  {
    id: "oatly-oat-milk-original",
    name: "Original Oat Milk",
    brand: "Oatly",
    category: "plant-milk",
    score: 38,
    qualityTier: "poor",
    barcode: "810020880015",
    servingSize: "8 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 120, sugar: 7, sodium: 100, caffeine: 0 },
    ingredients: "Oat Base (Water, Oats), Low Erucic Acid Rapeseed Oil (Canola Oil), Dipotassium Phosphate, Calcium Carbonate, Tricalcium Phosphate, Sea Salt, Dicalcium Phosphate, Riboflavin, Vitamin A, Vitamin D2, Vitamin B12",
    concerns: [
      "Canola oil (rapeseed) — seed oil, inflammatory",
      "Heavily processed — oats are enzymatically treated",
      "Dipotassium phosphate — industrial emulsifier",
      "Oats spike blood sugar faster than whole oats",
    ],
    benefits: ["Fortified with vitamins", "Dairy-free"],
    buyTip: "This oat milk scored lower because it contains canola oil (rapeseed oil), a seed oil high in omega-6 linoleic acid that is added to improve texture and mouthfeel. It also contains dipotassium phosphate, an industrial emulsifier. The oats undergo enzymatic processing that can raise the glycemic index compared to whole oats.",
    averagePrice: 5.49,
    imageUrl: "/manus-storage/oatly-oat-milk-original_8f18ebbb.jpg",
  },
  {
    id: "elmhurst-oat-milk",
    name: "Unsweetened Oat Milk",
    brand: "Elmhurst 1925",
    category: "plant-milk",
    score: 72,
    qualityTier: "good",
    barcode: "856392005015",
    servingSize: "8 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 90, sugar: 5, sodium: 90, caffeine: 0 },
    ingredients: "Water, Whole Grain Oats",
    concerns: ["Oats can spike blood sugar", "Not organic"],
    benefits: [
      "Only 2 ingredients — water and oats",
      "No seed oils",
      "No emulsifiers or additives",
      "HydroRelease process preserves nutrients",
    ],
    buyTip: "Best oat milk — no seed oils, minimal ingredients. Choose unsweetened to avoid added sugar.",
    averagePrice: 4.99,
    imageUrl: "/manus-storage/elmhurst-oat-milk_3396771e.jpg",
  },
  {
    id: "silk-almond-milk-unsweetened",
    name: "Unsweetened Almond Milk",
    brand: "Silk",
    category: "plant-milk",
    score: 45,
    qualityTier: "average",
    barcode: "025293001115",
    servingSize: "8 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: false,
    isSugarFree: true,
    isNaturallySweetened: false,
    nutrients: { calories: 30, sugar: 0, sodium: 150, caffeine: 0 },
    ingredients: "Almondmilk (Filtered Water, Almonds), Calcium Carbonate, Vitamin E Acetate, Vitamin A Palmitate, Vitamin D2, Riboflavin (B2), Vitamin B12, Sea Salt, Sunflower Lecithin, Locust Bean Gum, Gellan Gum",
    concerns: [
      "Only 2% almonds — mostly water",
      "Multiple gums and emulsifiers (locust bean, gellan)",
      "Sunflower lecithin",
      "Synthetic vitamins added",
    ],
    benefits: ["Zero sugar", "Low calorie", "Dairy-free"],
    buyTip: "This almond milk scored in the average tier because it contains only approximately 2% almonds by volume, with the remainder being water and additives. It also contains multiple gums (locust bean gum, gellan gum) and sunflower lecithin as emulsifiers and stabilizers. The low almond content means it provides minimal protein or healthy fats compared to whole almonds.",
    averagePrice: 3.99,
    imageUrl: "/manus-storage/silk-almond-milk-unsweetened_5d2c86fe.jpg",
  },
  {
    id: "malk-almond-milk",
    name: "Unsweetened Almond Malk",
    brand: "MALK Organics",
    category: "plant-milk",
    score: 90,
    qualityTier: "elite",
    barcode: "860002163015",
    servingSize: "8 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: true,
    isSugarFree: true,
    isNaturallySweetened: false,
    nutrients: { calories: 50, sugar: 0, sodium: 0, caffeine: 0 },
    ingredients: "Filtered Water, Organic Sprouted Almonds, Himalayan Pink Salt",
    concerns: ["Premium price"],
    benefits: [
      "USDA Certified Organic",
      "Only 3 ingredients",
      "Sprouted almonds — better nutrient absorption",
      "No gums, emulsifiers, or additives",
      "No seed oils",
    ],
    buyTip: "Best almond milk available. Sprouted organic almonds, zero additives. Worth the premium price.",
    imageUrl: "/manus-storage/malk-almond-milk_5f2d784b.jpg",
  },

  // ─── KOMBUCHA ─────────────────────────────────────────────────────────────
  {
    id: "gt-synergy-trilogy",
    name: "Synergy Trilogy Kombucha",
    brand: "GT's Living Foods",
    category: "kombucha",
    score: 88,
    qualityTier: "elite",
    barcode: "722430240015",
    servingSize: "16 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: true,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 60, sugar: 4, sodium: 10, caffeine: 8 },
    ingredients: "Organic Raw Kombucha (Organic Kombucha Culture, Organic Black Tea, Organic Green Tea, Organic Cane Sugar), Organic Raspberry Juice, Organic Lemon Juice, Organic Ginger Juice",
    concerns: ["Trace alcohol (0.5% — legal limit)", "Small amount of sugar from fermentation"],
    benefits: [
      "USDA Certified Organic",
      "Live probiotics — supports gut microbiome",
      "Raw — enzymes intact",
      "Only 4g sugar (most consumed by fermentation)",
      "B vitamins from fermentation",
    ],
    buyTip: "Best kombucha brand. Raw, organic, and genuinely probiotic-rich. Refrigerate and consume fresh.",
    averagePrice: 3.99,
    imageUrl: "/manus-storage/gt-synergy-trilogy_e9a77a98.jpg",
  },
  {
    id: "health-ade-ginger-lemon",
    name: "Ginger-Lemon Kombucha",
    brand: "Health-Ade",
    category: "kombucha",
    score: 85,
    qualityTier: "elite",
    barcode: "852684005015",
    servingSize: "16 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: true,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 60, sugar: 6, sodium: 10, caffeine: 8 },
    ingredients: "Organic Kombucha (Filtered Water, Organic Cane Sugar, Organic Black Tea, Organic Green Tea, Kombucha Culture), Organic Ginger Juice, Organic Lemon Juice",
    concerns: ["6g sugar", "Trace alcohol"],
    benefits: [
      "Certified Organic",
      "Brewed in glass — no plastic leaching",
      "Ginger is anti-inflammatory",
      "Live probiotics",
    ],
    buyTip: "Excellent kombucha. Brewed in glass vessels for purity. Anti-inflammatory ginger is a bonus.",
    averagePrice: 3.49,
    imageUrl: "/manus-storage/health-ade-ginger-lemon_b0d5e630.jpg",
  },
  {
    id: "kevita-sparkling-probiotic",
    name: "Lemon Cayenne Sparkling Probiotic",
    brand: "KeVita (PepsiCo)",
    category: "kombucha",
    score: 62,
    qualityTier: "average",
    barcode: "852723001015",
    servingSize: "15.2 fl oz",
    hasHFCS: false,
    hasArtificialSweeteners: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasSodiumBenzoate: false,
    hasPhosphoricAcid: false,
    isOrganic: true,
    isSugarFree: false,
    isNaturallySweetened: false,
    nutrients: { calories: 35, sugar: 4, sodium: 0, caffeine: 0 },
    ingredients: "Organic Water Kefir (Filtered Water, Organic Cane Sugar, Kefir Grains), Organic Lemon Juice, Organic Cayenne, Stevia Leaf Extract",
    concerns: [
      "Owned by PepsiCo — quality concerns post-acquisition",
      "Contains stevia",
      "Water kefir is less potent than traditional kombucha",
    ],
    benefits: ["Organic", "Probiotic cultures", "Low sugar"],
    buyTip: "This probiotic drink scored in the average tier because it uses water kefir cultures rather than traditional kombucha SCOBY, which generally produces a less diverse probiotic profile. It also contains stevia leaf extract. The organic certification and low sugar content are positives that keep the score in the average range.",
    averagePrice: 3.49,
    imageUrl: "/manus-storage/kevita-sparkling-probiotic_b76a82d2.jpg",
  },
];

export const BEVERAGE_DB_STATS = {
  total: ALL_BEVERAGES.length,
  hfcsCount: ALL_BEVERAGES.filter(b => b.hasHFCS).length,
  artificialSweetenerCount: ALL_BEVERAGES.filter(b => b.hasArtificialSweeteners).length,
  artificialColorCount: ALL_BEVERAGES.filter(b => b.hasArtificialColors).length,
  eliteCount: ALL_BEVERAGES.filter(b => b.qualityTier === "elite" || b.qualityTier === "good").length,
};
