/**
 * EatVera — Comprehensive US Condiments & Oils Database
 * Quality ratings based on:
 * - Seed oil content (canola, soybean, sunflower, safflower, corn, cottonseed, grapeseed, rice bran)
 * - HFCS and added sugar content
 * - Artificial preservatives and colors
 * - Organic / non-GMO status
 * - Processing level (cold-pressed vs refined)
 * - Smoke point and oxidation stability for cooking oils
 */

export type CondimentQualityTier = "elite" | "good" | "average" | "poor" | "avoid";
export type CondimentCategory =
  | "Cooking Oils"
  | "Ketchup & Tomato"
  | "Mayonnaise"
  | "Mustard"
  | "Salad Dressings"
  | "Hot Sauce"
  | "Soy Sauce & Liquid Aminos"
  | "Vinegar"
  | "Nut Butters"
  | "Jams & Jellies"
  | "BBQ Sauce"
  | "Other";

export interface CondimentEntry {
  id: string;
  name: string;
  brand: string;
  category: CondimentCategory;
  qualityTier: CondimentQualityTier;
  score: number;
  barcode?: string;
  hasSeedOils: boolean;
  hasHFCS: boolean;
  hasArtificialIngredients: boolean;
  organic: boolean;
  nonGMO: boolean;
  /** For oils: cold-pressed/expeller-pressed vs solvent-extracted */
  coldPressed?: boolean;
  /** For oils: smoke point in °F */
  smokePoint?: number;
  concerns: string[];
  benefits: string[];
  ingredients?: string;
  buyTip: string;
  averagePrice?: number;
  imageUrl?: string;
  nutrients?: {
    calories?: number;
    fat?: number;
    saturatedFat?: number;
    omega6?: string;
    omega3?: string;
    sodium?: number;
    sugar?: number;
};
}

export const CONDIMENT_QUALITY_TIER_CONFIG: Record<
  CondimentQualityTier,
  { label: string; color: string; bg: string; border: string; score: string }
> = {
  elite: { label: "Elite", color: "#145A3A", bg: "#F0FAF2", border: "#86d086", score: "85–100" },
  good: { label: "Good", color: "#3FA34D", bg: "#F0FAF2", border: "#b8e8b8", score: "65–84" },
  average: { label: "Average", color: "#d97706", bg: "#fffbf0", border: "#fde68a", score: "45–64" },
  poor: { label: "Poor", color: "#ea580c", bg: "#fff7f0", border: "#fed7aa", score: "25–44" },
  avoid: { label: "Avoid", color: "#dc2626", bg: "#fff5f5", border: "#fca5a5", score: "0–24" },
};

export const CONDIMENT_CATEGORIES: { id: string; label: string }[] = [
  { id: "all", label: "All" },
  { id: "Cooking Oils", label: "Cooking Oils" },
  { id: "Mayonnaise", label: "Mayo" },
  { id: "Ketchup & Tomato", label: "Ketchup" },
  { id: "Salad Dressings", label: "Dressings" },
  { id: "Nut Butters", label: "Nut Butters" },
  { id: "Hot Sauce", label: "Hot Sauce" },
  { id: "Mustard", label: "Mustard" },
  { id: "BBQ Sauce", label: "BBQ Sauce" },
  { id: "Jams & Jellies", label: "Jams" },
  { id: "Soy Sauce & Liquid Aminos", label: "Soy Sauce" },
  { id: "Vinegar", label: "Vinegar" },
];

export function getCondimentColor(score: number): string {
  if (score >= 85) return "#145A3A";
  if (score >= 70) return "#3FA34D";
  if (score >= 55) return "#65a30d";
  if (score >= 40) return "#d97706";
  if (score >= 25) return "#ea580c";
  return "#dc2626";
}

export const ALL_CONDIMENTS: CondimentEntry[] = [
  // ─── COOKING OILS ────────────────────────────────────────────────────────────
  {
    id: "beef-tallow",
    name: "Grass-Fed Beef Tallow",
    brand: "Force of Nature / Fatworks",
    category: "Cooking Oils",
    qualityTier: "elite",
    score: 99,
    barcode: "850026076131",
    imageUrl: "/manus-storage/condiment-grass-fed-beef-tallow-by-force-of-nature-fatworks_b9ead294.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: true,
    coldPressed: false,
    smokePoint: 400,
    concerns: ["High in saturated fat (though from healthy source)", "Strong beef flavor in some applications"],
    benefits: [
      "Ancestral fat — humans have cooked with tallow for millennia",
      "Extremely stable at high heat — no oxidation",
      "Rich in CLA and fat-soluble vitamins",
      "No seed oils whatsoever",
      "Supports hormone production",
    ],
    buyTip: "Best cooking fat for high-heat cooking. Use for frying, roasting, and sautéing. Force of Nature and Fatworks are top brands.",
    averagePrice: 14.99,
    ingredients: "Grass-Fed Beef Tallow.",
    nutrients: { calories: 115, fat: 13, saturatedFat: 6, omega6: "Low", omega3: "Trace" },
  },
  {
    id: "extra-virgin-olive-oil",
    name: "Extra Virgin Olive Oil",
    brand: "California Olive Ranch",
    category: "Cooking Oils",
    qualityTier: "elite",
    score: 95,
    barcode: "0850687000001",
    imageUrl: "/manus-storage/condiment-fix2-california-olive-ranch-extra-virgin-olive-oil-bott_097ff303.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: true,
    coldPressed: true,
    smokePoint: 375,
    concerns: [
      "Low smoke point — not ideal for high-heat cooking",
      "Widespread fraud in olive oil industry — many 'EVOO' products are cut with seed oils",
      "California Olive Ranch is one of the more verified brands",
    ],
    benefits: [
      "Rich in oleocanthal — anti-inflammatory",
      "High in monounsaturated fats (oleic acid)",
      "Polyphenols support cardiovascular health",
      "Cold-pressed — nutrients preserved",
      "California-sourced — traceable",
    ],
    buyTip: "Use for low-heat cooking, salad dressings, and finishing. California Olive Ranch is one of the few verified authentic EVOO brands in the US.",
    averagePrice: 11.99,
    ingredients: "Extra Virgin Olive Oil.",
    nutrients: { calories: 120, fat: 14, saturatedFat: 2, omega6: "Low (9%)", omega3: "Trace" },
  },
  {
    id: "coconut-oil-unrefined",
    name: "Unrefined Virgin Coconut Oil",
    brand: "Nutiva",
    category: "Cooking Oils",
    qualityTier: "elite",
    score: 90,
    barcode: "0692752100001",
    imageUrl: "/manus-storage/condiment-unrefined-virgin-coconut-oil-by-nutiva_6834ef64.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: true,
    nonGMO: true,
    coldPressed: true,
    smokePoint: 350,
    concerns: [
      "High in saturated fat — context-dependent",
      "Strong coconut flavor",
      "Medium smoke point",
      "Some debate on MCT health claims",
    ],
    benefits: [
      "Rich in MCTs — medium-chain triglycerides",
      "Lauric acid — antimicrobial properties",
      "Very stable — resistant to oxidation",
      "USDA Organic",
      "No seed oils",
    ],
    buyTip: "Great for medium-heat cooking and baking. Use unrefined for flavor, refined for neutral taste.",
    averagePrice: 9.99,
    ingredients: "Organic Virgin Coconut Oil.",
    nutrients: { calories: 130, fat: 14, saturatedFat: 12, omega6: "Very Low", omega3: "None" },
  },
  {
    id: "avocado-oil-primal-kitchen",
    name: "Pure Avocado Oil",
    brand: "Primal Kitchen",
    category: "Cooking Oils",
    qualityTier: "elite",
    score: 93,
    barcode: "0855232006001",
    imageUrl: "/manus-storage/condiment-pure-avocado-oil-by-primal-kitchen_4422b90a.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: true,
    coldPressed: true,
    smokePoint: 500,
    concerns: ["Not organic", "Premium price", "Some brands dilute with other oils — buy from verified brands"],
    benefits: [
      "Highest smoke point of healthy oils (500°F)",
      "Rich in oleic acid (monounsaturated)",
      "Neutral flavor — versatile",
      "Expeller-pressed",
      "No seed oils",
    ],
    buyTip: "Best oil for high-heat cooking. Primal Kitchen is a verified brand. Great for stir-fry, roasting, and grilling.",
    averagePrice: 12.99,
    ingredients: "100% Pure Avocado Oil.",
    nutrients: { calories: 124, fat: 14, saturatedFat: 1.6, omega6: "Low (12%)", omega3: "Trace" },
  },
  {
    id: "canola-oil-wesson",
    name: "Pure Canola Oil",
    brand: "Wesson",
    category: "Cooking Oils",
    qualityTier: "avoid",
    score: 5,
    barcode: "0051500280003",
    imageUrl: "/manus-storage/condiment-fix-wesson-pure-canola-oil-bottle_9e372a3d.png",
    hasSeedOils: true,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: false,
    coldPressed: false,
    smokePoint: 400,
    concerns: [
      "Seed oil — high omega-6 linoleic acid (21%)",
      "Solvent-extracted with hexane",
      "Deodorized at high heat — creates trans fats",
      "GMO canola (90%+ of US supply)",
      "Oxidizes at cooking temperatures — creates aldehydes",
      "Linked to inflammation when consumed in excess",
    ],
    benefits: ["High smoke point", "Affordable", "Neutral flavor"],
    buyTip: "This oil scored low because canola oil is extracted using chemical solvents (hexane) and undergoes high-heat deodorization, a process that can generate trans fats. It is also predominantly omega-6 linoleic acid (21%), which contributes to an imbalanced omega-6 to omega-3 ratio when consumed regularly. Over 90% of the US canola supply is from GMO crops.",
    averagePrice: 5.99,
    ingredients: "Canola Oil.",
    nutrients: { calories: 120, fat: 14, saturatedFat: 1, omega6: "High (21%)", omega3: "Low (9%)" },
  },
  {
    id: "vegetable-oil-crisco",
    name: "Pure Vegetable Oil",
    brand: "Crisco",
    category: "Cooking Oils",
    qualityTier: "avoid",
    score: 3,
    barcode: "0051500010006",
    imageUrl: "/manus-storage/condiment-fix-crisco-pure-vegetable-oil-bottle_af169035.jpg",
    hasSeedOils: true,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: false,
    coldPressed: false,
    smokePoint: 450,
    concerns: [
      "100% soybean oil — highest omega-6 of common oils (54%)",
      "Solvent-extracted with hexane",
      "GMO soybeans",
      "Highly oxidized during processing",
      "Promotes systemic inflammation",
      "Linked to metabolic dysfunction in research",
    ],
    benefits: ["Cheap", "Neutral flavor", "High smoke point"],
    buyTip: "This oil scored very low because soybean oil has the highest omega-6 linoleic acid content of common cooking oils (approximately 54%). Like other seed oils, it is solvent-extracted and highly refined. Research has linked diets high in linoleic acid to increased markers of systemic inflammation when omega-3 intake is not proportionally high.",
    averagePrice: 4.99,
    ingredients: "Soybean Oil.",
    nutrients: { calories: 120, fat: 14, saturatedFat: 2, omega6: "Very High (54%)", omega3: "Low (7%)" },
  },

  // ─── KETCHUP ─────────────────────────────────────────────────────────────────
  {
    id: "primal-kitchen-ketchup",
    name: "Organic Unsweetened Ketchup",
    brand: "Primal Kitchen",
    category: "Ketchup & Tomato",
    qualityTier: "elite",
    score: 94,
    barcode: "0855232007001",
    imageUrl: "/manus-storage/condiment-organic-unsweetened-ketchup-by-primal-kitchen_3eea50ae.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: true,
    nonGMO: true,
    concerns: ["Premium price", "Slightly less sweet than conventional ketchup"],
    benefits: [
      "No added sugar",
      "USDA Organic",
      "No seed oils",
      "No HFCS",
      "Clean simple ingredients",
    ],
    buyTip: "Best ketchup available. Available at Whole Foods, Target, and Amazon.",
    averagePrice: 6.99,
    ingredients: "Organic Tomato Concentrate, Organic Balsamic Vinegar, Organic Apple Cider Vinegar, Salt, Organic Onion Powder, Organic Garlic Powder.",
    nutrients: { calories: 10, fat: 0, saturatedFat: 0, sodium: 135, sugar: 1 },
  },
  {
    id: "heinz-organic-ketchup",
    name: "Organic Tomato Ketchup",
    brand: "Heinz",
    category: "Ketchup & Tomato",
    qualityTier: "average",
    score: 45,
    barcode: "0013000006286",
    imageUrl: "/manus-storage/condiment-fix2-heinz-organic-tomato-ketchup-bottle_ba4e9bd1.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: true,
    nonGMO: true,
    concerns: ["Contains cane sugar (4g per tbsp)", "Owned by Kraft Heinz — large corporate brand"],
    benefits: ["USDA Organic", "No HFCS", "Non-GMO", "Familiar taste", "Widely available"],
    buyTip: "Good upgrade from regular Heinz. Available at most grocery stores.",
    averagePrice: 5.99,
    ingredients: "Organic Tomato Concentrate, Organic Distilled Vinegar, Organic Cane Sugar, Salt, Organic Onion Powder, Organic Spice.",
    nutrients: { calories: 20, fat: 0, saturatedFat: 0, sodium: 160, sugar: 4 },
  },
  {
    id: "heinz-original-ketchup",
    name: "Tomato Ketchup",
    brand: "Heinz",
    category: "Ketchup & Tomato",
    qualityTier: "poor",
    score: 32,
    barcode: "0013000001007",
    imageUrl: "/manus-storage/condiment-organic-tomato-ketchup-by-heinz_68f63122.jpg",
    hasSeedOils: false,
    hasHFCS: true,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: false,
    concerns: [
      "High Fructose Corn Syrup as second ingredient",
      "4g HFCS per tablespoon",
      "GMO corn syrup",
      "Conventional tomatoes — pesticide residues",
    ],
    benefits: ["Affordable", "Widely available", "Familiar taste"],
    buyTip: "This ketchup scored lower primarily because High Fructose Corn Syrup is the second ingredient, contributing approximately 4g of fructose per tablespoon. HFCS is metabolized differently than glucose and is associated with elevated triglycerides and liver fat when consumed in excess. The tomatoes are also from conventional farming, which may carry pesticide residues.",
    ingredients: "Tomato Concentrate, Distilled Vinegar, High Fructose Corn Syrup, Corn Syrup, Salt, Spice, Onion Powder, Natural Flavoring.",
    nutrients: { calories: 20, fat: 0, saturatedFat: 0, sodium: 160, sugar: 4 },
  },

  // ─── MAYONNAISE ──────────────────────────────────────────────────────────────
  {
    id: "primal-kitchen-avocado-mayo",
    name: "Avocado Oil Mayo",
    brand: "Primal Kitchen",
    category: "Mayonnaise",
    qualityTier: "elite",
    score: 96,
    barcode: "0855232005001",
    imageUrl: "/manus-storage/condiment-fix-primal-kitchen-avocado-oil-mayo-jar_f14c9115.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: true,
    concerns: ["Premium price", "Slightly different texture than conventional mayo"],
    benefits: [
      "Made with avocado oil — no seed oils",
      "Cage-free eggs",
      "Non-GMO Project Verified",
      "No canola, soybean, or sunflower oil",
      "Clean simple ingredients",
    ],
    buyTip: "The best mayo available. Available at Costco (great value), Whole Foods, Target, and Amazon.",
    averagePrice: 8.99,
    ingredients: "Avocado Oil, Organic Eggs, Organic Egg Yolks, Organic Vinegar, Sea Salt, Organic Rosemary Extract.",
    nutrients: { calories: 90, fat: 10, saturatedFat: 1, sodium: 90, sugar: 0 },
  },
  {
    id: "chosen-foods-avocado-mayo",
    name: "Classic Avocado Oil Mayo",
    brand: "Chosen Foods",
    category: "Mayonnaise",
    qualityTier: "elite",
    score: 91,
    barcode: "0815733020001",
    imageUrl: "/manus-storage/condiment-fix-chosen-foods-classic-avocado-oil-mayo-jar_31b3938d.png",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: true,
    concerns: ["Not organic", "Contains modified food starch in some varieties"],
    benefits: [
      "100% avocado oil — no seed oils",
      "Non-GMO Project Verified",
      "Clean ingredients",
      "Good value",
    ],
    buyTip: "Great alternative to Primal Kitchen. Available at Costco and most grocery chains.",
    averagePrice: 7.99,
    ingredients: "Avocado Oil, Whole Eggs, Egg Yolks, Distilled Vinegar, Salt, Lemon Juice.",
    nutrients: { calories: 90, fat: 10, saturatedFat: 1, sodium: 90, sugar: 0 },
  },
  {
    id: "hellmanns-real-mayo",
    name: "Real Mayonnaise",
    brand: "Hellmann's",
    category: "Mayonnaise",
    qualityTier: "avoid",
    score: 18,
    barcode: "0048001217013",
    imageUrl: "/manus-storage/condiment-real-mayonnaise-by-hellmann-s_27f51850.jpg",
    hasSeedOils: true,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: false,
    concerns: [
      "Soybean oil as primary ingredient — seed oil",
      "GMO soybeans",
      "Calcium disodium EDTA preservative",
      "Conventional eggs — caged hens",
      "High omega-6 content",
    ],
    benefits: ["Affordable", "Widely available", "Familiar taste"],
    buyTip: "This mayonnaise scored low because soybean oil is the primary ingredient, making it a concentrated source of omega-6 linoleic acid. It also contains calcium disodium EDTA, a chelating preservative, and uses eggs from caged hens. The high omega-6 content is the primary driver of the low score.",
    averagePrice: 5.99,
    ingredients: "Soybean Oil, Water, Whole Eggs and Egg Yolks, Vinegar, Salt, Sugar, Lemon Juice, Calcium Disodium EDTA.",
    nutrients: { calories: 90, fat: 10, saturatedFat: 1.5, sodium: 90, sugar: 0 },
  },

  // ─── MUSTARD ─────────────────────────────────────────────────────────────────
  {
    id: "primal-kitchen-dijon-mustard",
    name: "Dijon Mustard",
    brand: "Primal Kitchen",
    category: "Mustard",
    qualityTier: "elite",
    score: 97,
    barcode: "0855232008001",
    imageUrl: "/manus-storage/condiment-pk-dijon-mustard_071c7e5f.png",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: true,
    nonGMO: true,
    concerns: ["Premium price"],
    benefits: ["USDA Organic", "No seed oils", "No HFCS", "Clean simple ingredients", "Non-GMO"],
    buyTip: "Best mustard available. Mustard is generally a clean condiment — even conventional is decent.",
    averagePrice: 3.99,
    ingredients: "Organic Distilled Vinegar, Water, Organic Mustard Seed, Salt, Organic Turmeric.",
    nutrients: { calories: 0, fat: 0, saturatedFat: 0, sodium: 55, sugar: 0 },
  },
  {
    id: "french-yellow-mustard",
    name: "Classic Yellow Mustard",
    brand: "French's",
    category: "Mustard",
    qualityTier: "good",
    score: 80,
    barcode: "0041500000001",
    imageUrl: "/manus-storage/condiment-classic-yellow-mustard-by-french-s_31df7d1b.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: false,
    concerns: ["Not organic", "Turmeric color (natural but not certified)", "Conventional mustard seed"],
    benefits: ["No seed oils", "No HFCS", "Very low calorie", "Simple ingredients", "Affordable"],
    buyTip: "Mustard is one of the cleanest condiments. French's is acceptable. Upgrade to organic if possible.",
    averagePrice: 2.99,
    ingredients: "Distilled Vinegar, Water, Mustard Seed, Salt, Turmeric, Paprika, Spice, Garlic Powder.",
    nutrients: { calories: 0, fat: 0, saturatedFat: 0, sodium: 55, sugar: 0 },
  },

  // ─── SALAD DRESSINGS ─────────────────────────────────────────────────────────
  {
    id: "primal-kitchen-ranch",
    name: "Ranch Dressing",
    brand: "Primal Kitchen",
    category: "Salad Dressings",
    qualityTier: "elite",
    score: 92,
    barcode: "0855232009001",
    imageUrl: "/manus-storage/condiment-ranch-dressing-by-primal-kitchen_cb5308f3.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: true,
    concerns: ["Not organic", "Premium price"],
    benefits: [
      "Avocado oil base — no seed oils",
      "Non-GMO Project Verified",
      "Cage-free eggs",
      "No artificial flavors or colors",
      "Clean ingredient list",
    ],
    buyTip: "Best ranch dressing available. Available at Costco, Whole Foods, and Target.",
    averagePrice: 3.49,
    ingredients: "Avocado Oil, Water, Organic Egg Yolks, Organic Vinegar, Organic Garlic, Organic Onion, Sea Salt, Organic Herbs.",
    nutrients: { calories: 130, fat: 14, saturatedFat: 2, sodium: 230, sugar: 1 },
  },
  {
    id: "hidden-valley-ranch",
    name: "Original Ranch Dressing",
    brand: "Hidden Valley",
    category: "Salad Dressings",
    qualityTier: "avoid",
    score: 10,
    barcode: "0071100003413",
    imageUrl: "/manus-storage/condiment-fix2-hidden-valley-original-ranch-dressing-bottle_1336b181.jpg",
    hasSeedOils: true,
    hasHFCS: false,
    hasArtificialIngredients: true,
    organic: false,
    nonGMO: false,
    concerns: [
      "Soybean oil as primary ingredient",
      "Monosodium glutamate (MSG)",
      "Phosphoric acid",
      "Artificial flavors",
      "Disodium phosphate",
      "High sodium",
    ],
    benefits: ["Affordable", "Widely available"],
    buyTip: "This dressing scored low because soybean oil is the primary ingredient, and it contains MSG (monosodium glutamate), phosphoric acid, and artificial flavors. The combination of a seed oil base with multiple synthetic additives is what drives the low quality score.",
    averagePrice: 3.99,
    ingredients: "Soybean Oil, Buttermilk, Water, Egg Yolk, Salt, Sugar, Garlic, Onion, MSG, Phosphoric Acid, Xanthan Gum, Modified Food Starch, Artificial Flavors, Disodium Phosphate.",
    nutrients: { calories: 140, fat: 14, saturatedFat: 2, sodium: 260, sugar: 1 },
  },
  {
    id: "wishbone-italian",
    name: "Italian Dressing",
    brand: "Wish-Bone",
    category: "Salad Dressings",
    qualityTier: "avoid",
    score: 10,
    barcode: "0041321000001",
    imageUrl: "/manus-storage/condiment-italian-dressing-by-wish-bone_eb721593.jpg",
    hasSeedOils: true,
    hasHFCS: false,
    hasArtificialIngredients: true,
    organic: false,
    nonGMO: false,
    concerns: [
      "Soybean oil primary ingredient",
      "Calcium disodium EDTA",
      "Artificial colors",
      "Propylene glycol alginate",
      "High sodium",
    ],
    benefits: ["Affordable", "Low calorie"],
    buyTip: "This dressing scored low because soybean oil is the primary ingredient, and it contains calcium disodium EDTA, propylene glycol alginate (a synthetic emulsifier), and artificial coloring agents. The sodium content is also relatively high at 310mg per serving.",
    ingredients: "Water, Soybean Oil, Vinegar, Salt, Sugar, Garlic, Onion, Red Bell Pepper, Xanthan Gum, Calcium Disodium EDTA, Artificial Color.",
    nutrients: { calories: 35, fat: 3, saturatedFat: 0, sodium: 310, sugar: 1 },
  },

  // ─── HOT SAUCE ───────────────────────────────────────────────────────────────
  {
    id: "tabasco-original",
    name: "Original Red Sauce",
    brand: "Tabasco",
    category: "Hot Sauce",
    qualityTier: "elite",
    score: 98,
    barcode: "0011210000001",
    imageUrl: "/manus-storage/condiment-original-red-sauce-by-tabasco_988382c1.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: false,
    concerns: ["Not organic", "Very high sodium per serving (if used heavily)"],
    benefits: [
      "Only 3 ingredients",
      "Aged in oak barrels on Avery Island",
      "No seed oils",
      "No HFCS",
      "No artificial ingredients",
      "Capsaicin — anti-inflammatory",
    ],
    buyTip: "One of the cleanest condiments available. 3 ingredients, no additives.",
    averagePrice: 3.49,
    ingredients: "Distilled Vinegar, Red Pepper, Salt.",
    nutrients: { calories: 0, fat: 0, saturatedFat: 0, sodium: 35, sugar: 0 },
  },
  {
    id: "franks-redhot",
    name: "Original Hot Sauce",
    brand: "Frank's RedHot",
    category: "Hot Sauce",
    qualityTier: "good",
    score: 82,
    barcode: "0041390000001",
    imageUrl: "/manus-storage/condiment-fix-frank-s-redhot-original-hot-sauce-bottle_cb96dd03.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: false,
    concerns: ["Contains garlic powder and natural flavor", "Not organic"],
    benefits: ["No seed oils", "No HFCS", "Simple ingredients", "Affordable", "Widely available"],
    buyTip: "Good clean hot sauce. Avoid the 'Buffalo Wing Sauce' variety which contains butter and seed oils.",
    averagePrice: 3.99,
    ingredients: "Aged Cayenne Red Peppers, Distilled Vinegar, Water, Salt, Garlic Powder.",
    nutrients: { calories: 0, fat: 0, saturatedFat: 0, sodium: 190, sugar: 0 },
  },

  // ─── NUT BUTTERS ─────────────────────────────────────────────────────────────
  {
    id: "once-again-almond-butter",
    name: "Organic Almond Butter",
    brand: "Once Again",
    category: "Nut Butters",
    qualityTier: "elite",
    score: 95,
    barcode: "0044082000001",
    imageUrl: "/manus-storage/condiment-organic-almond-butter-by-once-again_fb0d8200.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: true,
    nonGMO: true,
    concerns: ["High in omega-6 (though from whole almonds)", "Calorie-dense"],
    benefits: [
      "USDA Organic",
      "One ingredient — just almonds",
      "No added oils or sugar",
      "Non-GMO Project Verified",
      "Rich in vitamin E and magnesium",
    ],
    buyTip: "Best almond butter. One ingredient. Available at Whole Foods and specialty stores.",
    ingredients: "Organic Dry Roasted Almonds.",
    nutrients: { calories: 190, fat: 17, saturatedFat: 1.5, sodium: 0, sugar: 1 },
  },
  {
    id: "jif-peanut-butter",
    name: "Creamy Peanut Butter",
    brand: "Jif",
    category: "Nut Butters",
    qualityTier: "poor",
    score: 30,
    barcode: "0051500240007",
    imageUrl: "/manus-storage/condiment-creamy-peanut-butter-by-jif_08471532.jpg",
    hasSeedOils: true,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: false,
    concerns: [
      "Contains fully hydrogenated vegetable oils (palm, rapeseed, soybean)",
      "Added sugar",
      "Conventional peanuts — high pesticide load",
      "Mono and diglycerides",
    ],
    benefits: ["Affordable", "Widely available", "Good protein source"],
    buyTip: "This peanut butter scored lower due to the addition of fully hydrogenated vegetable oils (rapeseed, cottonseed, soybean), which are used to prevent oil separation. Hydrogenated oils contain trace trans fats. The product also contains added sugar and uses conventional peanuts, which are among the most pesticide-treated crops in the US.",
    ingredients: "Roasted Peanuts, Sugar, Contains 2% or Less of: Molasses, Fully Hydrogenated Vegetable Oils (Rapeseed, Cottonseed, Soybean), Mono and Diglycerides, Salt.",
    nutrients: { calories: 190, fat: 16, saturatedFat: 3.5, sodium: 135, sugar: 3 },
  },

  // ─── BBQ SAUCE ───────────────────────────────────────────────────────────────
  {
    id: "primal-kitchen-bbq",
    name: "Classic BBQ Sauce",
    brand: "Primal Kitchen",
    category: "BBQ Sauce",
    qualityTier: "elite",
    score: 90,
    barcode: "0855232010001",
    imageUrl: "/manus-storage/condiment-original-bbq-sauce-by-sweet-baby-ray-s_856a7be7.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: true,
    nonGMO: true,
    concerns: ["Premium price", "Less sweet than conventional BBQ sauce"],
    benefits: ["USDA Organic", "No HFCS", "No seed oils", "Non-GMO", "Clean ingredients"],
    buyTip: "Best BBQ sauce. Available at Whole Foods and Target.",
    averagePrice: 3.99,
    ingredients: "Organic Tomato Paste, Organic Apple Cider Vinegar, Organic Coconut Aminos, Organic Molasses, Sea Salt, Organic Garlic, Organic Spices.",
    nutrients: { calories: 25, fat: 0, saturatedFat: 0, sodium: 200, sugar: 5 },
  },
  {
    id: "sweet-baby-rays-bbq",
    name: "Original BBQ Sauce",
    brand: "Sweet Baby Ray's",
    category: "BBQ Sauce",
    qualityTier: "avoid",
    score: 15,
    barcode: "0013000004008",
    imageUrl: "/manus-storage/condiment-fix-sweet-baby-ray-s-original-bbq-sauce-bottle_462c4a6c.jpg",
    hasSeedOils: false,
    hasHFCS: true,
    hasArtificialIngredients: true,
    organic: false,
    nonGMO: false,
    concerns: [
      "High Fructose Corn Syrup as first ingredient",
      "16g sugar per 2 tbsp serving",
      "Caramel color (Class IV — potential carcinogen)",
      "Natural and artificial flavors",
      "Sodium benzoate preservative",
    ],
    benefits: ["Affordable", "Widely available", "Familiar taste"],
    buyTip: "This BBQ sauce scored very low because High Fructose Corn Syrup is the first ingredient, meaning it is the largest component by weight. At 16g of sugar per 2-tablespoon serving, it is one of the highest-sugar condiments available. It also contains Class IV caramel color, which is produced using ammonia and has been flagged by some health agencies as a potential carcinogen at high doses.",
    averagePrice: 3.49,
    ingredients: "High Fructose Corn Syrup, Distilled Vinegar, Tomato Paste, Modified Corn Starch, Salt, Pineapple Juice, Natural Flavor, Caramel Color, Sodium Benzoate.",
    nutrients: { calories: 70, fat: 0, saturatedFat: 0, sodium: 290, sugar: 16 },
  },

  // ─── JAMS & JELLIES ──────────────────────────────────────────────────────────
  {
    id: "bonne-maman-strawberry",
    name: "Strawberry Preserves",
    brand: "Bonne Maman",
    category: "Jams & Jellies",
    qualityTier: "good",
    score: 68,
    barcode: "0603398000001",
    imageUrl: "/manus-storage/condiment-bonne-maman-strawberry_d8d49606.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: false,
    concerns: ["High sugar (12g per tbsp)", "Not organic", "Cane sugar as second ingredient"],
    benefits: ["No HFCS", "No artificial colors or preservatives", "Real fruit", "Simple ingredients"],
    buyTip: "This jam scored in the good tier because it uses cane sugar rather than HFCS and contains no artificial colors or preservatives. The score is limited by the high sugar content (12g per tablespoon) and the use of non-organic fruit, which may carry pesticide residues.",
    averagePrice: 3.99,
    ingredients: "Strawberries, Cane Sugar, Fruit Pectin, Citric Acid.",
    nutrients: { calories: 50, fat: 0, saturatedFat: 0, sodium: 0, sugar: 12 },
  },
  {
    id: "smuckers-strawberry-jam",
    name: "Strawberry Jam",
    brand: "Smucker's",
    category: "Jams & Jellies",
    qualityTier: "poor",
    score: 28,
    barcode: "0051500010007",
    imageUrl: "/manus-storage/condiment-strawberry-jam-by-smucker-s_50c3e1ee.jpg",
    hasSeedOils: false,
    hasHFCS: true,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: false,
    concerns: [
      "High Fructose Corn Syrup",
      "Corn syrup",
      "Conventional strawberries — pesticide residues",
      "Very high sugar",
    ],
    benefits: ["Affordable", "Widely available"],
    buyTip: "This jam scored lower because it contains both High Fructose Corn Syrup and corn syrup, making sweeteners the two largest ingredients after fruit. The conventional strawberries may also carry pesticide residues, as strawberries consistently rank among the highest-pesticide produce items in EWG testing.",
    averagePrice: 4.99,
    ingredients: "Strawberries, High Fructose Corn Syrup, Corn Syrup, Sugar, Fruit Pectin, Citric Acid.",
    nutrients: { calories: 50, fat: 0, saturatedFat: 0, sodium: 0, sugar: 13 },
  },

  // ─── SOY SAUCE & AMINOS ──────────────────────────────────────────────────────
  {
    id: "coconut-aminos-bragg",
    name: "Coconut Liquid Aminos",
    brand: "Bragg",
    category: "Soy Sauce & Liquid Aminos",
    qualityTier: "elite",
    score: 92,
    barcode: "0074305000001",
    imageUrl: "/manus-storage/condiment-coconut-liquid-aminos-by-bragg_2c31ad53.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: true,
    nonGMO: true,
    concerns: ["Higher sodium than expected", "Slightly sweet — different from soy sauce"],
    benefits: [
      "Soy-free alternative to soy sauce",
      "USDA Organic",
      "Non-GMO",
      "Gluten-free",
      "17 amino acids",
      "No MSG",
    ],
    buyTip: "Best soy sauce alternative. Great for those avoiding soy or gluten. Available at most health food stores.",
    averagePrice: 7.99,
    ingredients: "Organic Coconut Tree Sap, Sea Salt.",
    nutrients: { calories: 10, fat: 0, saturatedFat: 0, sodium: 270, sugar: 1 },
  },
  {
    id: "kikkoman-soy-sauce",
    name: "All-Purpose Soy Sauce",
    brand: "Kikkoman",
    category: "Soy Sauce & Liquid Aminos",
    qualityTier: "average",
    score: 55,
    barcode: "0041390000002",
    imageUrl: "/manus-storage/condiment-all-purpose-soy-sauce-by-kikkoman_8bcc5574.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: false,
    concerns: ["Very high sodium (920mg per tbsp)", "Contains wheat (gluten)", "GMO soybeans likely", "Sodium benzoate in some varieties"],
    benefits: ["Traditional fermentation process", "No artificial colors", "Widely available", "Affordable"],
    buyTip: "Acceptable in moderation. Choose Kikkoman Organic or San-J Tamari (gluten-free) for a cleaner option.",
    ingredients: "Water, Wheat, Soybeans, Salt.",
    nutrients: { calories: 10, fat: 0, saturatedFat: 0, sodium: 920, sugar: 0 },
  },

  // ─── VINEGAR ─────────────────────────────────────────────────────────────────
  {
    id: "bragg-apple-cider-vinegar",
    name: "Organic Apple Cider Vinegar with Mother",
    brand: "Bragg",
    category: "Vinegar",
    qualityTier: "elite",
    score: 99,
    barcode: "0074305000002",
    imageUrl: "/manus-storage/condiment-organic-apple-cider-vinegar-with-mother-by-bragg_dac795c6.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: true,
    nonGMO: true,
    concerns: ["Strong taste — dilute before drinking", "May erode tooth enamel if consumed undiluted"],
    benefits: [
      "USDA Organic",
      "Contains 'mother' — beneficial enzymes and probiotics",
      "Supports blood sugar regulation",
      "Antimicrobial properties",
      "Supports gut health",
    ],
    buyTip: "The gold standard ACV. Available everywhere. Use in dressings, marinades, or diluted as a health tonic.",
    averagePrice: 5.99,
    ingredients: "Organic Raw Apple Cider Vinegar.",
    nutrients: { calories: 0, fat: 0, saturatedFat: 0, sodium: 0, sugar: 0 },
  },
  // ─── MORE PRIMAL KITCHEN PRODUCTS ──────────────────────────────────────
  {
    id: "primal-kitchen-buffalo-sauce",
    name: "Original Buffalo Sauce",
    brand: "Primal Kitchen",
    category: "Hot Sauce",
    qualityTier: "elite",
    score: 92,
    barcode: "0863699000184",
    imageUrl: "/manus-storage/condiment-fix2-primal-kitchen-original-buffalo-sauce-bottle_72bc4113.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: true,
    concerns: ["Not organic", "Contains cashew butter (tree nut allergen)"],
    benefits: [
      "No seed oils — uses avocado oil",
      "No dairy (unlike most buffalo sauces)",
      "Whole30 Approved",
      "Paleo and Keto certified",
      "Rich, creamy texture without butter",
    ],
    buyTip: "Best clean buffalo sauce on the market. Great for wings, cauliflower bites, and dipping. Available at most grocery stores.",
    averagePrice: 7.99,
    ingredients: "Cayenne pepper sauce (aged cayenne peppers, vinegar, salt), avocado oil, cashew butter, lemon juice, garlic, onion, paprika, black pepper.",
    nutrients: { calories: 35, fat: 3, saturatedFat: 0, sodium: 290, sugar: 0 },
  },
  {
    id: "primal-kitchen-caesar-dressing",
    name: "Caesar Dressing",
    brand: "Primal Kitchen",
    category: "Salad Dressings",
    qualityTier: "elite",
    score: 90,
    barcode: "0863699000108",
    imageUrl: "/manus-storage/condiment-caesar-dressing-by-primal-kitchen_110ebb8b.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: true,
    nonGMO: true,
    concerns: ["Contains cage-free eggs (allergen)", "Premium price"],
    benefits: [
      "Made with avocado oil",
      "Organic ingredients",
      "No seed oils",
      "No sugar added",
      "Whole30 Approved",
    ],
    buyTip: "The best clean Caesar dressing available. Creamy, tangy, and made with real avocado oil instead of soybean oil.",
    averagePrice: 8.49,
    ingredients: "Avocado oil, organic distilled vinegar, organic cage-free eggs, organic lemon juice, salt, organic garlic, anchovy extract, organic black pepper, organic rosemary extract.",
    nutrients: { calories: 100, fat: 11, saturatedFat: 1.5, sodium: 190, sugar: 0 },
  },
  {
    id: "primal-kitchen-italian-dressing",
    name: "Italian Vinaigrette & Marinade",
    brand: "Primal Kitchen",
    category: "Salad Dressings",
    qualityTier: "elite",
    score: 91,
    barcode: "0863699000122",
    imageUrl: "/manus-storage/condiment-pk-italian-dressing_9578f27f.png",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: true,
    nonGMO: true,
    concerns: ["Premium price"],
    benefits: [
      "Made with avocado oil",
      "Organic herbs and spices",
      "No sugar added",
      "Doubles as a marinade",
      "Whole30 Approved",
    ],
    buyTip: "Versatile — use as salad dressing or meat/veggie marinade. One of their best-selling products for good reason.",
    averagePrice: 8.49,
    ingredients: "Avocado oil, organic distilled vinegar, organic lemon juice, salt, organic garlic, organic onion, organic oregano, organic basil, organic black pepper, organic rosemary extract.",
    nutrients: { calories: 90, fat: 10, saturatedFat: 1, sodium: 170, sugar: 0 },
  },
  {
    id: "primal-kitchen-steak-sauce",
    name: "Organic Steak Sauce",
    brand: "Primal Kitchen",
    category: "Other",
    qualityTier: "elite",
    score: 89,
    barcode: "0863699000351",
    imageUrl: "/manus-storage/condiment-organic-steak-sauce-by-primal-kitchen_332959a1.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: true,
    nonGMO: true,
    concerns: ["Contains coconut aminos (may taste different from traditional)"],
    benefits: [
      "USDA Organic",
      "No sugar added",
      "No seed oils",
      "No artificial anything",
      "Whole30 Approved",
    ],
    buyTip: "Clean alternative to A1 steak sauce (which contains corn syrup and caramel color). Great on steaks, burgers, and roasted veggies.",
    averagePrice: 7.49,
    ingredients: "Organic balsamic vinegar, organic coconut aminos, organic tomato paste, organic distilled vinegar, organic date paste, organic onion, organic garlic, salt, organic spices.",
    nutrients: { calories: 10, fat: 0, saturatedFat: 0, sodium: 150, sugar: 2 },
  },
  {
    id: "primal-kitchen-mayo-chipotle",
    name: "Chipotle Lime Avocado Oil Mayo",
    brand: "Primal Kitchen",
    category: "Mayonnaise",
    qualityTier: "elite",
    score: 91,
    barcode: "0863699000047",
    imageUrl: "/manus-storage/condiment-pk-chipotle-lime-mayo_4b1a8618.png",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: true,
    nonGMO: true,
    concerns: ["Contains eggs (allergen)", "Spicy — not for everyone"],
    benefits: [
      "Made with avocado oil",
      "Organic cage-free eggs",
      "No sugar added",
      "Keto and Paleo certified",
      "Great smoky flavor without artificial smoke",
    ],
    buyTip: "Amazing on tacos, burgers, and as a spicy dipping sauce. One of their most popular flavored mayos.",
    averagePrice: 8.99,
    ingredients: "Avocado oil, organic cage-free eggs, organic distilled vinegar, organic lime juice, salt, organic chipotle pepper, organic garlic, organic rosemary extract.",
    nutrients: { calories: 100, fat: 11, saturatedFat: 1.5, sodium: 125, sugar: 0 },
  },
  {
    id: "primal-kitchen-special-sauce",
    name: "Special Sauce",
    brand: "Primal Kitchen",
    category: "Other",
    qualityTier: "elite",
    score: 88,
    barcode: "0863699000269",
    imageUrl: "/manus-storage/condiment-pk-special-sauce_44beea9e.png",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: true,
    nonGMO: true,
    concerns: ["Contains eggs (allergen)", "Higher calorie as a condiment"],
    benefits: [
      "Made with avocado oil",
      "No seed oils",
      "No sugar added",
      "Whole30 Approved",
      "Great Big Mac sauce alternative",
    ],
    buyTip: "Clean version of Thousand Island / Big Mac sauce. Perfect for burgers, wraps, and dipping fries.",
    averagePrice: 7.99,
    ingredients: "Avocado oil, organic cage-free eggs, organic distilled vinegar, organic tomato paste, organic pickles, salt, organic mustard, organic onion, organic garlic, organic spices.",
    nutrients: { calories: 90, fat: 10, saturatedFat: 1, sodium: 180, sugar: 1 },
  },
  {
    id: "primal-kitchen-yum-yum-sauce",
    name: "Yum Yum Sauce",
    brand: "Primal Kitchen",
    category: "Other",
    qualityTier: "elite",
    score: 87,
    barcode: "0863699000399",
    imageUrl: "/manus-storage/condiment-yum-yum-sauce-by-primal-kitchen_f701d5f7.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: true,
    concerns: ["Not organic", "Contains eggs (allergen)"],
    benefits: [
      "Made with avocado oil",
      "No seed oils",
      "No sugar added",
      "Clean hibachi-style dipping sauce",
      "Keto and Paleo certified",
    ],
    buyTip: "Clean alternative to Japanese steakhouse yum yum sauce (which is typically made with soybean oil). Great with stir-fry and rice bowls.",
    averagePrice: 7.99,
    ingredients: "Avocado oil, cage-free eggs, distilled vinegar, tomato paste, water, paprika, garlic, onion, salt, black pepper.",
    nutrients: { calories: 90, fat: 10, saturatedFat: 1, sodium: 160, sugar: 0 },
  },
  {
    id: "primal-kitchen-avocado-oil-spray",
    name: "Avocado Oil Spray",
    brand: "Primal Kitchen",
    category: "Cooking Oils",
    qualityTier: "elite",
    score: 93,
    barcode: "0863699000412",
    imageUrl: "/manus-storage/condiment-fix-primal-kitchen-avocado-oil-spray-can_170fde78.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasArtificialIngredients: false,
    organic: false,
    nonGMO: true,
    coldPressed: true,
    smokePoint: 500,
    concerns: ["Propellant used (non-toxic but present)", "Not organic"],
    benefits: [
      "Pure avocado oil — single ingredient",
      "500°F smoke point",
      "No soy lecithin (unlike PAM)",
      "No dimethyl silicone",
      "Convenient spray format",
    ],
    buyTip: "Best cooking spray available. PAM and other sprays contain soy lecithin and dimethyl silicone. This is just avocado oil.",
    averagePrice: 8.99,
    ingredients: "Avocado oil, propellant.",
    nutrients: { calories: 10, fat: 1, saturatedFat: 0, sodium: 0, sugar: 0 },
  },
];
