/**
 * EatVera — Comprehensive US Dairy & Eggs Database
 * Quality ratings based on:
 * - A1 vs A2 milk protein type
 * - Pasture-raised / grass-fed status
 * - rBGH / rBST hormone use
 * - Antibiotic policies
 * - Animal welfare certifications
 * - Processing level (raw, pasteurized, ultra-pasteurized)
 * - Organic certification
 * - Fat content and nutrient density
 */

export type DairyQualityTier = "elite" | "good" | "average" | "poor" | "avoid";
export type DairyCategory =
  | "Milk"
  | "Cheese"
  | "Yogurt"
  | "Butter & Ghee"
  | "Eggs"
  | "Cream & Half-and-Half"
  | "Ice Cream & Frozen"
  | "Plant-Based";

export interface DairyEntry {
  id: string;
  name: string;
  brand: string;
  category: DairyCategory;
  qualityTier: DairyQualityTier;
  score: number;
  barcode?: string;
  /** A1 vs A2 milk protein type */
  milkType?: "A1" | "A2" | "A1/A2" | "N/A";
  pastureRaised: boolean;
  grassFed: boolean;
  organic: boolean;
  hormoneFree: boolean;
  antibioticFree: boolean;
  /** Ultra-pasteurized destroys more nutrients */
  ultraPasteurized?: boolean;
  certifications: string[];
  concerns: string[];
  benefits: string[];
  ingredients?: string;
  buyTip: string;
  averagePrice?: number;
  imageUrl?: string;
  nutrients?: {
    calories?: number;
    protein?: number;
    fat?: number;
    saturatedFat?: number;
    carbs?: number;
    calcium?: number; // mg
    vitaminD?: number; // IU
    vitaminK2?: boolean;
    omega3?: boolean;
    CLA?: boolean;
    imageUrl?: string;
};
}

export const DAIRY_QUALITY_TIER_CONFIG: Record<
  DairyQualityTier,
  { label: string; color: string; bg: string; border: string; score: string }
> = {
  elite: { label: "Elite", color: "#145A3A", bg: "#F0FAF2", border: "#86d086", score: "85–100" },
  good: { label: "Good", color: "#3FA34D", bg: "#F0FAF2", border: "#b8e8b8", score: "65–84" },
  average: { label: "Average", color: "#d97706", bg: "#fffbf0", border: "#fde68a", score: "45–64" },
  poor: { label: "Poor", color: "#ea580c", bg: "#fff7f0", border: "#fed7aa", score: "25–44" },
  avoid: { label: "Avoid", color: "#dc2626", bg: "#fff5f5", border: "#fca5a5", score: "0–24" },
};

export const DAIRY_CATEGORIES: { id: string; label: string }[] = [
  { id: "all", label: "All" },
  { id: "Milk", label: "Milk" },
  { id: "Eggs", label: "Eggs" },
  { id: "Butter & Ghee", label: "Butter & Ghee" },
  { id: "Cheese", label: "Cheese" },
  { id: "Yogurt", label: "Yogurt" },
  { id: "Cream & Half-and-Half", label: "Cream" },
  { id: "Ice Cream & Frozen", label: "Ice Cream" },
  { id: "Plant-Based", label: "Plant-Based" },
];

export function getDairyColor(score: number): string {
  if (score >= 85) return "#145A3A";
  if (score >= 70) return "#3FA34D";
  if (score >= 55) return "#65a30d";
  if (score >= 40) return "#d97706";
  if (score >= 25) return "#ea580c";
  return "#dc2626";
}

export const ALL_DAIRY: DairyEntry[] = [
  // ─── MILK ───────────────────────────────────────────────────────────────────
  {
    id: "a2-whole-milk",
    name: "A2 Whole Milk",
    brand: "a2 Milk",
    category: "Milk",
    qualityTier: "elite",
    score: 92,
    barcode: "0810021970014",
    imageUrl: "https://images.openfoodfacts.org/images/products/081/326/702/0007/front_en.23.200.jpg",
    milkType: "A2",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: true,
    antibioticFree: true,
    ultraPasteurized: false,
    certifications: ["A2 Certified", "rBST-Free"],
    concerns: ["Not organic", "Not pasture-raised", "Conventional feed"],
    benefits: [
      "Pure A2 beta-casein protein — easier to digest",
      "No A1 protein linked to digestive discomfort",
      "rBST hormone-free",
      "Full-fat — retains fat-soluble vitamins",
    ],
    buyTip: "Best choice for those with dairy sensitivities. Available at most major US grocery chains.",
    averagePrice: 6.99,
    nutrients: { calories: 150, protein: 8, fat: 8, saturatedFat: 5, carbs: 12, calcium: 300, vitaminD: 120 },
  },
  {
    id: "organic-valley-whole-milk",
    name: "Organic Whole Milk",
    brand: "Organic Valley",
    category: "Milk",
    qualityTier: "elite",
    score: 91,
    barcode: "0093966001001",
    imageUrl: "/manus-storage/dairy-organic-whole-milk-by-organic-valley_e4a09f5a.jpg",
    milkType: "A1/A2",
    pastureRaised: true,
    grassFed: true,
    organic: true,
    hormoneFree: true,
    antibioticFree: true,
    ultraPasteurized: false,
    certifications: ["USDA Organic", "Certified Humane", "Non-GMO Project"],
    concerns: ["A1/A2 mix — not pure A2", "Slightly higher price"],
    benefits: [
      "USDA Certified Organic",
      "Pasture-raised — higher CLA and omega-3",
      "No synthetic hormones or antibiotics",
      "Non-GMO feed",
      "Farmer-owned cooperative",
    ],
    buyTip: "One of the best conventional organic milks. Available at Whole Foods, Costco, and most grocery chains.",
    averagePrice: 7.49,
    nutrients: { calories: 150, protein: 8, fat: 8, saturatedFat: 5, carbs: 12, calcium: 300, vitaminD: 120, CLA: true, omega3: true },
  },
  {
    id: "maple-hill-grassfed-milk",
    name: "100% Grass-Fed Whole Milk",
    brand: "Maple Hill",
    category: "Milk",
    qualityTier: "elite",
    score: 95,
    barcode: "0815369010003",
    imageUrl: "/manus-storage/dairy-fix-maple-hill-100-grass-fed-whole-milk-bottle_5432f1a1.jpg",
    milkType: "A1/A2",
    pastureRaised: true,
    grassFed: true,
    organic: true,
    hormoneFree: true,
    antibioticFree: true,
    ultraPasteurized: false,
    certifications: ["USDA Organic", "100% Grass-Fed", "Certified Humane"],
    concerns: ["Premium price", "Limited availability in some regions"],
    benefits: [
      "100% grass-fed — highest CLA content",
      "Certified Humane pasture-raised",
      "USDA Organic",
      "Higher omega-3 fatty acids than conventional",
      "Richer in fat-soluble vitamins A, D, K2",
    ],
    buyTip: "Top-tier milk. Find at Whole Foods, Sprouts, and specialty health stores.",
    averagePrice: 8.99,
    nutrients: { calories: 150, protein: 8, fat: 8, saturatedFat: 5, carbs: 12, calcium: 300, vitaminD: 120, CLA: true, omega3: true, vitaminK2: true },
  },
  {
    id: "horizon-organic-milk",
    name: "Organic Whole Milk",
    brand: "Horizon Organic",
    category: "Milk",
    qualityTier: "average",
    score: 58,
    barcode: "0742365100010",
    imageUrl: "/manus-storage/dairy-fix-horizon-organic-whole-milk-carton_17ce0fdd.jpg",
    milkType: "A1/A2",
    pastureRaised: false,
    grassFed: false,
    organic: true,
    hormoneFree: true,
    antibioticFree: true,
    ultraPasteurized: true,
    certifications: ["USDA Organic"],
    concerns: [
      "Ultra-pasteurized — destroys beneficial enzymes",
      "Not truly pasture-raised despite organic label",
      "Owned by Danone — large corporate dairy",
      "Cows may spend minimal time on pasture",
    ],
    benefits: ["USDA Organic certified", "No synthetic hormones", "Widely available"],
    buyTip: "Better than conventional but not as good as Organic Valley or Maple Hill. The ultra-pasteurization is a significant downside.",
    nutrients: { calories: 150, protein: 8, fat: 8, saturatedFat: 5, carbs: 12, calcium: 300, vitaminD: 120 },
  },
  {
    id: "fairlife-whole-milk",
    name: "Whole Milk Ultra-Filtered",
    brand: "Fairlife",
    category: "Milk",
    qualityTier: "average",
    score: 52,
    barcode: "0611269991009",
    imageUrl: "/manus-storage/dairy-fix-fairlife-whole-milk-ultra-filtered-bottle_ec074500.jpg",
    milkType: "A1/A2",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: true,
    antibioticFree: true,
    ultraPasteurized: true,
    certifications: ["rBST-Free"],
    concerns: [
      "Ultra-filtered and ultra-pasteurized — highly processed",
      "Owned by Coca-Cola",
      "Animal welfare concerns raised by investigators",
      "Not organic",
      "Heavily marketed as 'better' but highly processed",
    ],
    benefits: ["Higher protein than regular milk (13g)", "Lactose-free", "No added sugar"],
    buyTip: "If you need lactose-free, choose Organic Valley Lactose-Free instead. Fairlife's processing and corporate ownership are concerns.",
    averagePrice: 5.99,
    nutrients: { calories: 150, protein: 13, fat: 8, saturatedFat: 5, carbs: 6, calcium: 380, vitaminD: 120 },
  },
  {
    id: "store-brand-conventional-milk",
    name: "Whole Milk (Conventional)",
    brand: "Store Brand / Generic",
    category: "Milk",
    qualityTier: "poor",
    score: 35,
    barcode: "0000000000000",
    imageUrl: "http://www.aveda.co.uk/media/images/products/600x600/000000000000_FRONT.jpg",
    milkType: "A1/A2",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: false,
    antibioticFree: false,
    ultraPasteurized: false,
    certifications: [],
    concerns: [
      "May contain rBGH/rBST synthetic growth hormones",
      "Antibiotic residues possible",
      "CAFO conditions — cows rarely see pasture",
      "A1 dominant — harder to digest",
      "Pesticide residues from GMO feed",
    ],
    benefits: ["Affordable", "Widely available", "Provides calcium and protein"],
    buyTip: "This milk scored lower due to the potential presence of rBGH/rBST synthetic growth hormones and the use of CAFO (concentrated animal feeding operation) practices where cows typically have limited pasture access. It is also predominantly A1 beta-casein, which some research suggests may be harder to digest than A2 milk.",
    averagePrice: 3.99,
    nutrients: { calories: 150, protein: 8, fat: 8, saturatedFat: 5, carbs: 12, calcium: 300, vitaminD: 120 },
  },

  // ─── EGGS ────────────────────────────────────────────────────────────────────
  {
    id: "vital-farms-pasture-raised-eggs",
    name: "Pasture Raised Eggs",
    brand: "Vital Farms",
    category: "Eggs",
    qualityTier: "elite",
    score: 97,
    barcode: "0812717010004",
    imageUrl: "https://images.openfoodfacts.org/images/products/085/138/700/7416/front_en.32.200.jpg",
    milkType: "N/A",
    pastureRaised: true,
    grassFed: false,
    organic: false,
    hormoneFree: true,
    antibioticFree: true,
    certifications: ["Certified Humane", "Pasture Raised (108 sq ft/hen)"],
    concerns: ["Premium price", "Not organic (but pasture-raised is more important for eggs)"],
    benefits: [
      "108 sq ft per hen — true pasture access",
      "Certified Humane",
      "Higher omega-3 and vitamin D from foraging",
      "Deeper orange yolks — more nutrients",
      "2x vitamin E of caged eggs",
    ],
    buyTip: "The gold standard for eggs. Available at Whole Foods, Target, Kroger, and most major chains. Worth every penny.",
    averagePrice: 8.99,
    nutrients: { calories: 70, protein: 6, fat: 5, saturatedFat: 1.5, carbs: 0, vitaminD: 41, omega3: true, vitaminK2: true },
  },
  {
    id: "pete-and-gerrys-organic-eggs",
    name: "Organic Free Range Eggs",
    brand: "Pete and Gerry's",
    category: "Eggs",
    qualityTier: "elite",
    score: 91,
    barcode: "0081312100007",
    imageUrl: "/manus-storage/dairy-organic-free-range-eggs-by-pete-and-gerry-s_00b71d32.webp",
    milkType: "N/A",
    pastureRaised: false,
    grassFed: false,
    organic: true,
    hormoneFree: true,
    antibioticFree: true,
    certifications: ["USDA Organic", "Certified Humane", "Non-GMO Project"],
    concerns: ["Free-range, not full pasture-raised", "Less outdoor access than Vital Farms"],
    benefits: [
      "USDA Organic certified",
      "Certified Humane",
      "Non-GMO feed",
      "No antibiotics or hormones",
      "Family-farm network",
    ],
    buyTip: "Excellent organic option. Available at most major grocery chains. Great value for organic.",
    averagePrice: 7.99,
    nutrients: { calories: 70, protein: 6, fat: 5, saturatedFat: 1.5, carbs: 0, vitaminD: 41, omega3: true },
  },
  {
    id: "happy-egg-free-range",
    name: "Free Range Eggs",
    brand: "Happy Egg",
    category: "Eggs",
    qualityTier: "good",
    score: 78,
    barcode: "0856087005003",
    imageUrl: "/manus-storage/dairy-fix-happy-egg-free-range-eggs-carton_a0025b7f.jpg",
    milkType: "N/A",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: true,
    antibioticFree: true,
    certifications: ["Certified Humane", "Free Range"],
    concerns: ["Not organic", "Free-range but not full pasture-raised", "Conventional feed"],
    benefits: ["Certified Humane", "Genuine free-range access", "No antibiotics", "Good value"],
    buyTip: "Good mid-range option. Better than cage-free or conventional.",
    averagePrice: 5.99,
    nutrients: { calories: 70, protein: 6, fat: 5, saturatedFat: 1.5, carbs: 0 },
  },
  {
    id: "egglands-best-eggs",
    name: "Cage Free Eggs",
    brand: "Eggland's Best",
    category: "Eggs",
    qualityTier: "average",
    score: 50,
    barcode: "0071700700015",
    imageUrl: "/manus-storage/dairy-fix-egglands-best-cage-free_bd68d474.jpg",
    milkType: "N/A",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: true,
    antibioticFree: false,
    certifications: ["Cage Free"],
    concerns: [
      "Cage-free does NOT mean outdoor access",
      "Hens still confined indoors",
      "Proprietary feed blend — not transparent",
      "Antibiotic use not fully disclosed",
      "Marketing overstates quality",
    ],
    benefits: ["Better than conventional caged eggs", "Higher vitamin E claimed", "Widely available"],
    buyTip: "Cage-free certification means hens are not kept in battery cages, but it does not require outdoor access. Hens are still typically housed indoors in large flocks. The score reflects the absence of pasture access and limited transparency around the feed and antibiotic protocols used.",
    averagePrice: 4.49,
    nutrients: { calories: 70, protein: 6, fat: 4, saturatedFat: 1.5, carbs: 1 },
  },
  {
    id: "store-brand-conventional-eggs",
    name: "Large White Eggs (Conventional)",
    brand: "Store Brand",
    category: "Eggs",
    qualityTier: "poor",
    score: 28,
    barcode: "0000000000001",
    imageUrl: "/manus-storage/dairy-large-white-eggs-conventional-by-store-brand_ace72bde.jpg",
    milkType: "N/A",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: false,
    antibioticFree: false,
    certifications: [],
    concerns: [
      "Battery cage conditions — 67 sq in per hen",
      "Routine antibiotic use",
      "GMO corn/soy feed",
      "Pale yolks — nutrient-poor",
      "No outdoor access",
      "Debeaking common practice",
    ],
    benefits: ["Very affordable", "Widely available"],
    buyTip: "Conventional eggs scored lower due to battery cage housing (approximately 67 square inches per hen), routine antibiotic use, and GMO corn/soy feed. These conditions are associated with lower yolk nutrient density compared to pasture-raised eggs, which have access to insects and grasses.",
    nutrients: { calories: 70, protein: 6, fat: 5, saturatedFat: 1.5, carbs: 0 },
  },

  // ─── BUTTER & GHEE ──────────────────────────────────────────────────────────
  {
    id: "kerrygold-butter",
    name: "Pure Irish Butter",
    brand: "Kerrygold",
    category: "Butter & Ghee",
    qualityTier: "elite",
    score: 95,
    barcode: "0767707000001",
    imageUrl: "https://images.openfoodfacts.org/images/products/500/016/502/4014/front_en.20.200.jpg",
    milkType: "A1/A2",
    pastureRaised: true,
    grassFed: true,
    organic: false,
    hormoneFree: true,
    antibioticFree: true,
    certifications: ["Grass-Fed (Irish pasture standard)", "Non-GMO"],
    concerns: ["Not USDA Organic certified", "A1/A2 mix (Irish cows)", "Not certified humane (though pasture-raised)"],
    benefits: [
      "Irish cows graze 312 days/year on pasture",
      "Significantly higher CLA than US butter",
      "Rich in vitamin K2 (MK-4)",
      "Higher beta-carotene — deep yellow color",
      "No synthetic hormones or antibiotics",
    ],
    buyTip: "Best widely-available butter in the US. The gold standard. Available at Costco, Trader Joe's, and most grocery stores.",
    averagePrice: 5.49,
    ingredients: "Pasteurized Cream, Salt.",
    nutrients: { calories: 100, fat: 11, saturatedFat: 7, carbs: 0, vitaminK2: true, CLA: true },
  },
  {
    id: "organic-valley-pasture-butter",
    name: "Pasture Butter",
    brand: "Organic Valley",
    category: "Butter & Ghee",
    qualityTier: "elite",
    score: 93,
    barcode: "0093966000004",
    imageUrl: "https://images.openfoodfacts.org/images/products/009/396/600/3857/front_en.3.200.jpg",
    milkType: "A1/A2",
    pastureRaised: true,
    grassFed: true,
    organic: true,
    hormoneFree: true,
    antibioticFree: true,
    certifications: ["USDA Organic", "Certified Humane", "Non-GMO Project"],
    concerns: ["Premium price", "Seasonal — pasture butter availability varies"],
    benefits: [
      "USDA Organic + pasture-raised",
      "Highest CLA content of any US butter",
      "Certified Humane",
      "Rich in fat-soluble vitamins",
      "Farmer-owned cooperative",
    ],
    buyTip: "The best US organic butter. Available at Whole Foods and specialty stores. Seasonal availability.",
    averagePrice: 6.99,
    ingredients: "Organic Pasteurized Cream, Salt.",
    nutrients: { calories: 100, fat: 11, saturatedFat: 7, carbs: 0, vitaminK2: true, CLA: true, omega3: true },
  },
  {
    id: "fourth-and-heart-ghee",
    name: "Original Grass-Fed Ghee",
    brand: "Fourth & Heart",
    category: "Butter & Ghee",
    qualityTier: "elite",
    score: 96,
    barcode: "0852232006001",
    imageUrl: "/manus-storage/dairy-fix-fourth-and-heart-ghee-butter-jar_f4f69631.jpg",
    milkType: "A2",
    pastureRaised: true,
    grassFed: true,
    organic: false,
    hormoneFree: true,
    antibioticFree: true,
    certifications: ["Grass-Fed", "Certified Humane", "Non-GMO Project"],
    concerns: ["Not organic", "Premium price"],
    benefits: [
      "Made from A2 grass-fed butter",
      "Clarified — lactose and casein removed",
      "High smoke point (485°F) — stable for cooking",
      "Rich in butyrate — gut health",
      "Certified Humane",
    ],
    buyTip: "Best ghee for cooking. Lactose-free and casein-free. Available at Whole Foods and Amazon.",
    averagePrice: 11.99,
    ingredients: "Grass-Fed Butter (Pasteurized Cream).",
    nutrients: { calories: 130, fat: 14, saturatedFat: 9, carbs: 0, vitaminK2: true, CLA: true },
  },
  {
    id: "land-o-lakes-butter",
    name: "Salted Butter",
    brand: "Land O'Lakes",
    category: "Butter & Ghee",
    qualityTier: "average",
    score: 48,
    barcode: "0070882000003",
    imageUrl: "/manus-storage/dairy-salted-butter-by-land-o-lakes_8797c969.jpg",
    milkType: "A1/A2",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: false,
    antibioticFree: false,
    certifications: [],
    concerns: [
      "Conventional CAFO dairy",
      "rBST hormones may be used",
      "No pasture access",
      "GMO feed",
      "Lower CLA and omega-3 than grass-fed",
    ],
    benefits: ["Affordable", "Widely available", "Real butter (not margarine)"],
    buyTip: "This butter scored lower because it comes from conventional CAFO dairy where cows typically do not have pasture access. Grass-fed butter contains significantly more CLA (conjugated linoleic acid) and omega-3 fatty acids than conventional butter. The ingredients are clean — just cream and salt.",
    averagePrice: 4.29,
    ingredients: "Cream, Salt.",
    nutrients: { calories: 100, fat: 11, saturatedFat: 7, carbs: 0 },
  },
  {
    id: "country-crock-margarine",
    name: "Original Spread",
    brand: "Country Crock",
    category: "Butter & Ghee",
    qualityTier: "avoid",
    score: 12,
    barcode: "0011110000001",
    imageUrl: "/manus-storage/dairy-original-spread-by-country-crock_c25d8821.jpg",
    milkType: "N/A",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: true,
    antibioticFree: true,
    certifications: [],
    concerns: [
      "Contains seed oils (soybean oil, palm oil)",
      "Highly processed — industrial emulsification",
      "Artificial flavors",
      "Not real food — engineered to mimic butter",
      "Inflammatory omega-6 seed oils",
    ],
    benefits: ["Affordable", "Spreadable from fridge"],
    buyTip: "This spread scored very low due to its primary ingredients: soybean oil and palm oil. Unlike butter, it contains no dairy fat. The soybean oil is high in omega-6 linoleic acid, and the product requires industrial processing and emulsification to achieve a butter-like texture.",
    ingredients: "Soybean Oil, Palm Oil, Water, Salt, Natural Flavor, Soy Lecithin, Vitamin A Palmitate.",
    nutrients: { calories: 80, fat: 9, saturatedFat: 2.5, carbs: 0 },
  },

  // ─── CHEESE ─────────────────────────────────────────────────────────────────
  {
    id: "organic-valley-raw-cheddar",
    name: "Raw Milk Sharp Cheddar",
    brand: "Organic Valley",
    category: "Cheese",
    qualityTier: "elite",
    score: 94,
    barcode: "0093966002008",
    imageUrl: "/manus-storage/dairy-raw-milk-sharp-cheddar-by-organic-valley_a547005d.jpg",
    milkType: "A1/A2",
    pastureRaised: true,
    grassFed: true,
    organic: true,
    hormoneFree: true,
    antibioticFree: true,
    certifications: ["USDA Organic", "Raw Milk (aged 60+ days)", "Non-GMO Project"],
    concerns: ["Raw milk — not recommended for immunocompromised", "Premium price"],
    benefits: [
      "Raw milk retains beneficial enzymes and probiotics",
      "Aged 60+ days (USDA requirement for raw cheese safety)",
      "USDA Organic",
      "Pasture-raised cows",
      "Rich in CLA, K2, and fat-soluble vitamins",
    ],
    buyTip: "Best cheddar available. Find at Whole Foods and specialty cheese shops.",
    averagePrice: 8.99,
    ingredients: "Organic Pasteurized Whole Milk, Salt, Cheese Cultures, Enzymes.",
    nutrients: { calories: 110, protein: 7, fat: 9, saturatedFat: 5, carbs: 0, calcium: 200, vitaminK2: true, CLA: true },
  },
  {
    id: "tillamook-medium-cheddar",
    name: "Medium Cheddar",
    brand: "Tillamook",
    category: "Cheese",
    qualityTier: "good",
    score: 72,
    barcode: "0072830000001",
    imageUrl: "/manus-storage/dairy-medium-cheddar-by-tillamook_fc1d6d17.png",
    milkType: "A1/A2",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: true,
    antibioticFree: true,
    certifications: ["rBST-Free", "Farmer-Owned Cooperative"],
    concerns: ["Not organic", "Not pasture-raised", "Conventional feed"],
    benefits: [
      "rBST hormone-free",
      "Farmer-owned cooperative",
      "No artificial colors or preservatives",
      "Real aged cheddar",
      "Good value",
    ],
    buyTip: "Solid everyday cheddar. Much better than Kraft or store brands. Available nationwide.",
    averagePrice: 6.49,
    ingredients: "Pasteurized Milk, Cheese Cultures, Salt, Enzymes.",
    nutrients: { calories: 110, protein: 7, fat: 9, saturatedFat: 5, carbs: 0, calcium: 200 },
  },
  {
    id: "kraft-american-singles",
    name: "American Singles",
    brand: "Kraft",
    category: "Cheese",
    qualityTier: "avoid",
    score: 15,
    barcode: "0021000012619",
    imageUrl: "https://images.openfoodfacts.org/images/products/002/100/061/5261/front_en.47.200.jpg",
    milkType: "A1/A2",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: false,
    antibioticFree: false,
    certifications: [],
    concerns: [
      "Not real cheese — 'processed cheese product'",
      "Contains sodium citrate, sorbic acid, artificial color",
      "Only 51% real cheese by law",
      "rBGH hormones in milk supply",
      "Highly processed",
    ],
    benefits: ["Melts easily", "Affordable"],
    buyTip: "This product is classified as a \"processed cheese product\" rather than real cheese, meaning it contains less than 51% actual cheese by weight. The remaining ingredients include sodium citrate, sorbic acid, and artificial coloring agents. The score reflects the heavy processing and additives used to achieve its texture and shelf stability.",
    ingredients: "Cheddar Cheese, Whey, Milk Protein Concentrate, Milkfat, Sodium Citrate, Calcium Phosphate, Sorbic Acid, Apocarotenal, Annatto.",
    nutrients: { calories: 60, protein: 4, fat: 4.5, saturatedFat: 2.5, carbs: 2 },
  },

  // ─── YOGURT ─────────────────────────────────────────────────────────────────
  {
    id: "siggis-plain-yogurt",
    name: "Plain Whole Milk Skyr",
    brand: "Siggi's",
    category: "Yogurt",
    qualityTier: "elite",
    score: 93,
    barcode: "0040822011068",
    imageUrl: "https://images.openfoodfacts.org/images/products/004/082/201/1143/front_en.66.200.jpg",
    milkType: "A1/A2",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: true,
    antibioticFree: true,
    certifications: ["rBST-Free", "Non-GMO Project"],
    concerns: ["Not organic", "Not pasture-raised", "Icelandic skyr style — very thick"],
    benefits: [
      "Very high protein (17g per 5.3oz)",
      "Only 4 simple ingredients",
      "No added sugar",
      "Live active cultures",
      "Minimal processing",
    ],
    buyTip: "Best widely-available yogurt for protein and clean ingredients. Available at most major chains.",
    averagePrice: 5.99,
    ingredients: "Cultured Pasteurized Skim Milk, Cream.",
    nutrients: { calories: 110, protein: 17, fat: 4.5, saturatedFat: 3, carbs: 6, calcium: 200 },
  },
  {
    id: "stonyfield-organic-plain",
    name: "Organic Plain Whole Milk Yogurt",
    brand: "Stonyfield",
    category: "Yogurt",
    qualityTier: "elite",
    score: 88,
    barcode: "0052159503001",
    imageUrl: "https://images.openfoodfacts.org/images/products/005/215/900/0011/front_en.34.200.jpg",
    milkType: "A1/A2",
    pastureRaised: false,
    grassFed: false,
    organic: true,
    hormoneFree: true,
    antibioticFree: true,
    certifications: ["USDA Organic", "Non-GMO Project", "B Corp"],
    concerns: ["Not pasture-raised", "Lower protein than Siggi's"],
    benefits: [
      "USDA Organic",
      "6 live active cultures",
      "No artificial ingredients",
      "B Corp certified",
      "Good source of probiotics",
    ],
    buyTip: "Best organic yogurt option. Available at most major grocery chains.",
    averagePrice: 5.49,
    ingredients: "Organic Cultured Pasteurized Whole Milk, Pectin.",
    nutrients: { calories: 150, protein: 9, fat: 8, saturatedFat: 5, carbs: 11, calcium: 300 },
  },
  {
    id: "chobani-plain-greek",
    name: "Plain Non-Fat Greek Yogurt",
    brand: "Chobani",
    category: "Yogurt",
    qualityTier: "good",
    score: 68,
    barcode: "0818290011001",
    imageUrl: "https://images.openfoodfacts.org/images/products/000/004/484/3113/front_en.3.200.jpg",
    milkType: "A1/A2",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: true,
    antibioticFree: true,
    certifications: ["rBST-Free", "Non-GMO Project"],
    concerns: ["Not organic", "Non-fat — removes fat-soluble vitamins", "Conventional dairy"],
    benefits: [
      "rBST-free",
      "High protein (17g)",
      "Live active cultures",
      "No artificial flavors or sweeteners",
      "Widely available",
    ],
    buyTip: "Good everyday option. Choose whole-milk version for better nutrition. Avoid flavored varieties with added sugar.",
    averagePrice: 4.49,
    ingredients: "Cultured Nonfat Milk.",
    nutrients: { calories: 90, protein: 17, fat: 0, saturatedFat: 0, carbs: 6, calcium: 200 },
  },
  {
    id: "yoplait-strawberry-yogurt",
    name: "Original Strawberry Yogurt",
    brand: "Yoplait",
    category: "Yogurt",
    qualityTier: "poor",
    score: 22,
    barcode: "0070470000001",
    imageUrl: "/manus-storage/dairy-original-strawberry-yogurt-by-yoplait_46e83c0c.jpg",
    milkType: "A1/A2",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: false,
    antibioticFree: false,
    certifications: [],
    concerns: [
      "26g added sugar per serving",
      "Artificial colors (Red 40)",
      "Conventional dairy — rBGH hormones",
      "More sugar than a candy bar",
      "Minimal real fruit",
    ],
    benefits: ["Affordable", "Widely available"],
    buyTip: "This yogurt scored low due to 26g of added sugar per serving — higher than many candy bars — and the use of artificial colors (Red 40). The conventional dairy supply also carries the risk of rBGH hormone use. The base yogurt is real dairy, but the added sweeteners and colorings significantly reduce the quality score.",
    averagePrice: 1.29,
    ingredients: "Cultured Pasteurized Grade A Low Fat Milk, Sugar, Strawberries, Modified Corn Starch, High Fructose Corn Syrup, Kosher Gelatin, Citric Acid, Tricalcium Phosphate, Natural Flavor, Pectin, Red 40.",
    nutrients: { calories: 170, protein: 5, fat: 1.5, saturatedFat: 1, carbs: 33 },
  },

  // ─── CREAM & HALF-AND-HALF ──────────────────────────────────────────────────
  {
    id: "organic-valley-heavy-cream",
    name: "Organic Heavy Whipping Cream",
    brand: "Organic Valley",
    category: "Cream & Half-and-Half",
    qualityTier: "elite",
    score: 92,
    barcode: "0093966003005",
    imageUrl: "/manus-storage/dairy-organic-heavy-whipping-cream-by-organic-valley_78fc43c0.jpg",
    milkType: "A1/A2",
    pastureRaised: true,
    grassFed: true,
    organic: true,
    hormoneFree: true,
    antibioticFree: true,
    certifications: ["USDA Organic", "Certified Humane"],
    concerns: ["Premium price", "High in saturated fat (though from healthy source)"],
    benefits: [
      "USDA Organic",
      "Pasture-raised",
      "Rich in CLA and fat-soluble vitamins",
      "No carrageenan or additives",
      "Just one ingredient",
    ],
    buyTip: "Best heavy cream available. Use for coffee, cooking, and whipping.",
    averagePrice: 4.99,
    ingredients: "Organic Pasteurized Heavy Whipping Cream.",
    nutrients: { calories: 50, fat: 5, saturatedFat: 3.5, carbs: 0, CLA: true },
  },
  {
    id: "coffee-mate-original",
    name: "Original Coffee Creamer",
    brand: "Coffee-mate",
    category: "Cream & Half-and-Half",
    qualityTier: "avoid",
    score: 8,
    barcode: "0050000000001",
    imageUrl: "/manus-storage/dairy-original-coffee-creamer-by-coffee-mate_bf817672.jpg",
    milkType: "N/A",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: true,
    antibioticFree: true,
    certifications: [],
    concerns: [
      "Contains corn syrup solids (HFCS adjacent)",
      "Hydrogenated vegetable oil (trans fats)",
      "Sodium caseinate — artificial milk derivative",
      "Dipotassium phosphate — industrial additive",
      "No actual dairy cream",
      "Mono and diglycerides",
    ],
    benefits: ["Shelf-stable", "Affordable"],
    buyTip: "This product scored very low because it contains no actual dairy cream. The primary ingredients are corn syrup solids and hydrogenated vegetable oil. Hydrogenated oils contain trans fats, which the FDA has determined have no safe level of consumption. Sodium caseinate is a processed milk protein derivative used to create a cream-like appearance.",
    ingredients: "Corn Syrup Solids, Hydrogenated Vegetable Oil (Coconut and/or Palm Kernel and/or Soybean), Sodium Caseinate, Dipotassium Phosphate, Mono- and Diglycerides, Silicon Dioxide.",
    nutrients: { calories: 10, fat: 0.5, saturatedFat: 0.5, carbs: 1.5 },
  },

  // ─── ICE CREAM ──────────────────────────────────────────────────────────────
  {
    id: "haagen-dazs-vanilla",
    name: "Vanilla Ice Cream",
    brand: "Häagen-Dazs",
    category: "Ice Cream & Frozen",
    qualityTier: "good",
    score: 70,
    barcode: "0855710006001",
    imageUrl: "/manus-storage/dairy-vanilla-ice-cream-by-haagen-dazs_22cd388f.jpg",
    milkType: "A1/A2",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: false,
    antibioticFree: false,
    certifications: [],
    concerns: ["Conventional dairy", "High sugar (20g)", "rBGH hormones possible"],
    benefits: [
      "Only 5 real ingredients",
      "No artificial flavors or colors",
      "No gums or stabilizers",
      "Real vanilla bean",
    ],
    buyTip: "Best mainstream ice cream for ingredient quality. 5 ingredients only. Avoid flavors with more additives.",
    ingredients: "Cream, Skim Milk, Cane Sugar, Egg Yolks, Vanilla Extract.",
    nutrients: { calories: 270, protein: 5, fat: 18, saturatedFat: 11, carbs: 22 },
  },
  {
    id: "ben-jerrys-cookie-dough",
    name: "Chocolate Chip Cookie Dough",
    brand: "Ben & Jerry's",
    category: "Ice Cream & Frozen",
    qualityTier: "average",
    score: 45,
    barcode: "0043000200063",
    imageUrl: "https://i5.walmartimages.com/asr/3658082d-82bc-4f72-b9ea-dbc2de2d402c.e3335318b012e36e6189eebf0d195f50.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff",
    milkType: "A1/A2",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: true,
    antibioticFree: true,
    certifications: ["Non-GMO Project", "Fairtrade"],
    concerns: ["Very high sugar (32g)", "Contains soy lecithin", "Carrageenan in some varieties", "High calorie"],
    benefits: ["Non-GMO Project Verified", "Fairtrade ingredients", "No rBGH", "B Corp certified"],
    buyTip: "Better than most mainstream ice cream for sourcing, but very high in sugar. Occasional treat only.",
    ingredients: "Cream, Skim Milk, Liquid Sugar, Water, Sugar, Wheat Flour, Butter, Chocolate Chips, Cocoa, Vanilla, Soy Lecithin, Carrageenan.",
    nutrients: { calories: 310, protein: 5, fat: 16, saturatedFat: 10, carbs: 40 },
  },

  // ─── PLANT-BASED ────────────────────────────────────────────────────────────
  {
    id: "malk-oat-milk",
    name: "Unsweetened Oat Milk",
    brand: "MALK",
    category: "Plant-Based",
    qualityTier: "good",
    score: 75,
    barcode: "0854522007001",
    imageUrl: "/manus-storage/dairy-unsweetened-oat-milk-by-malk_dbcf4fbd.jpg",
    milkType: "N/A",
    pastureRaised: false,
    grassFed: false,
    organic: true,
    hormoneFree: true,
    antibioticFree: true,
    certifications: ["USDA Organic", "Non-GMO Project", "Gluten-Free Certified"],
    concerns: ["Lower protein than dairy milk", "Higher carbs", "Oats may spike blood sugar"],
    benefits: [
      "Only 3 ingredients",
      "USDA Organic",
      "No gums, oils, or emulsifiers",
      "Gluten-free certified",
      "Clean label",
    ],
    buyTip: "Best clean-label oat milk. Most oat milks contain rapeseed oil and gums — MALK does not.",
    ingredients: "Filtered Water, Organic Oats, Himalayan Pink Salt.",
    nutrients: { calories: 70, protein: 2, fat: 1.5, saturatedFat: 0, carbs: 12 },
  },
  {
    id: "oatly-oat-milk",
    name: "Original Oat Milk",
    brand: "Oatly",
    category: "Plant-Based",
    qualityTier: "poor",
    score: 30,
    barcode: "0810073640001",
    imageUrl: "/manus-storage/dairy-fix-oatly-original-oat-milk-carton_b103fb6a.jpg",
    milkType: "N/A",
    pastureRaised: false,
    grassFed: false,
    organic: false,
    hormoneFree: true,
    antibioticFree: true,
    certifications: [],
    concerns: [
      "Contains rapeseed oil (seed oil)",
      "Dipotassium phosphate additive",
      "Not organic — conventional oats may have glyphosate",
      "Heavily processed",
      "Owned by Blackstone investment group",
      "High glycemic index",
    ],
    benefits: ["Widely available", "Fortified with vitamins"],
    buyTip: "This oat milk scored lower due to the inclusion of rapeseed (canola) oil, which is high in omega-6 linoleic acid, and the use of non-organic oats, which may contain glyphosate residue. Dipotassium phosphate is added as a stabilizer. The product is also heavily processed compared to minimally processed oat milks.",
    ingredients: "Oat Base (Water, Oats), Rapeseed Oil, Dipotassium Phosphate, Calcium Carbonate, Vitamins.",
    nutrients: { calories: 120, protein: 3, fat: 5, saturatedFat: 0.5, carbs: 16 },
  },
];
