/**
 * EatVera — Frozen Foods Database
 * 100+ US grocery store frozen products rated on:
 * - Seed oil content (canola, soybean, sunflower, corn oil)
 * - Preservatives and artificial additives
 * - Sodium content
 * - Processing level (NOVA classification)
 * - Ingredient quality and sourcing
 * Sources: product labels, EWG, brand transparency
 */

export type FrozenCategory =
  | "all"
  | "meals"
  | "vegetables"
  | "meats"
  | "pizza"
  | "breakfast"
  | "snacks"
  | "desserts"
  | "seafood"
  | "burritos";

export type FrozenQualityTier = "elite" | "good" | "average" | "poor" | "avoid";

export interface FrozenEntry {
  id: string;
  name: string;
  brand: string;
  category: FrozenCategory;
  score: number;
  qualityTier: FrozenQualityTier;
  barcode?: string;
  servingSize?: string;
  hasSeedOils: boolean;
  hasPreservatives: boolean;
  hasArtificialColors: boolean;
  hasArtificialFlavors: boolean;
  hasHighSodium: boolean; // >600mg per serving
  isOrganic: boolean;
  isGlutenFree: boolean;
  novaGroup?: number;
  nutrients?: {
    calories?: number;
    fat?: number;
    sodium?: number;
    protein?: number;
    carbs?: number;
};
  ingredients?: string;
  concerns: string[];
  benefits: string[];
  buyTip: string;
  averagePrice?: number;
  imageUrl?: string;
}

export const FROZEN_QUALITY_TIER_CONFIG: Record<FrozenQualityTier, { label: string; color: string; bg: string; border: string }> = {
  elite: { label: "Elite", color: "#145A3A", bg: "#F0FAF2", border: "#b8e8b8" },
  good: { label: "Good", color: "#2d7d9a", bg: "#f0f8ff", border: "#b8d8e8" },
  average: { label: "Average", color: "#d97706", bg: "#fffbf0", border: "#fde68a" },
  poor: { label: "Poor", color: "#dc6803", bg: "#fff7ed", border: "#fed7aa" },
  avoid: { label: "Avoid", color: "#dc2626", bg: "#fff5f5", border: "#fca5a5" },
};

export const FROZEN_CATEGORIES: { id: FrozenCategory; label: string; emoji: string }[] = [
  { id: "all", label: "All", emoji: "🧊" },
  { id: "meals", label: "Meals", emoji: "🍽️" },
  { id: "vegetables", label: "Vegetables", emoji: "🥦" },
  { id: "meats", label: "Meats", emoji: "🥩" },
  { id: "pizza", label: "Pizza", emoji: "🍕" },
  { id: "breakfast", label: "Breakfast", emoji: "🍳" },
  { id: "seafood", label: "Seafood", emoji: "🐟" },
  { id: "burritos", label: "Burritos", emoji: "🌯" },
  { id: "snacks", label: "Snacks", emoji: "🧆" },
  { id: "desserts", label: "Desserts", emoji: "🍦" },
];

export function getFrozenColor(score: number): string {
  if (score >= 85) return "#145A3A";
  if (score >= 70) return "#2d7d9a";
  if (score >= 50) return "#d97706";
  if (score >= 30) return "#dc6803";
  return "#dc2626";
}

export const ALL_FROZEN: FrozenEntry[] = [
  // ─── FROZEN MEALS ────────────────────────────────────────────────────────
  {
    id: "lean-cuisine-chicken-bowl",
    name: "Chicken & Vegetable Bowl",
    brand: "Lean Cuisine",
    category: "meals",
    score: 28,
    qualityTier: "avoid",
    barcode: "013800145017",
    servingSize: "1 bowl (255g)",
    hasSeedOils: true,
    hasPreservatives: true,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasHighSodium: true,
    isOrganic: false,
    isGlutenFree: false,
    novaGroup: 4,
    nutrients: { calories: 280, fat: 7, sodium: 680, protein: 17, carbs: 38 },
    ingredients: "Cooked Enriched Pasta, Chicken Breast, Broccoli, Carrots, Canola Oil, Modified Corn Starch, Soy Sauce, Natural Flavors, Sodium Phosphate, Caramel Color",
    concerns: [
      "Canola oil (seed oil)",
      "680mg sodium per small serving",
      "Modified corn starch — ultra-processed thickener",
      "Enriched pasta (refined flour)",
      "Sodium phosphate — industrial preservative",
    ],
    benefits: ["17g protein", "Low calorie"],
    buyTip: "This frozen meal scored in the avoid tier because it contains canola oil (a seed oil), modified corn starch, sodium phosphate (an industrial preservative), and 680mg of sodium per small serving. The NOVA Group 4 classification reflects the high degree of processing. The 'healthy' branding does not align with the ingredient list.",
    averagePrice: 4.99,
    imageUrl: "/manus-storage/lean-cuisine-chicken-bowl_0a6e5a25.jpg",
  },
  {
    id: "healthy-choice-power-bowl",
    name: "Unwrapped Burrito Bowl",
    brand: "Healthy Choice",
    category: "meals",
    score: 32,
    qualityTier: "poor",
    barcode: "072655901015",
    servingSize: "1 bowl (283g)",
    hasSeedOils: true,
    hasPreservatives: true,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasHighSodium: true,
    isOrganic: false,
    isGlutenFree: false,
    novaGroup: 4,
    nutrients: { calories: 360, fat: 9, sodium: 590, protein: 20, carbs: 49 },
    ingredients: "Cooked Brown Rice, Black Beans, Chicken Breast, Salsa, Soybean Oil, Corn, Cheddar Cheese, Sour Cream, Modified Food Starch, Natural Flavors",
    concerns: [
      "Soybean oil (seed oil)",
      "Modified food starch",
      "590mg sodium",
      "Ultra-processed despite 'power bowl' marketing",
    ],
    benefits: ["Brown rice", "Black beans", "20g protein"],
    buyTip: "This frozen meal scored in the poor tier because it contains soybean oil (a seed oil), modified food starch, and 590mg of sodium. Despite the 'power bowl' branding, it is classified as NOVA Group 4 (ultra-processed). The brown rice and black beans are positives, but the seed oil and processing level limit the quality score.",
    averagePrice: 4.49,
    imageUrl: "/manus-storage/healthy-choice-power-bowl_cab7538d.jpg",
  },
  {
    id: "amy-organic-burrito",
    name: "Bean & Cheese Burrito",
    brand: "Amy's Kitchen",
    category: "meals",
    score: 62,
    qualityTier: "average",
    barcode: "042272000159",
    servingSize: "1 burrito (170g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: true,
    isOrganic: true,
    isGlutenFree: false,
    novaGroup: 3,
    nutrients: { calories: 290, fat: 8, sodium: 540, protein: 11, carbs: 43 },
    ingredients: "Organic Flour Tortilla, Organic Pinto Beans, Organic Cheddar Cheese, Organic Onions, Organic Tomatoes, Organic Green Chiles, Sea Salt, Organic Spices",
    concerns: ["540mg sodium", "Refined flour tortilla", "Moderate processing"],
    benefits: [
      "USDA Certified Organic",
      "No seed oils",
      "No artificial anything",
      "Real whole food ingredients",
    ],
    buyTip: "Best frozen burrito option. Organic, no seed oils. High sodium — pair with low-sodium sides.",
    averagePrice: 2.49,
    imageUrl: "/manus-storage/amy-organic-burrito_0077c790.jpg",
  },
  {
    id: "stouffers-lasagna",
    name: "Classic Lasagna with Meat Sauce",
    brand: "Stouffer's",
    category: "meals",
    score: 22,
    qualityTier: "avoid",
    barcode: "013800146014",
    servingSize: "1 portion (326g)",
    hasSeedOils: true,
    hasPreservatives: true,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasHighSodium: true,
    isOrganic: false,
    isGlutenFree: false,
    novaGroup: 4,
    nutrients: { calories: 370, fat: 14, sodium: 870, protein: 22, carbs: 38 },
    ingredients: "Cooked Enriched Pasta, Tomato Puree, Beef, Ricotta Cheese, Mozzarella Cheese, Soybean Oil, Modified Food Starch, Salt, Spices, Sodium Phosphate, Caramel Color, Natural Flavors",
    concerns: [
      "870mg sodium — 38% daily value",
      "Soybean oil",
      "Modified food starch",
      "Sodium phosphate",
      "Enriched (refined) pasta",
    ],
    benefits: ["22g protein", "Real beef and cheese"],
    buyTip: "This frozen lasagna scored in the avoid tier because it contains soybean oil, modified food starch, sodium phosphate, and 870mg of sodium per serving — 38% of the daily recommended value. The enriched (refined) pasta and multiple industrial additives contribute to the NOVA Group 4 classification.",
    averagePrice: 4.99,
    imageUrl: "/manus-storage/stouffers-lasagna_e894219f.jpg",
  },
  {
    id: "birds-eye-voila-chicken",
    name: "Garlic Chicken Complete Dinner",
    brand: "Birds Eye Voilà!",
    category: "meals",
    score: 25,
    qualityTier: "avoid",
    barcode: "014500014015",
    servingSize: "1 cup (227g)",
    hasSeedOils: true,
    hasPreservatives: true,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasHighSodium: true,
    isOrganic: false,
    isGlutenFree: false,
    novaGroup: 4,
    nutrients: { calories: 260, fat: 8, sodium: 720, protein: 15, carbs: 33 },
    ingredients: "Pasta, Chicken, Broccoli, Carrots, Canola Oil, Parmesan Cheese, Modified Corn Starch, Natural Flavors, Sodium Phosphate, Garlic, Salt",
    concerns: ["720mg sodium", "Canola oil", "Modified corn starch", "Natural flavors"],
    benefits: ["Vegetables included", "15g protein"],
    buyTip: "This frozen meal scored in the avoid tier because it contains canola oil (a seed oil), modified corn starch, sodium phosphate, and 720mg of sodium per serving. The combination of seed oil, industrial preservatives, and high sodium is what drives the low quality score.",
    averagePrice: 5.49,
    imageUrl: "/manus-storage/birds-eye-voila-chicken_28b840f6.jpg",
  },
  {
    id: "evol-chicken-burrito",
    name: "Chicken & Black Bean Burrito",
    brand: "EVOL",
    category: "burritos",
    score: 55,
    qualityTier: "average",
    barcode: "890456001015",
    servingSize: "1 burrito (170g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: true,
    isOrganic: false,
    isGlutenFree: false,
    novaGroup: 3,
    nutrients: { calories: 300, fat: 8, sodium: 560, protein: 16, carbs: 42 },
    ingredients: "Flour Tortilla, Chicken Breast, Black Beans, Brown Rice, Cheddar Cheese, Salsa, Spices",
    concerns: ["560mg sodium", "Non-organic ingredients", "Refined flour tortilla"],
    benefits: [
      "No seed oils",
      "No artificial additives",
      "Real whole food ingredients",
      "16g protein",
    ],
    buyTip: "Good frozen burrito. No seed oils or artificial additives. Choose organic version when available.",
    imageUrl: "/manus-storage/evol-chicken-burrito_5a6d368b.jpg",
  },

  // ─── FROZEN VEGETABLES ───────────────────────────────────────────────────
  {
    id: "birds-eye-steamfresh-broccoli",
    name: "Steamfresh Broccoli Florets",
    brand: "Birds Eye",
    category: "vegetables",
    score: 88,
    qualityTier: "elite",
    barcode: "014500014282",
    servingSize: "1 cup (85g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: false,
    isOrganic: false,
    isGlutenFree: true,
    novaGroup: 1,
    nutrients: { calories: 30, fat: 0, sodium: 30, protein: 2, carbs: 6 },
    ingredients: "Broccoli",
    concerns: ["Not organic — possible pesticide residue"],
    benefits: [
      "Single ingredient",
      "Flash-frozen preserves nutrients",
      "No additives",
      "Convenient and affordable",
    ],
    buyTip: "Excellent. Frozen broccoli is nutritionally comparable to fresh. Buy organic when budget allows.",
    averagePrice: 2.49,
    imageUrl: "/manus-storage/birds-eye-steamfresh-broccoli_a08e0fc3.jpg",
  },
  {
    id: "cascadian-farm-organic-spinach",
    name: "Organic Cut Spinach",
    brand: "Cascadian Farm",
    category: "vegetables",
    score: 96,
    qualityTier: "elite",
    barcode: "021908502618",
    servingSize: "1 cup (85g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: false,
    isOrganic: true,
    isGlutenFree: true,
    novaGroup: 1,
    nutrients: { calories: 20, fat: 0, sodium: 65, protein: 3, carbs: 3 },
    ingredients: "Organic Spinach",
    concerns: [],
    benefits: [
      "USDA Certified Organic",
      "Single ingredient",
      "Flash-frozen at peak nutrition",
      "Rich in iron, folate, and vitamin K",
    ],
    buyTip: "Perfect. Organic, single ingredient, flash-frozen. Use in smoothies, eggs, or pasta.",
    averagePrice: 2.49,
    imageUrl: "/manus-storage/cascadian-farm-organic-spinach_79479ea7.jpg",
  },
  {
    id: "green-giant-veggie-spirals",
    name: "Zucchini Veggie Spirals",
    brand: "Green Giant",
    category: "vegetables",
    score: 90,
    qualityTier: "elite",
    barcode: "020000116716",
    servingSize: "1 cup (85g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: false,
    isOrganic: false,
    isGlutenFree: true,
    novaGroup: 1,
    nutrients: { calories: 20, fat: 0, sodium: 0, protein: 1, carbs: 4 },
    ingredients: "Zucchini",
    concerns: ["Not organic"],
    benefits: ["Single ingredient", "Great pasta substitute", "Zero sodium", "Very low calorie"],
    buyTip: "Great low-carb pasta alternative. Single ingredient, no additives.",
    averagePrice: 3.99,
    imageUrl: "/manus-storage/green-giant-veggie-spirals_486fb9bd.jpg",
  },
  {
    id: "birds-eye-protein-blend",
    name: "Protein Blend with Edamame",
    brand: "Birds Eye",
    category: "vegetables",
    score: 72,
    qualityTier: "good",
    barcode: "014500016019",
    servingSize: "1 cup (85g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: false,
    isOrganic: false,
    isGlutenFree: true,
    novaGroup: 1,
    nutrients: { calories: 100, fat: 3, sodium: 15, protein: 7, carbs: 12 },
    ingredients: "Edamame, Broccoli, Carrots, Corn",
    concerns: ["Non-organic corn and edamame may be GMO"],
    benefits: ["7g plant protein", "No additives", "Minimal processing"],
    buyTip: "Good protein-rich vegetable blend. Buy organic version to avoid GMO corn and soy.",
    imageUrl: "/manus-storage/birds-eye-protein-blend_85c73dcc.jpg",
  },

  // ─── FROZEN MEATS ────────────────────────────────────────────────────────
  {
    id: "tyson-frozen-chicken-nuggets",
    name: "Chicken Nuggets",
    brand: "Tyson",
    category: "meats",
    score: 22,
    qualityTier: "avoid",
    barcode: "023700038210",
    servingSize: "5 pieces (88g)",
    hasSeedOils: true,
    hasPreservatives: true,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasHighSodium: true,
    isOrganic: false,
    isGlutenFree: false,
    novaGroup: 4,
    nutrients: { calories: 200, fat: 12, sodium: 470, protein: 11, carbs: 13 },
    ingredients: "Chicken, Water, Enriched Flour, Modified Corn Starch, Salt, Spices, Soybean Oil, Sodium Phosphate, Natural Flavor, Extractives of Paprika",
    concerns: [
      "Soybean oil (seed oil)",
      "Modified corn starch",
      "Sodium phosphate",
      "CAFO chicken — antibiotics and hormones",
      "Enriched (refined) flour breading",
    ],
    benefits: ["11g protein"],
    buyTip: "This frozen product scored in the avoid tier because it contains soybean oil (a seed oil), modified corn starch, sodium phosphate (an industrial preservative), and uses conventionally raised chicken from concentrated animal feeding operations (CAFO). The enriched flour breading and multiple additives contribute to the NOVA Group 4 classification.",
    averagePrice: 6.99,
    imageUrl: "/manus-storage/tyson-frozen-chicken-nuggets_7a019d33.jpg",
  },
  {
    id: "applegate-organic-chicken-nuggets",
    name: "Organic Chicken Nuggets",
    brand: "Applegate",
    category: "meats",
    score: 80,
    qualityTier: "good",
    barcode: "025317000015",
    servingSize: "5 pieces (88g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: false,
    isOrganic: true,
    isGlutenFree: false,
    novaGroup: 3,
    nutrients: { calories: 180, fat: 9, sodium: 310, protein: 13, carbs: 12 },
    ingredients: "Organic Chicken Breast, Organic Whole Wheat Flour, Organic Corn Flour, Organic Tapioca Starch, Sea Salt, Organic Spices",
    concerns: ["Whole wheat breading (not grain-free)", "310mg sodium"],
    benefits: [
      "USDA Certified Organic",
      "No seed oils",
      "No antibiotics or hormones",
      "No artificial additives",
      "13g protein",
    ],
    buyTip: "Best frozen chicken nuggets. Organic, no seed oils. Worth the price premium.",
    averagePrice: 8.99,
    imageUrl: "/manus-storage/applegate-organic-chicken-nuggets_f1e2b395.jpg",
  },
  {
    id: "wild-alaskan-salmon-portions",
    name: "Wild Alaskan Salmon Portions",
    brand: "Trident Seafoods",
    category: "seafood",
    score: 92,
    qualityTier: "elite",
    barcode: "041318001015",
    servingSize: "1 portion (113g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: false,
    isOrganic: false,
    isGlutenFree: true,
    novaGroup: 1,
    nutrients: { calories: 180, fat: 8, sodium: 75, protein: 26, carbs: 0 },
    ingredients: "Wild Alaskan Salmon",
    concerns: ["Ensure 'wild-caught' label is verified"],
    benefits: [
      "Wild-caught — no antibiotics or hormones",
      "26g protein per portion",
      "Rich in omega-3 fatty acids (EPA/DHA)",
      "Single ingredient",
      "Flash-frozen at sea for freshness",
    ],
    buyTip: "Excellent. Wild-caught Alaskan salmon is one of the cleanest protein sources available.",
    averagePrice: 12.99,
    imageUrl: "/manus-storage/wild-alaskan-salmon-portions_df0cbfb2.jpg",
  },
  {
    id: "gorton-fish-sticks",
    name: "Crunchy Breaded Fish Sticks",
    brand: "Gorton's",
    category: "seafood",
    score: 30,
    qualityTier: "poor",
    barcode: "044400151015",
    servingSize: "6 sticks (99g)",
    hasSeedOils: true,
    hasPreservatives: true,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasHighSodium: true,
    isOrganic: false,
    isGlutenFree: false,
    novaGroup: 4,
    nutrients: { calories: 250, fat: 13, sodium: 490, protein: 11, carbs: 24 },
    ingredients: "Pollock, Enriched Flour, Soybean Oil, Modified Corn Starch, Salt, Sugar, Sodium Tripolyphosphate, Natural Flavors, Paprika",
    concerns: [
      "Soybean oil",
      "Sodium tripolyphosphate — industrial preservative",
      "Modified corn starch",
      "Enriched flour breading",
      "490mg sodium",
    ],
    benefits: ["Contains real fish (pollock)"],
    buyTip: "This frozen product scored in the poor tier because it contains soybean oil (a seed oil), sodium tripolyphosphate (an industrial preservative used to retain moisture), modified corn starch, and enriched flour breading. The combination of seed oil, industrial preservatives, and refined flour is what drives the low quality score.",
    averagePrice: 5.99,
    imageUrl: "/manus-storage/gorton-fish-sticks_1933b055.jpg",
  },
  {
    id: "vital-choice-wild-shrimp",
    name: "Wild Pacific Shrimp",
    brand: "Vital Choice",
    category: "seafood",
    score: 95,
    qualityTier: "elite",
    barcode: "893830001015",
    servingSize: "4 oz (113g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: false,
    isOrganic: false,
    isGlutenFree: true,
    novaGroup: 1,
    nutrients: { calories: 100, fat: 1, sodium: 120, protein: 23, carbs: 0 },
    ingredients: "Wild Pacific Shrimp",
    concerns: ["Premium price"],
    benefits: [
      "Wild-caught — no antibiotics",
      "23g protein per serving",
      "Single ingredient",
      "No sodium tripolyphosphate",
    ],
    buyTip: "This frozen shrimp scored in the elite tier because it is a single-ingredient wild-caught product with no additives, preservatives, or sodium tripolyphosphate. Wild-caught Pacific shrimp are not treated with antibiotics, which is a common practice in farmed shrimp operations.",
    averagePrice: 9.99,
    imageUrl: "/manus-storage/vital-choice-wild-shrimp_f882099b.jpg",
  },

  // ─── FROZEN PIZZA ────────────────────────────────────────────────────────
  {
    id: "digiorno-pepperoni",
    name: "Rising Crust Pepperoni Pizza",
    brand: "DiGiorno",
    category: "pizza",
    score: 18,
    qualityTier: "avoid",
    barcode: "071921011018",
    servingSize: "1/4 pizza (133g)",
    hasSeedOils: true,
    hasPreservatives: true,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasHighSodium: true,
    isOrganic: false,
    isGlutenFree: false,
    novaGroup: 4,
    nutrients: { calories: 340, fat: 13, sodium: 780, protein: 15, carbs: 41 },
    ingredients: "Enriched Flour, Tomato Puree, Mozzarella Cheese, Pepperoni (Pork, Beef, Salt, Spices, Dextrose, BHA, BHT), Soybean Oil, Modified Food Starch, Sugar, Salt, Sodium Phosphate",
    concerns: [
      "BHA and BHT in pepperoni — synthetic antioxidants, potential carcinogens",
      "780mg sodium per slice",
      "Soybean oil",
      "Modified food starch",
      "Enriched (refined) flour",
    ],
    benefits: ["Convenient"],
    buyTip: "This frozen pizza scored in the avoid tier because the pepperoni contains BHA and BHT (synthetic antioxidant preservatives that the National Toxicology Program has listed as reasonably anticipated to be human carcinogens), soybean oil, modified food starch, and 780mg of sodium per slice. The enriched flour crust adds to the NOVA Group 4 classification.",
    averagePrice: 8.99,
    imageUrl: "/manus-storage/digiorno-pepperoni_6f3a1f86.jpg",
  },
  {
    id: "caulipower-pizza",
    name: "Three Cheese Cauliflower Pizza",
    brand: "Caulipower",
    category: "pizza",
    score: 65,
    qualityTier: "average",
    barcode: "850006001015",
    servingSize: "1/2 pizza (130g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: true,
    isOrganic: false,
    isGlutenFree: true,
    novaGroup: 3,
    nutrients: { calories: 290, fat: 10, sodium: 580, protein: 11, carbs: 38 },
    ingredients: "Cauliflower Crust (Cauliflower, Tapioca Starch, Potato Starch, Olive Oil, Rice Flour, Egg Whites, Sea Salt), Tomato Sauce, Mozzarella Cheese, Parmesan Cheese",
    concerns: ["580mg sodium", "Tapioca and potato starch (high glycemic)", "Not organic"],
    benefits: [
      "Gluten-free cauliflower crust",
      "No seed oils (olive oil used)",
      "No artificial additives",
      "Real cheese",
    ],
    buyTip: "Good gluten-free option. No seed oils. High sodium — limit to one serving.",
    averagePrice: 8.99,
    imageUrl: "/manus-storage/caulipower-pizza_834b919a.jpg",
  },
  {
    id: "siete-almond-flour-pizza",
    name: "Almond Flour Pizza",
    brand: "Siete Family Foods",
    category: "pizza",
    score: 75,
    qualityTier: "good",
    barcode: "856069005015",
    servingSize: "1/2 pizza (130g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: false,
    isOrganic: false,
    isGlutenFree: true,
    novaGroup: 3,
    nutrients: { calories: 310, fat: 17, sodium: 480, protein: 12, carbs: 28 },
    ingredients: "Almond Flour Crust (Almond Flour, Tapioca Starch, Egg Whites, Sea Salt), Tomato Sauce, Mozzarella Cheese",
    concerns: ["Almond flour is calorie-dense", "Not organic"],
    benefits: [
      "Grain-free almond flour crust",
      "No seed oils",
      "No artificial additives",
      "Gluten-free",
      "Lower carb than traditional pizza",
    ],
    buyTip: "Best grain-free frozen pizza. No seed oils, clean ingredients. Great for paleo/keto.",
    averagePrice: 9.99,
    imageUrl: "/manus-storage/siete-almond-flour-pizza_38065c65.jpg",
  },

  // ─── FROZEN BREAKFAST ────────────────────────────────────────────────────
  {
    id: "jimmy-dean-sausage-egg-biscuit",
    name: "Sausage, Egg & Cheese Biscuit",
    brand: "Jimmy Dean",
    category: "breakfast",
    score: 18,
    qualityTier: "avoid",
    barcode: "077900530015",
    servingSize: "1 sandwich (128g)",
    hasSeedOils: true,
    hasPreservatives: true,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasHighSodium: true,
    isOrganic: false,
    isGlutenFree: false,
    novaGroup: 4,
    nutrients: { calories: 390, fat: 23, sodium: 820, protein: 14, carbs: 31 },
    ingredients: "Biscuit (Enriched Flour, Soybean Oil, Partially Hydrogenated Soybean Oil, Lard, Sodium Aluminum Phosphate, Sodium Bicarbonate), Pork Sausage (Pork, Water, Salt, Spices, Dextrose, BHA, BHT, Citric Acid), Egg, American Cheese",
    concerns: [
      "Partially hydrogenated soybean oil — trans fat",
      "BHA and BHT in sausage",
      "820mg sodium",
      "Sodium aluminum phosphate — leavening agent linked to aluminum accumulation",
      "Soybean oil",
    ],
    benefits: ["14g protein"],
    buyTip: "This frozen breakfast sandwich scored in the avoid tier because the biscuit contains partially hydrogenated soybean oil (a source of trans fats), the sausage contains BHA and BHT (synthetic preservatives), and the total sodium is 820mg per sandwich. Partially hydrogenated oils are associated with increased cardiovascular disease risk, and this is the primary factor driving the very low quality score.",
    imageUrl: "/manus-storage/jimmy-dean-sausage-egg-biscuit_42c3a56f.jpg",
  },
  {
    id: "kashi-waffles",
    name: "7 Grain Waffles",
    brand: "Kashi",
    category: "breakfast",
    score: 52,
    qualityTier: "average",
    barcode: "018627330011",
    servingSize: "2 waffles (70g)",
    hasSeedOils: true,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: false,
    isOrganic: false,
    isGlutenFree: false,
    novaGroup: 3,
    nutrients: { calories: 170, fat: 4, sodium: 310, protein: 6, carbs: 30 },
    ingredients: "Whole Grain Wheat Flour, Whole Grain Oats, Whole Grain Rye, Whole Grain Triticale, Whole Grain Barley, Whole Grain Buckwheat, Whole Grain Sesame, Canola Oil, Cane Sugar, Baking Powder",
    concerns: ["Canola oil (seed oil)", "Multiple whole grains still spike blood sugar"],
    benefits: ["7 whole grains", "6g protein", "No artificial additives"],
    buyTip: "This waffle scored in the average tier because it contains canola oil (a seed oil high in omega-6 linoleic acid). The seven whole grains and absence of artificial additives are positives, but the seed oil content is what limits the quality score.",
    averagePrice: 4.49,
    imageUrl: "/manus-storage/kashi-waffles_caad3ba4.jpg",
  },
  {
    id: "eggo-original-waffles",
    name: "Homestyle Waffles",
    brand: "Eggo (Kellogg's)",
    category: "breakfast",
    score: 20,
    qualityTier: "avoid",
    barcode: "038000591518",
    servingSize: "2 waffles (70g)",
    hasSeedOils: true,
    hasPreservatives: true,
    hasArtificialColors: false,
    hasArtificialFlavors: true,
    hasHighSodium: false,
    isOrganic: false,
    isGlutenFree: false,
    novaGroup: 4,
    nutrients: { calories: 190, fat: 6, sodium: 380, protein: 5, carbs: 30 },
    ingredients: "Enriched Flour, Water, Soybean Oil, Eggs, Sugar, Leavening, Salt, Soy Lecithin, Artificial Flavor, Sodium Caseinate, Monoglycerides",
    concerns: [
      "Soybean oil",
      "Artificial flavor",
      "Monoglycerides (emulsifier)",
      "Sodium caseinate — processed milk derivative",
      "Enriched (refined) flour",
    ],
    benefits: [],
    buyTip: "This waffle scored in the avoid tier because it contains soybean oil (a seed oil), artificial flavor, monoglycerides (a synthetic emulsifier), sodium caseinate (a processed milk derivative), and enriched (refined) flour. The combination of seed oil, artificial flavoring, and synthetic emulsifiers is what drives the NOVA Group 4 classification and the low quality score.",
    averagePrice: 3.49,
    imageUrl: "/manus-storage/eggo-original-waffles_bec7bb07.jpg",
  },
  {
    id: "real-good-breakfast-burrito",
    name: "Egg, Cheese & Bacon Burrito",
    brand: "Real Good Foods",
    category: "breakfast",
    score: 78,
    qualityTier: "good",
    barcode: "850012001015",
    servingSize: "1 burrito (113g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: true,
    isOrganic: false,
    isGlutenFree: true,
    novaGroup: 3,
    nutrients: { calories: 220, fat: 13, sodium: 540, protein: 18, carbs: 5 },
    ingredients: "Egg White Tortilla (Egg Whites, Tapioca Starch, Sea Salt), Scrambled Eggs, Cheddar Cheese, Bacon",
    concerns: ["540mg sodium", "Egg white tortilla is processed", "Non-organic"],
    benefits: [
      "18g protein",
      "Only 5g carbs — keto-friendly",
      "No seed oils",
      "No artificial additives",
      "Gluten-free",
    ],
    buyTip: "Great low-carb breakfast option. High protein, no seed oils. Good for keto/paleo.",
    imageUrl: "/manus-storage/real-good-breakfast-burrito_c2cee6c3.jpg",
  },

  // ─── FROZEN SNACKS ───────────────────────────────────────────────────────
  {
    id: "alexia-sweet-potato-fries",
    name: "Organic Sweet Potato Fries",
    brand: "Alexia",
    category: "snacks",
    score: 72,
    qualityTier: "good",
    barcode: "021130000015",
    servingSize: "3 oz (84g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: false,
    isOrganic: true,
    isGlutenFree: true,
    novaGroup: 2,
    nutrients: { calories: 140, fat: 4, sodium: 120, protein: 2, carbs: 24 },
    ingredients: "Organic Sweet Potatoes, Organic Sunflower Oil, Sea Salt",
    concerns: ["Sunflower oil (seed oil)", "High glycemic sweet potato"],
    benefits: [
      "USDA Certified Organic",
      "Minimal ingredients",
      "No artificial additives",
      "Rich in beta-carotene",
    ],
    buyTip: "This frozen snack scored in the good tier because it is USDA Organic with minimal ingredients, but it contains sunflower oil (a seed oil high in omega-6 linoleic acid). The organic certification and simple ingredient list are positives, but the seed oil is what prevents a higher quality score.",
    averagePrice: 4.99,
    imageUrl: "/manus-storage/alexia-sweet-potato-fries_7ab79496.jpg",
  },
  {
    id: "ore-ida-french-fries",
    name: "Golden Crinkles French Fries",
    brand: "Ore-Ida (Kraft Heinz)",
    category: "snacks",
    score: 28,
    qualityTier: "avoid",
    barcode: "013000006019",
    servingSize: "3 oz (84g)",
    hasSeedOils: true,
    hasPreservatives: true,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: false,
    isOrganic: false,
    isGlutenFree: true,
    novaGroup: 4,
    nutrients: { calories: 130, fat: 4, sodium: 290, protein: 2, carbs: 22 },
    ingredients: "Potatoes, Canola Oil, Dextrose, Sodium Acid Pyrophosphate, Salt",
    concerns: [
      "Canola oil (seed oil)",
      "Sodium acid pyrophosphate — color preservative",
      "Dextrose (added sugar to maintain color)",
    ],
    benefits: ["Real potatoes"],
    buyTip: "This frozen product scored in the avoid tier because it contains canola oil (a seed oil), dextrose (added sugar used to maintain color during freezing), and sodium acid pyrophosphate (a color preservative). These additives are unnecessary for a simple potato product and are what drive the low quality score.",
    averagePrice: 3.49,
    imageUrl: "/manus-storage/ore-ida-french-fries_03ed5afb.jpg",
  },

  // ─── FROZEN DESSERTS ─────────────────────────────────────────────────────
  {
    id: "haagen-dazs-vanilla",
    name: "Vanilla Ice Cream",
    brand: "Häagen-Dazs",
    category: "desserts",
    score: 62,
    qualityTier: "average",
    barcode: "074570000015",
    servingSize: "2/3 cup (88g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: false,
    isOrganic: false,
    isGlutenFree: true,
    novaGroup: 3,
    nutrients: { calories: 270, fat: 18, sodium: 75, protein: 5, carbs: 22 },
    ingredients: "Cream, Skim Milk, Cane Sugar, Egg Yolks, Vanilla Extract",
    concerns: ["22g sugar per serving", "Non-organic dairy", "High calorie"],
    benefits: [
      "Only 5 ingredients",
      "No seed oils",
      "No artificial additives",
      "Real vanilla extract",
      "Real egg yolks",
    ],
    buyTip: "Best mainstream ice cream — minimal, real ingredients. Occasional treat. Choose organic dairy version.",
    averagePrice: 3.99,
    imageUrl: "/manus-storage/haagen-dazs-vanilla_b60cfa6e.jpg",
  },
  {
    id: "breyers-natural-vanilla",
    name: "Natural Vanilla Ice Cream",
    brand: "Breyers",
    category: "desserts",
    score: 48,
    qualityTier: "average",
    barcode: "077567001015",
    servingSize: "2/3 cup (88g)",
    hasSeedOils: false,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: false,
    isOrganic: false,
    isGlutenFree: true,
    novaGroup: 3,
    nutrients: { calories: 200, fat: 9, sodium: 55, protein: 3, carbs: 27 },
    ingredients: "Milk, Cream, Sugar, Tara Gum, Vanilla Extract",
    concerns: ["27g sugar per serving", "Tara gum (thickener)", "Non-organic dairy"],
    benefits: ["Simple ingredients", "No seed oils", "Real vanilla"],
    buyTip: "This ice cream scored in the average tier because it contains 27g of sugar per serving and tara gum (a thickening agent). The conventional (non-organic) dairy is also a factor. The ingredient list is relatively simple compared to many mainstream ice creams, which is a positive.",
    averagePrice: 4.99,
    imageUrl: "/manus-storage/breyers-natural-vanilla_77c59c5c.jpg",
  },
  {
    id: "ben-jerrys-chocolate-chip",
    name: "Chocolate Chip Cookie Dough",
    brand: "Ben & Jerry's",
    category: "desserts",
    score: 30,
    qualityTier: "poor",
    barcode: "076840100015",
    servingSize: "2/3 cup (88g)",
    hasSeedOils: true,
    hasPreservatives: false,
    hasArtificialColors: false,
    hasArtificialFlavors: false,
    hasHighSodium: false,
    isOrganic: false,
    isGlutenFree: false,
    novaGroup: 4,
    nutrients: { calories: 310, fat: 16, sodium: 120, protein: 5, carbs: 39 },
    ingredients: "Cream, Skim Milk, Sugar, Cookie Dough (Wheat Flour, Sugar, Butter, Chocolate Chips, Soybean Oil, Salt, Baking Soda), Egg Yolks, Vanilla Extract",
    concerns: [
      "39g sugar per serving",
      "Soybean oil in cookie dough",
      "Very high calorie",
    ],
    benefits: ["Real cream and egg yolks", "No artificial flavors"],
    buyTip: "This ice cream scored in the poor tier because the cookie dough mix-ins contain soybean oil (a seed oil high in omega-6 linoleic acid), and the overall product contains 39g of sugar per serving. The ice cream base uses real cream and egg yolks, but the seed oil in the mix-ins is the primary factor driving the low quality score.",
    averagePrice: 5.49,
    imageUrl: "/manus-storage/ben-jerrys-chocolate-chip_04470a76.jpg",
  },
];

export const FROZEN_DB_STATS = {
  total: ALL_FROZEN.length,
  seedOilCount: ALL_FROZEN.filter(f => f.hasSeedOils).length,
  highSodiumCount: ALL_FROZEN.filter(f => f.hasHighSodium).length,
  organicCount: ALL_FROZEN.filter(f => f.isOrganic).length,
  eliteCount: ALL_FROZEN.filter(f => f.qualityTier === "elite" || f.qualityTier === "good").length,
};
