/**
 * EatVera — Comprehensive US Fruit Database
 * Quality ratings based on:
 * - EWG Dirty Dozen / Clean Fifteen pesticide data (2024)
 * - USDA Pesticide Data Program residue findings
 * - Nutritional density (vitamins, antioxidants, fiber)
 * - Organic vs conventional availability
 * - Country of origin / sourcing transparency
 * - Processing level (fresh, frozen, canned, dried)
 */

export type FruitQualityTier = "excellent" | "good" | "caution" | "avoid";
export type FruitCategory =
  | "Berries"
  | "Citrus"
  | "Tropical"
  | "Stone Fruit"
  | "Pome Fruit"
  | "Melons"
  | "Grapes & Vine"
  | "Dried Fruit"
  | "Packaged / Canned"
  | "Exotic";

export interface FruitEntry {
  id: string;
  name: string;
  imageUrl?: string;
  category: FruitCategory;
  qualityTier: FruitQualityTier;
  /** EWG pesticide rank: lower = more pesticides. null if not ranked */
  ewgRank: number | null;
  ewgStatus: "dirty-dozen" | "clean-fifteen" | "middle" | "not-ranked";
  /** Conventional score (no organic) */
  conventionalScore: number;
  /** Organic score */
  organicScore: number;
  /** Whether organic is widely available in US stores */
  organicAvailable: boolean;
  pesticides: string;
  nutritionHighlights: string[];
  concerns: string[];
  benefits: string[];
  buyTip: string;
  averagePrice?: number;
  /** Typical US grocery store barcodes / PLU codes */
  pluCodes: string[];
  /** Key nutrients per 100g */
  nutrients: {
    calories?: number;
    carbs?: number;
    fiber?: number;
    sugar?: number;
    protein?: number;
    vitaminC?: number; // mg
    potassium?: number; // mg
    antioxidants?: string;
  };
  season: string;
  origin: string;
}

export const FRUIT_QUALITY_TIER_CONFIG: Record<
  FruitQualityTier,
  { label: string; color: string; bg: string; border: string; score: string }
> = {
  excellent: {
    label: "Excellent",
    color: "#145A3A",
    bg: "#F0FAF2",
    border: "#86d086",
    score: "85–100",
  },
  good: {
    label: "Good",
    color: "#3FA34D",
    bg: "#F0FAF2",
    border: "#b8e8b8",
    score: "65–84",
  },
  caution: {
    label: "Buy Organic",
    color: "#d97706",
    bg: "#fffbf0",
    border: "#fde68a",
    score: "40–64",
  },
  avoid: {
    label: "Avoid Conventional",
    color: "#dc2626",
    bg: "#fff5f5",
    border: "#fca5a5",
    score: "20–39",
  },
};

export const FRUIT_CATEGORIES: { id: string; label: string }[] = [
  { id: "all", label: "All Fruits" },
  { id: "Berries", label: "Berries" },
  { id: "Citrus", label: "Citrus" },
  { id: "Tropical", label: "Tropical" },
  { id: "Stone Fruit", label: "Stone Fruit" },
  { id: "Pome Fruit", label: "Pome Fruit" },
  { id: "Melons", label: "Melons" },
  { id: "Grapes & Vine", label: "Grapes & Vine" },
  { id: "Dried Fruit", label: "Dried Fruit" },
  { id: "Packaged / Canned", label: "Packaged" },
  { id: "Exotic", label: "Exotic" },
];

export function getFruitScore(entry: FruitEntry, organic: boolean): number {
  return organic ? entry.organicScore : entry.conventionalScore;
}

export function getFruitColor(score: number): string {
  if (score >= 85) return "#145A3A";
  if (score >= 70) return "#3FA34D";
  if (score >= 55) return "#65a30d";
  if (score >= 40) return "#d97706";
  if (score >= 25) return "#ea580c";
  return "#dc2626";
}

export const ALL_FRUITS: FruitEntry[] = [
  // ─── BERRIES ────────────────────────────────────────────────────────────────
  {
    id: "strawberry",
    name: "Strawberries",
    imageUrl: "/manus-storage/strawberries_d017b72a.jpg",
    category: "Berries",
    qualityTier: "avoid",
    ewgRank: 1,
    ewgStatus: "dirty-dozen",
    conventionalScore: 28,
    organicScore: 95,
    organicAvailable: true,
    pesticides:
      "#1 on EWG Dirty Dozen 2024. Up to 22 different pesticide residues found. Fungicides, insecticides including bifenthrin (possible carcinogen). Thin skin absorbs chemicals deeply — cannot be washed off.",
    nutritionHighlights: ["High vitamin C (59mg/100g)", "Rich in anthocyanins", "Good fiber source", "Folate"],
    concerns: [
      "Most pesticide-contaminated fruit in the US",
      "22+ pesticide residues detected by USDA",
      "Bifenthrin — possible carcinogen",
      "Carbendazim — endocrine disruptor",
    ],
    benefits: [
      "Extremely high in antioxidants",
      "Anti-inflammatory polyphenols",
      "Supports heart health",
      "Low glycemic index",
    ],
    buyTip: "Strawberries are ranked #1 on the EWG Dirty Dozen list, meaning they consistently test for the highest number of pesticide residues among all fruits. Organic strawberries have significantly lower pesticide exposure. Frozen organic strawberries are a year-round option that retains most of the nutritional value.",
    pluCodes: ["3032", "4032", "83032"],
    nutrients: { calories: 32, carbs: 7.7, fiber: 2, sugar: 4.9, protein: 0.7, vitaminC: 59, potassium: 153, antioxidants: "Anthocyanins, ellagic acid, quercetin" },
    season: "Spring–Summer (peak May–June)",
    origin: "California (domestic), Mexico (winter)",
  },
  {
    id: "spinach-fruit",
    name: "Blueberries",
    imageUrl: "/manus-storage/blueberries_d2eb9de7.jpg",
    category: "Berries",
    qualityTier: "caution",
    ewgRank: 10,
    ewgStatus: "dirty-dozen",
    conventionalScore: 45,
    organicScore: 96,
    organicAvailable: true,
    pesticides:
      "Entered Dirty Dozen in 2023. Phosmet and malathion (organophosphates) detected. Neonicotinoids found on domestic blueberries.",
    nutritionHighlights: ["Highest antioxidant of any common fruit", "Pterostilbene & resveratrol", "Vitamin K", "Manganese"],
    concerns: [
      "Entered EWG Dirty Dozen 2023",
      "Organophosphate pesticides (phosmet, malathion)",
      "Neonicotinoids detected — bee toxins",
    ],
    benefits: [
      "Highest ORAC antioxidant score of common fruits",
      "Supports brain health and memory",
      "Anti-inflammatory",
      "Supports cardiovascular health",
    ],
    buyTip: "Buy organic when possible. Wild blueberries (frozen) are lower in pesticides and higher in antioxidants than cultivated.",
    pluCodes: ["3242", "4242", "83242"],
    nutrients: { calories: 57, carbs: 14.5, fiber: 2.4, sugar: 10, protein: 0.7, vitaminC: 9.7, potassium: 77, antioxidants: "Anthocyanins, pterostilbene, resveratrol" },
    season: "Summer (June–August)",
    origin: "Michigan, Oregon, New Jersey; Chile (winter)",
  },
  {
    id: "raspberries",
    name: "Raspberries",
    imageUrl: "/manus-storage/raspberries_0cd1e803.jpg",
    category: "Berries",
    qualityTier: "caution",
    ewgRank: 22,
    ewgStatus: "middle",
    conventionalScore: 55,
    organicScore: 94,
    organicAvailable: true,
    pesticides:
      "Moderate pesticide load. Imidacloprid (neonicotinoid) and fenhexamid detected. Hollow structure makes washing ineffective.",
    nutritionHighlights: ["Highest fiber of any common fruit (6.5g/100g)", "Ellagic acid", "Vitamin C", "Manganese"],
    concerns: [
      "Neonicotinoid residues (imidacloprid)",
      "Fenhexamid fungicide detected",
      "Hollow structure traps pesticides",
    ],
    benefits: [
      "Highest fiber content of common fruits",
      "Powerful anti-cancer ellagic acid",
      "Low glycemic index",
      "Supports gut microbiome",
    ],
    buyTip: "Buy organic or frozen organic. Frozen raspberries retain nutrients well and are often cheaper.",
    pluCodes: ["3380", "4380"],
    nutrients: { calories: 52, carbs: 11.9, fiber: 6.5, sugar: 4.4, protein: 1.2, vitaminC: 26.2, potassium: 151, antioxidants: "Ellagic acid, quercetin, anthocyanins" },
    season: "Summer (June–September)",
    origin: "California, Washington; Chile (winter)",
  },
  {
    id: "blackberries",
    name: "Blackberries",
    imageUrl: "/manus-storage/blackberries_8573094b.jpg",
    category: "Berries",
    qualityTier: "good",
    ewgRank: 30,
    ewgStatus: "middle",
    conventionalScore: 68,
    organicScore: 95,
    organicAvailable: true,
    pesticides:
      "Lower pesticide load than other berries. Some fungicide residues. Organic strongly preferred.",
    nutritionHighlights: ["High vitamin C & K", "Anthocyanins", "High fiber (5.3g)", "Manganese"],
    concerns: ["Some fungicide residues", "Imported off-season may have higher residues"],
    benefits: [
      "Rich in anthocyanins — anti-inflammatory",
      "High fiber supports gut health",
      "Vitamin K for bone health",
      "Low sugar compared to other fruits",
    ],
    buyTip: "Conventional is acceptable. Organic is better. Frozen blackberries are a great year-round option.",
    pluCodes: ["3380", "4380"],
    nutrients: { calories: 43, carbs: 9.6, fiber: 5.3, sugar: 4.9, protein: 1.4, vitaminC: 21, potassium: 162, antioxidants: "Anthocyanins, ellagic acid, resveratrol" },
    season: "Summer (July–September)",
    origin: "Oregon, California; Mexico (winter)",
  },
  {
    id: "cranberries",
    name: "Cranberries",
    imageUrl: "/manus-storage/cranberries_ef006b09.jpg",
    category: "Berries",
    qualityTier: "good",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 72,
    organicScore: 93,
    organicAvailable: true,
    pesticides: "Moderate pesticide use in conventional farming. Flooding harvest method dilutes some residues.",
    nutritionHighlights: ["Proanthocyanidins (UTI prevention)", "Vitamin C", "Vitamin E", "Manganese"],
    concerns: [
      "Conventional uses significant pesticides",
      "Most cranberry products contain added sugar",
      "Dried cranberries often have added oils",
    ],
    benefits: [
      "Proanthocyanidins prevent UTI bacteria adhesion",
      "Powerful antioxidant profile",
      "Supports oral health",
      "Anti-inflammatory",
    ],
    buyTip: "Fresh or frozen cranberries are best. Avoid dried cranberries with added sugar or sunflower oil.",
    pluCodes: ["4415"],
    nutrients: { calories: 46, carbs: 12.2, fiber: 4.6, sugar: 4, protein: 0.4, vitaminC: 13.3, potassium: 85, antioxidants: "Proanthocyanidins, quercetin, myricetin" },
    season: "Fall (October–November)",
    origin: "Massachusetts, Wisconsin, New Jersey",
  },
  {
    id: "acai",
    name: "Açaí Berries",
    imageUrl: "/manus-storage/a_a_berries_fa0fb314.jpg",
    category: "Berries",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 88,
    organicScore: 97,
    organicAvailable: true,
    pesticides: "Typically wild-harvested from Amazon rainforest. Minimal pesticide exposure. Usually sold frozen or as powder.",
    nutritionHighlights: ["Highest antioxidant ORAC score", "Omega-9 healthy fats", "Anthocyanins", "Iron"],
    concerns: [
      "Açaí bowls often loaded with added sugar",
      "Some brands add seed oils or sweeteners",
      "Check ingredients on packaged açaí products",
    ],
    benefits: [
      "Extraordinarily high antioxidant content",
      "Heart-healthy monounsaturated fats",
      "Anti-inflammatory",
      "Supports brain health",
    ],
    buyTip: "Açaí is typically sold as frozen pulp packs or powder. Look for products with no added sugar or sweeteners in the ingredient list. Açaí bowls served at restaurants often contain added granola, honey, and sweetened toppings that significantly increase the sugar content.",
    pluCodes: ["3622", "4622"],
    nutrients: { calories: 70, carbs: 4, fiber: 2, sugar: 2, protein: 1, vitaminC: 0, potassium: 105, antioxidants: "Anthocyanins (highest known), oleic acid" },
    season: "Year-round (frozen)",
    origin: "Brazil (Amazon)",
  },
  {
    id: "goji-berries",
    name: "Goji Berries (Wolfberries)",
    imageUrl: "/manus-storage/goji_berries_wolfberries_a51933b2.jpg",
    category: "Berries",
    qualityTier: "caution",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 48,
    organicScore: 85,
    organicAvailable: true,
    pesticides: "Imported from China — high pesticide residue risk. USDA testing found multiple pesticide residues on imported goji berries. Buy organic only.",
    nutritionHighlights: ["Zeaxanthin (eye health)", "Vitamin A", "Complete protein", "Iron & zinc"],
    concerns: [
      "Most imported from China with heavy pesticide use",
      "USDA found multiple pesticide residues",
      "Often sold dried with added sugar",
      "High in sugar when dried",
    ],
    benefits: [
      "Zeaxanthin protects eye health",
      "High in vitamin A",
      "Adaptogenic properties",
      "Immune-supporting polysaccharides",
    ],
    buyTip: "Most goji berries are imported from China, where USDA testing has found multiple pesticide residues. Certified organic goji berries have significantly lower pesticide exposure. Unsweetened varieties are preferable, as many dried goji products contain added sugar.",
    pluCodes: ["3678", "4678"],
    nutrients: { calories: 349, carbs: 77, fiber: 13, sugar: 46, protein: 14, vitaminC: 48, potassium: 1132, antioxidants: "Zeaxanthin, beta-carotene, polysaccharides" },
    season: "Year-round (dried)",
    origin: "China (most), Tibet",
  },

  // ─── CITRUS ─────────────────────────────────────────────────────────────────
  {
    id: "oranges",
    name: "Navel Oranges",
    imageUrl: "/manus-storage/navel_oranges_f1970d3a.jpg",
    category: "Citrus",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "clean-fifteen",
    conventionalScore: 88,
    organicScore: 97,
    organicAvailable: true,
    pesticides: "Thick peel protects the flesh. On EWG Clean Fifteen. Minimal pesticide concern for the edible portion.",
    nutritionHighlights: ["Vitamin C (53mg/100g)", "Folate", "Hesperidin flavonoid", "Potassium"],
    concerns: [
      "Peel may have pesticide residue (avoid zesting conventional)",
      "Some post-harvest wax coatings on conventional",
    ],
    benefits: [
      "Excellent vitamin C source — immune support",
      "Hesperidin supports cardiovascular health",
      "Folate for cell health",
      "Natural hydration",
    ],
    buyTip: "Conventional is fine for eating. Buy organic if you plan to use the zest.",
    pluCodes: ["3107", "4107"],
    nutrients: { calories: 47, carbs: 11.8, fiber: 2.4, sugar: 9.4, protein: 0.9, vitaminC: 53.2, potassium: 181, antioxidants: "Hesperidin, naringenin, beta-carotene" },
    season: "Winter–Spring (November–April)",
    origin: "California, Florida; Spain, South Africa",
  },
  {
    id: "grapefruit",
    name: "Grapefruit",
    imageUrl: "/manus-storage/grapefruit_c0921c4c.jpg",
    category: "Citrus",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "clean-fifteen",
    conventionalScore: 86,
    organicScore: 96,
    organicAvailable: true,
    pesticides: "Thick peel protects flesh. Low pesticide concern for edible portion. On Clean Fifteen list.",
    nutritionHighlights: ["Vitamin C (31mg)", "Lycopene (pink/red)", "Naringenin", "Vitamin A"],
    concerns: [
      "Interacts with many medications (CYP3A4 inhibitor)",
      "High acidity may irritate sensitive stomachs",
    ],
    benefits: [
      "Lycopene in pink/red varieties — anti-cancer",
      "Naringenin supports fat metabolism",
      "Supports immune function",
      "Low calorie, high satiety",
    ],
    buyTip: "Conventional is fine. Choose pink or red for higher lycopene content. Check medication interactions.",
    pluCodes: ["4279", "3279"],
    nutrients: { calories: 42, carbs: 10.7, fiber: 1.6, sugar: 6.9, protein: 0.8, vitaminC: 31.2, potassium: 135, antioxidants: "Lycopene, naringenin, beta-carotene" },
    season: "Winter (November–March)",
    origin: "Florida, Texas, California",
  },
  {
    id: "lemons",
    name: "Lemons",
    imageUrl: "/manus-storage/lemons_f72db2ff.jpg",
    category: "Citrus",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "clean-fifteen",
    conventionalScore: 87,
    organicScore: 97,
    organicAvailable: true,
    pesticides: "Thick peel protects flesh. Clean Fifteen. Organic recommended if using zest.",
    nutritionHighlights: ["Vitamin C (53mg)", "Citric acid", "Limonene", "Flavonoids"],
    concerns: [
      "Conventional peel may have pesticide/wax coating",
      "High acidity can erode tooth enamel",
    ],
    benefits: [
      "Limonene — anti-cancer, detoxifying",
      "Alkalizing effect despite acidity",
      "Supports liver detox",
      "Vitamin C immune boost",
    ],
    buyTip: "Conventional OK for juice. Buy organic if using zest or making lemon water with the whole fruit.",
    pluCodes: ["4053", "3053"],
    nutrients: { calories: 29, carbs: 9.3, fiber: 2.8, sugar: 2.5, protein: 1.1, vitaminC: 53, potassium: 138, antioxidants: "Limonene, hesperidin, eriocitrin" },
    season: "Year-round (peak winter)",
    origin: "California, Arizona; Argentina, Spain",
  },
  {
    id: "limes",
    name: "Limes",
    imageUrl: "/manus-storage/limes_637eb408.jpg",
    category: "Citrus",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "clean-fifteen",
    conventionalScore: 87,
    organicScore: 96,
    organicAvailable: true,
    pesticides: "Thick peel protects flesh. Clean Fifteen. Very low pesticide concern.",
    nutritionHighlights: ["Vitamin C (29mg)", "Folate", "Limonoids", "Flavonoids"],
    concerns: ["Conventional peel may have wax coating", "Imported limes may have higher pesticide use"],
    benefits: [
      "Limonoids — anti-cancer properties",
      "Supports digestion",
      "Alkalizing",
      "Immune support",
    ],
    buyTip: "Conventional is fine for juice. Key limes (smaller, more aromatic) are nutritionally superior.",
    pluCodes: ["4048", "3048"],
    nutrients: { calories: 30, carbs: 10.5, fiber: 2.8, sugar: 1.7, protein: 0.7, vitaminC: 29.1, potassium: 102, antioxidants: "Limonoids, flavonoids, quercetin" },
    season: "Year-round",
    origin: "Mexico (primary), Florida",
  },
  {
    id: "clementines",
    name: "Clementines / Mandarins",
    imageUrl: "/manus-storage/clementines_mandarins_c2936f7e.png",
    category: "Citrus",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "clean-fifteen",
    conventionalScore: 85,
    organicScore: 95,
    organicAvailable: true,
    pesticides: "Thick peel provides protection. Generally low pesticide residue on flesh. Clean Fifteen.",
    nutritionHighlights: ["Vitamin C (49mg)", "Beta-carotene", "Folate", "Potassium"],
    concerns: ["Some post-harvest fungicide on peel", "Avoid if zesting conventional"],
    benefits: [
      "Easy to peel — great for kids",
      "Beta-carotene for eye health",
      "Immune-boosting vitamin C",
      "Natural sweetness with low calories",
    ],
    buyTip: "Clementines are on the EWG Clean Fifteen list, meaning they test for very low pesticide residues. The thick peel provides natural protection for the flesh. Organic is a good choice if you plan to zest the peel, since post-harvest fungicides are applied to the outer rind.",
    pluCodes: ["3337", "4337"],
    nutrients: { calories: 47, carbs: 12, fiber: 1.7, sugar: 9.9, protein: 0.9, vitaminC: 48.8, potassium: 177, antioxidants: "Beta-carotene, nobiletin, tangeretin" },
    season: "Winter (November–January)",
    origin: "California, Spain, Morocco",
  },
  {
    id: "blood-orange",
    name: "Blood Oranges",
    imageUrl: "/manus-storage/blood_oranges_0f2ea642.jpg",
    category: "Citrus",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "clean-fifteen",
    conventionalScore: 89,
    organicScore: 97,
    organicAvailable: true,
    pesticides: "Thick peel protection. Minimal pesticide concern for flesh.",
    nutritionHighlights: ["Anthocyanins (unique among citrus)", "Vitamin C (59mg)", "Folate", "Hesperidin"],
    concerns: ["Short season — limited availability", "Peel may have wax coating"],
    benefits: [
      "Unique anthocyanins — anti-inflammatory, anti-cancer",
      "Higher antioxidant than regular oranges",
      "Beautiful color indicates phytonutrient richness",
      "Supports cardiovascular health",
    ],
    buyTip: "Excellent choice. Organic preferred for zesting. Moro variety has highest anthocyanin content.",
    pluCodes: ["3108", "4108"],
    nutrients: { calories: 50, carbs: 11.8, fiber: 2.2, sugar: 9, protein: 1, vitaminC: 59, potassium: 200, antioxidants: "Anthocyanins, hesperidin, naringenin" },
    season: "Winter (December–March)",
    origin: "California, Sicily (Italy)",
  },

  // ─── TROPICAL ───────────────────────────────────────────────────────────────
  {
    id: "avocado",
    name: "Avocado (Hass)",
    imageUrl: "/manus-storage/avocado_hass_3c8f9518.jpg",
    category: "Tropical",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "clean-fifteen",
    conventionalScore: 94,
    organicScore: 98,
    organicAvailable: true,
    pesticides: "#1 on EWG Clean Fifteen. Thick skin protects flesh completely. Lowest pesticide residue of any fruit.",
    nutritionHighlights: ["Healthy monounsaturated fats (oleic acid)", "Potassium (485mg — more than banana)", "Folate", "Vitamin K & E"],
    concerns: [
      "High calorie density (160 cal/100g)",
      "Environmental water usage concerns",
      "Some avocado farms linked to deforestation",
    ],
    benefits: [
      "Oleic acid — same heart-healthy fat as olive oil",
      "Boosts absorption of fat-soluble nutrients",
      "Highest potassium of any common fruit",
      "Folate for DNA repair and cell health",
    ],
    buyTip: "Conventional is perfectly safe — thick skin blocks all pesticides. Buy Hass for best flavor and nutrition.",
    pluCodes: ["4046", "3046", "94046"],
    nutrients: { calories: 160, carbs: 8.5, fiber: 6.7, sugar: 0.7, protein: 2, vitaminC: 10, potassium: 485, antioxidants: "Lutein, zeaxanthin, beta-sitosterol" },
    season: "Year-round (peak spring)",
    origin: "California, Mexico, Peru",
  },
  {
    id: "mango",
    name: "Mango (Ataulfo / Tommy Atkins)",
    imageUrl: "/manus-storage/mango_ataulfo_tommy_atkins_5094b78b.png",
    category: "Tropical",
    qualityTier: "good",
    ewgRank: null,
    ewgStatus: "clean-fifteen",
    conventionalScore: 78,
    organicScore: 93,
    organicAvailable: true,
    pesticides: "On Clean Fifteen. Thick skin provides good protection. Low pesticide concern.",
    nutritionHighlights: ["Vitamin C (36mg)", "Vitamin A / beta-carotene", "Mangiferin antioxidant", "Folate"],
    concerns: [
      "High in natural sugar (14g/100g)",
      "Imported from Mexico/South America — check for irradiation",
      "Some imported mangoes irradiated for pest control",
    ],
    benefits: [
      "Mangiferin — powerful anti-inflammatory",
      "Beta-carotene for eye and immune health",
      "Digestive enzymes (amylases)",
      "Supports skin health",
    ],
    buyTip: "Conventional is fine. Ataulfo (champagne) mangoes are sweeter and less fibrous. Choose organic for best quality.",
    pluCodes: ["3114", "4114", "3115", "4115"],
    nutrients: { calories: 60, carbs: 15, fiber: 1.6, sugar: 13.7, protein: 0.8, vitaminC: 36.4, potassium: 168, antioxidants: "Mangiferin, beta-carotene, quercetin" },
    season: "Spring–Summer (April–August)",
    origin: "Mexico, Peru, Ecuador, Florida",
  },
  {
    id: "pineapple",
    name: "Pineapple",
    imageUrl: "/manus-storage/pineapple_4af4a7de.jpg",
    category: "Tropical",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "clean-fifteen",
    conventionalScore: 86,
    organicScore: 95,
    organicAvailable: true,
    pesticides: "On Clean Fifteen. Thick outer skin protects flesh. Very low pesticide residue.",
    nutritionHighlights: ["Bromelain enzyme (anti-inflammatory)", "Vitamin C (47mg)", "Manganese", "Thiamine (B1)"],
    concerns: [
      "High in natural sugar (10g/100g)",
      "Canned pineapple loses bromelain (heat destroys enzyme)",
      "Some farms use heavy pesticides on leaves (not flesh)",
    ],
    benefits: [
      "Bromelain — powerful anti-inflammatory, digestive aid",
      "Supports joint health",
      "Immune-boosting vitamin C",
      "Manganese for bone health",
    ],
    buyTip: "Conventional is safe. Buy fresh for bromelain benefits — canning destroys this enzyme. Gold (MD-2) variety is sweetest.",
    pluCodes: ["4430", "3430"],
    nutrients: { calories: 50, carbs: 13.1, fiber: 1.4, sugar: 9.9, protein: 0.5, vitaminC: 47.8, potassium: 109, antioxidants: "Bromelain, beta-carotene, ferulic acid" },
    season: "Year-round (peak spring)",
    origin: "Costa Rica (primary), Hawaii, Mexico",
  },
  {
    id: "papaya",
    name: "Papaya",
    imageUrl: "/manus-storage/papaya_e91d3501.jpg",
    category: "Tropical",
    qualityTier: "good",
    ewgRank: null,
    ewgStatus: "clean-fifteen",
    conventionalScore: 70,
    organicScore: 90,
    organicAvailable: true,
    pesticides: "Most US papaya is GMO (Rainbow variety from Hawaii). Non-GMO and organic available but less common. Thick skin protects flesh.",
    nutritionHighlights: ["Papain enzyme (digestion)", "Vitamin C (62mg)", "Vitamin A", "Folate"],
    concerns: [
      "Most US papaya (Hawaiian) is GMO",
      "Non-GMO papaya harder to find",
      "Some people sensitive to papain",
    ],
    benefits: [
      "Papain — powerful digestive enzyme",
      "Highest vitamin C of tropical fruits",
      "Beta-carotene for eye health",
      "Anti-inflammatory lycopene",
    ],
    buyTip: "Look for non-GMO or organic papaya. Mexican Maradol papayas are typically non-GMO and widely available.",
    pluCodes: ["4394", "3394"],
    nutrients: { calories: 43, carbs: 11, fiber: 1.7, sugar: 7.8, protein: 0.5, vitaminC: 61.8, potassium: 182, antioxidants: "Lycopene, beta-carotene, papain" },
    season: "Year-round",
    origin: "Mexico, Hawaii, Brazil",
  },
  {
    id: "banana",
    name: "Banana (Cavendish)",
    imageUrl: "/manus-storage/banana_cavendish_0e9e3940.jpg",
    category: "Tropical",
    qualityTier: "good",
    ewgRank: null,
    ewgStatus: "clean-fifteen",
    conventionalScore: 80,
    organicScore: 93,
    organicAvailable: true,
    pesticides: "Thick peel protects flesh. Low pesticide concern. However, banana farming uses significant pesticides on plants.",
    nutritionHighlights: ["Potassium (358mg)", "Vitamin B6", "Resistant starch (unripe)", "Magnesium"],
    concerns: [
      "High glycemic index when ripe (GI ~60)",
      "Monoculture farming — disease vulnerability",
      "Conventional farming uses heavy pesticide/fungicide on plants",
    ],
    benefits: [
      "Excellent potassium source for heart and muscles",
      "Unripe bananas — resistant starch feeds gut bacteria",
      "Vitamin B6 for brain health",
      "Quick energy source",
    ],
    buyTip: "Conventional is safe to eat. Organic is better for the environment. Eat slightly underripe for lower sugar and more resistant starch.",
    pluCodes: ["4011", "3011", "94011"],
    nutrients: { calories: 89, carbs: 23, fiber: 2.6, sugar: 12.2, protein: 1.1, vitaminC: 8.7, potassium: 358, antioxidants: "Dopamine, catechins, beta-carotene" },
    season: "Year-round",
    origin: "Ecuador, Guatemala, Costa Rica, Honduras",
  },
  {
    id: "kiwi",
    name: "Kiwifruit (Green & Gold)",
    imageUrl: "/manus-storage/kiwifruit_green_gold_22ad16b8.jpg",
    category: "Tropical",
    qualityTier: "caution",
    ewgRank: 14,
    ewgStatus: "dirty-dozen",
    conventionalScore: 52,
    organicScore: 91,
    organicAvailable: true,
    pesticides: "Entered EWG Dirty Dozen 2022. Acetamiprid (neonicotinoid) and other pesticides detected. Fuzzy skin traps residues.",
    nutritionHighlights: ["Highest vitamin C of any fruit (93mg)", "Vitamin K", "Actinidin enzyme", "Folate"],
    concerns: [
      "Entered EWG Dirty Dozen 2022",
      "Acetamiprid neonicotinoid detected",
      "Fuzzy skin traps pesticide residues",
    ],
    benefits: [
      "Highest vitamin C per gram of any common fruit",
      "Actinidin enzyme improves protein digestion",
      "Vitamin K for bone health",
      "Supports sleep quality (serotonin)",
    ],
    buyTip: "Kiwi has a moderate pesticide load on conventional fruit. Organic is preferred when available. Gold kiwi (yellow-fleshed variety) has approximately 3x the vitamin C of green kiwi and a sweeter, less acidic flavor profile.",
    pluCodes: ["4030", "3030", "4031"],
    nutrients: { calories: 61, carbs: 14.7, fiber: 3, sugar: 9, protein: 1.1, vitaminC: 92.7, potassium: 312, antioxidants: "Vitamin C, lutein, zeaxanthin, quercetin" },
    season: "Year-round (domestic fall, imported spring)",
    origin: "California, New Zealand, Italy",
  },
  {
    id: "coconut",
    name: "Coconut (Fresh)",
    imageUrl: "/manus-storage/coconut_fresh_5f4435d4.png",
    category: "Tropical",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 90,
    organicScore: 97,
    organicAvailable: true,
    pesticides: "Hard shell provides complete protection. Minimal pesticide concern. Typically grown without heavy chemical inputs.",
    nutritionHighlights: ["MCT fats (lauric acid)", "Manganese", "Copper", "Selenium"],
    concerns: [
      "High in saturated fat (though MCTs are metabolized differently)",
      "Coconut products often contain added sugar",
      "Coconut water brands often add sugar",
    ],
    benefits: [
      "Lauric acid — antimicrobial, antiviral",
      "MCTs provide quick brain fuel",
      "Electrolytes in coconut water",
      "Supports thyroid function",
    ],
    buyTip: "Fresh young coconuts have the highest electrolyte content and no additives. Packaged coconut water should have no added sugar or flavors in the ingredient list — pure coconut water is naturally sweet. Pink-colored coconut water indicates higher antioxidant content from natural oxidation.",
    pluCodes: ["4224"],
    nutrients: { calories: 354, carbs: 15.2, fiber: 9, sugar: 6.2, protein: 3.3, vitaminC: 3.3, potassium: 356, antioxidants: "Lauric acid, phenolic compounds" },
    season: "Year-round",
    origin: "Philippines, Thailand, Indonesia, Hawaii",
  },
  {
    id: "guava",
    name: "Guava",
    imageUrl: "/manus-storage/guava_dad3e716.jpg",
    category: "Tropical",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 87,
    organicScore: 96,
    organicAvailable: false,
    pesticides: "Generally low pesticide use. Not commonly tested by EWG. Tropical growing conditions reduce need for heavy pesticides.",
    nutritionHighlights: ["Highest vitamin C of any fruit (228mg/100g)", "Lycopene", "Folate", "Potassium"],
    concerns: ["Limited organic availability in US", "Seeds can be hard on sensitive digestion"],
    benefits: [
      "228mg vitamin C — 4x more than orange",
      "Lycopene — anti-cancer, heart health",
      "Folate for pregnancy health",
      "Extremely high antioxidant density",
    ],
    buyTip: "Excellent choice when available. Pink-fleshed guavas have more lycopene. Look at Latin/Asian grocery stores.",
    pluCodes: ["4318"],
    nutrients: { calories: 68, carbs: 14.3, fiber: 5.4, sugar: 8.9, protein: 2.6, vitaminC: 228.3, potassium: 417, antioxidants: "Lycopene, beta-carotene, quercetin" },
    season: "Year-round (tropical)",
    origin: "Mexico, Florida, California",
  },
  {
    id: "dragon-fruit",
    name: "Dragon Fruit (Pitaya)",
    imageUrl: "/manus-storage/dragon_fruit_pitaya_04c6f2a7.jpg",
    category: "Tropical",
    qualityTier: "good",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 75,
    organicScore: 90,
    organicAvailable: false,
    pesticides: "Mostly imported from Vietnam/Central America. Limited pesticide testing data. Thick skin provides some protection.",
    nutritionHighlights: ["Betalain antioxidants", "Vitamin C", "Iron", "Magnesium", "Prebiotic fiber"],
    concerns: [
      "Mostly imported — limited sourcing transparency",
      "Limited organic availability",
      "Red variety may cause red urine (harmless)",
    ],
    benefits: [
      "Betalains — unique anti-inflammatory antioxidants",
      "Prebiotic fiber feeds beneficial gut bacteria",
      "Iron for energy",
      "Low calorie, high fiber",
    ],
    buyTip: "Red-fleshed variety has more antioxidants than white. Frozen pitaya is a convenient option.",
    pluCodes: ["3922", "4922"],
    nutrients: { calories: 60, carbs: 13, fiber: 3, sugar: 8, protein: 1.2, vitaminC: 9, potassium: 436, antioxidants: "Betalains, hydroxycinnamates, flavonoids" },
    season: "Summer–Fall",
    origin: "Vietnam, Central America, Florida",
  },
  {
    id: "passion-fruit",
    name: "Passion Fruit",
    imageUrl: "/manus-storage/passion_fruit_2aecdd77.jpg",
    category: "Tropical",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 88,
    organicScore: 96,
    organicAvailable: false,
    pesticides: "Hard outer shell provides excellent protection. Minimal pesticide concern.",
    nutritionHighlights: ["Vitamin C (30mg)", "Vitamin A", "Iron", "Fiber (10.4g — very high)", "Piceatannol"],
    concerns: ["Limited availability", "Seeds may be hard to digest for some"],
    benefits: [
      "Piceatannol — anti-aging, anti-cancer compound",
      "Extremely high fiber content",
      "Supports sleep and anxiety (harman alkaloids)",
      "Rich in vitamin A",
    ],
    buyTip: "Wrinkled skin means it's ripe and sweeter. Purple variety is more common; yellow is larger.",
    pluCodes: ["4442"],
    nutrients: { calories: 97, carbs: 23.4, fiber: 10.4, sugar: 11.2, protein: 2.2, vitaminC: 30, potassium: 348, antioxidants: "Piceatannol, beta-carotene, chrysin" },
    season: "Summer–Fall",
    origin: "Hawaii, Florida, New Zealand",
  },

  // ─── STONE FRUIT ────────────────────────────────────────────────────────────
  {
    id: "peaches",
    name: "Peaches",
    imageUrl: "/manus-storage/peaches_80c33b94.jpg",
    category: "Stone Fruit",
    qualityTier: "avoid",
    ewgRank: 4,
    ewgStatus: "dirty-dozen",
    conventionalScore: 30,
    organicScore: 94,
    organicAvailable: true,
    pesticides:
      "#4 on EWG Dirty Dozen 2024. Thin fuzzy skin absorbs pesticides. Multiple fungicides and insecticides detected including chlorpyrifos.",
    nutritionHighlights: ["Vitamin C (6.6mg)", "Vitamin A", "Potassium", "Niacin (B3)"],
    concerns: [
      "#4 on EWG Dirty Dozen",
      "Chlorpyrifos — neurotoxic insecticide",
      "Thin fuzzy skin cannot be washed effectively",
      "Multiple fungicide residues",
    ],
    benefits: [
      "Beta-carotene for skin and eye health",
      "Chlorogenic acid — anti-inflammatory",
      "Supports gut health",
      "Low calorie, high flavor",
    ],
    buyTip: "Peaches are on the EWG Dirty Dozen list and consistently test for high pesticide residues, including organophosphates and neonicotinoids. Organic peaches have significantly lower pesticide exposure. Frozen organic peaches retain most nutrients and are available year-round.",
    pluCodes: ["3347", "4347"],
    nutrients: { calories: 39, carbs: 9.5, fiber: 1.5, sugar: 8.4, protein: 0.9, vitaminC: 6.6, potassium: 190, antioxidants: "Chlorogenic acid, beta-carotene, quercetin" },
    season: "Summer (June–September)",
    origin: "California, South Carolina, Georgia",
  },
  {
    id: "nectarines",
    name: "Nectarines",
    imageUrl: "/manus-storage/nectarines_3429ca1c.jpg",
    category: "Stone Fruit",
    qualityTier: "avoid",
    ewgRank: 7,
    ewgStatus: "dirty-dozen",
    conventionalScore: 32,
    organicScore: 93,
    organicAvailable: true,
    pesticides:
      "#7 on EWG Dirty Dozen 2024. Smooth skin (no fuzz) absorbs pesticides even more than peaches. Multiple systemic pesticides detected.",
    nutritionHighlights: ["Vitamin C (5.4mg)", "Beta-carotene", "Potassium", "Niacin"],
    concerns: [
      "#7 on EWG Dirty Dozen",
      "Smooth skin absorbs pesticides deeply",
      "Systemic pesticides cannot be washed off",
      "Multiple insecticide residues",
    ],
    benefits: [
      "Beta-carotene for eye health",
      "Potassium for heart health",
      "Low calorie summer fruit",
      "Antioxidant polyphenols",
    ],
    buyTip: "Nectarines are botanically nearly identical to peaches and share the same pesticide concerns — they appear on the EWG Dirty Dozen list. The smooth skin (no fuzz) does not provide additional protection from pesticide absorption. Organic is strongly recommended for the same reasons as peaches.",
    pluCodes: ["3039", "4039"],
    nutrients: { calories: 44, carbs: 10.6, fiber: 1.7, sugar: 7.9, protein: 1.1, vitaminC: 5.4, potassium: 201, antioxidants: "Chlorogenic acid, beta-carotene, catechins" },
    season: "Summer (June–September)",
    origin: "California, Washington",
  },
  {
    id: "cherries",
    name: "Cherries (Sweet & Tart)",
    imageUrl: "/manus-storage/cherries_sweet_tart_456eb70e.jpg",
    category: "Stone Fruit",
    qualityTier: "avoid",
    ewgRank: 3,
    ewgStatus: "dirty-dozen",
    conventionalScore: 29,
    organicScore: 95,
    organicAvailable: true,
    pesticides:
      "#3 on EWG Dirty Dozen 2024. Average of 5 pesticide residues. Iprodione (possible carcinogen) and multiple fungicides detected.",
    nutritionHighlights: ["Melatonin (natural sleep aid)", "Anthocyanins", "Vitamin C", "Potassium"],
    concerns: [
      "#3 on EWG Dirty Dozen",
      "Iprodione — possible carcinogen",
      "Multiple fungicide residues",
      "Average 5 pesticide residues per sample",
    ],
    benefits: [
      "Melatonin — natural sleep support",
      "Anthocyanins — powerful anti-inflammatory",
      "Reduces gout and arthritis symptoms",
      "Tart cherries reduce muscle soreness",
    ],
    buyTip: "Sweet cherries are on the EWG Dirty Dozen list and test for high pesticide residues. Tart (sour) cherries have a lower pesticide load than sweet cherries. Frozen tart cherries retain their anti-inflammatory anthocyanin content well and are available year-round.",
    pluCodes: ["4225", "3225"],
    nutrients: { calories: 63, carbs: 16, fiber: 2.1, sugar: 12.8, protein: 1.1, vitaminC: 7, potassium: 222, antioxidants: "Anthocyanins, melatonin, quercetin" },
    season: "Summer (June–August)",
    origin: "Washington, Oregon, Michigan",
  },
  {
    id: "plums",
    name: "Plums",
    imageUrl: "/manus-storage/plums_a6478554.jpg",
    category: "Stone Fruit",
    qualityTier: "caution",
    ewgRank: 20,
    ewgStatus: "middle",
    conventionalScore: 58,
    organicScore: 92,
    organicAvailable: true,
    pesticides: "Moderate pesticide load. Iprodione and other fungicides detected. Thin skin absorbs some residues.",
    nutritionHighlights: ["Vitamin C (9.5mg)", "Vitamin K", "Copper", "Sorbitol (digestive aid)"],
    concerns: [
      "Thin skin absorbs pesticides",
      "Iprodione fungicide detected",
      "Imported plums may have higher residues",
    ],
    benefits: [
      "Sorbitol supports digestive regularity",
      "Vitamin K for bone health",
      "Neochlorogenic acid — anti-inflammatory",
      "Supports iron absorption",
    ],
    buyTip: "Buy organic when available. Black plums have higher antioxidant content than red or yellow.",
    pluCodes: ["4042", "3042"],
    nutrients: { calories: 46, carbs: 11.4, fiber: 1.4, sugar: 9.9, protein: 0.7, vitaminC: 9.5, potassium: 157, antioxidants: "Neochlorogenic acid, anthocyanins, beta-carotene" },
    season: "Summer (June–October)",
    origin: "California, Chile (winter)",
  },
  {
    id: "apricots",
    name: "Apricots",
    imageUrl: "/manus-storage/apricots_46c90725.png",
    category: "Stone Fruit",
    qualityTier: "caution",
    ewgRank: 18,
    ewgStatus: "middle",
    conventionalScore: 60,
    organicScore: 91,
    organicAvailable: true,
    pesticides: "Moderate pesticide concern. Thin skin absorbs residues. Fungicides commonly used.",
    nutritionHighlights: ["Beta-carotene (highest of stone fruits)", "Vitamin C", "Potassium", "Iron"],
    concerns: [
      "Thin skin absorbs pesticides",
      "Short season — often imported off-season",
      "Dried apricots often treated with sulfur dioxide",
    ],
    benefits: [
      "Highest beta-carotene of stone fruits",
      "Supports eye health (lutein, zeaxanthin)",
      "Iron for energy",
      "Fiber for gut health",
    ],
    buyTip: "Buy organic fresh apricots. For dried, choose unsulfured organic (darker color, shorter shelf life).",
    pluCodes: ["4228", "3228"],
    nutrients: { calories: 48, carbs: 11.1, fiber: 2, sugar: 9.2, protein: 1.4, vitaminC: 10, potassium: 259, antioxidants: "Beta-carotene, lycopene, quercetin" },
    season: "Summer (May–August)",
    origin: "California, Turkey (dried)",
  },

  // ─── POME FRUIT ─────────────────────────────────────────────────────────────
  {
    id: "apples",
    name: "Apples (All Varieties)",
    imageUrl: "/manus-storage/apples_all_varieties_7cdaee38.png",
    category: "Pome Fruit",
    qualityTier: "avoid",
    ewgRank: 2,
    ewgStatus: "dirty-dozen",
    conventionalScore: 27,
    organicScore: 95,
    organicAvailable: true,
    pesticides:
      "#2 on EWG Dirty Dozen 2024. Up to 17 pesticide residues. Diphenylamine (DPA) post-harvest treatment. Thin edible skin cannot be peeled. Washing removes <50% of residues.",
    nutritionHighlights: ["Quercetin (anti-inflammatory)", "Pectin (prebiotic fiber)", "Vitamin C", "Polyphenols"],
    concerns: [
      "#2 on EWG Dirty Dozen",
      "DPA post-harvest treatment — banned in EU",
      "17+ pesticide residues detected",
      "Thin skin — cannot peel without losing nutrients",
    ],
    benefits: [
      "Quercetin — anti-inflammatory, anti-cancer",
      "Pectin feeds beneficial gut bacteria",
      "Polyphenols support heart health",
      "\"An apple a day\" — genuinely supported by research",
    ],
    buyTip: "Apples are consistently on the EWG Dirty Dozen list and test for the highest number of pesticide residues of any tree fruit. Organic apples have significantly lower pesticide exposure. The skin contains the majority of the fiber and antioxidants (quercetin, catechin), so peeling removes a significant portion of the nutritional value.",
    pluCodes: ["4131", "3131", "4133", "3133", "4135", "3135"],
    nutrients: { calories: 52, carbs: 13.8, fiber: 2.4, sugar: 10.4, protein: 0.3, vitaminC: 4.6, potassium: 107, antioxidants: "Quercetin, catechin, chlorogenic acid, pectin" },
    season: "Fall (peak September–November), year-round",
    origin: "Washington (primary), New York, Michigan",
  },
  {
    id: "pears",
    name: "Pears (Bartlett, Bosc, Anjou)",
    imageUrl: "/manus-storage/pears_bartlett_bosc_anjou_88519f10.webp",
    category: "Pome Fruit",
    qualityTier: "caution",
    ewgRank: 11,
    ewgStatus: "dirty-dozen",
    conventionalScore: 44,
    organicScore: 93,
    organicAvailable: true,
    pesticides:
      "Entered EWG Dirty Dozen 2022. Thiabendazole and other fungicides detected. Thin edible skin absorbs residues.",
    nutritionHighlights: ["Pectin (prebiotic fiber)", "Vitamin C", "Copper", "Vitamin K"],
    concerns: [
      "Entered EWG Dirty Dozen 2022",
      "Thiabendazole fungicide detected",
      "Thin edible skin absorbs residues",
    ],
    benefits: [
      "Pectin — excellent prebiotic for gut health",
      "Copper for immune function",
      "Low glycemic index",
      "Supports heart health",
    ],
    buyTip: "Buy organic. Bosc pears have slightly lower sugar than Bartlett. Eat with skin for maximum fiber.",
    pluCodes: ["4404", "3404", "4409", "3409"],
    nutrients: { calories: 57, carbs: 15.2, fiber: 3.1, sugar: 9.8, protein: 0.4, vitaminC: 4.3, potassium: 116, antioxidants: "Chlorogenic acid, quercetin, arbutin" },
    season: "Fall–Winter (August–February)",
    origin: "Washington, Oregon; Argentina (winter)",
  },
  {
    id: "quince",
    name: "Quince",
    imageUrl: "/manus-storage/quince_fc9d26ab.jpg",
    category: "Pome Fruit",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 85,
    organicScore: 95,
    organicAvailable: false,
    pesticides: "Rarely tested. Generally low pesticide use. Thick skin provides some protection.",
    nutritionHighlights: ["Vitamin C (15mg)", "Copper", "Iron", "Tannins (antimicrobial)"],
    concerns: ["Too astringent to eat raw — must be cooked", "Limited availability in US"],
    benefits: [
      "Tannins — antimicrobial, anti-inflammatory",
      "Supports digestive health",
      "Copper for immune function",
      "Unique flavor profile",
    ],
    buyTip: "Look at specialty or Middle Eastern grocery stores. Must be cooked — makes excellent jam or paste.",
    pluCodes: ["3194", "4194"],
    nutrients: { calories: 57, carbs: 15.3, fiber: 1.9, sugar: 6.3, protein: 0.4, vitaminC: 15, potassium: 197, antioxidants: "Tannins, quercetin, kaempferol" },
    season: "Fall (October–November)",
    origin: "California, imported from Turkey/Argentina",
  },

  // ─── MELONS ─────────────────────────────────────────────────────────────────
  {
    id: "watermelon",
    name: "Watermelon",
    imageUrl: "/manus-storage/watermelon_6749e771.jpg",
    category: "Melons",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "clean-fifteen",
    conventionalScore: 90,
    organicScore: 97,
    organicAvailable: true,
    pesticides: "On EWG Clean Fifteen. Thick rind protects flesh. Very low pesticide residue.",
    nutritionHighlights: ["Lycopene (highest of any fruit)", "Citrulline (athletic performance)", "Vitamin C", "Vitamin A"],
    concerns: [
      "High water content means low nutrient density per calorie",
      "High glycemic index (72) — eat in moderation if diabetic",
    ],
    benefits: [
      "Highest lycopene content of any fruit — anti-cancer",
      "Citrulline converts to arginine — improves blood flow",
      "Natural hydration (92% water)",
      "Supports athletic recovery",
    ],
    buyTip: "Conventional is perfectly safe. Choose seedless for convenience, seeded for slightly higher nutrients. Thump for hollow sound = ripe.",
    pluCodes: ["4032", "3032", "4529"],
    nutrients: { calories: 30, carbs: 7.6, fiber: 0.4, sugar: 6.2, protein: 0.6, vitaminC: 8.1, potassium: 112, antioxidants: "Lycopene, beta-carotene, citrulline" },
    season: "Summer (June–September)",
    origin: "Florida, Texas, California, Georgia",
  },
  {
    id: "cantaloupe",
    name: "Cantaloupe (Muskmelon)",
    imageUrl: "/manus-storage/cantaloupe_muskmelon_6feb11d6.jpg",
    category: "Melons",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "clean-fifteen",
    conventionalScore: 87,
    organicScore: 95,
    organicAvailable: true,
    pesticides: "On EWG Clean Fifteen. Netted rind traps some pesticides but flesh is protected. Low concern.",
    nutritionHighlights: ["Vitamin A (3382 IU — highest of melons)", "Vitamin C", "Potassium", "Beta-carotene"],
    concerns: [
      "Netted rind can harbor bacteria — wash before cutting",
      "High glycemic index when overripe",
    ],
    benefits: [
      "Highest vitamin A of any melon",
      "Beta-carotene for eye and skin health",
      "Natural hydration",
      "Supports immune function",
    ],
    buyTip: "Conventional is safe. Smell the stem end — should be sweet and fragrant when ripe. Wash rind before cutting.",
    pluCodes: ["4050", "3050"],
    nutrients: { calories: 34, carbs: 8.2, fiber: 0.9, sugar: 7.9, protein: 0.8, vitaminC: 36.7, potassium: 267, antioxidants: "Beta-carotene, zeaxanthin, lutein" },
    season: "Summer (June–September)",
    origin: "California, Arizona, Texas",
  },
  {
    id: "honeydew",
    name: "Honeydew Melon",
    imageUrl: "/manus-storage/honeydew_melon_1944a906.jpg",
    category: "Melons",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "clean-fifteen",
    conventionalScore: 86,
    organicScore: 94,
    organicAvailable: true,
    pesticides: "On EWG Clean Fifteen. Smooth rind provides good protection. Very low pesticide concern.",
    nutritionHighlights: ["Vitamin C (18mg)", "Potassium", "Vitamin B6", "Copper"],
    concerns: ["Lower antioxidant content than cantaloupe", "High sugar when overripe"],
    benefits: [
      "Excellent hydration",
      "Potassium for heart health",
      "Vitamin B6 for brain health",
      "Low calorie",
    ],
    buyTip: "Conventional is safe. Choose creamy yellow-white skin (not green) for ripeness.",
    pluCodes: ["4519", "3519"],
    nutrients: { calories: 36, carbs: 9.1, fiber: 0.8, sugar: 8.1, protein: 0.5, vitaminC: 18, potassium: 228, antioxidants: "Beta-carotene, lutein, zeaxanthin" },
    season: "Summer–Fall",
    origin: "California, Arizona",
  },

  // ─── GRAPES & VINE ──────────────────────────────────────────────────────────
  {
    id: "grapes-red",
    name: "Grapes (Red / Concord)",
    imageUrl: "/manus-storage/grapes_red_concord_42033793.jpg",
    category: "Grapes & Vine",
    qualityTier: "avoid",
    ewgRank: 5,
    ewgStatus: "dirty-dozen",
    conventionalScore: 31,
    organicScore: 94,
    organicAvailable: true,
    pesticides:
      "#5 on EWG Dirty Dozen 2024. Average 5.3 pesticide residues. Multiple fungicides. Thin skin absorbs residues. Imported grapes (Chile, Mexico) often have higher loads.",
    nutritionHighlights: ["Resveratrol (red/purple)", "Quercetin", "Vitamin C", "Vitamin K"],
    concerns: [
      "#5 on EWG Dirty Dozen",
      "5.3 average pesticide residues",
      "Multiple fungicides detected",
      "Imported grapes often higher residues",
    ],
    benefits: [
      "Resveratrol — anti-aging, heart health",
      "Quercetin — anti-inflammatory",
      "Supports cardiovascular health",
      "Polyphenols protect against oxidative stress",
    ],
    buyTip: "Grapes are on the EWG Dirty Dozen list and test for high pesticide residues. Organic is strongly recommended. Red and purple grapes contain significantly more resveratrol and anthocyanins than green grapes. Concord grapes have the highest antioxidant content of common grape varieties.",
    pluCodes: ["4023", "3023", "4022", "3022"],
    nutrients: { calories: 69, carbs: 18.1, fiber: 0.9, sugar: 15.5, protein: 0.7, vitaminC: 3.2, potassium: 191, antioxidants: "Resveratrol, quercetin, anthocyanins, OPCs" },
    season: "Summer–Fall (August–November)",
    origin: "California (domestic), Chile, Mexico (winter)",
  },
  {
    id: "grapes-green",
    name: "Grapes (Green / White)",
    imageUrl: "/manus-storage/grapes_green_white_5d28a675.jpg",
    category: "Grapes & Vine",
    qualityTier: "avoid",
    ewgRank: 5,
    ewgStatus: "dirty-dozen",
    conventionalScore: 30,
    organicScore: 90,
    organicAvailable: true,
    pesticides: "Same Dirty Dozen ranking as red grapes. Slightly lower antioxidant content but same pesticide concerns.",
    nutritionHighlights: ["Vitamin C", "Vitamin K", "Potassium", "Catechins"],
    concerns: [
      "#5 on EWG Dirty Dozen",
      "Same pesticide concerns as red grapes",
      "Lower antioxidant content than red/purple",
    ],
    benefits: ["Catechins — antioxidant", "Vitamin K for bone health", "Natural hydration", "Potassium"],
    buyTip: "Raisins are made from conventional grapes, which are on the EWG Dirty Dozen list. Drying concentrates both the nutrients and any pesticide residues present on the original fruit. Organic raisins are made from organic grapes and have significantly lower pesticide exposure. The ingredient list should contain only grapes, with no added oils or sulfur dioxide.",
    pluCodes: ["4021", "3021"],
    nutrients: { calories: 69, carbs: 18.1, fiber: 0.9, sugar: 15.5, protein: 0.7, vitaminC: 10.8, potassium: 191, antioxidants: "Catechins, quercetin, kaempferol" },
    season: "Summer–Fall",
    origin: "California, Chile",
  },

  // ─── DRIED FRUIT ────────────────────────────────────────────────────────────
  {
    id: "medjool-dates",
    name: "Medjool Dates",
    imageUrl: "/manus-storage/medjool_dates_937adf92.jpg",
    category: "Dried Fruit",
    qualityTier: "good",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 72,
    organicScore: 88,
    organicAvailable: true,
    pesticides: "Thick skin and arid growing conditions mean minimal pesticide use. Generally low concern.",
    nutritionHighlights: ["Potassium (696mg)", "Magnesium", "Copper", "Fiber (6.7g)", "Natural sugars"],
    concerns: [
      "Very high in sugar (66g/100g)",
      "High calorie density (277 cal/100g)",
      "Can spike blood sugar if eaten in excess",
    ],
    benefits: [
      "Natural energy source — better than refined sugar",
      "High potassium for heart health",
      "Magnesium for muscle and nerve function",
      "Fiber slows sugar absorption",
    ],
    buyTip: "Excellent natural sweetener in moderation. Organic Medjool dates from California or Middle East. Avoid dates with added sugar or sulfites.",
    pluCodes: ["3254", "4254", "94254"],
    nutrients: { calories: 277, carbs: 75, fiber: 6.7, sugar: 66.5, protein: 1.8, vitaminC: 0, potassium: 696, antioxidants: "Tannins, carotenoids, phenolic acids" },
    season: "Year-round (dried)",
    origin: "California, Israel, Morocco, Tunisia",
  },
  {
    id: "raisins",
    name: "Raisins (Dried Grapes)",
    imageUrl: "/manus-storage/raisins_dried_grapes_0f59c19c.jpg",
    category: "Dried Fruit",
    qualityTier: "caution",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 50,
    organicScore: 82,
    organicAvailable: true,
    pesticides: "Concentrated pesticide residues from conventional grapes. Drying concentrates both nutrients AND pesticides. Buy organic.",
    nutritionHighlights: ["Iron (1.9mg)", "Potassium (749mg)", "Boron (bone health)", "Antioxidants"],
    concerns: [
      "Concentrated pesticides from conventional grapes",
      "Very high sugar (59g/100g)",
      "Some brands add seed oils or sulfur dioxide",
      "Sticky — bad for dental health",
    ],
    benefits: [
      "Concentrated iron source",
      "Boron supports bone density",
      "Potassium for heart health",
      "Portable energy source",
    ],
    buyTip: "Raisins are made from conventional grapes, which are on the EWG Dirty Dozen list. Drying concentrates both the nutrients and any pesticide residues present on the original fruit. Organic raisins are made from organic grapes and have significantly lower pesticide exposure. The ingredient list should contain only grapes, with no added oils or sulfur dioxide.",
    pluCodes: ["3355", "4355"],
    nutrients: { calories: 299, carbs: 79.2, fiber: 3.7, sugar: 59.2, protein: 3.1, vitaminC: 2.3, potassium: 749, antioxidants: "Resveratrol (reduced), quercetin, catechins" },
    season: "Year-round",
    origin: "California (primary)",
  },
  {
    id: "dried-apricots",
    name: "Dried Apricots",
    imageUrl: "/manus-storage/dried_apricots_821f6c26.jpg",
    category: "Dried Fruit",
    qualityTier: "caution",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 48,
    organicScore: 83,
    organicAvailable: true,
    pesticides: "Concentrated pesticide residues. Most conventional dried apricots treated with sulfur dioxide (SO2) as preservative — causes reactions in sensitive individuals.",
    nutritionHighlights: ["Beta-carotene (very high)", "Iron (2.7mg)", "Potassium (1162mg)", "Fiber"],
    concerns: [
      "Sulfur dioxide (SO2) preservative in conventional",
      "Concentrated pesticide residues",
      "Very high sugar (53g/100g)",
      "Bright orange color = sulfured; dark brown = unsulfured",
    ],
    benefits: [
      "Extremely high beta-carotene",
      "Concentrated iron for anemia prevention",
      "Potassium for blood pressure",
      "Portable nutrient-dense snack",
    ],
    buyTip: "Buy organic unsulfured (dark brown color). Avoid bright orange conventional — the color comes from SO2 treatment.",
    pluCodes: ["3260", "4260"],
    nutrients: { calories: 241, carbs: 62.6, fiber: 7.3, sugar: 53.4, protein: 3.4, vitaminC: 1, potassium: 1162, antioxidants: "Beta-carotene, lycopene, chlorogenic acid" },
    season: "Year-round (dried)",
    origin: "California, Turkey",
  },
  {
    id: "prunes",
    name: "Prunes (Dried Plums)",
    imageUrl: "/manus-storage/prunes_dried_plums_84ed385b.jpg",
    category: "Dried Fruit",
    qualityTier: "good",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 65,
    organicScore: 85,
    organicAvailable: true,
    pesticides: "Moderate concern. California prunes generally have lower pesticide use. Organic preferred.",
    nutritionHighlights: ["Sorbitol (digestive aid)", "Vitamin K", "Potassium (732mg)", "Boron", "Neochlorogenic acid"],
    concerns: [
      "Very high sugar (38g/100g)",
      "Sorbitol can cause digestive upset in large amounts",
      "Some brands add potassium sorbate preservative",
    ],
    benefits: [
      "Sorbitol — natural laxative, supports regularity",
      "Neochlorogenic acid — anti-inflammatory",
      "Boron for bone density",
      "Vitamin K for bone health",
    ],
    buyTip: "Prunes are made from dried plums and are one of the most concentrated sources of sorbitol, a natural sugar alcohol that acts as a mild laxative. Organic is preferred when available. Check the ingredient list for potassium sorbate (a preservative) or added sugar, which some brands include.",
    pluCodes: ["3354", "4354"],
    nutrients: { calories: 240, carbs: 63.9, fiber: 7.1, sugar: 38.1, protein: 2.2, vitaminC: 0.6, potassium: 732, antioxidants: "Neochlorogenic acid, chlorogenic acid, quercetin" },
    season: "Year-round",
    origin: "California (90% of US supply)",
  },
  {
    id: "dried-cranberries",
    name: "Dried Cranberries (Craisins)",
    imageUrl: "/manus-storage/dried_cranberries_craisins_903851c0.jpg",
    category: "Dried Fruit",
    qualityTier: "avoid",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 25,
    organicScore: 60,
    organicAvailable: true,
    pesticides: "Added sugar and seed oils are the primary concern — not just pesticides. Most brands add sunflower oil to prevent clumping.",
    nutritionHighlights: ["Proanthocyanidins (reduced)", "Fiber", "Vitamin E"],
    concerns: [
      "Most brands add 26g+ of sugar per serving",
      "Ocean Spray Craisins contain sunflower oil",
      "Processing destroys most proanthocyanidins",
      "Very high sugar content",
    ],
    benefits: ["Some residual antioxidants", "Portable snack", "Fiber"],
    buyTip: "Most commercially dried cranberries contain 26g or more of added sugar per serving, as unsweetened cranberries are very tart. Many brands also add sunflower oil to prevent clumping. The drying and sweetening process destroys most of the proanthocyanidins (the key beneficial compound in cranberries). Fresh or frozen cranberries retain the full proanthocyanidin content.",
    pluCodes: ["3278", "4278"],
    nutrients: { calories: 308, carbs: 82.8, fiber: 5.3, sugar: 72.6, protein: 0.1, vitaminC: 0.2, potassium: 49, antioxidants: "Proanthocyanidins (reduced by processing)" },
    season: "Year-round",
    origin: "Massachusetts, Wisconsin",
  },

  // ─── PACKAGED / CANNED ──────────────────────────────────────────────────────
  {
    id: "canned-peaches",
    name: "Canned Peaches (in syrup)",
    imageUrl: "/manus-storage/canned_peaches_in_syrup_1727ccbb.jpg",
    category: "Packaged / Canned",
    qualityTier: "avoid",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 22,
    organicScore: 45,
    organicAvailable: false,
    pesticides: "Added sugar is the primary concern. Heavy syrup adds 15-20g sugar per serving. BPA lining in many cans.",
    nutritionHighlights: ["Some vitamin C (retained)", "Beta-carotene (partially retained)"],
    concerns: [
      "Heavy syrup adds 15-20g added sugar",
      "BPA lining in many cans",
      "Heat processing destroys heat-sensitive nutrients",
      "Added high fructose corn syrup in some brands",
    ],
    benefits: ["Convenient", "Some nutrients retained", "Long shelf life"],
    buyTip: "If buying canned, choose peaches in 100% juice (no syrup), BPA-free cans. Better: buy frozen peaches with no added ingredients.",
    pluCodes: ["3145", "4145"],
    nutrients: { calories: 55, carbs: 14.3, fiber: 1.5, sugar: 13.2, protein: 0.5, vitaminC: 3.7, potassium: 103, antioxidants: "Reduced by processing" },
    season: "Year-round",
    origin: "USA",
  },
  {
    id: "canned-pineapple",
    name: "Canned Pineapple (in juice)",
    imageUrl: "/manus-storage/canned_pineapple_in_juice_002536c2.jpg",
    category: "Packaged / Canned",
    qualityTier: "caution",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 55,
    organicScore: 72,
    organicAvailable: false,
    pesticides: "Bromelain enzyme destroyed by canning heat. In-juice versions are acceptable. Avoid heavy syrup.",
    nutritionHighlights: ["Vitamin C (partially retained)", "Manganese", "Thiamine"],
    concerns: [
      "Bromelain enzyme destroyed by heat processing",
      "Some brands use heavy syrup",
      "BPA lining in some cans",
    ],
    benefits: ["Convenient year-round option", "Manganese retained", "Vitamin C partially retained"],
    buyTip: "Canned pineapple in heavy syrup adds 15–20g of sugar per serving. Pineapple packed in 100% pineapple juice (no added sugar) is a significantly better option. Heat processing during canning destroys bromelain, the digestive enzyme unique to fresh pineapple. BPA-free cans are preferable since BPA can leach from can linings into acidic foods.",
    pluCodes: ["3048", "4048"],
    nutrients: { calories: 60, carbs: 15.7, fiber: 1.4, sugar: 14.2, protein: 0.5, vitaminC: 9.4, potassium: 130, antioxidants: "Reduced by processing" },
    season: "Year-round",
    origin: "Thailand, Philippines, Indonesia",
  },
  {
    id: "frozen-mixed-berries",
    name: "Frozen Mixed Berries (Organic)",
    imageUrl: "/manus-storage/frozen_mixed_berries_organic_0ce67663.jpg",
    category: "Packaged / Canned",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 60,
    organicScore: 94,
    organicAvailable: true,
    pesticides: "Frozen at peak ripeness — nutrients and antioxidants well-preserved. Organic frozen berries are one of the best value health foods available.",
    nutritionHighlights: ["Anthocyanins preserved", "Vitamin C retained", "Fiber", "Antioxidants"],
    concerns: [
      "Conventional frozen berries may have concentrated pesticides",
      "Some brands add sugar — check ingredients",
    ],
    benefits: [
      "Frozen at peak ripeness = maximum nutrients",
      "Year-round availability",
      "Often cheaper than fresh organic",
      "No added ingredients needed",
    ],
    buyTip: "Organic frozen berries are frozen at peak ripeness, which preserves antioxidants and vitamin C comparably to fresh. Conventional frozen berries may have concentrated pesticide residues from the original fruit. The ingredient list should contain only fruit with no added sugar or syrup.",
    pluCodes: ["3380", "4380", "94380"],
    nutrients: { calories: 50, carbs: 12, fiber: 3.5, sugar: 7, protein: 0.8, vitaminC: 20, potassium: 140, antioxidants: "Anthocyanins, ellagic acid, resveratrol" },
    season: "Year-round",
    origin: "USA, Chile, Mexico",
  },
  {
    id: "fruit-cups",
    name: "Fruit Cups (Dole, Del Monte)",
    imageUrl: "/manus-storage/fruit_cups_dole_del_monte_e2c5905a.jpg",
    category: "Packaged / Canned",
    qualityTier: "avoid",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 20,
    organicScore: 35,
    organicAvailable: false,
    pesticides: "High fructose corn syrup or heavy syrup, BPA plastic cups, artificial flavors in some varieties.",
    nutritionHighlights: ["Some vitamin C"],
    concerns: [
      "High fructose corn syrup or heavy syrup",
      "BPA in plastic cups",
      "Artificial flavors in some varieties",
      "Highly processed",
    ],
    benefits: ["Convenient for kids", "Some nutrients retained"],
    buyTip: "Fruit cups scored in the avoid tier because most varieties are packed in heavy syrup or high fructose corn syrup, adding 15–20g of sugar per serving. Many use BPA-lined plastic cups. The heat processing required for shelf stability destroys heat-sensitive vitamins. Varieties packed in 100% fruit juice with no added sugar have a significantly better nutritional profile.",
    pluCodes: ["3032", "4032"],
    nutrients: { calories: 70, carbs: 18, fiber: 0.5, sugar: 17, protein: 0.3, vitaminC: 2, potassium: 80, antioxidants: "Minimal" },
    season: "Year-round",
    origin: "USA",
  },
  {
    id: "applesauce",
    name: "Applesauce (Conventional)",
    imageUrl: "/manus-storage/applesauce_conventional_20dd6af8.jpg",
    category: "Packaged / Canned",
    qualityTier: "caution",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 48,
    organicScore: 78,
    organicAvailable: true,
    pesticides: "Concentrated apple pesticide residues. Unsweetened versions are acceptable. Organic strongly preferred given apple's Dirty Dozen status.",
    nutritionHighlights: ["Pectin (prebiotic)", "Vitamin C (some)", "Potassium"],
    concerns: [
      "Concentrated pesticides from conventional apples",
      "Sweetened versions add sugar",
      "Processing removes fiber from skin",
    ],
    benefits: ["Pectin for gut health", "Easy to digest", "Convenient"],
    buyTip: "Apples are on the EWG Dirty Dozen list, and applesauce concentrates the pesticide residues from multiple apples per serving. Organic applesauce has significantly lower pesticide exposure. Unsweetened varieties have no added sugar. Processing removes the apple skin, which contains the majority of the fiber and quercetin antioxidants.",
    pluCodes: ["3050", "4050"],
    nutrients: { calories: 48, carbs: 12.8, fiber: 1.3, sugar: 10.1, protein: 0.2, vitaminC: 0.9, potassium: 90, antioxidants: "Chlorogenic acid, quercetin (reduced)" },
    season: "Year-round",
    origin: "USA",
  },

  // ─── EXOTIC ─────────────────────────────────────────────────────────────────
  {
    id: "pomegranate",
    name: "Pomegranate",
    imageUrl: "/manus-storage/pomegranate_885b17f1.jpg",
    category: "Exotic",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 88,
    organicScore: 96,
    organicAvailable: true,
    pesticides: "Thick leathery rind provides excellent protection. Low pesticide concern for arils (seeds).",
    nutritionHighlights: ["Punicalagins (unique antioxidant)", "Vitamin C (10mg)", "Vitamin K", "Folate", "Potassium"],
    concerns: [
      "High in sugar (14g/100g)",
      "Pomegranate juice often has added sugar",
      "Interacts with some medications (like grapefruit)",
    ],
    benefits: [
      "Punicalagins — most powerful antioxidant known",
      "3x more antioxidants than red wine or green tea",
      "Reduces blood pressure",
      "Anti-cancer, anti-inflammatory",
    ],
    buyTip: "Pomegranate has a thick leathery rind that provides excellent protection against pesticide absorption, making conventional a lower-risk choice. Pomegranate juice should have no added sugar in the ingredient list — 100% pomegranate juice is naturally sweet. Pomegranate juice that has been diluted with apple or grape juice is a common practice; check the ingredient list.",
    pluCodes: ["4394", "3394"],
    nutrients: { calories: 83, carbs: 18.7, fiber: 4, sugar: 13.7, protein: 1.7, vitaminC: 10.2, potassium: 236, antioxidants: "Punicalagins, anthocyanins, ellagic acid" },
    season: "Fall–Winter (September–January)",
    origin: "California, Arizona; Iran, India",
  },
  {
    id: "fig",
    name: "Figs (Fresh & Dried)",
    imageUrl: "/manus-storage/figs_fresh_dried_4d640ac4.jpg",
    category: "Exotic",
    qualityTier: "good",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 70,
    organicScore: 88,
    organicAvailable: true,
    pesticides: "Generally low pesticide use. Thin skin on fresh figs absorbs some residues. Dried figs may have sulfites.",
    nutritionHighlights: ["Calcium (35mg — highest of fruits)", "Potassium (232mg)", "Fiber (2.9g)", "Copper"],
    concerns: [
      "Very high sugar when dried (47g/100g)",
      "Dried figs may contain sulfites",
      "Short fresh season",
    ],
    benefits: [
      "Highest calcium of any fruit",
      "Prebiotic fiber for gut health",
      "Copper for immune function",
      "Supports bone health",
    ],
    buyTip: "Fresh figs are excellent in season. For dried, choose organic unsulfured. Black Mission and Brown Turkey are most common varieties.",
    pluCodes: ["4922"],
    nutrients: { calories: 74, carbs: 19.2, fiber: 2.9, sugar: 16.3, protein: 0.8, vitaminC: 2, potassium: 232, antioxidants: "Chlorogenic acid, quercetin, anthocyanins" },
    season: "Summer–Fall (June–October)",
    origin: "California, Turkey (dried)",
  },
  {
    id: "lychee",
    name: "Lychee",
    imageUrl: "/manus-storage/lychee_f34523fd.jpg",
    category: "Exotic",
    qualityTier: "good",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 72,
    organicScore: 88,
    organicAvailable: false,
    pesticides: "Rough outer shell provides good protection. Limited pesticide testing data available.",
    nutritionHighlights: ["Vitamin C (71mg — very high)", "Copper", "Potassium", "Oligonol (antioxidant)"],
    concerns: [
      "High in sugar (15g/100g)",
      "Limited organic availability",
      "Mostly imported from Southeast Asia",
    ],
    benefits: [
      "Exceptional vitamin C content",
      "Oligonol — unique antioxidant with anti-aging properties",
      "Copper for immune function",
      "Supports skin health",
    ],
    buyTip: "Available fresh at Asian grocery stores in summer. Canned lychee in syrup should be avoided — high added sugar.",
    pluCodes: ["3132", "4132"],
    nutrients: { calories: 66, carbs: 16.5, fiber: 1.3, sugar: 15.2, protein: 0.8, vitaminC: 71.5, potassium: 171, antioxidants: "Oligonol, quercetin, kaempferol" },
    season: "Summer (June–July)",
    origin: "Florida, California; China, Thailand",
  },
  {
    id: "starfruit",
    name: "Starfruit (Carambola)",
    imageUrl: "/manus-storage/starfruit_carambola_c9d9e851.jpg",
    category: "Exotic",
    qualityTier: "good",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 74,
    organicScore: 88,
    organicAvailable: false,
    pesticides: "Edible waxy skin. Limited pesticide testing. Generally low pesticide use in tropical growing regions.",
    nutritionHighlights: ["Vitamin C (34mg)", "Fiber (2.8g)", "Potassium", "Copper"],
    concerns: [
      "Contains caramboxin — toxic to people with kidney disease",
      "Interacts with some medications (like grapefruit)",
      "Avoid if you have kidney problems",
    ],
    benefits: [
      "Low calorie (31 cal/100g)",
      "High fiber relative to calories",
      "Vitamin C immune support",
      "Unique flavor and presentation",
    ],
    buyTip: "Avoid if you have kidney disease or take certain medications. Yellow with slightly green edges = ripe. Available at Asian grocery stores.",
    pluCodes: ["3126", "4126"],
    nutrients: { calories: 31, carbs: 6.7, fiber: 2.8, sugar: 3.9, protein: 1, vitaminC: 34.4, potassium: 133, antioxidants: "Quercetin, gallic acid, epicatechin" },
    season: "Summer–Fall",
    origin: "Florida, Hawaii; Southeast Asia",
  },
  {
    id: "jackfruit",
    name: "Jackfruit",
    imageUrl: "/manus-storage/jackfruit_54f60647.jpg",
    category: "Exotic",
    qualityTier: "good",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 73,
    organicScore: 87,
    organicAvailable: false,
    pesticides: "Thick spiky rind provides excellent protection. Low pesticide concern for flesh.",
    nutritionHighlights: ["Vitamin C (13.7mg)", "Potassium (303mg)", "Magnesium", "Fiber", "Vitamin B6"],
    concerns: [
      "Canned green jackfruit often used as meat substitute — check for added sodium",
      "Very large fruit — difficult to prepare fresh",
      "High in sugar when ripe (16g/100g)",
    ],
    benefits: [
      "Unique texture — popular meat alternative",
      "Potassium for heart health",
      "Magnesium for muscle function",
      "Fiber for gut health",
    ],
    buyTip: "Fresh jackfruit available at Asian grocery stores. Canned green jackfruit (in brine, not syrup) is convenient for cooking.",
    pluCodes: ["3459", "4459"],
    nutrients: { calories: 95, carbs: 23.2, fiber: 1.5, sugar: 19.1, protein: 1.7, vitaminC: 13.7, potassium: 303, antioxidants: "Carotenoids, flavonoids, isoflavones" },
    season: "Summer",
    origin: "Florida, Hawaii; India, Bangladesh",
  },
  {
    id: "durian",
    name: "Durian",
    imageUrl: "/manus-storage/durian_6329edd2.jpg",
    category: "Exotic",
    qualityTier: "good",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 75,
    organicScore: 88,
    organicAvailable: false,
    pesticides: "Thick spiky shell provides complete protection. Very low pesticide concern.",
    nutritionHighlights: ["Vitamin C (19.7mg)", "Potassium (436mg)", "Thiamine (B1)", "Manganese", "Healthy fats"],
    concerns: [
      "Very high calorie (147 cal/100g for a fruit)",
      "Strong odor — banned in many public places",
      "High in sugar (27g/100g)",
      "Do not consume with alcohol",
    ],
    benefits: [
      "Unusually high in healthy fats for a fruit",
      "Thiamine for energy metabolism",
      "Potassium for heart health",
      "Tryptophan for serotonin production",
    ],
    buyTip: "Available frozen at Asian grocery stores. The 'King of Fruits' in Southeast Asia. Musang King variety is highest quality.",
    pluCodes: ["3314", "4314"],
    nutrients: { calories: 147, carbs: 27.1, fiber: 3.8, sugar: 27.1, protein: 1.5, vitaminC: 19.7, potassium: 436, antioxidants: "Carotenoids, anthocyanins, polyphenols" },
    season: "Summer",
    origin: "Thailand, Malaysia; available frozen year-round",
  },
  {
    id: "persimmon",
    name: "Persimmon (Fuyu & Hachiya)",
    imageUrl: "/manus-storage/persimmon_fuyu_hachiya_dbf371ec.jpg",
    category: "Exotic",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 84,
    organicScore: 94,
    organicAvailable: false,
    pesticides: "Generally low pesticide use. Thick skin provides good protection.",
    nutritionHighlights: ["Beta-carotene (very high)", "Vitamin C (7.5mg)", "Manganese", "Vitamin A", "Betulinic acid"],
    concerns: [
      "Hachiya variety must be fully ripe before eating (astringent when unripe)",
      "High in sugar (18g/100g)",
      "Limited organic availability",
    ],
    benefits: [
      "Extremely high beta-carotene",
      "Betulinic acid — anti-cancer properties",
      "Supports eye health",
      "Anti-inflammatory tannins",
    ],
    buyTip: "Fuyu (flat, squat) can be eaten firm. Hachiya (acorn-shaped) must be completely soft/ripe. Available at Asian grocery stores and farmers markets.",
    pluCodes: ["3146", "4146"],
    nutrients: { calories: 70, carbs: 18.6, fiber: 3.6, sugar: 12.5, protein: 0.6, vitaminC: 7.5, potassium: 161, antioxidants: "Beta-carotene, betulinic acid, catechins" },
    season: "Fall–Winter (October–February)",
    origin: "California; Japan, Korea",
  },
  {
    id: "tamarind",
    name: "Tamarind",
    imageUrl: "/manus-storage/tamarind_8eaceb07.jpg",
    category: "Exotic",
    qualityTier: "good",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 70,
    organicScore: 85,
    organicAvailable: false,
    pesticides: "Hard pod shell provides good protection. Generally low pesticide concern.",
    nutritionHighlights: ["Tartaric acid (unique antioxidant)", "Iron (2.8mg)", "Magnesium", "Potassium (628mg)", "Thiamine"],
    concerns: [
      "Very high in sugar (57g/100g)",
      "Tamarind paste/candy often has added sugar",
      "High calorie density",
    ],
    benefits: [
      "Tartaric acid — unique antioxidant",
      "Highest iron of any fruit",
      "Magnesium for muscle function",
      "Traditional digestive aid",
    ],
    buyTip: "Available at Indian and Latin grocery stores. Use fresh pods or pure tamarind paste (no added sugar) for cooking.",
    pluCodes: ["3127", "4127"],
    nutrients: { calories: 239, carbs: 62.5, fiber: 5.1, sugar: 57.4, protein: 2.8, vitaminC: 3.5, potassium: 628, antioxidants: "Tartaric acid, luteolin, quercetin" },
    season: "Year-round (dried/paste)",
    origin: "India, Mexico, Thailand",
  },
  {
    id: "kumquat",
    name: "Kumquat",
    imageUrl: "/manus-storage/kumquat_4cbbcdc5.jpg",
    category: "Exotic",
    qualityTier: "excellent",
    ewgRank: null,
    ewgStatus: "not-ranked",
    conventionalScore: 85,
    organicScore: 95,
    organicAvailable: false,
    pesticides: "Eaten whole including skin. Organic strongly preferred if eating the peel.",
    nutritionHighlights: ["Vitamin C (43.9mg)", "Fiber (6.5g — very high)", "Vitamin A", "Calcium", "Flavonoids"],
    concerns: [
      "Eaten whole with peel — organic preferred",
      "Very tart flavor not for everyone",
      "Limited availability",
    ],
    benefits: [
      "Eaten whole — maximum fiber and nutrients",
      "Highest fiber of citrus fruits",
      "Unique flavonoids in the peel",
      "Supports immune function",
    ],
    buyTip: "Eat whole — the sweet peel and tart flesh balance each other. Organic preferred since you eat the skin. Available at specialty stores.",
    pluCodes: ["3118", "4118"],
    nutrients: { calories: 71, carbs: 15.9, fiber: 6.5, sugar: 9.4, protein: 1.9, vitaminC: 43.9, potassium: 186, antioxidants: "Flavonoids in peel, vitamin C, beta-carotene" },
    season: "Winter–Spring (November–March)",
    origin: "California, Florida",
  },
];

/** Get the display score for a fruit entry */
export function getFruitDisplayScore(entry: FruitEntry, organic: boolean): number {
  return organic ? entry.organicScore : entry.conventionalScore;
}

/** Summary stats for the fruit database */
export const FRUIT_DB_STATS = {
  total: ALL_FRUITS.length,
  dirtyDozen: ALL_FRUITS.filter((f) => f.ewgStatus === "dirty-dozen").length,
  cleanFifteen: ALL_FRUITS.filter((f) => f.ewgStatus === "clean-fifteen").length,
  excellent: ALL_FRUITS.filter((f) => f.qualityTier === "excellent").length,
  good: ALL_FRUITS.filter((f) => f.qualityTier === "good").length,
  caution: ALL_FRUITS.filter((f) => f.qualityTier === "caution").length,
  avoid: ALL_FRUITS.filter((f) => f.qualityTier === "avoid").length,
};
