/**
 * EatVera — Bread & Grains Database
 * 150+ products: bread, pasta, rice, cereals, oats, tortillas, crackers
 * Scoring based on: seed oils, HFCS, enriched flour, whole grain %, additives
 */

export type GrainsQualityTier = "elite" | "good" | "average" | "poor" | "avoid";

export type GrainsCategory =
  | "bread"
  | "pasta"
  | "rice"
  | "cereal"
  | "oats"
  | "tortillas"
  | "crackers"
  | "wraps"
  | "bagels"
  | "muffins";

export interface GrainsEntry {
  id: string;
  name: string;
  brand: string;
  category: GrainsCategory;
  score: number;
  qualityTier: GrainsQualityTier;
  barcode?: string;
  // Key flags
  hasSeedOils: boolean;
  hasHFCS: boolean;
  hasEnrichedFlour: boolean;
  isWholeGrain: boolean;
  isOrganic: boolean;
  isGlutenFree: boolean;
  wholeGrainPercent?: number; // 0-100
  // Details
  ingredients?: string;
  concerns: string[];
  benefits: string[];
  buyTip: string;
  averagePrice?: number;
  imageUrl?: string;
  nutrients?: {
    calories?: number;
    carbs?: number;
    fiber?: number;
    sugar?: number;
    protein?: number;
    sodium?: number;
};
}

export const GRAINS_QUALITY_TIER_CONFIG: Record<GrainsQualityTier, { label: string; color: string; bg: string; border: string }> = {
  elite:   { label: "Elite",   color: "#145A3A", bg: "#F0FAF2", border: "#b8e8b8" },
  good:    { label: "Good",    color: "#3FA34D", bg: "#f5fdf5", border: "#c8ecc8" },
  average: { label: "Average", color: "#d97706", bg: "#fffbf0", border: "#fde68a" },
  poor:    { label: "Poor",    color: "#ea580c", bg: "#fff7ed", border: "#fed7aa" },
  avoid:   { label: "Avoid",   color: "#dc2626", bg: "#fff5f5", border: "#fca5a5" },
};

export const GRAINS_CATEGORIES: { id: GrainsCategory | "all"; label: string; emoji: string }[] = [
  { id: "all",      label: "All",       emoji: "🌾" },
  { id: "bread",    label: "Bread",     emoji: "🍞" },
  { id: "pasta",    label: "Pasta",     emoji: "🍝" },
  { id: "rice",     label: "Rice",      emoji: "🍚" },
  { id: "cereal",   label: "Cereal",    emoji: "🥣" },
  { id: "oats",     label: "Oats",      emoji: "🌾" },
  { id: "tortillas",label: "Tortillas", emoji: "🫓" },
  { id: "crackers", label: "Crackers",  emoji: "🍘" },
  { id: "bagels",   label: "Bagels",    emoji: "🥯" },
];

export function getGrainsColor(score: number): string {
  if (score >= 85) return "#145A3A";
  if (score >= 70) return "#3FA34D";
  if (score >= 50) return "#d97706";
  if (score >= 30) return "#ea580c";
  return "#dc2626";
}

export const ALL_GRAINS: GrainsEntry[] = [

  // ─── BREAD ───────────────────────────────────────────────────────────────

  {
    id: "ezekiel-sprouted-bread",
    name: "Sprouted Grain Bread",
    brand: "Food for Life (Ezekiel 4:9)",
    category: "bread",
    score: 97,
    qualityTier: "elite",
    barcode: "073472000029",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Organic Sprouted Wheat, Filtered Water, Organic Sprouted Barley, Organic Sprouted Millet, Organic Malted Barley, Organic Sprouted Lentils, Organic Sprouted Soybeans, Organic Sprouted Spelt, Fresh Yeast, Sea Salt",
    concerns: [],
    benefits: [
      "100% sprouted whole grains — no flour at all",
      "Sprouting increases nutrient bioavailability and reduces phytic acid",
      "Complete protein from grain + legume combination",
      "No added sugars, oils, or preservatives",
    ],
    buyTip: "The gold standard of bread. Find in the freezer section. Toast from frozen.",
    nutrients: { calories: 80, carbs: 15, fiber: 3, sugar: 0, protein: 4, sodium: 75 },
    imageUrl: "/manus-storage/ezekiel-sesame-bread_67473352.jpg",
  },
  {
    id: "ezekiel-cinnamon-raisin",
    name: "Sprouted Grain Cinnamon Raisin Bread",
    brand: "Food for Life (Ezekiel 4:9)",
    category: "bread",
    score: 91,
    qualityTier: "elite",
    barcode: "073472000098",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Organic Sprouted Wheat, Filtered Water, Organic Raisins, Organic Sprouted Barley, Organic Sprouted Millet, Organic Malted Barley, Organic Sprouted Lentils, Organic Sprouted Soybeans, Organic Sprouted Spelt, Fresh Yeast, Organic Cinnamon, Sea Salt",
    concerns: ["Contains raisins — slightly higher sugar"],
    benefits: ["Sprouted grains", "Organic", "No oils or HFCS"],
    buyTip: "Great for toast. Natural sweetness from raisins only.",
    nutrients: { calories: 80, carbs: 18, fiber: 2, sugar: 6, protein: 4, sodium: 80 },
    imageUrl: "/manus-storage/ezekiel-cinnamon-raisin_9b678f1e.jpg",
  },
  {
    id: "dave-killer-21-grain",
    name: "21 Whole Grains and Seeds Bread",
    brand: "Dave's Killer Bread",
    category: "bread",
    score: 82,
    qualityTier: "good",
    barcode: "013764000025",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Whole Wheat Flour, Water, Whole Grain Blend (Oats, Rye, Barley, Millet, Flaxseeds, Sunflower Seeds, Pumpkin Seeds, Sesame Seeds, Amaranth, Quinoa, Buckwheat, Chia Seeds, Sorghum, Teff), Cane Sugar, Yeast, Sea Salt, Vinegar, Cultured Wheat Starch",
    concerns: ["Contains added cane sugar", "Slightly higher carb count"],
    benefits: ["Certified organic", "21 whole grains and seeds", "No seed oils or HFCS", "Good fiber content"],
    buyTip: "One of the best mainstream breads. Available at most grocery stores.",
    nutrients: { calories: 120, carbs: 22, fiber: 5, sugar: 5, protein: 5, sodium: 170 },
    imageUrl: "/manus-storage/daves-powerseed_5427327f.jpg",
  },
  {
    id: "dave-killer-powerseed",
    name: "Powerseed Bread",
    brand: "Dave's Killer Bread",
    category: "bread",
    score: 80,
    qualityTier: "good",
    barcode: "013764000049",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Whole Wheat Flour, Water, Sunflower Seeds, Pumpkin Seeds, Flaxseeds, Sesame Seeds, Cane Sugar, Yeast, Sea Salt, Vinegar",
    concerns: ["Contains added cane sugar"],
    benefits: ["Organic", "Seed-rich for omega-3", "No seed oils or HFCS"],
    buyTip: "Great for sandwiches. High in healthy fats from seeds.",
    nutrients: { calories: 130, carbs: 20, fiber: 4, sugar: 4, protein: 6, sodium: 160 },
    imageUrl: "/manus-storage/daves-powerseed_5427327f.jpg",
  },
  {
    id: "silver-hills-sprouted",
    name: "Squirrelly Bread (Sprouted)",
    brand: "Silver Hills Sprouted Bakery",
    category: "bread",
    score: 88,
    qualityTier: "elite",
    barcode: "058496000013",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Organic Sprouted Whole Wheat, Filtered Water, Organic Sunflower Seeds, Organic Pumpkin Seeds, Organic Flaxseeds, Organic Sesame Seeds, Organic Rolled Oats, Sea Salt, Yeast",
    concerns: [],
    benefits: ["100% sprouted whole wheat", "Certified organic", "No oils or sweeteners", "High in seeds"],
    buyTip: "Excellent choice. Available at Whole Foods and natural grocers.",
    nutrients: { calories: 110, carbs: 18, fiber: 4, sugar: 1, protein: 5, sodium: 130 },
    imageUrl: "/manus-storage/silver-hills-squirrelly_d835feed.jpg",
  },
  {
    id: "pepperidge-farm-whole-grain",
    name: "Whole Grain White Bread",
    brand: "Pepperidge Farm",
    category: "bread",
    score: 52,
    qualityTier: "average",
    barcode: "014100044253",
    imageUrl: "/manus-storage/pepperidge-farm-whole-grain_51f9573e.png",
    hasSeedOils: true,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 50,
    ingredients: "Whole Wheat Flour, Water, High Fructose Corn Syrup, Soybean Oil, Yeast, Salt, Calcium Propionate, Datem, Monoglycerides, Soy Lecithin",
    concerns: ["Contains soybean oil (seed oil)", "Contains HFCS", "Contains calcium propionate (preservative)", "Datem and monoglycerides are emulsifiers"],
    benefits: ["Contains some whole wheat"],
    buyTip: "This bread scored low due to soybean oil, high fructose corn syrup, and multiple synthetic emulsifiers. Look for breads with whole grain flour as the first ingredient and fewer than 5 additives.",
    nutrients: { calories: 110, carbs: 22, fiber: 2, sugar: 3, protein: 4, sodium: 170 },
  },
  {
    id: "wonder-bread-classic",
    name: "Classic White Bread",
    brand: "Wonder Bread",
    category: "bread",
    score: 18,
    qualityTier: "avoid",
    barcode: "072250007909",
    hasSeedOils: true,
    hasHFCS: true,
    hasEnrichedFlour: true,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 0,
    ingredients: "Enriched Flour (Wheat Flour, Malted Barley Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Folic Acid), Water, High Fructose Corn Syrup, Soybean Oil, Yeast, Salt, Calcium Propionate, Datem, Ethoxylated Mono and Diglycerides, Sodium Stearoyl Lactylate, Calcium Sulfate, Ammonium Sulfate, Monocalcium Phosphate, Soy Lecithin, Azodicarbonamide",
    concerns: [
      "Enriched white flour — stripped of all nutrition",
      "High Fructose Corn Syrup",
      "Soybean oil (inflammatory seed oil)",
      "Azodicarbonamide — a dough conditioner banned in Europe",
      "Multiple synthetic emulsifiers",
      "Calcium propionate preservative",
    ],
    benefits: [],
    buyTip: "This bread is made primarily from enriched white flour, which has been stripped of fiber and most nutrients. It also contains HFCS, soybean oil, and azodicarbonamide — a dough conditioner not permitted in European baked goods.",
    nutrients: { calories: 70, carbs: 13, fiber: 0, sugar: 2, protein: 2, sodium: 130 },
    imageUrl: "/manus-storage/wonder-bread-white_add62f48.jpg",
  },
  {
    id: "nature-own-honey-wheat",
    name: "Honey Wheat Bread",
    brand: "Nature's Own",
    category: "bread",
    score: 28,
    qualityTier: "poor",
    barcode: "072250011129",
    hasSeedOils: true,
    hasHFCS: false,
    hasEnrichedFlour: true,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 20,
    ingredients: "Enriched Bleached Flour (Wheat Flour, Malted Barley Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Folic Acid), Water, Whole Wheat Flour, Sugar, Soybean Oil, Honey, Yeast, Salt, Calcium Propionate, Datem, Monoglycerides, Soy Lecithin",
    concerns: ["Enriched bleached flour as primary ingredient", "Soybean oil", "Multiple emulsifiers", "Calcium propionate"],
    benefits: ["Contains some whole wheat and honey"],
    buyTip: "Despite the wheat-forward name, enriched bleached flour is the primary ingredient here, meaning most natural fiber and nutrients have been removed. The soybean oil and multiple emulsifiers further reduce the quality score.",
    nutrients: { calories: 70, carbs: 13, fiber: 1, sugar: 3, protein: 3, sodium: 130 },
    imageUrl: "/manus-storage/natures-own-honey-wheat_86802e2b.jpg",
  },
  {
    id: "sara-lee-classic",
    name: "Classic White Bread",
    brand: "Sara Lee",
    category: "bread",
    score: 20,
    qualityTier: "avoid",
    barcode: "072250011006",
    hasSeedOils: true,
    hasHFCS: true,
    hasEnrichedFlour: true,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 0,
    ingredients: "Enriched Flour (Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Folic Acid), Water, High Fructose Corn Syrup, Soybean Oil, Yeast, Salt, Calcium Propionate, Datem, Monoglycerides, Calcium Sulfate, Soy Lecithin",
    concerns: ["Enriched white flour", "HFCS", "Soybean oil", "Multiple emulsifiers"],
    benefits: [],
    buyTip: "Made from enriched white flour with HFCS and soybean oil, this bread provides minimal fiber or micronutrients per serving. The enrichment process adds back only a fraction of what was removed during refining.",
    nutrients: { calories: 70, carbs: 13, fiber: 0, sugar: 2, protein: 2, sodium: 130 },
    imageUrl: "/manus-storage/sara-lee-white_2cd3c423.jpg",
  },
  {
    id: "arnold-whole-wheat",
    name: "100% Whole Wheat Bread",
    brand: "Arnold",
    category: "bread",
    score: 55,
    qualityTier: "average",
    barcode: "073130000053",
    hasSeedOils: true,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Whole Wheat Flour, Water, Sugar, Soybean Oil, Yeast, Salt, Calcium Propionate, Datem, Monoglycerides, Soy Lecithin, Citric Acid",
    concerns: ["Contains soybean oil", "Emulsifiers (Datem, monoglycerides)", "Calcium propionate preservative"],
    benefits: ["100% whole wheat flour", "No HFCS"],
    buyTip: "A solid whole wheat option with 100% whole wheat flour. The main concern is soybean oil, which is high in omega-6 linoleic acid. Emulsifiers like DATEM and monoglycerides are also present as dough conditioners.",
    nutrients: { calories: 120, carbs: 23, fiber: 3, sugar: 4, protein: 5, sodium: 160 },
    imageUrl: "/manus-storage/arnold-whole-wheat_831835fb.jpg",
  },
  {
    id: "udi-gluten-free-white",
    name: "Gluten-Free White Sandwich Bread",
    brand: "Udi's",
    category: "bread",
    score: 42,
    qualityTier: "average",
    barcode: "698997811008",
    hasSeedOils: true,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: true,
    wholeGrainPercent: 0,
    ingredients: "Water, Tapioca Starch, Brown Rice Flour, Canola Oil, Egg Whites, Tapioca Maltodextrin, Evaporated Cane Juice, Yeast, Xanthan Gum, Salt, Cultured Corn Syrup Solids",
    concerns: ["Canola oil (seed oil)", "Tapioca starch as primary carb — low fiber", "Xanthan gum emulsifier"],
    benefits: ["Certified gluten-free", "No HFCS"],
    buyTip: "Best GF option for those with celiac. Not ideal for metabolic health.",
    nutrients: { calories: 120, carbs: 24, fiber: 1, sugar: 3, protein: 2, sodium: 170 },
    imageUrl: "/manus-storage/udis-gf-white_f50e5d90.jpg",
  },
  {
    id: "canyon-bakehouse-gf",
    name: "Gluten-Free Mountain White Bread",
    brand: "Canyon Bakehouse",
    category: "bread",
    score: 48,
    qualityTier: "average",
    barcode: "856683002001",
    hasSeedOils: true,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: true,
    wholeGrainPercent: 0,
    ingredients: "Water, Tapioca Starch, Brown Rice Flour, Canola Oil, Whole Grain Sorghum Flour, Egg Whites, Cane Sugar, Yeast, Xanthan Gum, Salt",
    concerns: ["Canola oil (seed oil)", "Low fiber", "Xanthan gum"],
    benefits: ["Gluten-free", "No HFCS", "Contains sorghum"],
    buyTip: "Better than Udi's for GF bread. Still contains canola oil.",
    nutrients: { calories: 110, carbs: 22, fiber: 1, sugar: 2, protein: 2, sodium: 160 },
    imageUrl: "/manus-storage/canyon-bakehouse-gf_4d46b869.jpg",
  },
  {
    id: "sourdough-acme",
    name: "Sourdough Bread",
    brand: "Acme Bread",
    category: "bread",
    score: 84,
    qualityTier: "good",
    barcode: "041303004456",
    imageUrl: "/manus-storage/la-brea-sourdough_127f4373.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 30,
    ingredients: "Unbleached Wheat Flour, Water, Salt, Sourdough Culture",
    concerns: ["Primarily white flour (not whole grain)", "Low fiber"],
    benefits: ["Only 4 ingredients", "Traditional sourdough fermentation improves digestibility", "No oils, sugars, or preservatives", "Lower glycemic index than regular white bread"],
    buyTip: "Excellent choice for those who want traditional bread. Fermentation makes it more digestible.",
    nutrients: { calories: 120, carbs: 24, fiber: 1, sugar: 0, protein: 5, sodium: 230 },
  },
  {
    id: "la-brea-sourdough",
    name: "Sourdough Boule",
    brand: "La Brea Bakery",
    category: "bread",
    score: 72,
    qualityTier: "good",
    barcode: "073296000041",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 0,
    ingredients: "Enriched Flour (Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Folic Acid), Water, Salt, Sourdough Culture",
    concerns: ["Uses enriched flour (not whole grain)", "Lower fiber content"],
    benefits: ["No seed oils", "No HFCS", "No preservatives", "Sourdough fermentation"],
    buyTip: "A clean mainstream sourdough with no seed oils or preservatives. The main limitation is enriched white flour as the base, which is lower in fiber than whole grain versions. Sourdough fermentation does improve digestibility compared to standard white bread.",
    nutrients: { calories: 130, carbs: 26, fiber: 1, sugar: 0, protein: 5, sodium: 250 },
    imageUrl: "/manus-storage/la-brea-sourdough_127f4373.jpg",
  },
  {
    id: "thomas-english-muffins",
    name: "Original English Muffins",
    brand: "Thomas'",
    category: "muffins",
    score: 30,
    qualityTier: "poor",
    barcode: "072030000024",
    imageUrl: "/manus-storage/thomas-english-muffins_04cb0218.jpg",
    hasSeedOils: true,
    hasHFCS: false,
    hasEnrichedFlour: true,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 0,
    ingredients: "Enriched Flour (Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Folic Acid), Water, Farina, Soybean Oil, Yeast, Sugar, Salt, Calcium Propionate, Monoglycerides, Fumaric Acid, Soy Lecithin",
    concerns: ["Enriched white flour", "Soybean oil", "Calcium propionate preservative", "Monoglycerides emulsifier"],
    benefits: ["Low calorie per serving"],
    buyTip: "This English muffin scored low primarily due to enriched white flour as the base and soybean oil as a fat source. Enriched flour has most of its natural fiber and micronutrients removed during processing, with only a few synthetic vitamins added back.",
    nutrients: { calories: 130, carbs: 26, fiber: 1, sugar: 1, protein: 5, sodium: 200 },
  },
  {
    id: "ezekiel-english-muffins",
    name: "Sprouted Grain English Muffins",
    brand: "Food for Life (Ezekiel 4:9)",
    category: "muffins",
    score: 93,
    qualityTier: "elite",
    barcode: "073472001002",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Organic Sprouted Wheat, Filtered Water, Organic Sprouted Barley, Organic Sprouted Millet, Organic Malted Barley, Organic Sprouted Lentils, Organic Sprouted Soybeans, Organic Sprouted Spelt, Fresh Yeast, Sea Salt",
    concerns: [],
    benefits: ["100% sprouted grains", "Organic", "No oils or sweeteners", "Complete protein"],
    buyTip: "Best English muffin available. Freeze and toast from frozen.",
    nutrients: { calories: 160, carbs: 30, fiber: 6, sugar: 0, protein: 8, sodium: 160 },
    imageUrl: "/manus-storage/ezekiel-english-muffins_4deaf69e.jpg",
  },

  // ─── BAGELS ──────────────────────────────────────────────────────────────

  {
    id: "thomas-plain-bagels",
    name: "Plain Bagels",
    brand: "Thomas'",
    category: "bagels",
    score: 25,
    qualityTier: "poor",
    barcode: "072030000055",
    imageUrl: "/manus-storage/thomas-english-muffins_04cb0218.jpg",
    hasSeedOils: false,
    hasHFCS: true,
    hasEnrichedFlour: true,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 0,
    ingredients: "Enriched Flour (Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Folic Acid), Water, High Fructose Corn Syrup, Yeast, Salt, Calcium Propionate, Monoglycerides, Soy Lecithin",
    concerns: ["Enriched white flour", "HFCS", "Calcium propionate", "Monoglycerides"],
    benefits: ["Low fat"],
    buyTip: "This bagel scored low due to enriched white flour and high fructose corn syrup. At 55g of refined carbohydrates per serving with minimal fiber, it has a high glycemic impact. Calcium propionate is used as a preservative to extend shelf life.",
    nutrients: { calories: 270, carbs: 55, fiber: 2, sugar: 9, protein: 10, sodium: 430 },
  },
  {
    id: "ezekiel-sesame-bagels",
    name: "Sprouted Grain Sesame Bagels",
    brand: "Food for Life (Ezekiel 4:9)",
    category: "bagels",
    score: 90,
    qualityTier: "elite",
    barcode: "073472002009",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Organic Sprouted Wheat, Filtered Water, Organic Sesame Seeds, Organic Sprouted Barley, Organic Sprouted Millet, Organic Malted Barley, Organic Sprouted Lentils, Organic Sprouted Soybeans, Organic Sprouted Spelt, Fresh Yeast, Sea Salt",
    concerns: [],
    benefits: ["Sprouted grains", "Organic", "No oils or sweeteners", "Sesame seeds add healthy fats"],
    buyTip: "Best bagel option. High protein and fiber.",
    nutrients: { calories: 200, carbs: 36, fiber: 6, sugar: 0, protein: 10, sodium: 200 },
    imageUrl: "/manus-storage/ezekiel-sesame-bread_67473352.jpg",
  },

  // ─── PASTA ───────────────────────────────────────────────────────────────

  {
    id: "jovial-brown-rice-pasta",
    name: "Brown Rice Penne",
    brand: "Jovial",
    category: "pasta",
    score: 88,
    qualityTier: "elite",
    barcode: "039978002143",
    imageUrl: "/manus-storage/jovial-einkorn-spaghetti_43e36414.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: true,
    wholeGrainPercent: 100,
    ingredients: "Organic Brown Rice",
    concerns: ["Higher glycemic than legume-based pasta"],
    benefits: ["Single ingredient — organic brown rice", "Gluten-free", "No additives whatsoever", "Whole grain"],
    buyTip: "Best gluten-free pasta. One ingredient, certified organic.",
    nutrients: { calories: 210, carbs: 44, fiber: 2, sugar: 0, protein: 4, sodium: 0 },
  },
  {
    id: "banza-chickpea-pasta",
    name: "Chickpea Rotini",
    brand: "Banza",
    category: "pasta",
    score: 91,
    qualityTier: "elite",
    barcode: "857063005001",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: true,
    wholeGrainPercent: 0,
    ingredients: "Chickpeas, Tapioca, Pea Protein, Xanthan Gum",
    concerns: ["Xanthan gum emulsifier", "Not organic"],
    benefits: ["25g protein per serving (vs 7g in regular pasta)", "3x the fiber of regular pasta", "Gluten-free", "Low glycemic index", "High in iron"],
    buyTip: "Excellent high-protein, high-fiber pasta. Great for diabetics and low-carb eaters.",
    nutrients: { calories: 190, carbs: 32, fiber: 8, sugar: 2, protein: 14, sodium: 60 },
    imageUrl: "/manus-storage/banza-chickpea-rotini_cd0d9728.jpg",
  },
  {
    id: "barilla-whole-grain",
    name: "Whole Grain Penne",
    brand: "Barilla",
    category: "pasta",
    score: 72,
    qualityTier: "good",
    barcode: "076808000432",
    imageUrl: "/manus-storage/delallo-whole-wheat-penne_70f5db0a.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 51,
    ingredients: "Whole Grain Durum Wheat Semolina, Durum Wheat Semolina",
    concerns: ["Only 51% whole grain — rest is refined semolina", "Not organic"],
    benefits: ["No seed oils", "No additives", "Good fiber content", "Clean ingredients"],
    buyTip: "A clean pasta with no additives, seed oils, or HFCS. The score reflects that only 51% is whole grain — the rest is refined semolina, which is lower in fiber and micronutrients than 100% whole grain options.",
    nutrients: { calories: 200, carbs: 41, fiber: 6, sugar: 2, protein: 8, sodium: 0 },
  },
  {
    id: "barilla-classic",
    name: "Classic Spaghetti",
    brand: "Barilla",
    category: "pasta",
    score: 60,
    qualityTier: "average",
    barcode: "076808000012",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: true,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 0,
    ingredients: "Semolina (Enriched Durum Wheat Semolina, Niacin, Iron, Thiamine Mononitrate, Riboflavin, Folic Acid), Durum Wheat Flour",
    concerns: ["Enriched/refined semolina — stripped of bran and germ", "Low fiber", "High glycemic index"],
    benefits: ["No seed oils", "No HFCS", "No additives", "Clean otherwise"],
    buyTip: "A clean pasta with no additives or seed oils. The score reflects its enriched semolina base, which has been refined and stripped of most natural fiber. It has a higher glycemic index than whole grain pasta alternatives.",
    nutrients: { calories: 200, carbs: 42, fiber: 2, sugar: 2, protein: 7, sodium: 0 },
    imageUrl: "/manus-storage/barilla-spaghetti_1c20bcfd.jpeg",
  },
  {
    id: "ronzoni-gluten-free",
    name: "Gluten Free Rotini",
    brand: "Ronzoni",
    category: "pasta",
    score: 55,
    qualityTier: "average",
    barcode: "071300011107",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: true,
    wholeGrainPercent: 0,
    ingredients: "Corn Flour, Rice Flour",
    concerns: ["Corn flour — not whole grain", "Low fiber", "Higher glycemic index"],
    benefits: ["Gluten-free", "No additives", "Clean ingredients"],
    buyTip: "A clean gluten-free option with just two ingredients. The score reflects the use of refined corn and rice flour rather than whole grain, resulting in lower fiber content and a higher glycemic index per serving.",
    nutrients: { calories: 210, carbs: 44, fiber: 1, sugar: 0, protein: 4, sodium: 0 },
    imageUrl: "/manus-storage/ronzoni-gf-rotini_d8c96557.jpg",
  },
  {
    id: "tinkyada-rice-pasta",
    name: "Brown Rice Spaghetti",
    brand: "Tinkyada",
    category: "pasta",
    score: 85,
    qualityTier: "good",
    barcode: "624724100015",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: true,
    wholeGrainPercent: 100,
    ingredients: "Brown Rice, Rice Bran",
    concerns: ["Not organic"],
    benefits: ["100% whole grain brown rice", "Gluten-free", "Only 2 ingredients", "Good texture when cooked"],
    buyTip: "Best texture of all GF pasta brands. Great whole grain option.",
    nutrients: { calories: 210, carbs: 44, fiber: 2, sugar: 0, protein: 4, sodium: 5 },
    imageUrl: "/manus-storage/tinkyada-brown-rice-pasta_74d5bf13.jpg",
  },
  {
    id: "dreamfields-pasta",
    name: "Rotini Pasta",
    brand: "Dreamfields",
    category: "pasta",
    score: 45,
    qualityTier: "average",
    barcode: "047325400016",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: true,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 0,
    ingredients: "Semolina (Enriched Durum Wheat Semolina, Niacin, Iron, Thiamine Mononitrate, Riboflavin, Folic Acid), Inulin, Oat Fiber, Wheat Fiber",
    concerns: ["Enriched semolina base", "Added isolated fibers (inulin) — not the same as whole grain fiber", "Marketing claims about 'protected carbs' were disputed by FTC"],
    benefits: ["Higher fiber than regular pasta", "No seed oils"],
    buyTip: "Skip. The 'low glycemic' claims were misleading. Choose Banza or whole grain instead.",
    nutrients: { calories: 190, carbs: 41, fiber: 5, sugar: 2, protein: 7, sodium: 0 },
    imageUrl: "/manus-storage/dreamfields-rotini_f67e5163.jpg",
  },

  // ─── RICE ────────────────────────────────────────────────────────────────

  {
    id: "lundberg-brown-rice",
    name: "Organic Long Grain Brown Rice",
    brand: "Lundberg Family Farms",
    category: "rice",
    score: 95,
    qualityTier: "elite",
    barcode: "073416010013",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: true,
    wholeGrainPercent: 100,
    ingredients: "Organic Long Grain Brown Rice",
    concerns: ["Rice can contain arsenic — vary your grains"],
    benefits: ["Single ingredient", "Certified organic", "Whole grain", "Gluten-free", "Good source of magnesium and B vitamins"],
    buyTip: "Best rice brand. Lundberg tests for arsenic levels. Rinse before cooking.",
    nutrients: { calories: 170, carbs: 36, fiber: 2, sugar: 0, protein: 4, sodium: 0 },
    imageUrl: "/manus-storage/lundberg-brown-rice_e1dddf5c.png",
  },
  {
    id: "lundberg-white-jasmine",
    name: "Organic White Jasmine Rice",
    brand: "Lundberg Family Farms",
    category: "rice",
    score: 80,
    qualityTier: "good",
    barcode: "073416010020",
    imageUrl: "/manus-storage/lundberg-brown-rice_e1dddf5c.png",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: false,
    isOrganic: true,
    isGlutenFree: true,
    wholeGrainPercent: 0,
    ingredients: "Organic White Jasmine Rice",
    concerns: ["White rice — bran and germ removed", "Lower fiber and nutrients than brown rice"],
    benefits: ["Single ingredient", "Certified organic", "Gluten-free", "Easier to digest than brown rice"],
    buyTip: "Good choice for those with digestive issues. Organic white rice is fine in moderation.",
    nutrients: { calories: 160, carbs: 36, fiber: 0, sugar: 0, protein: 3, sodium: 0 },
  },
  {
    id: "uncle-bens-white-rice",
    name: "Original Long Grain White Rice",
    brand: "Ben's Original (Uncle Ben's)",
    category: "rice",
    score: 55,
    qualityTier: "average",
    barcode: "054800430019",
    imageUrl: "/manus-storage/bens-original-rice_38dabd29.jpeg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: true,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: true,
    wholeGrainPercent: 0,
    ingredients: "Enriched Long Grain Parboiled Rice (Rice, Niacin, Iron, Thiamine Mononitrate, Folic Acid)",
    concerns: ["Enriched white rice — synthetic vitamins added back after stripping", "Low fiber", "High glycemic index"],
    benefits: ["No seed oils or HFCS", "Parboiling retains some nutrients"],
    buyTip: "A clean, additive-free rice. The score reflects its enriched white rice base — the bran and germ have been removed during milling, which reduces fiber and most natural B vitamins. Parboiling does retain slightly more nutrients than standard milling.",
    nutrients: { calories: 170, carbs: 37, fiber: 0, sugar: 0, protein: 4, sodium: 0 },
  },
  {
    id: "success-boil-in-bag",
    name: "Boil-in-Bag White Rice",
    brand: "Success",
    category: "rice",
    score: 40,
    qualityTier: "average",
    barcode: "072400002009",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: true,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: true,
    wholeGrainPercent: 0,
    ingredients: "Enriched Long Grain White Rice (Rice, Niacin, Iron, Thiamine Mononitrate, Folic Acid)",
    concerns: ["Enriched white rice", "Plastic boil-in-bag may leach microplastics", "Low fiber"],
    benefits: ["Convenient", "No additives"],
    buyTip: "This rice scored lower due to enriched white rice and the boil-in-bag format, which uses plastic that may release microplastics during cooking at high temperatures. The rice itself has the same nutritional profile as other enriched white rice products.",
    nutrients: { calories: 190, carbs: 42, fiber: 0, sugar: 0, protein: 4, sodium: 0 },
    imageUrl: "/manus-storage/success-white-rice_ebf12100.jpg",
  },
  {
    id: "seeds-of-change-quinoa-brown-rice",
    name: "Organic Quinoa & Brown Rice",
    brand: "Seeds of Change",
    category: "rice",
    score: 85,
    qualityTier: "good",
    barcode: "013562000151",
    imageUrl: "/manus-storage/lundberg-brown-rice_e1dddf5c.png",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: true,
    wholeGrainPercent: 100,
    ingredients: "Organic Brown Rice, Organic Quinoa, Water, Sea Salt",
    concerns: ["Pre-cooked pouches — slightly higher sodium"],
    benefits: ["Certified organic", "Quinoa adds complete protein", "Whole grain", "Ready in 90 seconds"],
    buyTip: "Best convenient rice option. Organic and whole grain.",
    nutrients: { calories: 220, carbs: 43, fiber: 3, sugar: 0, protein: 6, sodium: 280 },
  },

  // ─── CEREALS ─────────────────────────────────────────────────────────────

  {
    id: "ezekiel-sprouted-cereal",
    name: "Sprouted Grain Cereal",
    brand: "Food for Life (Ezekiel 4:9)",
    category: "cereal",
    score: 95,
    qualityTier: "elite",
    barcode: "073472003006",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Organic Sprouted Wheat, Organic Sprouted Barley, Organic Sprouted Millet, Organic Malted Barley, Organic Sprouted Lentils, Organic Sprouted Soybeans, Organic Sprouted Spelt, Sea Salt",
    concerns: [],
    benefits: ["100% sprouted grains", "No sugar added", "Organic", "Complete protein"],
    buyTip: "Best cereal available. No sugar, all sprouted grains.",
    nutrients: { calories: 200, carbs: 40, fiber: 6, sugar: 0, protein: 8, sodium: 160 },
    imageUrl: "/manus-storage/ezekiel-cereal_f873da33.jpg",
  },
  {
    id: "one-degree-sprouted-oat-os",
    name: "Sprouted Oat O's",
    brand: "One Degree Organics",
    category: "cereal",
    score: 88,
    qualityTier: "elite",
    barcode: "624915000012",
    imageUrl: "/manus-storage/natures-path-heritage_46bf04e9.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Organic Sprouted Whole Grain Oat Flour, Organic Cane Sugar, Sea Salt, Vitamin E (Mixed Tocopherols)",
    concerns: ["Contains cane sugar"],
    benefits: ["Sprouted whole grain oats", "Certified organic", "Biodynamic certified", "No artificial anything"],
    buyTip: "Best O-shaped cereal. Sprouted and organic.",
    nutrients: { calories: 110, carbs: 22, fiber: 3, sugar: 1, protein: 4, sodium: 100 },
  },
  {
    id: "nature-path-heritage-flakes",
    name: "Heritage Flakes",
    brand: "Nature's Path",
    category: "cereal",
    score: 82,
    qualityTier: "good",
    barcode: "058449000011",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Organic Whole Wheat, Organic Whole Rye, Organic Whole Barley, Organic Whole Spelt, Organic Whole Kamut, Organic Cane Sugar, Sea Salt",
    concerns: ["Contains cane sugar"],
    benefits: ["5 ancient whole grains", "Certified organic", "No seed oils or HFCS", "High fiber"],
    buyTip: "Excellent everyday cereal. Ancient grains provide diverse nutrients.",
    nutrients: { calories: 120, carbs: 25, fiber: 5, sugar: 5, protein: 4, sodium: 130 },
    imageUrl: "/manus-storage/natures-path-heritage_46bf04e9.jpg",
  },
  {
    id: "cheerios-original",
    name: "Original Cheerios",
    brand: "General Mills",
    category: "cereal",
    score: 55,
    qualityTier: "average",
    barcode: "016000275287",
    imageUrl: "/manus-storage/natures-path-heritage_46bf04e9.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Whole Grain Oats, Modified Corn Starch, Sugar, Salt, Calcium Carbonate, Oat Bran, Monocalcium Phosphate, Wheat Starch, Niacinamide, Iron, Zinc, Vitamin B6, Riboflavin, Vitamin A, Thiamine, Vitamin B12, Folic Acid, Vitamin D",
    concerns: ["Contains modified corn starch", "Synthetic vitamin fortification", "Glyphosate residue detected in independent testing", "Not organic"],
    benefits: ["Whole grain oats", "Low sugar (1g)", "No seed oils or HFCS", "High fiber"],
    buyTip: "A solid whole grain cereal with low sugar and no seed oils. The main concerns are modified corn starch as a texture agent and the fact that it is not organic — independent testing has detected glyphosate residue in non-organic oat products.",
    nutrients: { calories: 100, carbs: 20, fiber: 3, sugar: 1, protein: 3, sodium: 140 },
  },
  {
    id: "honey-nut-cheerios",
    name: "Honey Nut Cheerios",
    brand: "General Mills",
    category: "cereal",
    score: 35,
    qualityTier: "poor",
    barcode: "016000275294",
    imageUrl: "/manus-storage/natures-path-heritage_46bf04e9.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Whole Grain Oats, Sugar, Oat Bran, Modified Corn Starch, Honey, Brown Sugar Syrup, Salt, Calcium Carbonate, Almond Flavor, Niacinamide, Zinc, Iron, Vitamin B6, Riboflavin, Vitamin A, Thiamine, Folic Acid, Vitamin D",
    concerns: ["9g sugar per serving — high for a breakfast cereal", "Modified corn starch", "Artificial almond flavor", "Glyphosate residue detected in testing"],
    benefits: ["Whole grain oats", "No seed oils"],
    buyTip: "This cereal scored lower due to 9g of added sugar per serving, which is high for a breakfast food. It also contains modified corn starch and artificial almond flavor. Independent testing has detected glyphosate residue in non-organic oat products.",
    nutrients: { calories: 110, carbs: 22, fiber: 2, sugar: 9, protein: 3, sodium: 150 },
  },
  {
    id: "frosted-flakes",
    name: "Frosted Flakes",
    brand: "Kellogg's",
    category: "cereal",
    score: 15,
    qualityTier: "avoid",
    barcode: "038000591013",
    imageUrl: "/manus-storage/natures-path-heritage_46bf04e9.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: true,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 0,
    ingredients: "Milled Corn, Sugar, Malt Flavor, Salt, BHT for Freshness, Niacinamide, Reduced Iron, Zinc, Vitamin B6, Riboflavin, Thiamine Hydrochloride, Vitamin A, Folic Acid, Vitamin D, Vitamin B12",
    concerns: ["11g sugar per serving", "Refined corn — no whole grain", "BHT preservative (linked to cancer in animal studies)", "Synthetic vitamins only", "Extremely high glycemic index"],
    benefits: [],
    buyTip: "This cereal scored low due to refined corn as the primary ingredient with no whole grain content, 11g of sugar per serving, and BHT as a preservative. BHT is an antioxidant additive that has shown mixed results in animal carcinogenicity studies, though it remains FDA-approved.",
    nutrients: { calories: 130, carbs: 31, fiber: 1, sugar: 11, protein: 1, sodium: 150 },
  },
  {
    id: "lucky-charms",
    name: "Lucky Charms",
    brand: "General Mills",
    category: "cereal",
    score: 10,
    qualityTier: "avoid",
    barcode: "016000275348",
    imageUrl: "/manus-storage/natures-path-heritage_46bf04e9.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 50,
    ingredients: "Whole Grain Oats, Sugar, Oat Flour, Corn Starch, Modified Corn Starch, Salt, Gelatin, Red 40, Yellow 5, Yellow 6, Blue 1, Artificial Flavor, Vitamin E, Niacinamide, Zinc, Iron, Vitamin B6, Riboflavin, Thiamine, Vitamin A, Folic Acid, Vitamin D, Vitamin B12",
    concerns: ["10g sugar per serving", "Artificial dyes Red 40, Yellow 5, Yellow 6, Blue 1 — linked to hyperactivity in children", "Artificial flavor", "Modified corn starch", "Gelatin"],
    benefits: [],
    buyTip: "This cereal scored low due to 10g of sugar per serving and four artificial dyes (Red 40, Yellow 5, Yellow 6, Blue 1). Multiple studies have found associations between these synthetic dyes and increased hyperactivity in children. The EU requires warning labels on foods containing these dyes.",
    nutrients: { calories: 110, carbs: 22, fiber: 2, sugar: 10, protein: 2, sodium: 190 },
  },
  {
    id: "raisin-bran-kelloggs",
    name: "Raisin Bran",
    brand: "Kellogg's",
    category: "cereal",
    score: 40,
    qualityTier: "average",
    barcode: "038000591037",
    imageUrl: "/manus-storage/natures-path-heritage_46bf04e9.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 70,
    ingredients: "Whole Grain Wheat, Raisins, Wheat Bran, Sugar, High Fructose Corn Syrup, Salt, Malt Flavor, Niacinamide, Iron, Zinc, Vitamin B6, Riboflavin, Thiamine, Folic Acid, Vitamin D",
    concerns: ["17g sugar per serving — extremely high", "HFCS in raisin coating", "Synthetic vitamin fortification"],
    benefits: ["Whole grain wheat", "High fiber (7g)", "No seed oils"],
    buyTip: "This cereal scored lower due to 17g of sugar per serving — one of the highest among bran cereals. The raisin coating contains high fructose corn syrup, which contributes to the elevated sugar count. The whole grain wheat base and 7g of fiber are genuine positives.",
    nutrients: { calories: 190, carbs: 46, fiber: 7, sugar: 17, protein: 5, sodium: 210 },
  },
  {
    id: "granola-bob-red-mill",
    name: "Organic Whole Grain Granola",
    brand: "Bob's Red Mill",
    category: "cereal",
    score: 75,
    qualityTier: "good",
    barcode: "039978003010",
    imageUrl: "/manus-storage/bobs-red-mill-oats_a87b17a8.jpeg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Organic Rolled Oats, Organic Cane Sugar, Organic Coconut Oil, Organic Honey, Sea Salt, Organic Vanilla Extract",
    concerns: ["Contains cane sugar and honey — 12g sugar per serving", "Higher calorie density"],
    benefits: ["Organic", "Coconut oil instead of seed oils", "Whole grain oats", "No artificial anything"],
    buyTip: "Good granola. Watch portion size — it's calorie dense. Best with plain yogurt.",
    nutrients: { calories: 280, carbs: 42, fiber: 4, sugar: 12, protein: 6, sodium: 80 },
  },

  // ─── OATS ────────────────────────────────────────────────────────────────

  {
    id: "bobs-red-mill-rolled-oats",
    name: "Organic Extra Thick Rolled Oats",
    brand: "Bob's Red Mill",
    category: "oats",
    score: 97,
    qualityTier: "elite",
    barcode: "039978003034",
    imageUrl: "/manus-storage/bobs-red-mill-oats_a87b17a8.jpeg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Organic Whole Grain Rolled Oats",
    concerns: ["Oats can contain glyphosate — choose certified organic"],
    benefits: ["Single ingredient", "Certified organic", "Whole grain", "High in beta-glucan (lowers cholesterol)", "No additives"],
    buyTip: "The gold standard of oats. One ingredient, certified organic. Cook on stovetop.",
    nutrients: { calories: 150, carbs: 27, fiber: 4, sugar: 1, protein: 5, sodium: 0 },
  },
  {
    id: "quaker-instant-oats",
    name: "Instant Oatmeal Original",
    brand: "Quaker",
    category: "oats",
    score: 52,
    qualityTier: "average",
    barcode: "030000056011",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Whole Grain Rolled Oats, Salt",
    concerns: ["Not organic — Quaker oats have tested positive for glyphosate in independent studies", "Instant oats have higher glycemic index than rolled oats"],
    benefits: ["Whole grain", "Only 2 ingredients", "No seed oils or HFCS", "Convenient"],
    buyTip: "A clean, minimally processed oat with just two ingredients. The score reflects that it is not certified organic — independent testing has detected glyphosate residue in non-organic oat products. Instant-cut oats also have a slightly higher glycemic index than thick-rolled oats.",
    nutrients: { calories: 100, carbs: 19, fiber: 3, sugar: 0, protein: 4, sodium: 75 },
    imageUrl: "/manus-storage/quaker-original-oatmeal_f501f0df.jpeg",
  },
  {
    id: "quaker-maple-brown-sugar",
    name: "Instant Oatmeal Maple & Brown Sugar",
    brand: "Quaker",
    category: "oats",
    score: 28,
    qualityTier: "poor",
    barcode: "030000056028",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Whole Grain Rolled Oats, Sugar, Salt, Natural and Artificial Maple Flavor, Caramel Color",
    concerns: ["12g sugar per packet", "Artificial maple flavor", "Caramel color (possible carcinogen)", "Not organic"],
    benefits: ["Whole grain oats"],
    buyTip: "This flavored oat packet scored lower due to 12g of added sugar per serving, artificial maple flavor, and caramel color. The base oats are whole grain, but the added flavorings and sweeteners significantly reduce the overall quality score.",
    nutrients: { calories: 160, carbs: 32, fiber: 3, sugar: 12, protein: 4, sodium: 250 },
    imageUrl: "/manus-storage/quaker-maple-oatmeal_db2b0b3b.jpg",
  },
  {
    id: "one-degree-sprouted-oats",
    name: "Organic Sprouted Rolled Oats",
    brand: "One Degree Organics",
    category: "oats",
    score: 99,
    qualityTier: "elite",
    barcode: "624915000029",
    imageUrl: "/manus-storage/bobs-red-mill-oats_a87b17a8.jpeg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Organic Sprouted Whole Grain Oats",
    concerns: [],
    benefits: ["Sprouted oats — higher nutrient bioavailability", "Certified biodynamic organic", "Single ingredient", "Reduced phytic acid from sprouting"],
    buyTip: "The best oats available. Sprouted and biodynamic certified.",
    nutrients: { calories: 150, carbs: 27, fiber: 4, sugar: 1, protein: 5, sodium: 0 },
  },

  // ─── TORTILLAS ───────────────────────────────────────────────────────────

  {
    id: "siete-almond-flour-tortillas",
    name: "Almond Flour Tortillas",
    brand: "Siete",
    category: "tortillas",
    score: 88,
    qualityTier: "elite",
    barcode: "857251006001",
    imageUrl: "/manus-storage/siete-cassava-tortillas_f228bb1e.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: true,
    wholeGrainPercent: 0,
    ingredients: "Almond Flour, Tapioca Flour, Water, Coconut Oil, Sea Salt",
    concerns: ["High in calories from almond flour", "Not organic"],
    benefits: ["Grain-free and gluten-free", "Coconut oil instead of seed oils", "Clean 5-ingredient formula", "High in healthy fats and protein"],
    buyTip: "Best grain-free tortilla. Great for paleo/keto. Warm in a dry skillet.",
    nutrients: { calories: 100, carbs: 10, fiber: 1, sugar: 0, protein: 3, sodium: 115 },
  },
  {
    id: "siete-cassava-tortillas",
    name: "Cassava Flour Tortillas",
    brand: "Siete",
    category: "tortillas",
    score: 82,
    qualityTier: "good",
    barcode: "857251006018",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: true,
    wholeGrainPercent: 0,
    ingredients: "Cassava Flour, Water, Coconut Oil, Sea Salt",
    concerns: ["High in starch — higher glycemic than almond flour version", "Not organic"],
    benefits: ["Grain-free and gluten-free", "Coconut oil", "4 clean ingredients", "Closest texture to flour tortillas"],
    buyTip: "Best texture of all GF tortillas. Great for tacos.",
    nutrients: { calories: 90, carbs: 18, fiber: 1, sugar: 0, protein: 1, sodium: 115 },
    imageUrl: "/manus-storage/siete-cassava-tortillas_f228bb1e.jpg",
  },
  {
    id: "mission-flour-tortillas",
    name: "Soft Taco Flour Tortillas",
    brand: "Mission",
    category: "tortillas",
    score: 22,
    qualityTier: "avoid",
    barcode: "073731000019",
    imageUrl: "/manus-storage/mission-tortillas_4dbeb569.jpeg",
    hasSeedOils: true,
    hasHFCS: false,
    hasEnrichedFlour: true,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 0,
    ingredients: "Enriched Flour (Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Folic Acid), Water, Vegetable Shortening (Interesterified Soybean Oil, Hydrogenated Soybean Oil), Sugar, Salt, Leavening (Sodium Bicarbonate, Sodium Aluminum Sulfate, Corn Starch, Monocalcium Phosphate), Fumaric Acid, Calcium Propionate, Cellulose Gum, Distilled Monoglycerides, Enzymes, Soy Lecithin",
    concerns: [
      "Hydrogenated soybean oil — contains trans fats",
      "Interesterified soybean oil — linked to metabolic dysfunction",
      "Enriched white flour",
      "Sodium aluminum sulfate leavening",
      "Multiple emulsifiers and preservatives",
    ],
    benefits: ["Widely available"],
    buyTip: "This tortilla scored low due to hydrogenated soybean oil and interesterified soybean oil. Hydrogenated oils contain trans fats, which the FDA has determined have no safe level of consumption. Interesterified oils are a newer fat modification process with limited long-term safety data.",
    nutrients: { calories: 140, carbs: 24, fiber: 1, sugar: 1, protein: 3, sodium: 320 },
  },
  {
    id: "old-el-paso-flour-tortillas",
    name: "Flour Tortillas",
    brand: "Old El Paso",
    category: "tortillas",
    score: 25,
    qualityTier: "poor",
    barcode: "046000820018",
    imageUrl: "/manus-storage/mission-tortillas_4dbeb569.jpeg",
    hasSeedOils: true,
    hasHFCS: false,
    hasEnrichedFlour: true,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 0,
    ingredients: "Enriched Flour (Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Folic Acid), Water, Soybean Oil, Sugar, Salt, Leavening, Calcium Propionate, Monoglycerides",
    concerns: ["Enriched white flour", "Soybean oil", "Calcium propionate", "Monoglycerides"],
    benefits: ["No HFCS"],
    buyTip: "This tortilla scored low due to enriched white flour as the base and soybean oil as the primary fat. Enriched flour has most of its natural fiber removed during processing. Calcium propionate is used as a mold inhibitor and preservative.",
    nutrients: { calories: 130, carbs: 22, fiber: 1, sugar: 1, protein: 3, sodium: 290 },
  },
  {
    id: "guerrero-corn-tortillas",
    name: "White Corn Tortillas",
    brand: "Guerrero",
    category: "tortillas",
    score: 68,
    qualityTier: "average",
    barcode: "074030000013",
    imageUrl: "/manus-storage/mission-tortillas_4dbeb569.jpeg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: true,
    wholeGrainPercent: 100,
    ingredients: "Ground Corn Treated with Lime (Masa), Water, Cellulose Gum, Propionic Acid, Benzoic Acid, Phosphoric Acid, Guar Gum, Amylase",
    concerns: ["Propionic acid and benzoic acid preservatives", "Cellulose gum emulsifier", "Not organic — corn is often GMO"],
    benefits: ["Whole grain corn", "Gluten-free", "No seed oils", "Traditional nixtamalization"],
    buyTip: "A traditional corn tortilla made with nixtamalized masa. The score reflects the use of preservatives (propionic acid, benzoic acid) and the fact that it is not certified organic — conventional corn in the US is predominantly grown from GMO varieties.",
    nutrients: { calories: 50, carbs: 11, fiber: 1, sugar: 0, protein: 1, sodium: 10 },
  },
  {
    id: "la-tortilla-factory-whole-wheat",
    name: "Whole Wheat Low Carb Tortillas",
    brand: "La Tortilla Factory",
    category: "tortillas",
    score: 58,
    qualityTier: "average",
    barcode: "071518000015",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 80,
    ingredients: "Whole Wheat Flour, Water, Oat Fiber, Wheat Gluten, Soybean Oil, Salt, Leavening, Cellulose Gum, Calcium Propionate",
    concerns: ["Contains soybean oil", "Calcium propionate preservative", "Added wheat gluten"],
    benefits: ["High fiber (9g)", "Whole wheat", "Low net carbs"],
    buyTip: "Good fiber content but contains soybean oil. Acceptable for low-carb diets.",
    nutrients: { calories: 80, carbs: 15, fiber: 9, sugar: 0, protein: 5, sodium: 280 },
    imageUrl: "/manus-storage/la-tortilla-factory_34eac89e.jpg",
  },

  // ─── CRACKERS ────────────────────────────────────────────────────────────

  {
    id: "ak-mak-crackers",
    name: "100% Whole Wheat Sesame Crackers",
    brand: "Ak-Mak",
    category: "crackers",
    score: 90,
    qualityTier: "elite",
    barcode: "072220000018",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Whole Wheat Flour, Sesame Seeds, Unbleached Wheat Flour, Honey, Sesame Oil, Yeast, Salt",
    concerns: ["Contains a small amount of sesame oil (not a major seed oil)", "Not organic"],
    benefits: ["100% whole wheat", "Sesame seeds add healthy fats", "No artificial anything", "Clean short ingredient list"],
    buyTip: "Excellent cracker. Great with cheese, hummus, or avocado.",
    nutrients: { calories: 115, carbs: 19, fiber: 3, sugar: 1, protein: 4, sodium: 220 },
    imageUrl: "/manus-storage/ak-mak-crackers_d07f9418.jpg",
  },
  {
    id: "wasa-crispbread",
    name: "Whole Grain Crispbread",
    brand: "Wasa",
    category: "crackers",
    score: 88,
    qualityTier: "elite",
    barcode: "041220000019",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Whole Grain Rye Flour, Water, Yeast, Salt",
    concerns: ["Not organic"],
    benefits: ["4 clean ingredients", "100% whole grain rye", "High fiber (3g per cracker)", "No oils or sweeteners", "Traditional Scandinavian recipe"],
    buyTip: "One of the cleanest crackers available. High fiber, minimal ingredients.",
    nutrients: { calories: 35, carbs: 7, fiber: 3, sugar: 0, protein: 1, sodium: 35 },
    imageUrl: "/manus-storage/wasa-crispbread_9484e328.jpeg",
  },
  {
    id: "ryvita-dark-rye",
    name: "Dark Rye Crispbread",
    brand: "Ryvita",
    category: "crackers",
    score: 87,
    qualityTier: "elite",
    barcode: "011152000013",
    imageUrl: "/manus-storage/wasa-crispbread_9484e328.jpeg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Whole Grain Rye Flour, Salt",
    concerns: ["Not organic"],
    benefits: ["Only 2 ingredients", "100% whole grain rye", "Very high fiber", "No oils or additives"],
    buyTip: "Excellent cracker. Just 2 ingredients. Great for weight management.",
    nutrients: { calories: 35, carbs: 8, fiber: 2, sugar: 0, protein: 1, sodium: 50 },
  },
  {
    id: "triscuit-original",
    name: "Original Crackers",
    brand: "Triscuit",
    category: "crackers",
    score: 72,
    qualityTier: "good",
    barcode: "044000032029",
    imageUrl: "/manus-storage/triscuit-original_5db07bef.jpg",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 100,
    ingredients: "Whole Grain Soft White Winter Wheat, Soybean Oil, Salt",
    concerns: ["Contains soybean oil (seed oil)", "Not organic"],
    benefits: ["100% whole grain wheat", "Only 3 ingredients", "No HFCS or enriched flour", "High fiber"],
    buyTip: "A solid whole grain cracker with just three ingredients. The score reflects the use of soybean oil, which is high in omega-6 linoleic acid. The whole grain wheat base and 3g of fiber per serving are genuine positives.",
    nutrients: { calories: 120, carbs: 20, fiber: 3, sugar: 0, protein: 3, sodium: 160 },
  },
  {
    id: "ritz-crackers",
    name: "Original Crackers",
    brand: "Ritz",
    category: "crackers",
    score: 20,
    qualityTier: "avoid",
    barcode: "044000032036",
    hasSeedOils: true,
    hasHFCS: false,
    hasEnrichedFlour: true,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 0,
    ingredients: "Enriched Flour (Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Folic Acid), Soybean Oil, Sugar, Salt, Leavening (Baking Soda, Calcium Phosphate), High Fructose Corn Syrup, Soy Lecithin, Natural Flavor",
    concerns: ["Enriched white flour", "Soybean oil", "HFCS", "Multiple emulsifiers"],
    benefits: [],
    buyTip: "This cracker scored low due to enriched white flour as the primary ingredient, soybean oil, and high fructose corn syrup. Enriched flour has been stripped of its natural fiber and most micronutrients, with only a few synthetic vitamins added back.",
    nutrients: { calories: 80, carbs: 10, fiber: 0, sugar: 1, protein: 1, sodium: 105 },
    imageUrl: "/manus-storage/ritz-crackers_698050e6.jpg",
  },
  {
    id: "cheez-it-original",
    name: "Original Crackers",
    brand: "Cheez-It",
    category: "crackers",
    score: 18,
    qualityTier: "avoid",
    barcode: "024100103805",
    hasSeedOils: true,
    hasHFCS: false,
    hasEnrichedFlour: true,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: false,
    wholeGrainPercent: 0,
    ingredients: "Enriched Flour (Wheat Flour, Niacin, Reduced Iron, Vitamin B1, Riboflavin, Folic Acid), Vegetable Oil (High Oleic Soybean, Soybean, Hydrogenated Soybean), Skim Milk Cheese, Salt, Paprika, Yeast, Paprika Oleoresin, Soy Lecithin",
    concerns: ["Enriched white flour", "Multiple soybean oils including hydrogenated", "Hydrogenated soybean oil = trans fats", "Highly processed"],
    benefits: ["Contains real cheese"],
    buyTip: "This cracker scored low due to enriched white flour and multiple soybean oils, including hydrogenated soybean oil. Hydrogenated oils contain trans fats, which the FDA has determined have no safe level of consumption. The combination of refined flour and trans fats is the primary reason for the low score.",
    nutrients: { calories: 150, carbs: 17, fiber: 0, sugar: 0, protein: 3, sodium: 230 },
    imageUrl: "/manus-storage/cheez-it-original_9bcbb9c7.jpg",
  },
  {
    id: "mary-gone-crackers",
    name: "Original Crackers (GF)",
    brand: "Mary's Gone Crackers",
    category: "crackers",
    score: 86,
    qualityTier: "elite",
    barcode: "858133000014",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: true,
    isOrganic: true,
    isGlutenFree: true,
    wholeGrainPercent: 100,
    ingredients: "Organic Brown Rice, Organic Quinoa, Organic Brown Flax Seeds, Organic Brown Sesame Seeds, Organic Amaranth, Filtered Water, Tamari (Water, Organic Soybeans, Salt), Sea Salt",
    concerns: ["Contains soy (tamari)", "Not suitable for soy-free diets"],
    benefits: ["Certified organic", "Gluten-free", "5 whole grains and seeds", "No seed oils", "High fiber"],
    buyTip: "Excellent GF cracker. Organic, whole grain, and seed-rich.",
    nutrients: { calories: 140, carbs: 21, fiber: 3, sugar: 0, protein: 3, sodium: 160 },
    imageUrl: "/manus-storage/marys-gone-crackers_b4200418.jpg",
  },
  {
    id: "simple-mills-almond-crackers",
    name: "Almond Flour Crackers",
    brand: "Simple Mills",
    category: "crackers",
    score: 84,
    qualityTier: "good",
    barcode: "855174006001",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: false,
    isOrganic: false,
    isGlutenFree: true,
    wholeGrainPercent: 0,
    ingredients: "Almond Flour, Tapioca Starch, Sunflower Seeds, Flax Seeds, Cassava Flour, Organic Sunflower Oil, Rosemary Extract, Sea Salt",
    concerns: ["Contains sunflower oil (seed oil)", "Not organic"],
    benefits: ["Grain-free and gluten-free", "Almond flour base — high protein and healthy fats", "Clean ingredients", "No HFCS or enriched flour"],
    buyTip: "Great grain-free cracker. The sunflower oil is a minor concern.",
    nutrients: { calories: 150, carbs: 16, fiber: 1, sugar: 1, protein: 3, sodium: 115 },
    imageUrl: "/manus-storage/simple-mills-crackers_119bd217.png",
  },
  {
    id: "bread-alone-french-sourdough",
    name: "Organic French Sourdough",
    brand: "Bread Alone",
    category: "bread",
    score: 94,
    qualityTier: "elite",
    barcode: "020865000010",
    hasSeedOils: false,
    hasHFCS: false,
    hasEnrichedFlour: false,
    isWholeGrain: false,
    isOrganic: true,
    isGlutenFree: false,
    wholeGrainPercent: 0,
    ingredients: "Organic Unbleached Wheat Flour, Water, Sea Salt, Organic Sourdough Culture",
    concerns: ["Not whole grain (uses unbleached white flour)", "Contains gluten"],
    benefits: ["Certified organic", "Only 4 ingredients", "Traditional sourdough fermentation", "No seed oils", "No preservatives", "No added sugar", "Naturally leavened with wild yeast", "Long fermentation improves digestibility"],
    buyTip: "One of the cleanest breads available. Only 4 organic ingredients — flour, water, salt, culture. True artisan sourdough from a Hudson Valley bakery using organic grains since 1983.",
    nutrients: { calories: 130, carbs: 26, fiber: 1, sugar: 0, protein: 5, sodium: 290 },
    imageUrl: "/manus-storage/bread-alone-french-sourdough_349d068e.jpg",
  },
];

export function getGrainsTierFromScore(score: number): GrainsQualityTier {
  if (score >= 85) return "elite";
  if (score >= 70) return "good";
  if (score >= 50) return "average";
  if (score >= 30) return "poor";
  return "avoid";
}
