/**
 * EatVera — Comprehensive US Ice Cream Database
 * Quality ratings based on:
 * - Ingredient simplicity (fewer = better)
 * - Seed oil content (palm oil, coconut oil derivatives vs real cream)
 * - Artificial sweeteners, colors, and flavors
 * - Gums and stabilizers (carrageenan, polysorbate 80, etc.)
 * - Organic / grass-fed / hormone-free dairy
 * - Sugar content and type (cane sugar vs HFCS vs sugar alcohols)
 */
export type IceCreamQualityTier = "elite" | "good" | "average" | "poor" | "avoid";
export type IceCreamCategory =
  | "Classic"
  | "Light & Low-Cal"
  | "Organic & Grass-Fed"
  | "Plant-Based"
  | "Gelato & Sorbet"
  | "Kids & Novelty";

export interface IceCreamEntry {
  id: string;
  name: string;
  brand: string;
  category: IceCreamCategory;
  qualityTier: IceCreamQualityTier;
  score: number;
  barcode?: string;
  organic: boolean;
  grassFed: boolean;
  hormoneFree: boolean;
  hasSeedOils: boolean;
  hasArtificialSweeteners: boolean;
  hasCarrageenan: boolean;
  hasArtificialColors: boolean;
  ingredientCount: number;
  concerns: string[];
  benefits: string[];
  ingredients?: string;
  buyTip: string;
  averagePrice?: number;
  imageUrl?: string;
  nutrients?: {
    calories?: number;
    fat?: number;
    saturatedFat?: number;
    sugar?: number;
    protein?: number;
    servingSize?: string;
  };
}

export const ICE_CREAM_QUALITY_TIER_CONFIG: Record<
  IceCreamQualityTier,
  { label: string; color: string; bg: string; border: string; score: string }
> = {
  elite: { label: "Elite", color: "#145A3A", bg: "#F0FAF2", border: "#86d086", score: "85–100" },
  good: { label: "Good", color: "#3FA34D", bg: "#F0FAF2", border: "#b8e8b8", score: "65–84" },
  average: { label: "Average", color: "#d97706", bg: "#fffbf0", border: "#fde68a", score: "45–64" },
  poor: { label: "Poor", color: "#ea580c", bg: "#fff7f0", border: "#fed7aa", score: "25–44" },
  avoid: { label: "Avoid", color: "#dc2626", bg: "#fff5f5", border: "#fca5a5", score: "0–24" },
};

export const ICE_CREAM_CATEGORIES: { id: string; label: string }[] = [
  { id: "all", label: "All" },
  { id: "Classic", label: "Classic" },
  { id: "Light & Low-Cal", label: "Light" },
  { id: "Organic & Grass-Fed", label: "Organic" },
  { id: "Plant-Based", label: "Plant-Based" },
  { id: "Gelato & Sorbet", label: "Gelato" },
  { id: "Kids & Novelty", label: "Kids" },
];

export const ALL_ICE_CREAM: IceCreamEntry[] = [
  // ─── ELITE ──────────────────────────────────────────────────────────────
  {
    id: "cosmic-bliss-vanilla-bean",
    name: "Vanilla Bean Nirvana",
    brand: "Cosmic Bliss",
    category: "Organic & Grass-Fed",
    qualityTier: "elite",
    score: 95,
    organic: true,
    grassFed: true,
    hormoneFree: true,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 5,
    concerns: [],
    benefits: [
      "USDA Organic certified",
      "100% grass-fed dairy",
      "Only 5 ingredients",
      "No gums, stabilizers, or carrageenan",
      "No artificial anything",
    ],
    ingredients: "Organic grass-fed cream, organic grass-fed milk, organic cane sugar, organic vanilla extract, organic vanilla bean",
    buyTip: "The gold standard of clean ice cream. Available at Whole Foods, Sprouts, and most natural grocers.",
    averagePrice: 7.99,
    imageUrl: "/manus-storage/cosmic-bliss-vanilla_4eaf20dc.png",
    nutrients: { calories: 250, fat: 16, saturatedFat: 10, sugar: 19, protein: 4, servingSize: "2/3 cup" },
  },
  {
    id: "alecs-vanilla",
    name: "Vanilla Bean",
    brand: "Alec's Ice Cream",
    category: "Organic & Grass-Fed",
    qualityTier: "elite",
    score: 94,
    organic: true,
    grassFed: true,
    hormoneFree: true,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 5,
    concerns: [],
    benefits: [
      "Organic grass-fed A2 dairy",
      "Only 5 ingredients",
      "A2 protein (easier to digest)",
      "No gums or stabilizers",
      "Small-batch crafted",
    ],
    ingredients: "Organic grass-fed cream, organic grass-fed milk, organic cane sugar, organic egg yolks, organic vanilla",
    buyTip: "Premium A2 grass-fed ice cream. Found at Whole Foods and specialty stores. Worth the price for digestive-sensitive folks.",
    averagePrice: 9.99,
    imageUrl: "/manus-storage/alecs-vanilla_a8a9cdf3.png",
    nutrients: { calories: 260, fat: 17, saturatedFat: 11, sugar: 18, protein: 4, servingSize: "2/3 cup" },
  },
  {
    id: "straus-vanilla",
    name: "Organic Vanilla Bean",
    brand: "Straus Family Creamery",
    category: "Organic & Grass-Fed",
    qualityTier: "elite",
    score: 92,
    organic: true,
    grassFed: true,
    hormoneFree: true,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 6,
    concerns: [],
    benefits: [
      "100% organic grass-fed dairy",
      "Family farm in Northern California",
      "No gums or stabilizers",
      "Non-homogenized cream",
      "Carbon-neutral certified",
    ],
    ingredients: "Organic cream, organic milk, organic cane sugar, organic egg yolks, organic vanilla extract, organic vanilla bean",
    buyTip: "West Coast gem. Available at Whole Foods, Sprouts, and local co-ops in California and surrounding states.",
    averagePrice: 8.49,
    imageUrl: "/manus-storage/straus-vanilla_b0f9e404.png",
    nutrients: { calories: 240, fat: 15, saturatedFat: 9, sugar: 20, protein: 4, servingSize: "2/3 cup" },
  },
  // ─── GOOD ──────────────────────────────────────────────────────────────
  {
    id: "haagen-dazs-vanilla-ic",
    name: "Vanilla",
    brand: "Häagen-Dazs",
    category: "Classic",
    qualityTier: "good",
    score: 78,
    organic: false,
    grassFed: false,
    hormoneFree: false,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 5,
    concerns: ["Conventional dairy (possible rBGH)", "High sugar content"],
    benefits: [
      "Only 5 ingredients",
      "No gums or stabilizers",
      "No artificial flavors or colors",
      "Widely available",
    ],
    ingredients: "Cream, skim milk, cane sugar, egg yolks, vanilla extract",
    buyTip: "The best widely-available conventional option. Only 5 real ingredients — a rare find in mainstream brands.",
    averagePrice: 5.99,
    imageUrl: "/manus-storage/haagen-dazs-vanilla_e153551b.jpeg",
    nutrients: { calories: 250, fat: 16, saturatedFat: 10, sugar: 21, protein: 5, servingSize: "2/3 cup" },
  },
  {
    id: "jenis-brambleberry-crisp",
    name: "Brambleberry Crisp",
    brand: "Jeni's Splendid",
    category: "Classic",
    qualityTier: "good",
    score: 75,
    organic: false,
    grassFed: true,
    hormoneFree: true,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 12,
    concerns: ["Contains tapioca syrup", "Higher ingredient count", "Premium price"],
    benefits: [
      "Grass-fed dairy",
      "No artificial ingredients",
      "No corn syrup",
      "Creative artisan flavors",
      "No carrageenan",
    ],
    ingredients: "Grass-fed milk, cream, cane sugar, blackberries, blueberries, tapioca syrup, butter, oats, brown sugar, vanilla, salt, lemon juice",
    buyTip: "Artisan quality with grass-fed dairy. Available at Whole Foods, Target, and their own scoop shops.",
    averagePrice: 8.99,
    imageUrl: "/manus-storage/jenis-honey-vanilla_6a4aa663.jpg",
    nutrients: { calories: 240, fat: 13, saturatedFat: 8, sugar: 24, protein: 4, servingSize: "2/3 cup" },
  },
  {
    id: "aldens-organic-vanilla",
    name: "Organic Vanilla Bean",
    brand: "Alden's Organic",
    category: "Organic & Grass-Fed",
    qualityTier: "good",
    score: 82,
    organic: true,
    grassFed: false,
    hormoneFree: true,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 7,
    concerns: ["Not grass-fed", "Contains guar gum (natural but still a stabilizer)"],
    benefits: [
      "USDA Organic",
      "No carrageenan",
      "Simple ingredients",
      "Oregon-made small batch",
      "Affordable organic option",
    ],
    ingredients: "Organic cream, organic milk, organic cane sugar, organic egg yolks, organic vanilla extract, organic guar gum, organic vanilla bean",
    buyTip: "Best value organic ice cream. Available at most grocery stores including Kroger, Safeway, and Whole Foods.",
    averagePrice: 6.49,
    imageUrl: "/manus-storage/aldens-vanilla_fcd29c3f.png",
    nutrients: { calories: 230, fat: 14, saturatedFat: 9, sugar: 19, protein: 4, servingSize: "2/3 cup" },
  },
  {
    id: "van-leeuwen-vanilla",
    name: "Vanilla Bean French",
    brand: "Van Leeuwen",
    category: "Classic",
    qualityTier: "good",
    score: 76,
    organic: false,
    grassFed: false,
    hormoneFree: true,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 7,
    concerns: ["Not organic", "Not grass-fed", "Premium price"],
    benefits: [
      "Simple clean ingredients",
      "No gums or stabilizers",
      "Hormone-free dairy",
      "Artisan Brooklyn brand",
      "No artificial anything",
    ],
    ingredients: "Cream, milk, cane sugar, egg yolks, vanilla extract, vanilla bean, salt",
    buyTip: "Brooklyn artisan quality. Available at Whole Foods, Target, and their own shops. Great flavor variety.",
    averagePrice: 8.99,
    imageUrl: "/manus-storage/van-leeuwen-honeycomb_b3a46a32.jpg",
    nutrients: { calories: 260, fat: 17, saturatedFat: 11, sugar: 20, protein: 4, servingSize: "2/3 cup" },
  },
  {
    id: "tillamook-vanilla",
    name: "Vanilla Bean",
    brand: "Tillamook",
    category: "Classic",
    qualityTier: "good",
    score: 68,
    organic: false,
    grassFed: false,
    hormoneFree: true,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 8,
    concerns: ["Contains locust bean gum", "Not organic", "Not grass-fed"],
    benefits: [
      "No artificial flavors",
      "No high fructose corn syrup",
      "rBST-free dairy",
      "Oregon farmer-owned co-op",
      "Good value for quality",
    ],
    ingredients: "Cream, milk, sugar, egg yolks, vanilla extract, vanilla bean, locust bean gum, guar gum",
    buyTip: "Best mainstream brand for quality-to-price ratio. Available everywhere. Their extra creamy line is excellent.",
    averagePrice: 5.49,
    imageUrl: "/manus-storage/tillamook-vanilla_13f81e86.png",
    nutrients: { calories: 230, fat: 14, saturatedFat: 9, sugar: 21, protein: 4, servingSize: "2/3 cup" },
  },
  // ─── LIGHT & LOW-CAL ──────────────────────────────────────────────────
  {
    id: "nicks-swedish-vanilj",
    name: "Swedish Vanilj",
    brand: "Nick's",
    category: "Light & Low-Cal",
    qualityTier: "average",
    score: 52,
    organic: false,
    grassFed: false,
    hormoneFree: false,
    hasSeedOils: false,
    hasArtificialSweeteners: true,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 14,
    concerns: [
      "Contains erythritol and stevia (sugar alcohols)",
      "Contains polydextrose (fiber filler)",
      "Highly processed for a 'light' product",
      "Many stabilizers and emulsifiers",
    ],
    benefits: [
      "No added sugar",
      "Low calorie (270 per pint)",
      "No seed oils",
      "Keto-friendly",
      "No artificial colors",
    ],
    ingredients: "Milk, cream, water, erythritol, polydextrose, milk protein concentrate, vegetable fiber, vanilla, stevia, locust bean gum, guar gum, salt",
    buyTip: "This ice cream scored in the average tier because it relies on erythritol, stevia, and polydextrose (a synthetic fiber) to achieve its low-calorie profile, resulting in a high ingredient count with multiple stabilizers and gums. These additives are what limit the quality score compared to simpler ice creams.",
    averagePrice: 6.99,
    imageUrl: "/manus-storage/nicks-vanilla_e50c0de8.jpg",
    nutrients: { calories: 270, fat: 16, saturatedFat: 6, sugar: 0, protein: 8, servingSize: "1 pint" },
  },
  {
    id: "nicks-peanut-butter-cup",
    name: "Peanut Butter Cup",
    brand: "Nick's",
    category: "Light & Low-Cal",
    qualityTier: "average",
    score: 50,
    organic: false,
    grassFed: false,
    hormoneFree: false,
    hasSeedOils: false,
    hasArtificialSweeteners: true,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 18,
    concerns: [
      "Contains erythritol and stevia",
      "Contains polydextrose",
      "High ingredient count (18)",
      "Contains palm oil in peanut butter cups",
    ],
    benefits: [
      "No added sugar",
      "Low calorie (330 per pint)",
      "High protein (8g per pint)",
      "No seed oils in base",
    ],
    ingredients: "Milk, cream, water, erythritol, polydextrose, peanut butter cups (peanuts, cocoa, palm oil, erythritol), milk protein concentrate, vegetable fiber, cocoa, stevia, locust bean gum, guar gum, salt",
    buyTip: "This ice cream scored in the average tier because it uses erythritol, stevia, and polydextrose as sugar substitutes, and the peanut butter cup inclusions contain palm oil. The high ingredient count (18) and multiple stabilizers are the primary factors that limit the quality score.",
    averagePrice: 6.99,
    imageUrl: "/manus-storage/nicks-vanilla_e50c0de8.jpg",
    nutrients: { calories: 330, fat: 20, saturatedFat: 8, sugar: 0, protein: 8, servingSize: "1 pint" },
  },
  {
    id: "halo-top-vanilla-bean",
    name: "Vanilla Bean",
    brand: "Halo Top",
    category: "Light & Low-Cal",
    qualityTier: "average",
    score: 45,
    organic: false,
    grassFed: false,
    hormoneFree: false,
    hasSeedOils: false,
    hasArtificialSweeteners: true,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 15,
    concerns: [
      "Contains erythritol and stevia",
      "Contains vegetable glycerin",
      "Highly processed texture",
      "Contains natural flavors (vague)",
      "Icy texture due to low fat content",
    ],
    benefits: [
      "Low calorie (290 per pint)",
      "High protein (16g per pint)",
      "No seed oils",
      "No artificial colors",
      "Widely available",
    ],
    ingredients: "Milk, cream, eggs, erythritol, prebiotic fiber, milk protein concentrate, organic cane sugar, vegetable glycerin, vanilla extract, vanilla bean, stevia, guar gum, carob gum, salt",
    buyTip: "This ice cream scored in the average tier because it uses erythritol, stevia, prebiotic fiber, and vegetable glycerin to achieve its low-calorie profile. The result is a highly processed texture with 15 ingredients. The low-fat content also contributes to an icy texture that differs significantly from traditional ice cream.",
    averagePrice: 5.49,
    imageUrl: "/manus-storage/halo-top-vanilla_bcb50149.jpg",
    nutrients: { calories: 290, fat: 10, saturatedFat: 5, sugar: 16, protein: 16, servingSize: "1 pint" },
  },
  // ─── PLANT-BASED ──────────────────────────────────────────────────────
  {
    id: "cosmic-bliss-dark-chocolate",
    name: "Dark Chocolate",
    brand: "Cosmic Bliss",
    category: "Plant-Based",
    qualityTier: "good",
    score: 80,
    organic: true,
    grassFed: false,
    hormoneFree: true,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 7,
    concerns: ["Coconut cream base (high saturated fat)", "Premium price"],
    benefits: [
      "USDA Organic",
      "Dairy-free / vegan",
      "No gums or carrageenan",
      "Simple ingredients",
      "Fair-trade cocoa",
    ],
    ingredients: "Organic coconut cream, organic cane sugar, organic cocoa, organic cocoa butter, organic vanilla extract, sea salt, organic sunflower lecithin",
    buyTip: "Best plant-based ice cream for clean ingredients. The coconut base is rich and creamy without any gums.",
    averagePrice: 7.99,
    imageUrl: "/manus-storage/cosmic-bliss-vanilla_4eaf20dc.png",
    nutrients: { calories: 280, fat: 19, saturatedFat: 16, sugar: 18, protein: 2, servingSize: "2/3 cup" },
  },
  {
    id: "oatly-vanilla",
    name: "Vanilla",
    brand: "Oatly",
    category: "Plant-Based",
    qualityTier: "average",
    score: 55,
    organic: false,
    grassFed: false,
    hormoneFree: true,
    hasSeedOils: true,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 12,
    concerns: [
      "Contains rapeseed (canola) oil",
      "Contains pea protein (processed)",
      "High ingredient count",
      "Not organic",
    ],
    benefits: [
      "Dairy-free / vegan",
      "Oat-based (lower saturated fat)",
      "No artificial colors or flavors",
      "No carrageenan",
    ],
    ingredients: "Oat base (water, oats), coconut oil, sugar, rapeseed oil, dextrose, pea protein, vanilla extract, locust bean gum, salt, gellan gum",
    buyTip: "This plant-based ice cream scored in the average tier because it contains rapeseed (canola) oil, a seed oil high in omega-6 linoleic acid, as a key ingredient in the oat base. It also contains pea protein (a highly processed ingredient) and multiple stabilizers. The seed oil content is the primary factor driving the lower score.",
    averagePrice: 5.99,
    imageUrl: "/manus-storage/oatly-vanilla_7ba4b848.png",
    nutrients: { calories: 220, fat: 12, saturatedFat: 6, sugar: 18, protein: 2, servingSize: "2/3 cup" },
  },
  // ─── AVERAGE ──────────────────────────────────────────────────────────
  {
    id: "breyers-natural-vanilla",
    name: "Natural Vanilla",
    brand: "Breyers",
    category: "Classic",
    qualityTier: "average",
    score: 58,
    organic: false,
    grassFed: false,
    hormoneFree: false,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: true,
    hasArtificialColors: false,
    ingredientCount: 9,
    concerns: [
      "Contains carrageenan",
      "Contains guar gum and tara gum",
      "Conventional dairy",
      "Unilever-owned (mass production)",
    ],
    benefits: [
      "Real vanilla bean specks",
      "No artificial flavors",
      "No high fructose corn syrup",
      "Affordable",
      "Widely available",
    ],
    ingredients: "Milk, cream, sugar, vanilla extract, tara gum, carrageenan, guar gum, natural flavor, vanilla bean",
    buyTip: "This ice cream scored in the average tier because it contains carrageenan (a seaweed-derived emulsifier that some research has linked to gut inflammation), tara gum, and guar gum as stabilizers. The conventional dairy and mass-production practices also contribute to the lower score.",
    averagePrice: 4.49,
    imageUrl: "/manus-storage/breyers-vanilla_de7e6ccc.png",
    nutrients: { calories: 220, fat: 12, saturatedFat: 7, sugar: 20, protein: 4, servingSize: "2/3 cup" },
  },
  {
    id: "turkey-hill-vanilla",
    name: "Original Vanilla",
    brand: "Turkey Hill",
    category: "Classic",
    qualityTier: "average",
    score: 55,
    organic: false,
    grassFed: false,
    hormoneFree: false,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: true,
    hasArtificialColors: false,
    ingredientCount: 10,
    concerns: [
      "Contains carrageenan",
      "Contains mono & diglycerides",
      "Contains polysorbate 80",
      "Conventional dairy",
    ],
    benefits: [
      "No artificial colors",
      "No high fructose corn syrup",
      "Affordable",
      "All Natural line available",
    ],
    ingredients: "Milk, cream, sugar, corn syrup, whey, vanilla extract, mono & diglycerides, carrageenan, polysorbate 80, natural flavor",
    buyTip: "This ice cream scored in the average tier because the regular line contains carrageenan, polysorbate 80 (a synthetic emulsifier), mono and diglycerides, and corn syrup. Polysorbate 80 has been studied for potential effects on gut microbiome composition. The brand's All Natural line has a simpler ingredient list.",
    averagePrice: 3.99,
    imageUrl: "/manus-storage/turkey-hill-vanilla_825e943f.jpg",
    nutrients: { calories: 220, fat: 11, saturatedFat: 7, sugar: 21, protein: 3, servingSize: "2/3 cup" },
  },
  // ─── POOR ──────────────────────────────────────────────────────────────
  {
    id: "blue-bunny-vanilla",
    name: "Homemade Vanilla",
    brand: "Blue Bunny",
    category: "Classic",
    qualityTier: "poor",
    score: 32,
    organic: false,
    grassFed: false,
    hormoneFree: false,
    hasSeedOils: true,
    hasArtificialSweeteners: false,
    hasCarrageenan: true,
    hasArtificialColors: false,
    ingredientCount: 16,
    concerns: [
      "Contains palm oil",
      "Contains corn syrup",
      "Contains carrageenan",
      "Contains polysorbate 80",
      "Contains mono & diglycerides",
      "High ingredient count",
    ],
    benefits: [
      "Affordable",
      "Widely available",
    ],
    ingredients: "Milk, cream, sugar, corn syrup, whey, palm oil, natural flavor, mono & diglycerides, guar gum, carrageenan, polysorbate 80, cellulose gum, vitamin A palmitate",
    buyTip: "This ice cream scored very low because it contains palm oil, corn syrup, carrageenan, polysorbate 80, mono and diglycerides, cellulose gum, and guar gum — a total of 16 ingredients. The combination of palm oil, corn syrup, and multiple synthetic emulsifiers is what drives the low quality score.",
    averagePrice: 3.99,
    imageUrl: "/manus-storage/blue-bunny-chocolate_75ec4147.png",
    nutrients: { calories: 230, fat: 12, saturatedFat: 8, sugar: 22, protein: 3, servingSize: "2/3 cup" },
  },
  {
    id: "dreyers-vanilla",
    name: "Grand Vanilla",
    brand: "Dreyer's/Edy's",
    category: "Classic",
    qualityTier: "poor",
    score: 35,
    organic: false,
    grassFed: false,
    hormoneFree: false,
    hasSeedOils: true,
    hasArtificialSweeteners: false,
    hasCarrageenan: true,
    hasArtificialColors: false,
    ingredientCount: 14,
    concerns: [
      "Contains palm oil",
      "Contains corn syrup",
      "Contains carrageenan",
      "Contains polysorbate 80",
      "Nestlé-owned (mass production)",
    ],
    benefits: [
      "No artificial colors",
      "Widely available",
      "Affordable",
    ],
    ingredients: "Milk, cream, sugar, corn syrup, whey, palm oil, natural flavor, mono & diglycerides, carrageenan, polysorbate 80, guar gum, cellulose gum",
    buyTip: "This ice cream scored very low because it contains palm oil, corn syrup, carrageenan, polysorbate 80, mono and diglycerides, cellulose gum, and guar gum. The combination of palm oil, corn syrup, and multiple synthetic emulsifiers is what drives the low quality score.",
    averagePrice: 4.49,
    imageUrl: "/manus-storage/dreyers-french-vanilla_55d3ecc8.jpg",
    nutrients: { calories: 220, fat: 11, saturatedFat: 7, sugar: 21, protein: 3, servingSize: "2/3 cup" },
  },
  // ─── AVOID ──────────────────────────────────────────────────────────────
  {
    id: "great-value-vanilla",
    name: "Vanilla Flavored",
    brand: "Great Value (Walmart)",
    category: "Classic",
    qualityTier: "avoid",
    score: 18,
    organic: false,
    grassFed: false,
    hormoneFree: false,
    hasSeedOils: true,
    hasArtificialSweeteners: false,
    hasCarrageenan: true,
    hasArtificialColors: true,
    ingredientCount: 20,
    concerns: [
      "Contains palm oil and coconut oil",
      "Contains high fructose corn syrup",
      "Contains carrageenan",
      "Contains polysorbate 80",
      "Contains artificial color (Yellow 5, Blue 1)",
      "Contains cellulose gum",
      "20+ ingredients",
    ],
    benefits: [
      "Cheapest option available",
    ],
    ingredients: "Milk, sugar, cream, corn syrup, whey, palm oil, coconut oil, high fructose corn syrup, natural and artificial flavor, mono & diglycerides, carrageenan, polysorbate 80, guar gum, cellulose gum, Yellow 5, Blue 1, annatto",
    buyTip: "This ice cream scored in the avoid tier because it contains high fructose corn syrup, palm oil, coconut oil, carrageenan, polysorbate 80, FD&C Yellow #5, FD&C Blue #1 (artificial colors), and over 20 total ingredients. The combination of HFCS, seed oils, artificial colors, and multiple synthetic emulsifiers is what drives the very low quality score.",
    averagePrice: 2.99,
    imageUrl: "/manus-storage/great-value-cookies_2f31440e.jpeg",
    nutrients: { calories: 230, fat: 11, saturatedFat: 7, sugar: 23, protein: 3, servingSize: "2/3 cup" },
  },
  {
    id: "magnum-classic",
    name: "Classic Vanilla Ice Cream Bar",
    brand: "Magnum",
    category: "Kids & Novelty",
    qualityTier: "poor",
    score: 38,
    organic: false,
    grassFed: false,
    hormoneFree: false,
    hasSeedOils: true,
    hasArtificialSweeteners: false,
    hasCarrageenan: true,
    hasArtificialColors: false,
    ingredientCount: 15,
    concerns: [
      "Contains coconut oil",
      "Contains glucose syrup",
      "Contains carrageenan",
      "Contains soy lecithin",
      "Premium marketing hides average ingredients",
    ],
    benefits: [
      "Belgian chocolate coating",
      "No artificial colors",
      "Recognizable brand",
    ],
    ingredients: "Cream, milk, sugar, coconut oil, cocoa butter, chocolate, glucose syrup, whey, vanilla extract, soy lecithin, carrageenan, guar gum, natural flavor",
    buyTip: "This ice cream bar scored in the poor tier because it contains coconut oil, glucose syrup, carrageenan, soy lecithin, and guar gum. Despite premium marketing, the ingredient list includes multiple stabilizers and emulsifiers that are not found in higher-scoring ice creams.",
    averagePrice: 5.99,
    imageUrl: "/manus-storage/magnum-sea-salt-caramel_6c2f26f1.jpg",
    nutrients: { calories: 250, fat: 17, saturatedFat: 12, sugar: 21, protein: 3, servingSize: "1 bar" },
  },
  {
    id: "ben-jerrys-half-baked",
    name: "Half Baked",
    brand: "Ben & Jerry's",
    category: "Classic",
    qualityTier: "average",
    score: 48,
    organic: false,
    grassFed: false,
    hormoneFree: true,
    hasSeedOils: true,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 22,
    concerns: [
      "Contains soybean oil in cookie dough",
      "Very high ingredient count (22)",
      "Contains corn syrup",
      "Very high sugar content",
      "Contains multiple gums",
    ],
    benefits: [
      "Non-GMO ingredients",
      "Cage-free eggs",
      "Fairtrade certified ingredients",
      "No carrageenan",
      "No artificial colors or flavors",
    ],
    ingredients: "Cream, milk, sugar, water, cookie dough (flour, sugar, soybean oil, butter, eggs, vanilla), brownie (sugar, eggs, flour, butter, cocoa), corn syrup, egg yolks, vanilla, guar gum, soy lecithin",
    buyTip: "This ice cream scored in the average tier because the cookie dough and brownie mix-ins contain soybean oil (a seed oil high in omega-6 linoleic acid) and corn syrup. The ice cream base itself uses non-GMO and Fairtrade ingredients, but the mix-in components are what limit the overall quality score.",
    averagePrice: 5.99,
    imageUrl: "/manus-storage/ben-jerrys-everything_396b0fd2.jpg",
    nutrients: { calories: 280, fat: 14, saturatedFat: 9, sugar: 28, protein: 4, servingSize: "2/3 cup" },
  },
  // ─── ICE CREAM FOR BEARS ──────────────────────────────────────────────
  {
    id: "bears-queen-bean",
    name: "Queen & Bean (Vanilla Bean)",
    brand: "Ice Cream for Bears",
    category: "Organic & Grass-Fed",
    qualityTier: "elite",
    score: 97,
    organic: false,
    grassFed: true,
    hormoneFree: true,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 7,
    concerns: [],
    benefits: [
      "Sweetened only with raw honey",
      "Regenerative grass-fed dairy",
      "No gums, stabilizers, or emulsifiers",
      "Pastured egg yolks (replaces gums)",
      "No refined sugar of any kind",
    ],
    ingredients: "Milk, Cream, Raw Honey, Skim Milk, Egg Yolk, Pure Vanilla Extract, Vanilla Bean",
    buyTip: "The cleanest ice cream on the market. Raw honey sweetened, grass-fed, no gums. Available at Whole Foods, Sprouts, and their website.",
    averagePrice: 10.99,
    imageUrl: "/manus-storage/bears-queen-bean_f2d61961.png",
    nutrients: { calories: 260, fat: 16, saturatedFat: 10, sugar: 18, protein: 5, servingSize: "2/3 cup" },
  },
  {
    id: "bears-chocturnal",
    name: "Chocturnal (Triple Chocolate)",
    brand: "Ice Cream for Bears",
    category: "Organic & Grass-Fed",
    qualityTier: "elite",
    score: 96,
    organic: false,
    grassFed: true,
    hormoneFree: true,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 7,
    concerns: [],
    benefits: [
      "Sweetened only with raw honey",
      "Regenerative grass-fed dairy",
      "Real cacao and butter (no cocoa processed with alkali)",
      "No gums or stabilizers",
      "No refined sugar",
    ],
    ingredients: "Milk, Cream, Raw Honey, Skim Milk, Egg Yolk, Cacao, Butter",
    buyTip: "Rich triple chocolate with zero junk. The cacao is unprocessed and the butter adds creaminess naturally instead of gums.",
    averagePrice: 10.99,
    imageUrl: "/manus-storage/bears-chocturnal_b200e614.png",
    nutrients: { calories: 270, fat: 17, saturatedFat: 11, sugar: 17, protein: 5, servingSize: "2/3 cup" },
  },
  {
    id: "bears-strawbeary",
    name: "Strawbeary (Strawberry)",
    brand: "Ice Cream for Bears",
    category: "Organic & Grass-Fed",
    qualityTier: "elite",
    score: 97,
    organic: false,
    grassFed: true,
    hormoneFree: true,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 7,
    concerns: [],
    benefits: [
      "Real strawberries (first ingredient)",
      "Sweetened only with raw honey",
      "Regenerative grass-fed dairy",
      "No gums, stabilizers, or emulsifiers",
      "No natural or artificial flavors",
    ],
    ingredients: "Strawberries, Cream, Raw Honey, Skim Milk, Water, Egg Yolk, Salt",
    buyTip: "Real fruit first ingredient — most strawberry ice creams use artificial flavor. This is the real deal.",
    averagePrice: 10.99,
    imageUrl: "/manus-storage/bears-strawbeary_c5f83b19.png",
    nutrients: { calories: 240, fat: 14, saturatedFat: 9, sugar: 19, protein: 4, servingSize: "2/3 cup" },
  },
  {
    id: "bears-mint-to-bee",
    name: "Mint to Bee (Mint Chip)",
    brand: "Ice Cream for Bears",
    category: "Organic & Grass-Fed",
    qualityTier: "elite",
    score: 96,
    organic: false,
    grassFed: true,
    hormoneFree: true,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 7,
    concerns: [],
    benefits: [
      "Real peppermint oil (not artificial mint flavor)",
      "Chocolate chips made from cacao, dates & coconut oil",
      "Sweetened only with raw honey",
      "Regenerative grass-fed dairy",
      "No artificial green coloring",
    ],
    ingredients: "Milk, Cream, Raw Honey, Skim Milk, Egg Yolk, Chocolate Chips (Cacao, Dates, Coconut Oil), Pure Peppermint Oil",
    buyTip: "Unlike most mint chip ice creams (which use artificial green dye and fake mint), this uses real peppermint oil and date-sweetened chips.",
    averagePrice: 10.99,
    imageUrl: "/manus-storage/bears-mint-to-bee_977b8f52.png",
    nutrients: { calories: 270, fat: 16, saturatedFat: 10, sugar: 18, protein: 5, servingSize: "2/3 cup" },
  },
  {
    id: "bears-salted-caramaul",
    name: "Salted Caramaul (Salted Caramel)",
    brand: "Ice Cream for Bears",
    category: "Organic & Grass-Fed",
    qualityTier: "elite",
    score: 95,
    organic: false,
    grassFed: true,
    hormoneFree: true,
    hasSeedOils: false,
    hasArtificialSweeteners: false,
    hasCarrageenan: false,
    hasArtificialColors: false,
    ingredientCount: 10,
    concerns: ["Contains coconut oil (in caramel — not a seed oil but noted)"],
    benefits: [
      "Caramel made from honey, butter & dates",
      "Sweetened only with raw honey",
      "Regenerative grass-fed dairy",
      "No gums or stabilizers",
      "No refined sugar or corn syrup",
    ],
    ingredients: "Cream, Milk, Honey, Skim Milk, Egg Yolk, Butter, Dates, Water, Coconut Oil, Pure Vanilla Extract, Salt",
    buyTip: "Most salted caramel ice creams use corn syrup and artificial caramel flavor. This one makes real caramel from honey and butter.",
    averagePrice: 10.99,
    imageUrl: "/manus-storage/bears-salted-caramaul_ac09e9a3.png",
    nutrients: { calories: 280, fat: 18, saturatedFat: 12, sugar: 19, protein: 4, servingSize: "2/3 cup" },
  },
];

export function getIceCreamColor(score: number): string {
  if (score >= 85) return "#145A3A";
  if (score >= 65) return "#3FA34D";
  if (score >= 45) return "#d97706";
  if (score >= 25) return "#ea580c";
  return "#dc2626";
}
