/**
 * Pet Care Database — Dog & Cat Food Quality Ratings
 * Scores 1–100 based on ingredient quality, protein source, fillers, and harmful additives
 */

export interface PetProduct {
  id: string;
  name: string;
  brand: string;
  category: "dog-dry" | "dog-wet" | "dog-treat" | "cat-dry" | "cat-wet" | "cat-treat";
  petType: "dog" | "cat" | "both";
  score: number;
  grade: "A" | "B" | "C" | "D" | "F";
  color: string;
  proteinSource: string;
  mainIngredients: string[];
  redFlags: string[];
  greenFlags: string[];
  priceRange: "$" | "$$" | "$$$" | "$$$$";
  notes: string;
  averagePrice?: number;
  imageUrl?: string;
}

function gradeFromScore(score: number): { grade: "A" | "B" | "C" | "D" | "F"; color: string } {
  if (score >= 85) return { grade: "A", color: "#145A3A" };
  if (score >= 70) return { grade: "B", color: "#3FA34D" };
  if (score >= 55) return { grade: "C", color: "#d97706" };
  if (score >= 40) return { grade: "D", color: "#ea580c" };
  return { grade: "F", color: "#dc2626" };
}

const RAW_PRODUCTS: Omit<PetProduct, "grade" | "color">[] = [
  // ── DOG DRY ──────────────────────────────────────────────────────────────────
  {
    id: "orijen-dog-original",
    name: "Original Dry Dog Food",
    brand: "Orijen",
    category: "dog-dry",
    petType: "dog",
    score: 96,
    proteinSource: "Free-run chicken, turkey, wild-caught fish",
    mainIngredients: ["Deboned chicken", "Deboned turkey", "Atlantic flounder", "Whole eggs", "Whole Atlantic mackerel"],
    redFlags: [],
    greenFlags: ["85% animal ingredients", "No grain fillers", "No artificial preservatives", "Freeze-dried liver coating", "Biologically appropriate"],
    priceRange: "$$$$",
    notes: "One of the highest-quality dry dog foods available. Mirrors ancestral diet.",
  imageUrl: "/manus-storage/orijen-dog-original_bb00d25e_59b11c28.jpg",
  },
  {
    id: "acana-dog-heritage",
    name: "Heritage Grains Dry Dog Food",
    brand: "Acana",
    category: "dog-dry",
    petType: "dog",
    score: 90,
    proteinSource: "Free-run chicken, turkey, whole eggs",
    mainIngredients: ["Deboned chicken", "Deboned turkey", "Whole eggs", "Whole oat groats", "Whole green peas"],
    redFlags: [],
    greenFlags: ["70% animal ingredients", "Whole grains only", "No artificial preservatives", "Regionally sourced"],
    priceRange: "$$$",
    notes: "Premium quality with whole grains for dogs that tolerate them well.",
  imageUrl: "/manus-storage/acana-dog-heritage_ba0bbf7e_bda5c16f.jpg",
  },
  {
    id: "zignature-dog-turkey",
    name: "Turkey Formula Dry Dog Food",
    brand: "Zignature",
    category: "dog-dry",
    petType: "dog",
    score: 87,
    proteinSource: "Turkey",
    mainIngredients: ["Turkey", "Turkey meal", "Chickpeas", "Peas", "Pea flour"],
    redFlags: ["High legume content (DCM concern)"],
    greenFlags: ["Limited ingredient", "No chicken", "No corn/wheat/soy", "Good for allergies"],
    priceRange: "$$$",
    notes: "Great for dogs with chicken allergies. Legume-heavy — monitor DCM research.",
  imageUrl: "/manus-storage/zignature-dog-turkey_cc7a665c_363b4531.jpg",
  },
  {
    id: "taste-wild-sierra-mountain",
    name: "Sierra Mountain Roasted Lamb",
    brand: "Taste of the Wild",
    category: "dog-dry",
    petType: "dog",
    score: 82,
    proteinSource: "Roasted lamb",
    mainIngredients: ["Lamb", "Lamb meal", "Sweet potatoes", "Peas", "Potatoes"],
    redFlags: ["High legume/potato content (DCM concern)"],
    greenFlags: ["Grain-free", "No artificial colors/flavors", "Added probiotics", "Good value"],
    priceRange: "$$",
    notes: "Good mid-range option. Grain-free with legumes — watch DCM FDA advisory.",
  imageUrl: "/manus-storage/taste-wild-sierra-mountain_f4d86a9a_652053ff.png",
  },
  {
    id: "blue-buffalo-life-protection",
    name: "Life Protection Formula Adult",
    brand: "Blue Buffalo",
    category: "dog-dry",
    petType: "dog",
    score: 72,
    proteinSource: "Deboned chicken",
    mainIngredients: ["Deboned chicken", "Brown rice", "Barley", "Oatmeal", "Chicken meal"],
    redFlags: ["Chicken meal quality varies", "Contains pea starch"],
    greenFlags: ["LifeSource Bits (vitamins)", "No by-product meals", "No corn/wheat/soy", "Whole grains"],
    priceRange: "$$",
    notes: "Solid mainstream option. Whole grains are a plus. Watch for recalls history.",
  imageUrl: "/manus-storage/blue-buffalo-life-protection_60f8c238_bd527f19.jpg",
  },
  {
    id: "purina-pro-plan-adult",
    name: "Savor Adult Shredded Blend",
    brand: "Purina Pro Plan",
    category: "dog-dry",
    petType: "dog",
    score: 68,
    proteinSource: "Chicken",
    mainIngredients: ["Chicken", "Rice flour", "Corn gluten meal", "Whole grain wheat", "Poultry by-product meal"],
    redFlags: ["Corn gluten meal filler", "Poultry by-product meal", "Whole grain wheat"],
    greenFlags: ["Science-backed formulas", "Widely vet-recommended", "Added probiotics"],
    priceRange: "$$",
    notes: "Vet-recommended but uses corn gluten and by-products. Functional, not optimal.",
  imageUrl: "/manus-storage/purina-pro-plan-adult_chewy_012902dd.jpg",
  },
  {
    id: "iams-adult-large-breed",
    name: "ProActive Health Adult Large Breed",
    brand: "Iams",
    category: "dog-dry",
    petType: "dog",
    score: 52,
    proteinSource: "Chicken",
    mainIngredients: ["Chicken", "Corn meal", "Sorghum", "Chicken by-product meal", "Dried beet pulp"],
    redFlags: ["Corn meal filler", "Chicken by-product meal", "Sorghum filler"],
    greenFlags: ["Affordable", "Added fiber", "Omega-3 from fish oil"],
    priceRange: "$",
    notes: "Budget option with significant filler content. Adequate but not ideal.",
  imageUrl: "/manus-storage/iams-adult-large-breed_walmart_f51fddfe.jpg",
  },
  {
    id: "pedigree-adult-complete",
    name: "Adult Complete Nutrition",
    brand: "Pedigree",
    category: "dog-dry",
    petType: "dog",
    score: 35,
    proteinSource: "Chicken (listed 3rd)",
    mainIngredients: ["Ground whole grain corn", "Meat and bone meal", "Corn gluten meal", "Animal fat", "Soybean meal"],
    redFlags: ["Corn as #1 ingredient", "Meat and bone meal (unspecified)", "Corn gluten meal", "Animal fat (unspecified)", "Soybean meal", "Artificial colors"],
    greenFlags: ["Very affordable", "Widely available"],
    priceRange: "$",
    notes: "Heavy filler content, unspecified meat sources, artificial colors. Not recommended.",
  imageUrl: "/manus-storage/pedigree-adult-complete_a19a7cbd_065e655f.jpg",
  },
  {
    id: "hills-science-diet-adult",
    name: "Adult Perfect Weight",
    brand: "Hill's Science Diet",
    category: "dog-dry",
    petType: "dog",
    score: 60,
    proteinSource: "Chicken meal",
    mainIngredients: ["Chicken meal", "Whole grain wheat", "Whole grain corn", "Corn gluten meal", "Pork fat"],
    redFlags: ["Corn gluten meal", "Whole grain corn filler", "Pork fat (unspecified source)"],
    greenFlags: ["Vet-recommended", "Science-backed weight management", "No artificial colors"],
    priceRange: "$$",
    notes: "Clinically tested weight management. Corn-heavy but vet-trusted formulation.",
  imageUrl: "/manus-storage/hills-science-diet-adult_b76abb7e_0ab9d157.jpg",
  },
  {
    id: "merrick-grain-free-real-chicken",
    name: "Grain Free Real Chicken & Sweet Potato",
    brand: "Merrick",
    category: "dog-dry",
    petType: "dog",
    score: 84,
    proteinSource: "Deboned chicken",
    mainIngredients: ["Deboned chicken", "Chicken meal", "Sweet potatoes", "Potatoes", "Peas"],
    redFlags: ["High legume/potato content (DCM concern)"],
    greenFlags: ["Real meat first ingredient", "No artificial colors/flavors", "Omega-3 & 6", "Made in USA"],
    priceRange: "$$$",
    notes: "High-quality ingredients. Grain-free with legumes — note DCM advisory.",
  imageUrl: "/manus-storage/merrick-grain-free-real-chicken_54530e04_1d25b1a8.jpg",
  },

  // ── DOG WET ──────────────────────────────────────────────────────────────────
  {
    id: "stella-chewys-dog-wet",
    name: "Carnivore Cravings Chicken & Chicken Liver",
    brand: "Stella & Chewy's",
    category: "dog-wet",
    petType: "dog",
    score: 95,
    proteinSource: "Chicken, chicken liver",
    mainIngredients: ["Chicken", "Chicken liver", "Chicken broth", "Dried chicken", "Pumpkin"],
    redFlags: [],
    greenFlags: ["95%+ animal ingredients", "No fillers", "No artificial preservatives", "Pumpkin for digestion"],
    priceRange: "$$$$",
    notes: "Excellent wet food. Minimal ingredients, high meat content.",
  imageUrl: "/manus-storage/stella-chewys-dog-wet_amazon_dcf47f0b.jpg",
  },
  {
    id: "weruva-dog-wet-paw-lickin",
    name: "Paw Lickin' Chicken in Gravy",
    brand: "Weruva",
    category: "dog-wet",
    petType: "dog",
    score: 89,
    proteinSource: "Boneless skinless chicken breast",
    mainIngredients: ["Chicken broth", "Chicken", "Sunflower seed oil", "Guar gum", "Cassia gum"],
    redFlags: ["Guar gum (minor)"],
    greenFlags: ["Human-grade ingredients", "No carrageenan", "BPA-free cans", "High moisture"],
    priceRange: "$$$",
    notes: "Human-grade quality. Excellent for hydration. Very clean label.",
  imageUrl: "/manus-storage/weruva-dog-wet-paw-lickin_357d911e_fd2c2e7a.jpg",
  },
  {
    id: "purina-beneful-wet",
    name: "Chopped Blends with Beef",
    brand: "Purina Beneful",
    category: "dog-wet",
    petType: "dog",
    score: 38,
    proteinSource: "Beef (listed 3rd)",
    mainIngredients: ["Water", "Chicken", "Beef", "Liver", "Wheat gluten"],
    redFlags: ["Wheat gluten filler", "Artificial colors (Red 40, Yellow 5, Yellow 6)", "Propylene glycol", "Sugar"],
    greenFlags: ["Affordable", "High moisture"],
    priceRange: "$",
    notes: "Artificial dyes and propylene glycol are concerning. Not recommended.",
  imageUrl: "/manus-storage/purina-beneful-wet_300a9d7d_74b9617d.jpg",
  },

  // ── DOG TREATS ───────────────────────────────────────────────────────────────
  {
    id: "zuke-mini-naturals-chicken",
    name: "Mini Naturals Chicken Recipe",
    brand: "Zuke's",
    category: "dog-treat",
    petType: "dog",
    score: 78,
    proteinSource: "Chicken",
    mainIngredients: ["Chicken", "Chickpea flour", "Tapioca starch", "Canola oil", "Dried cherries"],
    redFlags: ["Canola oil (seed oil)"],
    greenFlags: ["Real chicken first", "Under 3 calories each", "No corn/wheat/soy", "Small size for training"],
    priceRange: "$$",
    notes: "Popular training treat. Canola oil is a minor concern. Otherwise clean.",
  imageUrl: "/manus-storage/zuke-mini-naturals-chicken_08e0eda2_412f2f65.jpg",
  },
  {
    id: "vital-essentials-freeze-dried-treats",
    name: "Freeze-Dried Chicken Breast Treats",
    brand: "Vital Essentials",
    category: "dog-treat",
    petType: "dog",
    score: 97,
    proteinSource: "Chicken breast",
    mainIngredients: ["Chicken breast"],
    redFlags: [],
    greenFlags: ["Single ingredient", "Freeze-dried raw", "No additives", "High protein"],
    priceRange: "$$$",
    notes: "Single-ingredient freeze-dried treat. As clean as it gets.",
  imageUrl: "/manus-storage/vital-essentials-freeze-dried-treats_83261762_69846c0d.jpg",
  },
  {
    id: "milk-bone-original",
    name: "Original Dog Biscuits",
    brand: "Milk-Bone",
    category: "dog-treat",
    petType: "dog",
    score: 28,
    proteinSource: "Bone meal",
    mainIngredients: ["Wheat flour", "Wheat bran", "Meat and bone meal", "Milk", "Wheat germ"],
    redFlags: ["Wheat flour as #1 ingredient", "Meat and bone meal (unspecified)", "BHA preservative", "Artificial flavors"],
    greenFlags: ["Affordable", "Widely available", "Dental cleaning claim"],
    priceRange: "$",
    notes: "BHA is a suspected carcinogen. Wheat-heavy with unspecified meat. Avoid.",
  imageUrl: "/manus-storage/milk-bone-original_68067d08_b953b571.jpg",
  },

  // ── CAT DRY ──────────────────────────────────────────────────────────────────
  {
    id: "orijen-cat-original",
    name: "Original Dry Cat Food",
    brand: "Orijen",
    category: "cat-dry",
    petType: "cat",
    score: 97,
    proteinSource: "Free-run chicken, turkey, wild-caught fish",
    mainIngredients: ["Deboned chicken", "Deboned turkey", "Atlantic flounder", "Whole eggs", "Atlantic mackerel"],
    redFlags: [],
    greenFlags: ["90% animal ingredients", "Obligate carnivore formula", "No grain fillers", "Freeze-dried liver coating"],
    priceRange: "$$$$",
    notes: "Best-in-class dry cat food. Cats are obligate carnivores — this delivers.",
  imageUrl: "/manus-storage/orijen-cat-original_3df2a03a_cd016918.jpg",
  },
  {
    id: "acana-cat-indoor",
    name: "Indoor Entrée Dry Cat Food",
    brand: "Acana",
    category: "cat-dry",
    petType: "cat",
    score: 91,
    proteinSource: "Free-run chicken, turkey",
    mainIngredients: ["Deboned chicken", "Deboned turkey", "Chicken meal", "Whole oat groats", "Whole green peas"],
    redFlags: [],
    greenFlags: ["75% animal ingredients", "Hairball control", "No artificial preservatives", "Regionally sourced"],
    priceRange: "$$$",
    notes: "Excellent for indoor cats. High protein, hairball support.",
  imageUrl: "/manus-storage/acana-cat-indoor_beae2d61_138ed9ed.jpg",
  },
  {
    id: "blue-buffalo-wilderness-cat",
    name: "Wilderness High Protein Chicken",
    brand: "Blue Buffalo",
    category: "cat-dry",
    petType: "cat",
    score: 75,
    proteinSource: "Deboned chicken",
    mainIngredients: ["Deboned chicken", "Chicken meal", "Tapioca starch", "Peas", "Chicken fat"],
    redFlags: ["Pea content (legume)", "Tapioca starch filler"],
    greenFlags: ["Grain-free", "High protein", "No by-product meals", "LifeSource Bits"],
    priceRange: "$$",
    notes: "Good grain-free option. Peas and tapioca are minor concerns.",
  imageUrl: "/manus-storage/blue-buffalo-wilderness-cat_3435fbc8_5db74463.png",
  },
  {
    id: "purina-cat-chow-complete",
    name: "Complete Adult Dry Cat Food",
    brand: "Purina Cat Chow",
    category: "cat-dry",
    petType: "cat",
    score: 32,
    proteinSource: "Chicken (listed 4th)",
    mainIngredients: ["Ground yellow corn", "Corn gluten meal", "Soybean meal", "Chicken by-product meal", "Beef tallow"],
    redFlags: ["Corn as #1 ingredient", "Corn gluten meal", "Soybean meal", "Chicken by-product meal", "BHA/BHT preservatives"],
    greenFlags: ["Very affordable", "Widely available"],
    priceRange: "$",
    notes: "Corn-dominated formula with BHA/BHT. Not appropriate for obligate carnivores.",
  imageUrl: "/manus-storage/purina-cat-chow-complete_45d9033b_262fcb7b.jpg",
  },
  {
    id: "hills-science-diet-cat-indoor",
    name: "Adult Indoor Dry Cat Food",
    brand: "Hill's Science Diet",
    category: "cat-dry",
    petType: "cat",
    score: 58,
    proteinSource: "Chicken meal",
    mainIngredients: ["Chicken meal", "Brewers rice", "Corn gluten meal", "Pork fat", "Chicken liver flavor"],
    redFlags: ["Corn gluten meal filler", "Brewers rice filler", "Pork fat (unspecified source)"],
    greenFlags: ["Vet-recommended", "Hairball control", "Weight management"],
    priceRange: "$$",
    notes: "Clinically tested. Corn-heavy but vet-trusted. Better than budget options.",
  imageUrl: "/manus-storage/hills-science-diet-cat-indoor_2a096ca5_a7a68b9f.jpg",
  },
  {
    id: "instinct-raw-boost-cat",
    name: "Raw Boost Grain-Free Chicken",
    brand: "Instinct",
    category: "cat-dry",
    petType: "cat",
    score: 88,
    proteinSource: "Chicken",
    mainIngredients: ["Chicken", "Chicken meal", "Tapioca starch", "Chicken fat", "Freeze-dried raw chicken pieces"],
    redFlags: ["Tapioca starch filler"],
    greenFlags: ["Freeze-dried raw pieces mixed in", "Grain-free", "No artificial colors/flavors", "High protein"],
    priceRange: "$$$",
    notes: "Unique kibble + freeze-dried raw combo. Great for transitioning to raw.",
  imageUrl: "/manus-storage/instinct-raw-boost-cat_a3fc8b67_41e3e788.jpg",
  },

  // ── CAT WET ──────────────────────────────────────────────────────────────────
  {
    id: "stella-chewys-cat-wet",
    name: "Carnivore Cravings Chicken & Chicken Liver Pâté",
    brand: "Stella & Chewy's",
    category: "cat-wet",
    petType: "cat",
    score: 96,
    proteinSource: "Chicken, chicken liver",
    mainIngredients: ["Chicken", "Chicken liver", "Chicken broth", "Dried chicken", "Pumpkin"],
    redFlags: [],
    greenFlags: ["95%+ animal ingredients", "No fillers", "No carrageenan", "High moisture for urinary health"],
    priceRange: "$$$$",
    notes: "Top-tier wet cat food. High moisture is critical for cats' urinary health.",
  imageUrl: "/manus-storage/stella-chewys-cat-wet_fbbf0753_53ede811.jpg",
  },
  {
    id: "weruva-cat-wet-paw-lickin",
    name: "Paw Lickin' Chicken in Gravy",
    brand: "Weruva",
    category: "cat-wet",
    petType: "cat",
    score: 90,
    proteinSource: "Boneless skinless chicken breast",
    mainIngredients: ["Chicken broth", "Chicken", "Sunflower seed oil", "Guar gum", "Xanthan gum"],
    redFlags: ["Guar gum (minor)"],
    greenFlags: ["Human-grade", "No carrageenan", "BPA-free cans", "Very high moisture"],
    priceRange: "$$$",
    notes: "Human-grade wet food. Excellent hydration source for cats.",
  imageUrl: "/manus-storage/weruva-cat-wet-paw-lickin_85c82aba_e9c3b8d9.jpg",
  },
  {
    id: "fancy-feast-classic-chicken",
    name: "Classic Pâté Chicken Feast",
    brand: "Fancy Feast",
    category: "cat-wet",
    petType: "cat",
    score: 55,
    proteinSource: "Chicken, chicken liver",
    mainIngredients: ["Chicken", "Chicken broth", "Chicken liver", "Meat by-products", "Artificial flavor"],
    redFlags: ["Meat by-products (unspecified)", "Artificial flavor", "Added salt"],
    greenFlags: ["High moisture", "Affordable", "Cats love it", "No carrageenan in classic line"],
    priceRange: "$",
    notes: "Better than dry budget food for hydration. By-products and artificial flavor are concerns.",
  imageUrl: "/manus-storage/fancy-feast-classic-chicken_proper_a1964073.jpg",
  },
  {
    id: "friskies-wet-cat",
    name: "Savory Shreds Chicken in Gravy",
    brand: "Friskies",
    category: "cat-wet",
    petType: "cat",
    score: 30,
    proteinSource: "Chicken (minor)",
    mainIngredients: ["Water", "Chicken", "Meat by-products", "Wheat gluten", "Artificial colors"],
    redFlags: ["Wheat gluten filler", "Meat by-products (unspecified)", "Artificial colors", "Carrageenan"],
    greenFlags: ["Very affordable", "High moisture"],
    priceRange: "$",
    notes: "Carrageenan is a known gut irritant. Wheat gluten and artificial dyes. Avoid.",
  imageUrl: "/manus-storage/friskies-wet-cat_b3ee22cb_c829e7af.jpg",
  },
  {
    id: "tiki-cat-luau-chicken",
    name: "Luau Wild Salmon in Chicken Consommé",
    brand: "Tiki Cat",
    category: "cat-wet",
    petType: "cat",
    score: 93,
    proteinSource: "Wild salmon, chicken",
    mainIngredients: ["Wild salmon", "Chicken consommé", "Sunflower seed oil", "Tricalcium phosphate"],
    redFlags: [],
    greenFlags: ["No carrageenan", "No thickeners", "Human-grade fish", "Very high protein", "Low carb"],
    priceRange: "$$$",
    notes: "Exceptional wet food. Very clean label, high protein, low carb — ideal for cats.",
  imageUrl: "/manus-storage/tiki-cat-luau-chicken_a41dd932_b6fa45eb.png",
  },

  // ── CAT TREATS ───────────────────────────────────────────────────────────────
  {
    id: "churu-cat-treats",
    name: "Purée Chicken Lickable Treats",
    brand: "Inaba Churu",
    category: "cat-treat",
    petType: "cat",
    score: 82,
    proteinSource: "Chicken",
    mainIngredients: ["Chicken", "Chicken broth", "Tapioca starch", "Dried bonito flakes", "Scallop extract"],
    redFlags: ["Tapioca starch (minor)"],
    greenFlags: ["No artificial colors/flavors", "High moisture", "Cats love it", "Low calorie"],
    priceRange: "$$",
    notes: "Very popular and reasonably clean. Great for hydration and medication delivery.",
  imageUrl: "/manus-storage/churu-cat-treats_0e3bb6b8_ad8199c2.jpg",
  },
  {
    id: "vital-essentials-freeze-dried-cat",
    name: "Freeze-Dried Chicken Breast Cat Treats",
    brand: "Vital Essentials",
    category: "cat-treat",
    petType: "cat",
    score: 98,
    proteinSource: "Chicken breast",
    mainIngredients: ["Chicken breast"],
    redFlags: [],
    greenFlags: ["Single ingredient", "Freeze-dried raw", "No additives whatsoever"],
    priceRange: "$$$",
    notes: "Cleanest possible treat. Single ingredient, nothing else.",
  imageUrl: "/manus-storage/vital-essentials-freeze-dried-cat_6c56717c_d668db07.jpg",
  },
  {
    id: "temptations-classic-treats",
    name: "Classic Treats Tempting Tuna Flavor",
    brand: "Temptations",
    category: "cat-treat",
    petType: "cat",
    score: 22,
    proteinSource: "Chicken by-product meal",
    mainIngredients: ["Chicken by-product meal", "Ground corn", "Animal fat", "Corn gluten meal", "Artificial flavor"],
    redFlags: ["Chicken by-product meal", "Ground corn filler", "Corn gluten meal", "Artificial flavor", "Artificial colors", "BHA preservative"],
    greenFlags: ["Cats are addicted to them", "Affordable"],
    priceRange: "$",
    notes: "Highly palatable due to flavor enhancers. BHA, artificial dyes, corn fillers. Avoid.",
  imageUrl: "/manus-storage/temptations-classic-treats_1f9dcca4_0a03be97.jpg",
  },
];

export const ALL_PET_PRODUCTS: PetProduct[] = RAW_PRODUCTS.map(p => ({
  ...p,
  ...gradeFromScore(p.score),
}));

export const PET_CATEGORIES = [
  { key: "all", label: "All" },
  { key: "dog-dry", label: "Dog Dry" },
  { key: "dog-wet", label: "Dog Wet" },
  { key: "dog-treat", label: "Dog Treats" },
  { key: "cat-dry", label: "Cat Dry" },
  { key: "cat-wet", label: "Cat Wet" },
  { key: "cat-treat", label: "Cat Treats" },
] as const;

export const PET_BRANDS = Array.from(new Set(ALL_PET_PRODUCTS.map(p => p.brand))).sort();
