/**
 * EatVera — Comprehensive US Snack Database
 * Covers all major snack categories sold in US grocery stores.
 * Quality scores based on:
 * - Ingredient quality (seed oils, artificial additives, HFCS, preservatives)
 * - Processing level (NOVA classification)
 * - Sugar, sodium, and trans fat content
 * - Presence of whole food ingredients
 * - Brand sourcing and manufacturing practices
 */

export type SnackCategory =
  | "Chips & Crisps"
  | "Crackers"
  | "Cookies & Biscuits"
  | "Candy & Chocolate"
  | "Granola & Bars"
  | "Popcorn"
  | "Nuts & Seeds"
  | "Jerky & Meat Snacks"
  | "Trail Mix & Dried Fruit"
  | "Pretzels"
  | "Rice Cakes & Puffed Snacks"
  | "Dips & Spreads"
  | "Cheese Snacks"
  | "Fruit Snacks"
  | "Veggie Snacks"
  | "Protein Snacks"
  | "Ice Cream & Frozen"
  | "Pudding & Gelatin";

export type SnackTier = "elite" | "good" | "average" | "poor" | "avoid";

export interface SnackEntry {
  id: string;
  barcode: string;
  name: string;
  brand: string;
  category: SnackCategory;
  tier: SnackTier;
  score: number;
  ingredients: string;
  concerns: string[];
  positives: string[];
  whyScore: string;
  servingSize: string;
  nutriments: Record<string, number>;
  certifications: string[];
  /** Real UPC barcode */
  upc: string;
  /** Alternative UPCs for same product */
  altUPCs?: string[];
  averagePrice?: number;
  imageUrl?: string;
}

export const SNACK_TIER_CONFIG: Record<SnackTier, { label: string; color: string; bg: string; border: string; description: string }> = {
  elite:   { label: "Elite",   color: "#145A3A", bg: "#F0FAF2", border: "#86d086",  description: "Clean ingredients, minimal processing, real food" },
  good:    { label: "Good",    color: "#3FA34D", bg: "#F0FAF2", border: "#b8e8b8",  description: "Mostly clean with minor concerns" },
  average: { label: "Average", color: "#d97706", bg: "#fffbf0", border: "#fde68a",  description: "Moderate processing, some concerning ingredients" },
  poor:    { label: "Poor",    color: "#ea580c", bg: "#fff7ed", border: "#fed7aa",  description: "Heavy processing, seed oils, artificial additives" },
  avoid:   { label: "Avoid",   color: "#dc2626", bg: "#fff5f5", border: "#fca5a5",  description: "Harmful ingredients, ultra-processed, avoid regularly" },
};

export const SNACK_CATEGORIES: SnackCategory[] = [
  "Chips & Crisps", "Crackers", "Cookies & Biscuits", "Candy & Chocolate",
  "Granola & Bars", "Popcorn", "Nuts & Seeds", "Jerky & Meat Snacks",
  "Trail Mix & Dried Fruit", "Pretzels", "Rice Cakes & Puffed Snacks",
  "Dips & Spreads", "Cheese Snacks", "Fruit Snacks", "Veggie Snacks",
  "Protein Snacks", "Ice Cream & Frozen", "Pudding & Gelatin",
];

export function getSnackColor(score: number): string {
  if (score >= 80) return "#145A3A";
  if (score >= 65) return "#3FA34D";
  if (score >= 45) return "#d97706";
  if (score >= 25) return "#ea580c";
  return "#dc2626";
}

export const ALL_SNACKS: SnackEntry[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // CHIPS & CRISPS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "lays-classic",
    barcode: "0028400589871", upc: "0028400589871",
    imageUrl: "https://pics.walgreens.com/prodimg/632881/450.jpg",
    name: "Lay's Classic Potato Chips",
    brand: "Lay's (PepsiCo)",
    category: "Chips & Crisps", tier: "poor", score: 28,
    ingredients: "Potatoes, Vegetable Oil (Sunflower, Corn, and/or Canola Oil), Salt.",
    concerns: ["Sunflower oil — high omega-6, inflammatory", "Canola oil — highly processed seed oil", "Corn oil — seed oil", "Ultra-processed"],
    positives: ["Only 3 ingredients", "No artificial flavors or preservatives"],
    whyScore: "Seed oils (sunflower, corn, canola) are the primary fat source. These omega-6-heavy oils promote systemic inflammation when consumed regularly.",
    servingSize: "28g (about 15 chips)",
    nutriments: { "energy-kcal_100g": 536, "fat_100g": 33.9, "saturated-fat_100g": 3.6, "carbohydrates_100g": 55.4, "sugars_100g": 0.5, "sodium_100g": 0.625, "proteins_100g": 5.4 },
    certifications: [], altUPCs: ["0028400589888"],
  },
  {
    id: "kettle-brand-sea-salt",
    barcode: "0084114100016", upc: "0084114100016",
    imageUrl: "/manus-storage/lay_s_classic_potato_chips_bag_5376b6b5.jpg",
    name: "Kettle Brand Sea Salt Potato Chips",
    brand: "Kettle Brand",
    category: "Chips & Crisps", tier: "average", score: 48,
    ingredients: "Potatoes, Safflower and/or Sunflower Oil, Sea Salt.",
    concerns: ["Safflower oil — very high omega-6", "Sunflower oil — inflammatory seed oil", "Still seed oil-based"],
    positives: ["Kettle-cooked — lower acrylamide than continuous process", "Sea salt instead of refined salt", "Non-GMO Project Verified", "No artificial additives"],
    whyScore: "Better than conventional chips but still uses high-omega-6 seed oils. Kettle cooking method is slightly better but the oil choice remains the main concern.",
    averagePrice: 4.29,
    servingSize: "28g (about 13 chips)",
    nutriments: { "energy-kcal_100g": 536, "fat_100g": 32.1, "saturated-fat_100g": 3.6, "carbohydrates_100g": 55.4, "sugars_100g": 0.5, "sodium_100g": 0.536, "proteins_100g": 5.4 },
    certifications: ["Non-GMO Project Verified"],
  },
  {
    id: "siete-grain-free-chips",
    barcode: "0856349006001", upc: "0856349006001",
    name: "Siete Grain Free Tortilla Chips — Sea Salt",
    brand: "Siete Family Foods",
    category: "Chips & Crisps", tier: "good", score: 72,
    ingredients: "Cassava Flour, Avocado Oil, Sea Salt.",
    concerns: ["Cassava is high in starch — moderate glycemic index"],
    positives: ["Avocado oil — healthy monounsaturated fat", "Grain-free and gluten-free", "Only 3 clean ingredients", "No seed oils", "Paleo-friendly"],
    whyScore: "One of the cleanest chip options available. Avocado oil is a healthy fat, cassava is a whole-food starch, and there are zero seed oils or artificial additives.",
    averagePrice: 5.99,
    servingSize: "28g (about 10 chips)",
    nutriments: { "energy-kcal_100g": 464, "fat_100g": 21.4, "saturated-fat_100g": 3.6, "carbohydrates_100g": 64.3, "sugars_100g": 0, "sodium_100g": 0.393, "proteins_100g": 0 },
    certifications: ["Certified Gluten-Free", "Non-GMO Project Verified", "Paleo Certified"],
  imageUrl: "/manus-storage/siete-grain-free-chips_4d28cf38.png",
  },
  {
    id: "jackson-honest-chips",
    barcode: "0856717003015", upc: "0856717003015",
    name: "Jackson's Sea Salt Sweet Potato Chips",
    brand: "Jackson's Honest",
    category: "Chips & Crisps", tier: "elite", score: 88,
    ingredients: "Sweet Potatoes, Coconut Oil, Sea Salt.",
    concerns: ["High in natural sugars from sweet potato"],
    positives: ["Coconut oil — stable saturated fat, no oxidation", "Sweet potato — nutrient-dense whole food", "Zero seed oils", "Only 3 ingredients", "Non-GMO"],
    whyScore: "The gold standard of chips. Coconut oil is one of the most stable cooking fats — no oxidation, no omega-6 overload. Sweet potato adds beta-carotene and fiber.",
    servingSize: "28g",
    nutriments: { "energy-kcal_100g": 500, "fat_100g": 28.6, "saturated-fat_100g": 25, "carbohydrates_100g": 60.7, "sugars_100g": 7.1, "sodium_100g": 0.357, "proteins_100g": 3.6 },
    certifications: ["Non-GMO Project Verified", "Certified Gluten-Free"],
  imageUrl: "/manus-storage/jackson_s_sea_salt_sweet_potato_chips_bag_5bfc504c.jpg",
  },
  {
    id: "doritos-nacho-cheese",
    barcode: "0028400090018", upc: "0028400090018",
    imageUrl: "https://pics.walgreens.com/prodimg/642055/450.jpg",
    name: "Doritos Nacho Cheese Flavored Tortilla Chips",
    brand: "Doritos (PepsiCo)",
    category: "Chips & Crisps", tier: "avoid", score: 12,
    ingredients: "Whole Corn, Vegetable Oil (Corn, Canola, and/or Sunflower Oil), Salt, Cheddar Cheese (Milk, Cheese Cultures, Salt, Enzymes), Maltodextrin, Whey, Monosodium Glutamate, Buttermilk, Romano Cheese, Whey Protein Concentrate, Onion Powder, Corn Flour, Natural and Artificial Flavors, Dextrose, Tomato Powder, Lactose, Spices, Artificial Color (Yellow 6, Yellow 5, and Red 40), Lactic Acid, Citric Acid, Sugar, Garlic Powder, Skim Milk, Red and Green Bell Pepper Powder, Disodium Inosinate, Disodium Guanylate.",
    concerns: ["Corn, canola, sunflower seed oils", "Monosodium glutamate (MSG)", "Artificial colors Red 40, Yellow 5, Yellow 6 — linked to hyperactivity", "Maltodextrin — high glycemic", "Disodium inosinate/guanylate — flavor enhancers", "Ultra-processed NOVA Group 4"],
    positives: ["Contains some real cheese"],
    whyScore: "A textbook ultra-processed food. Multiple seed oils, artificial dyes linked to behavioral issues in children, MSG, and a 30+ ingredient list. Engineered to override satiety signals.",
    averagePrice: 4.49,
    servingSize: "28g (about 11 chips)",
    nutriments: { "energy-kcal_100g": 500, "fat_100g": 25, "saturated-fat_100g": 3.6, "carbohydrates_100g": 60.7, "sugars_100g": 1.8, "sodium_100g": 0.768, "proteins_100g": 7.1 },
    certifications: [],
  },
  {
    id: "pringles-original",
    barcode: "0038000845031", upc: "0038000845031",
    imageUrl: "/manus-storage/doritos_nacho_cheese_flavored_tortilla_chips_bag_ad8746d4.jpg",
    name: "Pringles Original",
    brand: "Pringles (Kellogg's)",
    category: "Chips & Crisps", tier: "avoid", score: 15,
    ingredients: "Dried Potatoes, Vegetable Oil (Corn Oil, Cottonseed Oil, High Oleic Soybean Oil, and Sunflower Oil), Degerminated Yellow Corn Flour, Cornstarch, Rice Flour, Maltodextrin, Mono and Diglycerides, Salt, Wheat Starch.",
    concerns: ["Corn oil, cottonseed oil, soybean oil, sunflower oil — 4 seed oils", "Cottonseed oil — highest pesticide residue of any oil", "Mono and diglycerides — hidden trans fats", "Maltodextrin — spikes blood sugar", "Highly engineered shape designed for overconsumption"],
    positives: ["Consistent portion size"],
    whyScore: "Contains FOUR different seed oils including cottonseed — one of the most pesticide-contaminated oils. Mono and diglycerides are a form of partially hydrogenated fat. Engineered for addictive consumption.",
    averagePrice: 2.49,
    servingSize: "28g (about 15 crisps)",
    nutriments: { "energy-kcal_100g": 536, "fat_100g": 33.9, "saturated-fat_100g": 8.9, "carbohydrates_100g": 55.4, "sugars_100g": 1.8, "sodium_100g": 0.536, "proteins_100g": 3.6 },
    certifications: [],
  },
  {
    id: "ruffles-original",
    barcode: "0028400589918", upc: "0028400589918",
    name: "Ruffles Original Potato Chips",
    brand: "Ruffles (PepsiCo)",
    category: "Chips & Crisps", tier: "poor", score: 25,
    ingredients: "Potatoes, Vegetable Oil (Sunflower, Corn, and/or Canola Oil), Salt.",
    concerns: ["Sunflower, corn, canola seed oils", "Ultra-processed"],
    positives: ["Only 3 ingredients"],
    whyScore: "Same seed oil profile as Lay's. The ridged texture increases surface area for oil absorption, meaning more seed oil per chip.",
    averagePrice: 4.49,
    servingSize: "28g",
    nutriments: { "energy-kcal_100g": 536, "fat_100g": 33.9, "saturated-fat_100g": 3.6, "carbohydrates_100g": 55.4, "sugars_100g": 0.5, "sodium_100g": 0.625, "proteins_100g": 5.4 },
    certifications: [],
  imageUrl: "/manus-storage/ruffles_original_potato_chips_bag_e46ee0a6.jpg",
  },
  {
    id: "tostitos-original",
    barcode: "0028400090100", upc: "0028400090100",
    imageUrl: "https://images.openfoodfacts.org/images/products/002/840/001/7459/front_en.8.200.jpg",
    name: "Tostitos Original Restaurant Style",
    brand: "Tostitos (PepsiCo)",
    category: "Chips & Crisps", tier: "poor", score: 30,
    ingredients: "Corn, Vegetable Oil (Corn, Canola, and/or Sunflower Oil), Salt.",
    concerns: ["Corn, canola, sunflower seed oils", "GMO corn likely"],
    positives: ["Only 3 ingredients", "No artificial additives"],
    whyScore: "Three seed oils in rotation. Corn is likely GMO. Simple ingredient list but the seed oil base is the primary concern.",
    averagePrice: 4.99,
    servingSize: "28g (about 6 chips)",
    nutriments: { "energy-kcal_100g": 500, "fat_100g": 25, "saturated-fat_100g": 3.6, "carbohydrates_100g": 64.3, "sugars_100g": 0, "sodium_100g": 0.536, "proteins_100g": 7.1 },
    certifications: [],
  },
  {
    id: "late-july-tortilla-chips",
    barcode: "0890175001012", upc: "0890175001012",
    imageUrl: "/manus-storage/tostitos_original_restaurant_style_tortilla_chips_bag_904a10b0.jpg",
    name: "Late July Organic Sea Salt Tortilla Chips",
    brand: "Late July Snacks",
    category: "Chips & Crisps", tier: "good", score: 68,
    ingredients: "Organic Stone Ground White Corn, Organic Sunflower Oil, Sea Salt.",
    concerns: ["Sunflower oil — still high omega-6", "Organic sunflower is better but still inflammatory"],
    positives: ["Organic corn — no GMO, no pesticides", "USDA Organic certified", "Non-GMO Project Verified", "Simple 3-ingredient list"],
    whyScore: "Organic corn is a major upgrade over conventional. Sunflower oil is still a concern but organic sourcing reduces pesticide exposure. Better than most tortilla chips.",
    averagePrice: 4.99,
    servingSize: "28g",
    nutriments: { "energy-kcal_100g": 500, "fat_100g": 25, "saturated-fat_100g": 3.6, "carbohydrates_100g": 64.3, "sugars_100g": 0, "sodium_100g": 0.393, "proteins_100g": 7.1 },
    certifications: ["USDA Organic", "Non-GMO Project Verified"],
  },
  {
    id: "sun-chips-original",
    barcode: "0028400090179", upc: "0028400090179",
    imageUrl: "https://products.blains.com/600/137/1373293.jpg",
    name: "SunChips Original Multigrain Snacks",
    brand: "SunChips (PepsiCo)",
    category: "Chips & Crisps", tier: "poor", score: 22,
    ingredients: "Whole Corn, Sunflower and/or Canola Oil, Whole Wheat, Brown Rice Flour, Whole Oat Flour, Sugar, Salt, Natural Flavor.",
    concerns: ["Sunflower and canola seed oils", "Added sugar", "Misleading 'multigrain' health halo", "Ultra-processed"],
    positives: ["Contains some whole grains"],
    whyScore: "Marketed as healthy due to 'multigrain' branding but contains seed oils and added sugar. The health halo is misleading — this is still an ultra-processed snack.",
    servingSize: "28g (about 16 chips)",
    nutriments: { "energy-kcal_100g": 464, "fat_100g": 21.4, "saturated-fat_100g": 1.8, "carbohydrates_100g": 64.3, "sugars_100g": 3.6, "sodium_100g": 0.393, "proteins_100g": 7.1 },
    certifications: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CRACKERS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "ritz-original",
    barcode: "0044000032036", upc: "0044000000000",
    name: "Ritz Original Crackers",
    brand: "Ritz (Mondelez)",
    category: "Crackers", tier: "avoid", score: 14,
    ingredients: "Enriched Flour (Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Folic Acid), Soybean Oil, Sugar, Partially Hydrogenated Cottonseed Oil, Salt, Leavening (Calcium Phosphate, Baking Soda), High Fructose Corn Syrup, Natural Flavor.",
    concerns: ["Partially hydrogenated cottonseed oil — trans fat", "High fructose corn syrup", "Soybean oil — seed oil", "Enriched refined flour", "NOVA Group 4 ultra-processed"],
    positives: ["Widely available"],
    whyScore: "Contains partially hydrogenated oil (trans fat) and HFCS. Trans fats are directly linked to cardiovascular disease. One of the worst crackers on the market.",
    averagePrice: 3.99,
    servingSize: "16g (5 crackers)",
    nutriments: { "energy-kcal_100g": 500, "fat_100g": 21.4, "saturated-fat_100g": 3.6, "trans-fat_100g": 0.5, "carbohydrates_100g": 67.9, "sugars_100g": 7.1, "sodium_100g": 0.714, "proteins_100g": 7.1 },
    certifications: [],
  imageUrl: "/manus-storage/ritz-original_db170668.jpeg",
  },
  {
    id: "triscuit-original",
    barcode: "0044000030162", upc: "0044000030162",
    name: "Triscuit Original Crackers",
    brand: "Triscuit (Mondelez)",
    category: "Crackers", tier: "average", score: 52,
    ingredients: "Whole Grain Soft White Winter Wheat, Soybean Oil, Salt.",
    concerns: ["Soybean oil — seed oil", "Only 3 ingredients but one is seed oil"],
    positives: ["100% whole grain wheat", "Only 3 ingredients", "Good fiber source", "No artificial additives"],
    whyScore: "One of the simpler cracker options. Whole grain wheat is genuinely nutritious. The only real concern is soybean oil — swapping to an avocado oil version would make this elite.",
    averagePrice: 4.49,
    servingSize: "28g (6 crackers)",
    nutriments: { "energy-kcal_100g": 393, "fat_100g": 10.7, "saturated-fat_100g": 1.8, "carbohydrates_100g": 64.3, "sugars_100g": 0, "sodium_100g": 0.357, "proteins_100g": 10.7 },
    certifications: [],
  imageUrl: "/manus-storage/triscuit-original_d8770faf.jpg",
  },
  {
    id: "simple-mills-almond-flour",
    barcode: "0711747001538", upc: "0711747001538",
    imageUrl: "https://i5.walmartimages.com/asr/0cb3c749-f878-4a29-95c1-d975ac940084_1.ef8cde4a3bf05e581b153ce2b939923a.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff",
    name: "Simple Mills Almond Flour Crackers — Sea Salt",
    brand: "Simple Mills",
    category: "Crackers", tier: "elite", score: 90,
    ingredients: "Almond Flour, Arrowroot, Flaxseed, Sunflower Seeds, Onion, Sea Salt, Rosemary Extract.",
    concerns: ["Sunflower seeds — moderate omega-6 (whole seed, not oil — acceptable)"],
    positives: ["Almond flour base — protein and healthy fats", "Grain-free, gluten-free", "No seed oils", "Whole food ingredients only", "Paleo and Keto friendly", "Non-GMO Project Verified"],
    whyScore: "Exceptional ingredient quality. Almond flour provides protein and healthy monounsaturated fats. All whole food ingredients with no seed oils, no refined grains, no artificial anything.",
    averagePrice: 5.99,
    servingSize: "15g (4 crackers)",
    nutriments: { "energy-kcal_100g": 467, "fat_100g": 26.7, "saturated-fat_100g": 1.3, "carbohydrates_100g": 46.7, "sugars_100g": 0, "sodium_100g": 0.333, "proteins_100g": 13.3 },
    certifications: ["Non-GMO Project Verified", "Certified Gluten-Free", "Paleo Certified"],
  },
  {
    id: "wheat-thins-original",
    barcode: "0044000030131", upc: "0044000030131",
    imageUrl: "https://images.openfoodfacts.org/images/products/004/400/003/0131/front_en.3.200.jpg",
    name: "Wheat Thins Original",
    brand: "Wheat Thins (Mondelez)",
    category: "Crackers", tier: "poor", score: 28,
    ingredients: "Whole Grain Wheat Flour, Enriched Flour (Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Folic Acid), Soybean Oil, Sugar, Cornstarch, Malt Syrup (from Corn and Barley), Salt, Refiner's Syrup, Leavening (Calcium Phosphate and/or Baking Soda), Vegetable Color (Annatto Extract).",
    concerns: ["Soybean oil", "Multiple forms of added sugar (sugar, malt syrup, refiner's syrup)", "Enriched refined flour mixed with whole grain", "Ultra-processed"],
    positives: ["Contains some whole grain wheat"],
    whyScore: "Despite 'whole grain' branding, contains enriched flour, soybean oil, and three different sweeteners. The health halo is misleading.",
    averagePrice: 3.99,
    servingSize: "29g (16 crackers)",
    nutriments: { "energy-kcal_100g": 414, "fat_100g": 13.8, "saturated-fat_100g": 1.7, "carbohydrates_100g": 68.9, "sugars_100g": 10.3, "sodium_100g": 0.483, "proteins_100g": 6.9 },
    certifications: [],
  },
  {
    id: "mary-gone-crackers",
    barcode: "0188481000018", upc: "0188481000018",
    name: "Mary's Gone Crackers Original",
    brand: "Mary's Gone Crackers",
    category: "Crackers", tier: "good", score: 75,
    ingredients: "Organic Brown Rice, Organic Quinoa, Organic Brown Flax Seeds, Organic Brown Sesame Seeds, Filtered Water, Sea Salt, Organic Tamari (Water, Organic Soybeans, Salt).",
    concerns: ["Contains soy (tamari) — allergen for some", "Brown rice is high glycemic"],
    positives: ["All organic ingredients", "Gluten-free certified", "Whole grain and seeds", "No seed oils", "USDA Organic"],
    whyScore: "Genuinely clean ingredients — all organic, whole grains and seeds, no seed oils. The soy in tamari is fermented which improves digestibility.",
    servingSize: "30g (13 crackers)",
    nutriments: { "energy-kcal_100g": 400, "fat_100g": 13.3, "saturated-fat_100g": 1.3, "carbohydrates_100g": 60, "sugars_100g": 0, "sodium_100g": 0.4, "proteins_100g": 10 },
    certifications: ["USDA Organic", "Certified Gluten-Free", "Non-GMO Project Verified"],
  imageUrl: "/manus-storage/mary-gone-crackers_716549c2.png",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // COOKIES & BISCUITS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "oreo-original",
    barcode: "0044000032036", upc: "0044000032036",
    name: "Oreo Original Sandwich Cookies",
    brand: "Oreo (Mondelez)",
    category: "Cookies & Biscuits", tier: "avoid", score: 10,
    ingredients: "Unbleached Enriched Flour (Wheat Flour, Niacin, Reduced Iron, Thiamine Mononitrate {Vitamin B1}, Riboflavin {Vitamin B2}, Folic Acid), Sugar, Palm and/or Canola Oil, Cocoa (Processed with Alkali), High Fructose Corn Syrup, Leavening (Baking Soda and/or Calcium Phosphate), Salt, Soy Lecithin, Chocolate, Artificial Flavor, Blue 2 Lake.",
    concerns: ["High fructose corn syrup", "Canola oil — seed oil", "Palm oil — deforestation concerns", "Artificial flavor", "Blue 2 Lake artificial dye", "Soy lecithin — GMO soy", "Ultra-processed NOVA Group 4", "Enriched refined flour"],
    positives: ["Iconic taste"],
    whyScore: "HFCS, artificial dye, canola oil, and enriched flour make this one of the worst cookies. The artificial Blue 2 dye has been linked to behavioral issues. Engineered for overconsumption.",
    averagePrice: 3.99,
    servingSize: "34g (3 cookies)",
    nutriments: { "energy-kcal_100g": 471, "fat_100g": 20.6, "saturated-fat_100g": 5.9, "carbohydrates_100g": 70.6, "sugars_100g": 41.2, "sodium_100g": 0.559, "proteins_100g": 5.9 },
    certifications: [],
  imageUrl: "/manus-storage/oreo-original_e1d640d2.png",
  },
  {
    id: "chips-ahoy-original",
    barcode: "0044000030018", upc: "0044000030018",
    name: "Chips Ahoy! Original Chocolate Chip Cookies",
    brand: "Chips Ahoy! (Mondelez)",
    category: "Cookies & Biscuits", tier: "avoid", score: 12,
    ingredients: "Unbleached Enriched Flour, Sugar, Semisweet Chocolate Chips (Sugar, Chocolate, Dextrose), Soybean Oil, High Fructose Corn Syrup, Leavening, Salt, Whey, Soy Lecithin, Natural and Artificial Flavor, Caramel Color.",
    concerns: ["High fructose corn syrup", "Soybean oil", "Caramel color — potential carcinogen (4-MEI)", "Artificial flavor", "Enriched refined flour", "Ultra-processed"],
    positives: ["Contains real chocolate chips"],
    whyScore: "HFCS, soybean oil, caramel color (linked to 4-MEI carcinogen), and artificial flavors. A textbook ultra-processed cookie with no redeeming nutritional value.",
    averagePrice: 3.99,
    servingSize: "30g (3 cookies)",
    nutriments: { "energy-kcal_100g": 467, "fat_100g": 20, "saturated-fat_100g": 6.7, "carbohydrates_100g": 66.7, "sugars_100g": 33.3, "sodium_100g": 0.467, "proteins_100g": 6.7 },
    certifications: [],
  imageUrl: "/manus-storage/chips-ahoy-original_4a42327f.jpeg",
  },
  {
    id: "nutter-butter",
    barcode: "0044000030049", upc: "0044000030049",
    imageUrl: "https://i5.walmartimages.com/asr/e6a0074f-5a62-4ee6-94c6-2521e4eac833_2.d9bae9afa1db0437de54e1c77c6ef55b.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff",
    name: "Nutter Butter Peanut Butter Sandwich Cookies",
    brand: "Nutter Butter (Mondelez)",
    category: "Cookies & Biscuits", tier: "avoid", score: 11,
    ingredients: "Unbleached Enriched Flour, Sugar, Peanut Butter (Peanuts, Hydrogenated Vegetable Oil), Soybean Oil, High Fructose Corn Syrup, Dextrose, Salt, Leavening, Soy Lecithin, Natural Flavor.",
    concerns: ["Hydrogenated vegetable oil in peanut butter — trans fat", "High fructose corn syrup", "Soybean oil", "Enriched refined flour"],
    positives: ["Contains real peanut butter"],
    whyScore: "Hydrogenated oil in the peanut butter filling means hidden trans fats. Combined with HFCS and soybean oil, this is a triple threat of harmful fats.",
    averagePrice: 3.49,
    servingSize: "31g (2 cookies)",
    nutriments: { "energy-kcal_100g": 484, "fat_100g": 22.6, "saturated-fat_100g": 4.8, "carbohydrates_100g": 64.5, "sugars_100g": 29, "sodium_100g": 0.484, "proteins_100g": 9.7 },
    certifications: [],
  },
  {
    id: "partake-cookies",
    barcode: "0850019270018", upc: "0850019270018",
    imageUrl: "https://i5.walmartimages.com/asr/fc7ea3d7-2f80-4600-af6c-b3be986de4f2.84d60e6a15958c1af5c3430747252451.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff",
    name: "Partake Chocolate Chip Cookies",
    brand: "Partake Foods",
    category: "Cookies & Biscuits", tier: "good", score: 70,
    ingredients: "Oat Flour, Cane Sugar, Chocolate Chips (Cane Sugar, Cocoa Butter, Cocoa Mass, Vanilla Extract), Sunflower Oil, Tapioca Starch, Coconut Sugar, Flaxseed, Baking Soda, Sea Salt, Vanilla Extract.",
    concerns: ["Sunflower oil — seed oil", "Contains cane sugar and coconut sugar (double sugar)"],
    positives: ["Allergen-free (top 9)", "Oat flour base", "Real vanilla extract", "No artificial additives", "Non-GMO"],
    whyScore: "Clean allergen-free cookie with real ingredients. Sunflower oil is a concern but the rest of the ingredient list is genuinely clean. Good option for those with allergies.",
    averagePrice: 6.99,
    servingSize: "28g (4 cookies)",
    nutriments: { "energy-kcal_100g": 429, "fat_100g": 17.9, "saturated-fat_100g": 7.1, "carbohydrates_100g": 64.3, "sugars_100g": 28.6, "sodium_100g": 0.357, "proteins_100g": 7.1 },
    certifications: ["Non-GMO Project Verified", "Certified Gluten-Free", "Vegan Certified"],
  },
  {
    id: "thin-mints",
    barcode: "0012232100012", upc: "0012232100012",
    imageUrl: "https://images.openfoodfacts.org/images/products/008/201/157/0710/front_en.54.200.jpg",
    name: "Girl Scout Thin Mints",
    brand: "Girl Scouts",
    category: "Cookies & Biscuits", tier: "poor", score: 20,
    ingredients: "Enriched Flour, Sugar, Vegetable Oil (Palm, Soybean, and/or Canola Oil), Cocoa, Invert Sugar, Peppermint Oil, Soy Lecithin, Baking Soda, Salt.",
    concerns: ["Palm, soybean, canola seed oils", "Invert sugar — processed sweetener", "Enriched refined flour", "Soy lecithin"],
    positives: ["Contains real peppermint oil", "Iconic seasonal treat"],
    whyScore: "Three seed oils and invert sugar. Seasonal nostalgia aside, the ingredient quality is poor. Occasional indulgence is fine but not a health food.",
    servingSize: "29g (4 cookies)",
    nutriments: { "energy-kcal_100g": 483, "fat_100g": 24.1, "saturated-fat_100g": 13.8, "carbohydrates_100g": 65.5, "sugars_100g": 37.9, "sodium_100g": 0.345, "proteins_100g": 3.4 },
    certifications: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CANDY & CHOCOLATE
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "snickers-bar",
    barcode: "0040000001522", upc: "0040000001522",
    name: "Snickers Original Bar",
    brand: "Mars",
    category: "Candy & Chocolate", tier: "poor", score: 22,
    ingredients: "Milk Chocolate (Sugar, Cocoa Butter, Chocolate, Skim Milk, Lactose, Milkfat, Soy Lecithin, Artificial Flavor), Peanuts, Corn Syrup, Sugar, Palm Oil, Skim Milk, Lactose, Salt, Egg Whites, Artificial Flavor.",
    concerns: ["Corn syrup", "Palm oil", "Artificial flavor", "Soy lecithin", "High sugar content", "Ultra-processed"],
    positives: ["Contains real peanuts", "Some protein from peanuts and milk"],
    whyScore: "Corn syrup and palm oil are the primary concerns. High sugar content and artificial flavors. Occasional treat but not a health food.",
    averagePrice: 1.79,
    servingSize: "52.7g (1 bar)",
    nutriments: { "energy-kcal_100g": 488, "fat_100g": 22.7, "saturated-fat_100g": 8.7, "carbohydrates_100g": 63.6, "sugars_100g": 54.5, "sodium_100g": 0.227, "proteins_100g": 9.1 },
    certifications: [],
  imageUrl: "/manus-storage/snickers-bar_79f14f7c.jpg",
  },
  {
    id: "skittles-original",
    barcode: "0022000010291", upc: "0022000010291",
    imageUrl: "https://i5.walmartimages.com/asr/538b1fe3-657b-4160-9e4f-8fa65608d978_1.be04513bfc2c52d66455b77b418730fe.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff",
    name: "Skittles Original",
    brand: "Skittles (Mars)",
    category: "Candy & Chocolate", tier: "avoid", score: 5,
    ingredients: "Sugar, Corn Syrup, Hydrogenated Palm Kernel Oil, Citric Acid, Tapioca Dextrin, Modified Corn Starch, Natural and Artificial Flavors, Colors (Red 40, Yellow 5, Yellow 6, Blue 1, Blue 2, Green 3, Titanium Dioxide).",
    concerns: ["Hydrogenated palm kernel oil — trans fat", "Corn syrup", "Titanium dioxide — potential carcinogen (banned in EU)", "Red 40, Yellow 5, Yellow 6, Blue 1, Blue 2 — artificial dyes linked to hyperactivity", "Green 3 artificial dye", "Modified corn starch", "Zero nutritional value"],
    positives: ["None of nutritional significance"],
    whyScore: "One of the worst candies. Titanium dioxide is banned in the EU as a potential carcinogen. Six artificial dyes, hydrogenated oil (trans fat), and zero nutrition. Especially harmful for children.",
    averagePrice: 1.99,
    servingSize: "61g",
    nutriments: { "energy-kcal_100g": 393, "fat_100g": 4.3, "saturated-fat_100g": 4.3, "carbohydrates_100g": 90.2, "sugars_100g": 75.4, "sodium_100g": 0.049, "proteins_100g": 0 },
    certifications: [],
  },
  {
    id: "dark-chocolate-85",
    barcode: "0747599400117", upc: "0747599400117",
    imageUrl: "/manus-storage/lindt-85-dark-chocolate_6d79de24.jpeg",
    name: "Lindt Excellence 85% Cocoa Dark Chocolate",
    brand: "Lindt",
    category: "Candy & Chocolate", tier: "elite", score: 88,
    ingredients: "Chocolate, Cocoa Powder, Sugar, Cocoa Butter, Bourbon Vanilla Beans.",
    concerns: ["Contains sugar (low amount at 85% cacao)", "High calorie density"],
    positives: ["85% cacao — very high in flavanols", "Only 5 clean ingredients", "No seed oils, no artificial additives", "Rich in magnesium and antioxidants", "Supports cardiovascular health"],
    whyScore: "High-cacao dark chocolate is genuinely health-promoting. Flavanols support heart health, brain function, and blood pressure. Minimal sugar at 85% cacao.",
    averagePrice: 3.99,
    servingSize: "40g (8 squares)",
    nutriments: { "energy-kcal_100g": 575, "fat_100g": 47.5, "saturated-fat_100g": 28.75, "carbohydrates_100g": 27.5, "sugars_100g": 12.5, "sodium_100g": 0.025, "proteins_100g": 12.5 },
    certifications: [],
  },
  {
    id: "endangered-species-dark",
    barcode: "0037014220018", upc: "0037014220018",
    name: "Endangered Species 72% Dark Chocolate Bar",
    brand: "Endangered Species Chocolate",
    category: "Candy & Chocolate", tier: "good", score: 78,
    ingredients: "Dark Chocolate (Cacao Beans, Cane Sugar, Cocoa Butter, Vanilla Extract), Soy Lecithin.",
    concerns: ["Soy lecithin — minor concern", "Contains sugar"],
    positives: ["72% cacao — high flavanol content", "Fair Trade Certified", "Non-GMO Project Verified", "Real vanilla extract", "Clean ingredient list"],
    whyScore: "Clean dark chocolate with Fair Trade certification. 72% cacao provides meaningful antioxidant benefits. Soy lecithin is a minor emulsifier concern.",
    averagePrice: 3.49,
    servingSize: "40g",
    nutriments: { "energy-kcal_100g": 525, "fat_100g": 37.5, "saturated-fat_100g": 22.5, "carbohydrates_100g": 47.5, "sugars_100g": 35, "sodium_100g": 0.025, "proteins_100g": 7.5 },
    certifications: ["Fair Trade Certified", "Non-GMO Project Verified"],
  imageUrl: "/manus-storage/endangered-species-dark_234f19c6.png",
  },
  {
    id: "m-and-ms",
    barcode: "0040000001591", upc: "0040000001591",
    imageUrl: "/manus-storage/mms-milk-chocolate_4135beea.jpg",
    name: "M&M's Milk Chocolate",
    brand: "Mars",
    category: "Candy & Chocolate", tier: "avoid", score: 8,
    ingredients: "Milk Chocolate (Sugar, Chocolate, Skim Milk, Cocoa Butter, Lactose, Milkfat, Soy Lecithin, Salt, Artificial Flavors), Sugar, Cornstarch, Less than 1% - Corn Syrup, Dextrin, Coloring (Blue 1 Lake, Blue 2 Lake, Yellow 6, Yellow 6 Lake, Red 40, Yellow 5, Blue 1, Red 40 Lake, Yellow 5 Lake, Blue 2), Gum Acacia.",
    concerns: ["8 artificial dyes (Blue 1, Blue 2, Yellow 5, Yellow 6, Red 40 and their lake versions)", "Corn syrup", "Artificial flavors", "Soy lecithin", "Ultra-processed"],
    positives: ["Contains real milk chocolate"],
    whyScore: "The most artificial dyes of any mainstream candy. Multiple studies link these dyes to hyperactivity in children. The EU requires warning labels on products with these dyes.",
    servingSize: "42g",
    nutriments: { "energy-kcal_100g": 476, "fat_100g": 19, "saturated-fat_100g": 11.9, "carbohydrates_100g": 71.4, "sugars_100g": 61.9, "sodium_100g": 0.095, "proteins_100g": 4.8 },
    certifications: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GRANOLA & BARS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "kind-dark-chocolate",
    barcode: "0602652179227", upc: "0602652179227",
    imageUrl: "http://i5.walmartimages.com/asr/ae5e85c7-aac9-491f-8319-f7228707eec7_1.df9e5fe9b2df3cbb234b5c952b64b95c.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff",
    name: "KIND Dark Chocolate Nuts & Sea Salt Bar",
    brand: "KIND Snacks",
    category: "Granola & Bars", tier: "good", score: 72,
    ingredients: "Almonds, Peanuts, Chicory Root Fiber, Honey, Palm Kernel Oil, Sugar, Glucose Syrup, Rice Flour, Soy Lecithin, Dark Chocolate (Sugar, Chocolate, Cocoa Butter, Vanilla Extract), Sea Salt.",
    concerns: ["Palm kernel oil", "Glucose syrup — processed sweetener", "Soy lecithin", "Contains added sugars"],
    positives: ["Whole nuts as primary ingredient", "Chicory root fiber — prebiotic", "Real dark chocolate", "Good protein and fiber", "Non-GMO Project Verified"],
    whyScore: "Whole nuts make this genuinely nutritious. Palm kernel oil and glucose syrup are concerns but the overall profile is better than most bars. Good protein-to-sugar ratio.",
    averagePrice: 1.99,
    servingSize: "40g (1 bar)",
    nutriments: { "energy-kcal_100g": 475, "fat_100g": 32.5, "saturated-fat_100g": 10, "carbohydrates_100g": 37.5, "sugars_100g": 20, "sodium_100g": 0.25, "proteins_100g": 12.5 },
    certifications: ["Non-GMO Project Verified", "Certified Gluten-Free"],
  },
  {
    id: "rxbar-chocolate-sea-salt",
    barcode: "0850000625018", upc: "0850000625018",
    name: "RXBAR Chocolate Sea Salt Protein Bar",
    brand: "RXBAR",
    category: "Granola & Bars", tier: "elite", score: 85,
    ingredients: "Dates, Egg Whites, Almonds, Cashews, Cocoa, Sea Salt, Natural Flavors.",
    concerns: ["Dates are high in natural sugar", "Natural flavors — vague term"],
    positives: ["Whole food ingredients only", "12g protein from egg whites", "No added sugar — sweetened only by dates", "No seed oils", "No artificial additives", "Transparent ingredient list"],
    whyScore: "Exceptional whole-food bar. Dates provide natural sweetness with fiber, egg whites deliver complete protein, and nuts add healthy fats. No seed oils, no artificial anything.",
    averagePrice: 2.99,
    servingSize: "52g (1 bar)",
    nutriments: { "energy-kcal_100g": 365, "fat_100g": 11.5, "saturated-fat_100g": 1.9, "carbohydrates_100g": 46.2, "sugars_100g": 23.1, "sodium_100g": 0.308, "proteins_100g": 23.1 },
    certifications: ["Certified Gluten-Free"],
  imageUrl: "/manus-storage/rxbar-chocolate-sea-salt_0a2085d9.jpeg",
  },
  {
    id: "larabar-apple-pie",
    barcode: "0021908501000", upc: "0021908501000",
    name: "Larabar Apple Pie Bar",
    brand: "Larabar (General Mills)",
    category: "Granola & Bars", tier: "elite", score: 87,
    ingredients: "Dates, Almonds, Unsweetened Apples, Walnuts, Cinnamon.",
    concerns: ["High in natural sugar from dates", "High calorie density"],
    positives: ["Only 5 whole food ingredients", "No added sugar", "No seed oils", "No artificial additives", "Paleo and vegan", "Non-GMO Project Verified"],
    whyScore: "One of the cleanest bars available. Five recognizable whole food ingredients, zero seed oils, zero added sugar. The dates provide natural sweetness with fiber and minerals.",
    averagePrice: 1.79,
    servingSize: "45g (1 bar)",
    nutriments: { "energy-kcal_100g": 378, "fat_100g": 15.6, "saturated-fat_100g": 1.1, "carbohydrates_100g": 57.8, "sugars_100g": 42.2, "sodium_100g": 0, "proteins_100g": 6.7 },
    certifications: ["Non-GMO Project Verified", "Certified Gluten-Free", "Vegan Certified", "Paleo Certified"],
  imageUrl: "/manus-storage/larabar-apple-pie_72d5abef.jpg",
  },
  {
    id: "clif-bar-chocolate-chip",
    barcode: "0722252100047", upc: "0722252100047",
    name: "Clif Bar Chocolate Chip",
    brand: "Clif Bar",
    category: "Granola & Bars", tier: "poor", score: 32,
    ingredients: "Organic Rolled Oats, Organic Brown Rice Syrup, Organic Cane Syrup, Soy Rice Crisps (Soy Protein Isolate, Rice Flour, Malt), Organic Roasted Soybeans, Organic Soy Flour, Organic Oat Fiber, Organic Sunflower Oil, Organic Chocolate Chips, Organic Soy Butter, Natural Flavors, Organic Invert Cane Syrup.",
    concerns: ["Brown rice syrup — high glycemic, arsenic risk", "Cane syrup + invert cane syrup = multiple added sugars", "Soy protein isolate — highly processed", "Sunflower oil — seed oil", "Very high sugar content (44g per bar)", "Ultra-processed despite organic label"],
    positives: ["USDA Organic certified", "Contains oats and some whole grains"],
    whyScore: "Despite organic certification, this bar has 44g of sugar per bar (more than a Snickers) and multiple processed soy ingredients. The organic label masks the ultra-processed nature.",
    averagePrice: 1.99,
    servingSize: "68g (1 bar)",
    nutriments: { "energy-kcal_100g": 382, "fat_100g": 7.4, "saturated-fat_100g": 2.9, "carbohydrates_100g": 67.6, "sugars_100g": 44.1, "sodium_100g": 0.25, "proteins_100g": 10.3 },
    certifications: ["USDA Organic"],
  imageUrl: "/manus-storage/clif-bar-chocolate-chip_2a43e80d.jpeg",
  },
  {
    id: "quest-bar-chocolate-chip",
    barcode: "0888849000012", upc: "0888849000012",
    imageUrl: "https://images.openfoodfacts.org/images/products/088/884/900/0012/front_en.272.200.jpg",
    name: "Quest Bar Chocolate Chip Cookie Dough",
    brand: "Quest Nutrition",
    category: "Granola & Bars", tier: "average", score: 50,
    ingredients: "Protein Blend (Milk Protein Isolate, Whey Protein Isolate), Soluble Corn Fiber (Prebiotic Fiber), Almonds, Water, Unsweetened Chocolate, Erythritol, Natural Flavors, Sea Salt, Sunflower Lecithin, Steviol Glycosides (Stevia).",
    concerns: ["Milk protein isolate — highly processed", "Erythritol — sugar alcohol, digestive issues for some", "Natural flavors — vague", "Sunflower lecithin", "Highly processed protein sources"],
    positives: ["21g protein per bar", "Low sugar (1g)", "High fiber (14g)", "No seed oils", "Stevia as sweetener"],
    whyScore: "High protein and low sugar are genuine positives. The processing level is a concern — protein isolates are heavily processed. Better than most bars for blood sugar management.",
    servingSize: "60g (1 bar)",
    nutriments: { "energy-kcal_100g": 367, "fat_100g": 13.3, "saturated-fat_100g": 5, "carbohydrates_100g": 40, "sugars_100g": 1.7, "sodium_100g": 0.417, "proteins_100g": 35 },
    certifications: ["Certified Gluten-Free"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // POPCORN
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "skinny-pop-original",
    barcode: "0816925020014", upc: "0816925020014",
    imageUrl: "https://images.openfoodfacts.org/images/products/085/025/100/4001/front_en.44.200.jpg",
    name: "SkinnyPop Original Popcorn",
    brand: "SkinnyPop",
    category: "Popcorn", tier: "average", score: 55,
    ingredients: "Popcorn, Sunflower Oil, Salt.",
    concerns: ["Sunflower oil — high omega-6 seed oil", "Oil is heated during popping — oxidation risk"],
    positives: ["Only 3 ingredients", "Non-GMO Project Verified", "Gluten-free", "No artificial additives", "Good fiber source"],
    whyScore: "Simple ingredient list but sunflower oil is problematic — high omega-6 and prone to oxidation when heated. Popcorn itself is a whole grain with good fiber.",
    averagePrice: 4.99,
    servingSize: "28g (about 3.5 cups)",
    nutriments: { "energy-kcal_100g": 536, "fat_100g": 32.1, "saturated-fat_100g": 3.6, "carbohydrates_100g": 55.4, "sugars_100g": 0, "sodium_100g": 0.357, "proteins_100g": 10.7 },
    certifications: ["Non-GMO Project Verified", "Certified Gluten-Free"],
  },
  {
    id: "lesser-evil-popcorn",
    barcode: "0851477006005", upc: "0851477006005",
    name: "LesserEvil Himalayan Gold Popcorn",
    brand: "LesserEvil",
    category: "Popcorn", tier: "elite", score: 92,
    ingredients: "Organic Popcorn, Organic Coconut Oil, Himalayan Pink Salt.",
    concerns: ["High in saturated fat from coconut oil (not a health concern — stable fat)"],
    positives: ["Coconut oil — most stable cooking fat, no oxidation", "Organic popcorn", "Himalayan salt — trace minerals", "Only 3 clean ingredients", "USDA Organic", "No seed oils"],
    whyScore: "The gold standard of popcorn. Coconut oil is the ideal popping fat — highly stable at high heat, no oxidation, no omega-6 overload. Organic corn eliminates pesticide concerns.",
    averagePrice: 4.99,
    servingSize: "28g (about 3 cups)",
    nutriments: { "energy-kcal_100g": 500, "fat_100g": 28.6, "saturated-fat_100g": 25, "carbohydrates_100g": 57.1, "sugars_100g": 0, "sodium_100g": 0.357, "proteins_100g": 10.7 },
    certifications: ["USDA Organic", "Non-GMO Project Verified", "Certified Gluten-Free"],
  imageUrl: "/manus-storage/lesser-evil-popcorn_4e6cbaf8.png",
  },
  {
    id: "act-ii-butter-popcorn",
    barcode: "0076150120018", upc: "0076150120018",
    name: "Act II Butter Lovers Microwave Popcorn",
    brand: "Act II (ConAgra)",
    category: "Popcorn", tier: "avoid", score: 15,
    ingredients: "Popcorn, Palm Oil, Salt, Natural and Artificial Butter Flavor, Annatto (Color), TBHQ (Preservative).",
    concerns: ["TBHQ — synthetic preservative, potential carcinogen", "Artificial butter flavor — diacetyl linked to lung disease", "Palm oil", "Microwave bag lining — PFAS chemicals", "Artificial flavor"],
    positives: ["Contains real popcorn"],
    whyScore: "TBHQ is a synthetic antioxidant preservative that has shown carcinogenic effects in animal studies. Artificial butter flavor (diacetyl) caused 'popcorn lung' in factory workers. The microwave bag may contain PFAS.",
    servingSize: "28g (about 3.5 cups popped)",
    nutriments: { "energy-kcal_100g": 464, "fat_100g": 25, "saturated-fat_100g": 10.7, "carbohydrates_100g": 57.1, "sugars_100g": 0, "sodium_100g": 0.714, "proteins_100g": 10.7 },
    certifications: [],
  imageUrl: "/manus-storage/act-ii-butter-popcorn_ba714f8b.png",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NUTS & SEEDS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "planters-dry-roasted-peanuts",
    barcode: "0029000016491", upc: "0029000016491",
    imageUrl: "https://i5.walmartimages.com/asr/363fba53-cb9e-4df3-a75f-ca9540eed318.36680115bc0ea9734a215bb278285b99.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff",
    name: "Planters Dry Roasted Peanuts",
    brand: "Planters (Kraft Heinz)",
    category: "Nuts & Seeds", tier: "average", score: 55,
    ingredients: "Peanuts, Sea Salt, Maltodextrin, Gelatin, Corn Starch, Sugar, Paprika, Onion Powder, Spices, Monosodium Glutamate, Torula Yeast.",
    concerns: ["Monosodium glutamate (MSG)", "Maltodextrin — high glycemic", "Gelatin — unexpected in a nut product", "Corn starch filler", "Added sugar"],
    positives: ["Real peanuts as primary ingredient", "Good protein source", "Contains healthy monounsaturated fats"],
    whyScore: "Peanuts themselves are nutritious but Planters adds MSG, maltodextrin, gelatin, and sugar unnecessarily. Buy plain roasted peanuts instead.",
    averagePrice: 4.99,
    servingSize: "28g (about 39 peanuts)",
    nutriments: { "energy-kcal_100g": 571, "fat_100g": 46.4, "saturated-fat_100g": 7.1, "carbohydrates_100g": 21.4, "sugars_100g": 3.6, "sodium_100g": 0.357, "proteins_100g": 25 },
    certifications: [],
  },
  {
    id: "blue-diamond-almonds",
    barcode: "0041570050200", upc: "0041570050200",
    name: "Blue Diamond Almonds Whole Natural",
    brand: "Blue Diamond",
    category: "Nuts & Seeds", tier: "elite", score: 93,
    ingredients: "Almonds.",
    concerns: ["High calorie density — easy to overeat"],
    positives: ["Single ingredient — whole almonds", "Rich in vitamin E, magnesium, healthy fats", "High in fiber and protein", "No additives whatsoever", "Heart-healthy monounsaturated fats"],
    whyScore: "One ingredient: almonds. Nothing else. Almonds are one of the most nutrient-dense snacks available — vitamin E, magnesium, healthy fats, protein, and fiber.",
    averagePrice: 8.99,
    servingSize: "28g (about 23 almonds)",
    nutriments: { "energy-kcal_100g": 579, "fat_100g": 50, "saturated-fat_100g": 3.8, "carbohydrates_100g": 21.6, "sugars_100g": 4.4, "sodium_100g": 0, "proteins_100g": 21.2 },
    certifications: [],
  imageUrl: "/manus-storage/blue-diamond-almonds_44ce7fad.jpeg",
  },
  {
    id: "wonderful-pistachios",
    barcode: "0014113108082", upc: "0014113108082",
    name: "Wonderful Pistachios No Shell Roasted & Salted",
    brand: "Wonderful Pistachios",
    category: "Nuts & Seeds", tier: "elite", score: 90,
    ingredients: "Pistachios, Salt.",
    concerns: ["High calorie density"],
    positives: ["Two clean ingredients", "Highest protein of any nut", "Rich in B6, potassium, antioxidants", "Prebiotic fiber for gut health", "Heart-healthy"],
    whyScore: "Pistachios with just salt — excellent snack. Highest protein content of any nut, rich in antioxidants, and the act of shelling slows eating pace naturally.",
    averagePrice: 7.99,
    servingSize: "28g (about 49 kernels)",
    nutriments: { "energy-kcal_100g": 571, "fat_100g": 46.4, "saturated-fat_100g": 5.4, "carbohydrates_100g": 28.6, "sugars_100g": 7.1, "sodium_100g": 0.286, "proteins_100g": 21.4 },
    certifications: [],
  imageUrl: "/manus-storage/wonderful-pistachios_84111bfa.jpg",
  },
  {
    id: "mixed-nuts-kirkland",
    barcode: "0096619038947", upc: "0096619038947",
    name: "Kirkland Signature Mixed Nuts",
    brand: "Kirkland (Costco)",
    category: "Nuts & Seeds", tier: "elite", score: 91,
    ingredients: "Cashews, Almonds, Macadamia Nuts, Brazil Nuts, Pecans, Sea Salt.",
    concerns: ["High calorie density", "Cashews are higher in carbs than other nuts"],
    positives: ["Six whole nut varieties", "Only sea salt added", "No seed oils", "No artificial additives", "Brazil nuts provide selenium (1-2 per day meets daily requirement)", "Excellent nutrient diversity"],
    whyScore: "Premium mixed nuts with clean ingredients. Brazil nuts provide selenium, macadamias offer oleic acid, almonds give vitamin E. Exceptional nutrient diversity in one snack.",
    averagePrice: 19.99,
    servingSize: "30g",
    nutriments: { "energy-kcal_100g": 600, "fat_100g": 53.3, "saturated-fat_100g": 10, "carbohydrates_100g": 20, "sugars_100g": 3.3, "sodium_100g": 0.2, "proteins_100g": 16.7 },
    certifications: [],
  imageUrl: "/manus-storage/mixed-nuts-kirkland_b6a1a9b5.jpg",
  },
  {
    id: "honey-roasted-peanuts",
    barcode: "0029000071032", upc: "0029000071032",
    name: "Planters Honey Roasted Peanuts",
    brand: "Planters (Kraft Heinz)",
    category: "Nuts & Seeds", tier: "poor", score: 35,
    ingredients: "Peanuts, Sugar, Honey, Soybean Oil, Corn Starch, Salt, Maltodextrin.",
    concerns: ["Soybean oil — seed oil", "Added sugar and honey (double sweetener)", "Maltodextrin", "Corn starch filler"],
    positives: ["Real peanuts as primary ingredient", "Contains real honey"],
    whyScore: "The honey roasting process requires soybean oil, sugar, and maltodextrin. Plain peanuts are far superior — the added sweeteners and seed oil negate the nutritional benefits.",
    servingSize: "28g",
    nutriments: { "energy-kcal_100g": 536, "fat_100g": 42.9, "saturated-fat_100g": 7.1, "carbohydrates_100g": 28.6, "sugars_100g": 14.3, "sodium_100g": 0.179, "proteins_100g": 21.4 },
    certifications: [],
  imageUrl: "/manus-storage/honey-roasted-peanuts_f817e3cf.jpeg",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // JERKY & MEAT SNACKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "epic-beef-jerky",
    barcode: "0891627001018", upc: "0891627001018",
    name: "EPIC Beef Jerky — Sea Salt & Pepper",
    brand: "EPIC Provisions",
    category: "Jerky & Meat Snacks", tier: "elite", score: 91,
    ingredients: "100% Grass-Fed Beef, Sea Salt, Black Pepper.",
    concerns: ["High sodium per serving"],
    positives: ["100% grass-fed beef", "Only 3 clean ingredients", "No nitrates, no preservatives", "No seed oils", "High protein", "Paleo and Whole30 approved"],
    whyScore: "Exceptional jerky. Grass-fed beef with just salt and pepper — no nitrates, no artificial preservatives, no seed oils. One of the cleanest meat snacks available.",
    averagePrice: 3.49,
    servingSize: "28g",
    nutriments: { "energy-kcal_100g": 286, "fat_100g": 7.1, "saturated-fat_100g": 3.6, "carbohydrates_100g": 7.1, "sugars_100g": 3.6, "sodium_100g": 1.071, "proteins_100g": 50 },
    certifications: ["Certified Gluten-Free", "Paleo Certified", "Whole30 Approved"],
  imageUrl: "/manus-storage/epic-beef-jerky_f94ed0fb.png",
  },
  {
    id: "jack-links-original",
    barcode: "0017082875021", upc: "0017082875021",
    name: "Jack Link's Original Beef Jerky",
    brand: "Jack Link's",
    category: "Jerky & Meat Snacks", tier: "poor", score: 30,
    ingredients: "Beef, Water, Sugar, Salt, Soy Sauce (Water, Wheat, Soybeans, Salt), Vinegar, Flavorings, Sodium Nitrite.",
    concerns: ["Sodium nitrite — preservative linked to cancer risk", "Added sugar", "Soy sauce (wheat/soy allergens)", "Conventional beef — no grass-fed claims", "High sodium"],
    positives: ["High protein", "Low fat", "Widely available"],
    whyScore: "Sodium nitrite is a preservative that can form nitrosamines (carcinogens) when exposed to high heat. Conventional beef with added sugar. Better options exist.",
    servingSize: "28g",
    nutriments: { "energy-kcal_100g": 286, "fat_100g": 7.1, "saturated-fat_100g": 3.6, "carbohydrates_100g": 14.3, "sugars_100g": 10.7, "sodium_100g": 1.429, "proteins_100g": 50 },
    certifications: [],
  imageUrl: "/manus-storage/jack-links-original_00e8ea33.jpg",
  },
  {
    id: "chomps-beef-stick",
    barcode: "0860000000000", upc: "0860000000000",
    imageUrl: "https://i5.walmartimages.com/asr/1413a6ef-50c3-4bee-8f30-e7506a595d86.75452694ad16d8635869f720d4fdf2e0.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff",
    name: "Chomps Grass-Fed Beef Stick — Original",
    brand: "Chomps",
    category: "Jerky & Meat Snacks", tier: "elite", score: 94,
    ingredients: "Grass-Fed Beef, Water, Sea Salt, Organic Spices, Organic Garlic Powder, Organic Onion Powder, Organic Paprika, Celery Powder.",
    concerns: ["Celery powder contains natural nitrates (considered safer than synthetic)"],
    positives: ["100% grass-fed beef", "No synthetic nitrates", "No sugar added", "Whole30 Approved", "Paleo Certified", "Non-GMO Project Verified", "Gluten-free", "High protein, low calorie"],
    whyScore: "The best meat stick on the market. Grass-fed beef, organic spices, no added sugar, no synthetic nitrates. Celery powder provides natural preservation. Whole30 and Paleo approved.",
    averagePrice: 2.49,
    servingSize: "28g (1 stick)",
    nutriments: { "energy-kcal_100g": 179, "fat_100g": 7.1, "saturated-fat_100g": 3.6, "carbohydrates_100g": 0, "sugars_100g": 0, "sodium_100g": 0.893, "proteins_100g": 28.6 },
    certifications: ["Whole30 Approved", "Paleo Certified", "Non-GMO Project Verified", "Certified Gluten-Free"],
  },
  {
    id: "slim-jim-original",
    barcode: "0026200462001", upc: "0026200462001",
    name: "Slim Jim Original Smoked Snack Stick",
    brand: "Slim Jim (ConAgra)",
    category: "Jerky & Meat Snacks", tier: "avoid", score: 8,
    ingredients: "Beef, Pork, Mechanically Separated Chicken, Water, Corn Syrup, Salt, Spices, Dextrose, Paprika, Hydrolyzed Soy Protein, Lactic Acid Starter Culture, Sodium Nitrite.",
    concerns: ["Mechanically separated chicken — lowest quality meat", "Corn syrup", "Hydrolyzed soy protein — MSG precursor", "Sodium nitrite", "Dextrose added sugar", "Ultra-processed meat product"],
    positives: ["High protein content"],
    whyScore: "Mechanically separated chicken (paste-like byproduct), corn syrup, hydrolyzed soy protein (hidden MSG), and sodium nitrite. One of the worst processed meat snacks available.",
    averagePrice: 1.49,
    servingSize: "28g (1 stick)",
    nutriments: { "energy-kcal_100g": 464, "fat_100g": 39.3, "saturated-fat_100g": 14.3, "carbohydrates_100g": 10.7, "sugars_100g": 7.1, "sodium_100g": 1.607, "proteins_100g": 21.4 },
    certifications: [],
  imageUrl: "/manus-storage/slim-jim-original_1c02eed2.jpeg",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TRAIL MIX & DRIED FRUIT
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "sun-maid-raisins",
    barcode: "0041143000000", upc: "0041143000000",
    name: "Sun-Maid California Sun-Dried Raisins",
    brand: "Sun-Maid",
    category: "Trail Mix & Dried Fruit", tier: "average", score: 52,
    ingredients: "Raisins.",
    concerns: ["Very high natural sugar concentration (dried)", "High glycemic index", "Conventional grapes — pesticide residue risk", "Easy to overconsume"],
    positives: ["Single ingredient", "Iron, potassium, antioxidants", "Natural sugar only", "No additives"],
    whyScore: "Single ingredient is good but conventional grapes are on the EWG Dirty Dozen. Drying concentrates both nutrients and sugars. Buy organic raisins when possible.",
    averagePrice: 3.49,
    servingSize: "43g (1/4 cup)",
    nutriments: { "energy-kcal_100g": 299, "fat_100g": 0.5, "saturated-fat_100g": 0, "carbohydrates_100g": 79.2, "sugars_100g": 59.2, "sodium_100g": 0.011, "proteins_100g": 3.1 },
    certifications: [],
  imageUrl: "/manus-storage/sun-maid-raisins_a2a120a6.png",
  },
  {
    id: "trail-mix-kirkland",
    barcode: "0096619024476", upc: "0096619024476",
    name: "Kirkland Signature Trail Mix",
    brand: "Kirkland (Costco)",
    category: "Trail Mix & Dried Fruit", tier: "good", score: 65,
    ingredients: "Cashews, Almonds, Macadamia Nuts, Dried Cranberries (Cranberries, Sugar, Sunflower Oil), Dark Chocolate Chips (Sugar, Chocolate Liquor, Cocoa Butter, Vanilla Extract, Soy Lecithin), Pecans.",
    concerns: ["Dried cranberries contain added sugar", "Sunflower oil in cranberries", "Soy lecithin in chocolate chips", "High calorie density"],
    positives: ["Premium whole nuts", "Dark chocolate chips", "Good protein and healthy fats", "No artificial additives"],
    whyScore: "Quality nuts with the main concern being added sugar and sunflower oil in the dried cranberries. Overall a good trail mix — the nuts are the star.",
    averagePrice: 14.99,
    servingSize: "30g",
    nutriments: { "energy-kcal_100g": 533, "fat_100g": 40, "saturated-fat_100g": 8.3, "carbohydrates_100g": 36.7, "sugars_100g": 20, "sodium_100g": 0.067, "proteins_100g": 13.3 },
    certifications: [],
  imageUrl: "/manus-storage/trail-mix-kirkland_bb3a128c.jpeg",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PRETZELS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "snyder-of-hanover-pretzels",
    barcode: "0077975090015", upc: "0077975090015",
    name: "Snyder's of Hanover Mini Pretzels",
    brand: "Snyder's of Hanover (Campbell's)",
    category: "Pretzels", tier: "poor", score: 30,
    ingredients: "Enriched Wheat Flour (Flour, Niacin, Reduced Iron, Thiamine Mononitrate, Riboflavin, Folic Acid), Water, Corn Syrup, Salt, Vegetable Oil (Soybean and/or Canola Oil), Yeast, Baking Soda, Ammonium Bicarbonate.",
    concerns: ["Enriched refined flour — stripped of nutrients", "Corn syrup", "Soybean and canola seed oils", "Ammonium bicarbonate — chemical leavener"],
    positives: ["Low fat", "Low calorie snack option"],
    whyScore: "Enriched refined flour, corn syrup, and seed oils. Pretzels are nutritionally empty — mostly refined carbs with minimal fiber or protein.",
    servingSize: "28g (about 18 pretzels)",
    nutriments: { "energy-kcal_100g": 375, "fat_100g": 3.6, "saturated-fat_100g": 0.4, "carbohydrates_100g": 78.6, "sugars_100g": 3.6, "sodium_100g": 1.071, "proteins_100g": 10.7 },
    certifications: [],
  imageUrl: "/manus-storage/snyder-of-hanover-pretzels_b6236b70.jpeg",
  },
  {
    id: "quinn-pretzels",
    barcode: "0852888004013", upc: "0852888004013",
    name: "Quinn Snacks Sea Salt Pretzels",
    brand: "Quinn Snacks",
    category: "Pretzels", tier: "good", score: 68,
    ingredients: "Whole Grain Wheat Flour, Water, Sea Salt, Sunflower Oil, Yeast, Baking Soda.",
    concerns: ["Sunflower oil — seed oil", "Refined carbs even with whole grain"],
    positives: ["Whole grain wheat flour", "Non-GMO Project Verified", "Gluten-free options available", "No artificial additives", "Simpler ingredient list than conventional pretzels"],
    whyScore: "Significantly cleaner than conventional pretzels. Whole grain flour and no corn syrup. Sunflower oil is still a concern but the overall profile is much better.",
    averagePrice: 4.99,
    servingSize: "28g",
    nutriments: { "energy-kcal_100g": 375, "fat_100g": 5.4, "saturated-fat_100g": 0.7, "carbohydrates_100g": 75, "sugars_100g": 1.8, "sodium_100g": 0.893, "proteins_100g": 10.7 },
    certifications: ["Non-GMO Project Verified"],
  imageUrl: "/manus-storage/quinn-pretzels_54176d31.jpg",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // RICE CAKES & PUFFED SNACKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "quaker-rice-cakes-plain",
    barcode: "0030000315002", upc: "0030000315002",
    name: "Quaker Lightly Salted Rice Cakes",
    brand: "Quaker (PepsiCo)",
    category: "Rice Cakes & Puffed Snacks", tier: "average", score: 55,
    ingredients: "Whole Grain Brown Rice, Salt.",
    concerns: ["High glycemic index — spikes blood sugar quickly", "Low in protein and fiber", "White rice base in flavored varieties"],
    positives: ["Only 2 ingredients", "Whole grain brown rice", "Low calorie", "Gluten-free", "No seed oils or artificial additives"],
    whyScore: "Simple and clean but nutritionally limited. Brown rice cakes are a low-calorie option but spike blood sugar quickly due to high glycemic index. Best paired with protein.",
    averagePrice: 3.49,
    servingSize: "9g (1 cake)",
    nutriments: { "energy-kcal_100g": 389, "fat_100g": 2.8, "saturated-fat_100g": 0.6, "carbohydrates_100g": 83.3, "sugars_100g": 0, "sodium_100g": 0.278, "proteins_100g": 8.3 },
    certifications: ["Certified Gluten-Free"],
  imageUrl: "/manus-storage/quaker-rice-cakes-plain_5eaf2647.jpeg",
  },
  {
    id: "lundberg-rice-cakes",
    barcode: "0073416050019", upc: "0073416050019",
    name: "Lundberg Organic Brown Rice Cakes — Lightly Salted",
    brand: "Lundberg Family Farms",
    category: "Rice Cakes & Puffed Snacks", tier: "good", score: 72,
    ingredients: "Organic Whole Grain Brown Rice, Sea Salt.",
    concerns: ["High glycemic index", "Low protein and fiber"],
    positives: ["USDA Organic certified", "Only 2 clean ingredients", "Non-GMO Project Verified", "No seed oils", "Gluten-free"],
    whyScore: "Organic brown rice with sea salt — the cleanest rice cake option. Organic certification eliminates pesticide concerns. Still high glycemic but a clean whole-grain snack.",
    servingSize: "18g (2 cakes)",
    nutriments: { "energy-kcal_100g": 389, "fat_100g": 2.8, "saturated-fat_100g": 0.6, "carbohydrates_100g": 83.3, "sugars_100g": 0, "sodium_100g": 0.278, "proteins_100g": 8.3 },
    certifications: ["USDA Organic", "Non-GMO Project Verified", "Certified Gluten-Free"],
  imageUrl: "/manus-storage/lundberg-rice-cakes_c61dff0a.jpg",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CHEESE SNACKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "cheetos-crunchy",
    barcode: "0028400090032", upc: "0028400090032",
    imageUrl: "https://images.openfoodfacts.org/images/products/002/840/009/0032/front_en.3.200.jpg",
    name: "Cheetos Crunchy",
    brand: "Cheetos (PepsiCo)",
    category: "Cheese Snacks", tier: "avoid", score: 10,
    ingredients: "Enriched Corn Meal (Corn Meal, Ferrous Sulfate, Niacin, Thiamine Mononitrate, Riboflavin, Folic Acid), Vegetable Oil (Corn, Canola, and/or Sunflower Oil), Cheddar Cheese (Milk, Cheese Cultures, Salt, Enzymes), Whey, Salt, Maltodextrin, Natural and Artificial Flavor, Monosodium Glutamate, Lactic Acid, Citric Acid, Artificial Color (Yellow 6).",
    concerns: ["Corn, canola, sunflower seed oils", "Monosodium glutamate (MSG)", "Yellow 6 artificial dye", "Maltodextrin", "Artificial flavor", "Ultra-processed NOVA Group 4"],
    positives: ["Contains some real cheese"],
    whyScore: "Three seed oils, MSG, artificial dye, and maltodextrin. Engineered to be hyper-palatable and override satiety. The cheese flavor is mostly artificial.",
    averagePrice: 4.29,
    servingSize: "28g (about 21 pieces)",
    nutriments: { "energy-kcal_100g": 536, "fat_100g": 33.9, "saturated-fat_100g": 5.4, "carbohydrates_100g": 55.4, "sugars_100g": 0.9, "sodium_100g": 0.893, "proteins_100g": 7.1 },
    certifications: [],
  },
  {
    id: "whisps-cheese-crisps",
    barcode: "0072058630019", upc: "0072058630019",
    name: "Whisps Cheddar Cheese Crisps",
    brand: "Whisps",
    category: "Cheese Snacks", tier: "elite", score: 88,
    ingredients: "Cheddar Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes).",
    concerns: ["High sodium", "High in saturated fat"],
    positives: ["Single ingredient — 100% real cheese", "No seed oils", "No artificial additives", "High protein (9g per serving)", "Keto and grain-free", "Natural source of calcium"],
    whyScore: "One ingredient: cheddar cheese. Nothing else. High protein, zero carbs, no seed oils. The saturated fat in cheese is not the health concern it was once thought to be.",
    averagePrice: 4.99,
    servingSize: "23g",
    nutriments: { "energy-kcal_100g": 522, "fat_100g": 34.8, "saturated-fat_100g": 21.7, "carbohydrates_100g": 4.3, "sugars_100g": 0, "sodium_100g": 1.304, "proteins_100g": 39.1 },
    certifications: ["Certified Gluten-Free"],
  imageUrl: "/manus-storage/whisps-cheese-crisps_33e4a9fa.png",
  },
  {
    id: "babybel-original",
    barcode: "0070882001000", upc: "0070882001000",
    name: "Babybel Original Mini Cheese",
    brand: "Babybel (Bel Group)",
    category: "Cheese Snacks", tier: "good", score: 78,
    ingredients: "Pasteurized Milk, Cheese Cultures, Salt, Enzymes.",
    concerns: ["Conventional dairy — no grass-fed claims", "High in sodium"],
    positives: ["4 clean ingredients", "No seed oils", "No artificial additives", "Portion-controlled", "Good protein and calcium source", "Natural whole food"],
    whyScore: "Clean real cheese with 4 simple ingredients. Portion-controlled format prevents overconsumption. No seed oils or artificial additives. Would score higher with grass-fed milk.",
    servingSize: "21g (1 wheel)",
    nutriments: { "energy-kcal_100g": 333, "fat_100g": 23.8, "saturated-fat_100g": 16.7, "carbohydrates_100g": 0, "sugars_100g": 0, "sodium_100g": 0.714, "proteins_100g": 28.6 },
    certifications: [],
  imageUrl: "/manus-storage/babybel-original_5dc7e13e.jpeg",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FRUIT SNACKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "welchs-fruit-snacks",
    barcode: "0034856300016", upc: "0034856300016",
    imageUrl: "https://images.openfoodfacts.org/images/products/003/485/600/8187/front_en.96.200.jpg",
    name: "Welch's Mixed Fruit Snacks",
    brand: "Welch's",
    category: "Fruit Snacks", tier: "avoid", score: 12,
    ingredients: "Fruit Puree (Grape, Peach, Strawberry, Raspberry, Orange), Corn Syrup, Sugar, Modified Corn Starch, Gelatin, Citric Acid, Lactic Acid, Natural and Artificial Flavor, Ascorbic Acid (Vitamin C), Alpha Tocopherol Acetate (Vitamin E), Vitamin A Palmitate, Colors (Red 40, Yellow 5, Blue 1).",
    concerns: ["Corn syrup as second ingredient", "Red 40, Yellow 5, Blue 1 artificial dyes", "Artificial flavor", "Modified corn starch", "Gelatin (not vegan)", "Marketed to children with artificial dyes"],
    positives: ["Contains real fruit puree", "Fortified with vitamins"],
    whyScore: "Marketed as fruit snacks but corn syrup is the second ingredient. Three artificial dyes and artificial flavors. The vitamin fortification doesn't offset the harmful additives.",
    servingSize: "25g (1 pouch)",
    nutriments: { "energy-kcal_100g": 320, "fat_100g": 0, "saturated-fat_100g": 0, "carbohydrates_100g": 80, "sugars_100g": 48, "sodium_100g": 0.04, "proteins_100g": 0 },
    certifications: [],
  },
  {
    id: "stretch-island-fruit-strips",
    barcode: "0016229100010", upc: "0016229100010",
    name: "Stretch Island Original Fruit Strips — Strawberry",
    brand: "Stretch Island Fruit Co.",
    category: "Fruit Snacks", tier: "good", score: 65,
    ingredients: "Strawberry Puree Concentrate, Pear Juice Concentrate, Grape Juice Concentrate.",
    concerns: ["Concentrated fruit = high sugar density", "No fiber (juices)", "High natural sugar"],
    positives: ["Only real fruit ingredients", "No artificial colors or flavors", "No added sugar", "Non-GMO Project Verified", "Gluten-free"],
    whyScore: "Genuinely made from real fruit with no artificial additives. The concentration process removes fiber and increases sugar density, but the ingredients are clean.",
    servingSize: "14g (1 strip)",
    nutriments: { "energy-kcal_100g": 286, "fat_100g": 0, "saturated-fat_100g": 0, "carbohydrates_100g": 71.4, "sugars_100g": 57.1, "sodium_100g": 0, "proteins_100g": 0 },
    certifications: ["Non-GMO Project Verified", "Certified Gluten-Free"],
  imageUrl: "/manus-storage/stretch-island-fruit-strips_24cbac89.jpg",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // VEGGIE SNACKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "bare-apple-chips",
    barcode: "0852767001003", upc: "0852767001003",
    name: "Bare Baked Crunchy Apple Chips — Fuji & Reds",
    brand: "Bare Snacks",
    category: "Veggie Snacks", tier: "elite", score: 90,
    ingredients: "Apples.",
    concerns: ["High natural sugar from apples", "Conventional apples — pesticide risk (EWG Dirty Dozen)"],
    positives: ["Single ingredient — 100% real apples", "No seed oils", "No added sugar", "No artificial additives", "Baked not fried", "Good fiber source"],
    whyScore: "One ingredient: apples. Baked to a crisp with no oil, no sugar, no additives. The only concern is conventional apple pesticide residue — buy organic version when available.",
    averagePrice: 4.99,
    servingSize: "14g",
    nutriments: { "energy-kcal_100g": 357, "fat_100g": 0, "saturated-fat_100g": 0, "carbohydrates_100g": 85.7, "sugars_100g": 71.4, "sodium_100g": 0, "proteins_100g": 0 },
    certifications: ["Certified Gluten-Free"],
  imageUrl: "/manus-storage/bare-apple-chips_2da85f22.jpg",
  },
  {
    id: "terra-chips-original",
    barcode: "0021908100013", upc: "0021908100013",
    name: "Terra Original Chips",
    brand: "Terra",
    category: "Veggie Snacks", tier: "average", score: 50,
    ingredients: "Taro, Batata, Yuca, Sweet Potato, Ruby Taro, Parsnip, Canola Oil and/or Safflower Oil, Sea Salt.",
    concerns: ["Canola and safflower seed oils — high omega-6", "Seed oils heated during frying"],
    positives: ["Real vegetable variety (6 types)", "No artificial additives", "Non-GMO Project Verified", "Interesting nutrient diversity"],
    whyScore: "Genuinely diverse vegetables but fried in canola/safflower seed oils. The vegetable variety is a real positive — taro, yuca, and parsnip offer different nutrients than potato chips.",
    averagePrice: 4.99,
    servingSize: "28g",
    nutriments: { "energy-kcal_100g": 536, "fat_100g": 28.6, "saturated-fat_100g": 3.6, "carbohydrates_100g": 64.3, "sugars_100g": 3.6, "sodium_100g": 0.357, "proteins_100g": 3.6 },
    certifications: ["Non-GMO Project Verified"],
  imageUrl: "/manus-storage/terra-chips-original_ce6d7707.jpg",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PROTEIN SNACKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "hard-boiled-eggs-snack",
    barcode: "0070784000000", upc: "0070784000000",
    imageUrl: "https://images.openfoodfacts.org/images/products/081/565/200/2162/front_en.23.200.jpg",
    name: "Pete and Gerry's Organic Hard-Boiled Eggs",
    brand: "Pete and Gerry's",
    category: "Protein Snacks", tier: "elite", score: 97,
    ingredients: "Organic Free-Range Eggs.",
    concerns: ["High cholesterol (dietary cholesterol has minimal impact on blood cholesterol for most people)"],
    positives: ["Single ingredient — organic free-range eggs", "Complete protein with all essential amino acids", "Rich in choline, B12, vitamin D, selenium", "No seed oils, no additives", "Pasture-raised"],
    whyScore: "One of nature's most perfect foods. Complete protein, rich in choline (critical for brain health), vitamin D, B12, and selenium. Organic free-range ensures better welfare and nutrient profile.",
    servingSize: "50g (1 egg)",
    nutriments: { "energy-kcal_100g": 155, "fat_100g": 10.6, "saturated-fat_100g": 3.3, "carbohydrates_100g": 1.1, "sugars_100g": 1.1, "sodium_100g": 0.124, "proteins_100g": 12.6 },
    certifications: ["USDA Organic", "Certified Humane", "Non-GMO Project Verified"],
  },
  {
    id: "siggi-skyr-plain",
    barcode: "0898248001001", upc: "0898248001001",
    name: "Siggi's Plain Icelandic Skyr",
    brand: "Siggi's",
    category: "Protein Snacks", tier: "elite", score: 92,
    ingredients: "Skim Milk, Live Active Cultures (S. Thermophilus, L. Bulgaricus, L. Acidophilus, Bifidus, L. Paracasei).",
    concerns: ["Skim milk — lower fat than whole milk skyr", "Conventional dairy"],
    positives: ["Only 2 ingredients", "17g protein per serving", "No added sugar", "Live probiotic cultures", "No artificial additives", "Icelandic straining process removes whey"],
    whyScore: "Exceptional protein snack. Two clean ingredients, 17g protein, zero added sugar, and live probiotic cultures for gut health. Icelandic skyr is one of the most nutrient-dense dairy products.",
    servingSize: "150g (5.3 oz)",
    nutriments: { "energy-kcal_100g": 63, "fat_100g": 0.3, "saturated-fat_100g": 0.2, "carbohydrates_100g": 4, "sugars_100g": 4, "sodium_100g": 0.047, "proteins_100g": 11.3 },
    certifications: ["Certified Gluten-Free"],
  imageUrl: "/manus-storage/siggi-skyr-plain_006d22e7.jpg",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DIPS & SPREADS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "sabra-classic-hummus",
    barcode: "0040822011068", upc: "0040822011068",
    imageUrl: "https://images.openfoodfacts.org/images/products/004/082/201/1143/front_en.66.200.jpg",
    name: "Sabra Classic Hummus",
    brand: "Sabra",
    category: "Dips & Spreads", tier: "poor", score: 35,
    ingredients: "Cooked Chickpeas, Water, Tahini (Ground Sesame), Soybean Oil, Garlic, Salt, Citric Acid, Potassium Sorbate, Natural Flavors.",
    concerns: ["Soybean oil — seed oil as third ingredient", "Potassium sorbate — preservative", "Natural flavors — vague", "Soybean oil replaces traditional olive oil"],
    positives: ["Real chickpeas as primary ingredient", "Contains tahini", "Good protein and fiber"],
    whyScore: "Traditional hummus uses olive oil — Sabra substitutes soybean oil to cut costs. This fundamentally changes the fat profile from healthy to inflammatory. Make your own or buy brands using olive oil.",
    averagePrice: 4.99,
    servingSize: "28g (2 tbsp)",
    nutriments: { "energy-kcal_100g": 179, "fat_100g": 10.7, "saturated-fat_100g": 1.4, "carbohydrates_100g": 14.3, "sugars_100g": 0, "sodium_100g": 0.357, "proteins_100g": 7.1 },
    certifications: [],
  },
  {
    id: "hope-hummus",
    barcode: "0852595003009", upc: "0852595003009",
    name: "Hope Foods Original Recipe Hummus",
    brand: "Hope Foods",
    category: "Dips & Spreads", tier: "elite", score: 88,
    ingredients: "Organic Chickpeas, Organic Tahini, Organic Extra Virgin Olive Oil, Organic Lemon Juice, Organic Garlic, Sea Salt, Organic Cumin.",
    concerns: ["High calorie density"],
    positives: ["All organic ingredients", "Extra virgin olive oil — traditional and healthy", "No seed oils", "No preservatives", "No artificial additives", "USDA Organic"],
    whyScore: "Traditional hummus made the right way — with extra virgin olive oil instead of soybean oil. All organic ingredients, no preservatives. This is what hummus should be.",
    averagePrice: 5.99,
    servingSize: "28g (2 tbsp)",
    nutriments: { "energy-kcal_100g": 214, "fat_100g": 14.3, "saturated-fat_100g": 1.8, "carbohydrates_100g": 14.3, "sugars_100g": 0, "sodium_100g": 0.286, "proteins_100g": 7.1 },
    certifications: ["USDA Organic", "Non-GMO Project Verified", "Certified Gluten-Free"],
  imageUrl: "/manus-storage/hope-hummus_7ec564b3.jpg",
  },
  {
    id: "justin-almond-butter",
    barcode: "0894455000000", upc: "0894455000000",
    imageUrl: "https://images.openfoodfacts.org/images/products/344/986/524/0898/front_fr.81.200.jpg",
    name: "Justin's Classic Almond Butter",
    brand: "Justin's",
    category: "Dips & Spreads", tier: "good", score: 75,
    ingredients: "Dry Roasted Almonds, Palm Oil.",
    concerns: ["Palm oil — deforestation concerns, though Justin's uses RSPO certified palm", "Palm oil adds saturated fat"],
    positives: ["Only 2 ingredients", "No added sugar", "No seed oils", "RSPO certified palm oil", "Non-GMO Project Verified", "Good protein and healthy fat source"],
    whyScore: "Clean almond butter with just two ingredients. Palm oil is used to prevent separation — Justin's uses RSPO certified sustainable palm. No added sugar or seed oils.",
    servingSize: "32g (2 tbsp)",
    nutriments: { "energy-kcal_100g": 594, "fat_100g": 53.1, "saturated-fat_100g": 6.3, "carbohydrates_100g": 18.8, "sugars_100g": 3.1, "sodium_100g": 0, "proteins_100g": 21.9 },
    certifications: ["Non-GMO Project Verified", "Certified Gluten-Free"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ICE CREAM & FROZEN
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "haagen-dazs-vanilla",
    barcode: "0074570000000", upc: "0074570000000",
    name: "Häagen-Dazs Vanilla Ice Cream",
    brand: "Häagen-Dazs (Nestlé)",
    category: "Ice Cream & Frozen", tier: "good", score: 70,
    ingredients: "Cream, Skim Milk, Sugar, Egg Yolks, Vanilla Extract.",
    concerns: ["High sugar content", "High calorie density", "Conventional dairy"],
    positives: ["Only 5 clean ingredients", "Real vanilla extract", "No seed oils", "No artificial flavors or colors", "No stabilizers or emulsifiers", "Real egg yolks"],
    whyScore: "One of the cleanest mainstream ice creams. Five recognizable ingredients, real vanilla, no artificial additives. The sugar content is the main concern for regular consumption.",
    servingSize: "106g (2/3 cup)",
    nutriments: { "energy-kcal_100g": 250, "fat_100g": 16, "saturated-fat_100g": 10, "carbohydrates_100g": 23, "sugars_100g": 21, "sodium_100g": 0.075, "proteins_100g": 4 },
    certifications: [],
  imageUrl: "/manus-storage/haagen-dazs-vanilla_cf06b967.webp",
  },
  {
    id: "halo-top-vanilla",
    barcode: "0855710006001", upc: "0855710006001",
    name: "Halo Top Vanilla Bean Ice Cream",
    brand: "Halo Top",
    category: "Ice Cream & Frozen", tier: "average", score: 45,
    ingredients: "Skim Milk, Eggs, Erythritol, Prebiotic Fiber (Chicory Root), Milk Protein Concentrate, Cream, Organic Cane Sugar, Vegetable Glycerin, Sea Salt, Organic Carob Gum, Organic Guar Gum, Organic Stevia Leaf Extract, Vanilla Extract.",
    concerns: ["Erythritol — sugar alcohol, digestive issues, recent cardiovascular concern studies", "Milk protein concentrate — highly processed", "Multiple gums and stabilizers", "Vegetable glycerin — processed additive"],
    positives: ["Low calorie (70 cal/serving)", "Good protein content", "Stevia as sweetener", "Real vanilla extract"],
    whyScore: "Low calorie but achieves this through heavy processing — erythritol, protein concentrates, and multiple stabilizers. Recent studies link erythritol to cardiovascular risk. Häagen-Dazs is a better choice.",
    servingSize: "85g (1/2 cup)",
    nutriments: { "energy-kcal_100g": 82, "fat_100g": 2.4, "saturated-fat_100g": 1.2, "carbohydrates_100g": 12.9, "sugars_100g": 4.7, "sodium_100g": 0.141, "proteins_100g": 5.9 },
    certifications: ["Certified Gluten-Free"],
  imageUrl: "/manus-storage/halo-top-vanilla_37e96a33.jpg",
  },
  {
    id: "ben-jerrys-chocolate-chip-cookie",
    barcode: "0076840100116", upc: "0076840100116",
    name: "Ben & Jerry's Chocolate Chip Cookie Dough",
    brand: "Ben & Jerry's (Unilever)",
    category: "Ice Cream & Frozen", tier: "poor", score: 28,
    ingredients: "Cream, Skim Milk, Liquid Sugar, Water, Sugar, Wheat Flour, Chocolate Chips (Sugar, Chocolate Liquor, Cocoa Butter, Soy Lecithin, Vanilla Extract), Butter, Brown Sugar, Eggs, Corn Syrup, Soybean Oil, Guar Gum, Carrageenan, Natural Flavor.",
    concerns: ["Corn syrup", "Soybean oil", "Carrageenan — inflammatory gut irritant", "Multiple added sugars", "Guar gum stabilizer"],
    positives: ["Real cream and eggs", "Real vanilla extract", "Non-GMO Project Verified", "Fairtrade certified"],
    whyScore: "Corn syrup, soybean oil, and carrageenan (linked to gut inflammation) in ice cream. Despite Fairtrade and Non-GMO certifications, the ingredient quality is poor.",
    servingSize: "106g (2/3 cup)",
    nutriments: { "energy-kcal_100g": 274, "fat_100g": 14.2, "saturated-fat_100g": 8.5, "carbohydrates_100g": 35.8, "sugars_100g": 28.3, "sodium_100g": 0.094, "proteins_100g": 3.8 },
    certifications: ["Non-GMO Project Verified", "Fairtrade Certified"],
  imageUrl: "/manus-storage/ben-jerrys-chocolate-chip-cookie_adffaf09.jpeg",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PUDDING & GELATIN
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "jello-strawberry",
    barcode: "0043000200063", upc: "0043000200063",
    imageUrl: "https://i5.walmartimages.com/asr/3658082d-82bc-4f72-b9ea-dbc2de2d402c.e3335318b012e36e6189eebf0d195f50.jpeg?odnHeight=450&odnWidth=450&odnBg=ffffff",
    name: "Jell-O Strawberry Gelatin Dessert",
    brand: "Jell-O (Kraft Heinz)",
    category: "Pudding & Gelatin", tier: "avoid", score: 8,
    ingredients: "Sugar, Gelatin, Adipic Acid, Artificial Flavor, Disodium Phosphate, Sodium Citrate, Fumaric Acid, Red 40.",
    concerns: ["Red 40 artificial dye — linked to hyperactivity", "Artificial flavor", "Adipic acid — synthetic food acid", "No real fruit whatsoever", "Pure sugar and artificial chemicals"],
    positives: ["Low calorie", "Contains gelatin (collagen)"],
    whyScore: "Essentially sugar, artificial flavor, and Red 40 dye. Zero real fruit. The gelatin is the only potentially beneficial ingredient. One of the most artificial desserts available.",
    servingSize: "21g dry mix",
    nutriments: { "energy-kcal_100g": 381, "fat_100g": 0, "saturated-fat_100g": 0, "carbohydrates_100g": 90.5, "sugars_100g": 85.7, "sodium_100g": 0.476, "proteins_100g": 9.5 },
    certifications: [],
  },
];

// ─── Database stats ────────────────────────────────────────────────────────────
export const SNACK_DB_STATS = {
  total: ALL_SNACKS.length,
  elite: ALL_SNACKS.filter((s) => s.tier === "elite").length,
  good: ALL_SNACKS.filter((s) => s.tier === "good").length,
  average: ALL_SNACKS.filter((s) => s.tier === "average").length,
  poor: ALL_SNACKS.filter((s) => s.tier === "poor").length,
  avoid: ALL_SNACKS.filter((s) => s.tier === "avoid").length,
  categories: SNACK_CATEGORIES.length,
};
