/**
 * EatVera — Grocery Store Ratings Database
 * Research-based ratings for major US grocery chains.
 * Scores based on: organic selection, meat quality standards, seed oil
 * avoidance, transparency, sourcing practices, private label quality,
 * and overall food quality commitment.
 */

export type StoreCategory = "Premium" | "Natural/Organic" | "Conventional" | "Warehouse" | "Discount" | "Regional";
export type StoreTier = "elite" | "excellent" | "good" | "fair" | "poor" | "avoid";

export interface StoreRating {
  id: string;
  name: string;
  emoji: string;
  logoUrl?: string;
  category: StoreCategory;
  tier: StoreTier;
  overallScore: number;
  scores: {
    meatQuality: number;
    organicSelection: number;
    ingredientTransparency: number;
    seedOilAvoidance: number;
    privateLabelQuality: number;
    valueForQuality: number;
    sourcingEthics: number;
  };
  tagline: string;
  pros: string[];
  cons: string[];
  bestFor: string[];
  avoidAt: string[];
  meatNotes: string;
  organicNotes: string;
  overallVerdict: string;
  storeCount: string;
  ownership: string;
}

export const STORE_TIER_CONFIG: Record<StoreTier, { label: string; color: string; bg: string }> = {
  elite:     { label: "Elite",     color: "#145A3A", bg: "#F0FAF2" },
  excellent: { label: "Excellent", color: "#3FA34D", bg: "#DCF4DF" },
  good:      { label: "Good",      color: "#4ade80", bg: "#f0fdf4" },
  fair:      { label: "Fair",      color: "#d97706", bg: "#fffbf0" },
  poor:      { label: "Poor",      color: "#ea580c", bg: "#fff7ed" },
  avoid:     { label: "Avoid",     color: "#dc2626", bg: "#fff5f5" },
};

export const ALL_STORES: StoreRating[] = [
  {
    id: "whole-foods",
    name: "Whole Foods Market",
    emoji: "🌿",
    logoUrl: "/manus-storage/whole-foods_6b8fbebc.png",
    category: "Premium",
    tier: "excellent",
    overallScore: 84,
    scores: {
      meatQuality: 88,
      organicSelection: 95,
      ingredientTransparency: 85,
      seedOilAvoidance: 72,
      privateLabelQuality: 82,
      valueForQuality: 55,
      sourcingEthics: 88,
    },
    tagline: "Best organic selection, but Amazon ownership raises concerns",
    pros: [
      "Largest organic produce selection in the US",
      "5-Step Animal Welfare Rating for all meat",
      "No artificial colors, flavors, or preservatives in store brand",
      "Extensive grass-fed and pasture-raised meat options",
      "Transparent sourcing — most products list farm of origin",
      "No high-fructose corn syrup in any products",
    ],
    cons: [
      "Owned by Amazon since 2017 — quality standards have reportedly declined",
      "Still sells many products with seed oils (canola, sunflower)",
      "Very expensive — 'Whole Paycheck' reputation is earned",
      "Some 'natural' products still contain questionable ingredients",
      "Prepared foods section uses seed oils extensively",
    ],
    bestFor: ["Organic produce", "Grass-fed beef", "Pasture-raised eggs", "Clean supplements", "Wild-caught seafood"],
    avoidAt: ["Prepared foods (seed oil heavy)", "Conventional packaged snacks", "Anything labeled 'natural' without organic certification"],
    meatNotes: "All beef is rated under the Global Animal Partnership (GAP) 5-Step program. Step 1-2 is conventional CAFO; Step 4-5+ is pasture-raised. Look for Step 4+ for best quality. Carries Force of Nature, Niman Ranch, and other premium brands.",
    organicNotes: "Best organic produce selection of any mainstream chain. USDA Certified Organic for all labeled products. Carries 365 Organic private label at slightly lower prices.",
    overallVerdict: "Still the best mainstream option for clean eating, despite Amazon's influence. The 5-Step meat rating system and no-artificial-ingredients policy make it a reliable choice. Shop the perimeter and stick to organic produce and high-step meats.",
    storeCount: "500+ stores (US)",
    ownership: "Amazon (since 2017)",
  },
  {
    id: "sprouts",
    name: "Sprouts Farmers Market",
    emoji: "🌱",
    logoUrl: "/manus-storage/sprouts_3a4f6b0b.png",
    category: "Natural/Organic",
    tier: "excellent",
    overallScore: 82,
    scores: {
      meatQuality: 80,
      organicSelection: 88,
      ingredientTransparency: 82,
      seedOilAvoidance: 75,
      privateLabelQuality: 78,
      valueForQuality: 80,
      sourcingEthics: 82,
    },
    tagline: "Best value for organic and natural foods",
    pros: [
      "Significantly cheaper than Whole Foods for similar quality",
      "Large bulk section for nuts, seeds, and grains",
      "Good selection of grass-fed and pasture-raised meats",
      "Weekly sales make organic produce very affordable",
      "Extensive supplement and natural health section",
      "No artificial colors or flavors in store brand",
    ],
    cons: [
      "Smaller store footprint — less selection than Whole Foods",
      "Meat quality ratings less transparent than Whole Foods",
      "Some conventional products with seed oils",
      "Not all 'natural' products are organic",
    ],
    bestFor: ["Budget organic produce", "Bulk nuts and seeds", "Natural supplements", "Grass-fed meats on sale"],
    avoidAt: ["Conventional packaged snacks", "Store-brand items without organic certification"],
    meatNotes: "Good selection of grass-fed and pasture-raised options. Carries many of the same premium brands as Whole Foods at slightly lower prices. Check labels carefully — not all meat is pasture-raised.",
    organicNotes: "Strong organic produce section with competitive pricing. Weekly organic produce sales are excellent value. Bulk section is a standout.",
    overallVerdict: "The best value alternative to Whole Foods. If you're on a budget but want to eat clean, Sprouts is your best option. The weekly sales on organic produce are exceptional.",
    storeCount: "380+ stores (US)",
    ownership: "Publicly traded (SFM)",
  },
  {
    id: "trader-joes",
    name: "Trader Joe's",
    emoji: "🛒",
    logoUrl: "/manus-storage/trader-joes_8543f604.png",
    category: "Natural/Organic",
    tier: "good",
    overallScore: 72,
    scores: {
      meatQuality: 68,
      organicSelection: 75,
      ingredientTransparency: 70,
      seedOilAvoidance: 60,
      privateLabelQuality: 78,
      valueForQuality: 88,
      sourcingEthics: 70,
    },
    tagline: "Good value with hidden seed oil traps",
    pros: [
      "Excellent price-to-quality ratio",
      "No artificial colors, flavors, or preservatives in TJ's brand",
      "Good organic produce selection at fair prices",
      "Interesting international and specialty products",
      "No MSG in any products",
      "No partially hydrogenated oils (trans fats)",
    ],
    cons: [
      "Many products use canola, sunflower, and soybean oils",
      "Meat quality is inconsistent — not all is grass-fed",
      "Limited transparency on meat sourcing",
      "Frozen meals often contain seed oils",
      "No in-store butcher — pre-packaged only",
      "Limited selection compared to larger stores",
    ],
    bestFor: ["Organic frozen vegetables", "Nuts and nut butters (check ingredients)", "Olive oil", "Organic eggs", "Seasonal produce"],
    avoidAt: ["Frozen meals (seed oil heavy)", "Packaged snacks", "Salad dressings (canola oil)", "Prepared foods"],
    meatNotes: "Meat quality is the weakest aspect of Trader Joe's. Most conventional beef is CAFO-raised. They do carry some organic and grass-fed options but selection is limited and labeling can be confusing. Not recommended for meat purchases.",
    organicNotes: "Decent organic produce at competitive prices. The organic frozen vegetable section is excellent value. Look for the 'Organic' label specifically.",
    overallVerdict: "Great for budget-conscious clean eating on specific items, but requires careful label reading. The seed oil problem is significant — many beloved TJ's products contain canola or sunflower oil. Stick to whole foods, organic produce, and items with simple ingredient lists.",
    storeCount: "560+ stores (US)",
    ownership: "Aldi Nord (private)",
  },
  {
    id: "costco",
    name: "Costco",
    emoji: "🏪",
    logoUrl: "/manus-storage/costco_e3bc68eb.png",
    category: "Warehouse",
    tier: "good",
    overallScore: 70,
    scores: {
      meatQuality: 72,
      organicSelection: 68,
      ingredientTransparency: 62,
      seedOilAvoidance: 55,
      privateLabelQuality: 70,
      valueForQuality: 95,
      sourcingEthics: 65,
    },
    tagline: "Best value for bulk organic staples — but watch the Kirkland labels",
    pros: [
      "Exceptional value on organic staples (olive oil, nuts, eggs)",
      "Kirkland Signature organic products are generally high quality",
      "Good selection of wild-caught seafood",
      "Organic chicken and some grass-fed beef options",
      "Rotisserie chicken is a good value (though conventionally raised)",
      "Excellent organic extra virgin olive oil at unbeatable price",
    ],
    cons: [
      "Many Kirkland products contain seed oils (canola, soybean)",
      "Most conventional meat is CAFO-raised",
      "Bulk quantities lead to waste for smaller households",
      "Limited fresh organic produce selection",
      "Prepared foods and bakery items are heavily processed",
      "Hard to find grass-fed beef consistently",
    ],
    bestFor: ["Organic olive oil", "Organic nuts and seeds", "Wild-caught salmon", "Organic eggs", "Organic frozen vegetables"],
    avoidAt: ["Kirkland salad dressings (canola oil)", "Prepared rotisserie items", "Bakery products", "Conventional packaged snacks"],
    meatNotes: "Costco has improved meat quality in recent years. They carry some organic and grass-fed options, but the majority of beef is conventional USDA Choice from major packers. The organic ground beef is a good value when available. Avoid the pre-marinated meats — they often contain seed oils and additives.",
    organicNotes: "The organic staples at Costco are outstanding value — organic olive oil, organic nuts, organic frozen vegetables, and organic eggs are among the best deals in any grocery store.",
    overallVerdict: "Costco is excellent for stocking up on organic pantry staples at unbeatable prices. The key is knowing what to buy: organic olive oil, nuts, eggs, and frozen vegetables are exceptional value. Avoid the prepared foods, bakery, and conventional packaged goods.",
    storeCount: "600+ US warehouses",
    ownership: "Publicly traded (COST)",
  },
  {
    id: "walmart",
    name: "Walmart",
    emoji: "🏬",
    logoUrl: "/manus-storage/walmart_d29f6e46.png",
    category: "Conventional",
    tier: "poor",
    overallScore: 35,
    scores: {
      meatQuality: 28,
      organicSelection: 40,
      ingredientTransparency: 30,
      seedOilAvoidance: 25,
      privateLabelQuality: 32,
      valueForQuality: 70,
      sourcingEthics: 22,
    },
    tagline: "Lowest prices, lowest quality standards",
    pros: [
      "Lowest prices of any major grocery chain",
      "Expanding organic section (though limited)",
      "Some Sam's Choice products are decent",
      "Widely accessible — 4,700+ stores",
      "Now carries some organic produce in larger stores",
    ],
    cons: [
      "Meat is almost entirely CAFO-raised with no welfare standards",
      "Great Value brand products are heavily processed",
      "Extensive use of seed oils, HFCS, and artificial additives",
      "Minimal transparency on sourcing",
      "Prepared foods are among the lowest quality available",
      "Suppliers face extreme cost pressure — quality suffers",
      "Antibiotic use in meat supply is widespread",
    ],
    bestFor: ["Organic canned goods (if available)", "Bottled water", "Basic pantry staples in emergencies"],
    avoidAt: ["All meat", "Great Value brand processed foods", "Deli items", "Prepared foods", "Conventional produce"],
    meatNotes: "Walmart meat is among the lowest quality available in US grocery stores. The beef comes primarily from large CAFO operations with minimal welfare standards. Antibiotics and growth hormones are routinely used. The Great Value brand has no meaningful quality standards beyond USDA minimum requirements.",
    organicNotes: "Walmart has been expanding its organic section, but the selection is limited and quality control is inconsistent. If organic options are available, they are USDA certified, but the selection pales compared to natural grocery stores.",
    overallVerdict: "Avoid for meat and processed foods. If Walmart is your only option, stick to whole foods (produce, eggs, canned goods) and check labels carefully. The price savings are not worth the quality trade-offs on meat and packaged foods.",
    storeCount: "4,700+ stores (US)",
    ownership: "Walton family (publicly traded, WMT)",
  },
  {
    id: "kroger",
    name: "Kroger",
    emoji: "🛍️",
    logoUrl: "/manus-storage/kroger_7675eb3c.png",
    category: "Conventional",
    tier: "fair",
    overallScore: 48,
    scores: {
      meatQuality: 45,
      organicSelection: 55,
      ingredientTransparency: 45,
      seedOilAvoidance: 35,
      privateLabelQuality: 48,
      valueForQuality: 65,
      sourcingEthics: 42,
    },
    tagline: "Improving but still conventional at its core",
    pros: [
      "Simple Truth Organic brand is a decent private label",
      "Expanding organic and natural sections",
      "Murray's Cheese counter in many locations",
      "Some stores carry grass-fed beef options",
      "Competitive pricing on Simple Truth organic items",
    ],
    cons: [
      "Most Kroger brand meat is conventional CAFO",
      "Private Selection and Kroger brand products often contain seed oils",
      "Inconsistent quality across store locations",
      "Prepared foods section is heavily processed",
      "Limited grass-fed and pasture-raised selection",
      "Simple Truth 'natural' (not organic) products can be misleading",
    ],
    bestFor: ["Simple Truth Organic produce", "Simple Truth Organic dairy", "Wild-caught seafood (check labels)", "Organic eggs"],
    avoidAt: ["Kroger brand processed foods", "Deli meats", "Prepared foods", "Conventional meat"],
    meatNotes: "Kroger has made some improvements with their Simple Truth Natural and Organic lines, but the majority of meat sold is conventional CAFO. The Simple Truth Natural label does not mean grass-fed or pasture-raised — read carefully. Some stores carry Murray's premium meats.",
    organicNotes: "Simple Truth Organic is a legitimate USDA certified organic line at reasonable prices. Good for organic dairy, eggs, and some produce. The 'Simple Truth Natural' line is not organic — don't confuse the two.",
    overallVerdict: "A step above Walmart but still primarily conventional. The Simple Truth Organic line is genuinely useful for budget-conscious shoppers. Stick to the organic section and avoid the conventional processed foods.",
    storeCount: "2,800+ stores (US)",
    ownership: "Publicly traded (KR)",
  },
  {
    id: "target",
    name: "Target",
    emoji: "🎯",
    logoUrl: "/manus-storage/target_29019c77.png",
    category: "Conventional",
    tier: "fair",
    overallScore: 45,
    scores: {
      meatQuality: 40,
      organicSelection: 52,
      ingredientTransparency: 42,
      seedOilAvoidance: 38,
      privateLabelQuality: 50,
      valueForQuality: 62,
      sourcingEthics: 40,
    },
    tagline: "Good for organic pantry staples, poor for fresh meat",
    pros: [
      "Good Value brand has decent organic options",
      "Good & Gather organic line is reasonably priced",
      "Convenient for combining grocery and non-grocery shopping",
      "Carries some natural and organic brands",
      "Expanding fresh food section in larger stores",
    ],
    cons: [
      "Fresh meat quality is poor — limited selection and conventional only",
      "Good & Gather products often contain seed oils",
      "Not a primary grocery destination — limited fresh selection",
      "Prepared foods are heavily processed",
      "Inconsistent organic availability across locations",
    ],
    bestFor: ["Good & Gather Organic pantry staples", "Organic canned goods", "Organic frozen vegetables", "Natural personal care"],
    avoidAt: ["Fresh meat", "Prepared foods", "Market Pantry brand (heavily processed)", "Deli items"],
    meatNotes: "Target is not a reliable source for quality meat. The fresh meat section is conventional CAFO with no meaningful welfare or sourcing standards. Not recommended for meat purchases.",
    organicNotes: "The Good & Gather Organic line has some decent options for pantry staples. Organic canned goods and frozen vegetables are reasonably priced. Not a primary destination for fresh organic produce.",
    overallVerdict: "Target is acceptable for organic pantry staples and dry goods, but should not be your primary grocery store for fresh foods. The meat section is particularly weak. Best used for supplemental shopping.",
    storeCount: "1,900+ stores (US)",
    ownership: "Publicly traded (TGT)",
  },
  {
    id: "aldi",
    name: "Aldi",
    emoji: "💰",
    logoUrl: "/manus-storage/aldi_564898cc.png",
    category: "Discount",
    tier: "fair",
    overallScore: 52,
    scores: {
      meatQuality: 50,
      organicSelection: 58,
      ingredientTransparency: 50,
      seedOilAvoidance: 42,
      privateLabelQuality: 55,
      valueForQuality: 92,
      sourcingEthics: 48,
    },
    tagline: "Surprisingly decent quality for the price — especially organic",
    pros: [
      "SimplyNature Organic line is legitimately USDA certified",
      "Exceptional value on organic produce (often cheapest in market)",
      "No artificial colors or flavors in many products",
      "NEVER Antibiotic Free chicken available in most stores",
      "Cage-free eggs at very competitive prices",
      "Grass-fed beef available in some stores",
    ],
    cons: [
      "Many products contain canola and soybean oils",
      "Limited selection — typically 1,500 SKUs vs 30,000 at conventional stores",
      "Inconsistent availability — products rotate frequently",
      "Meat quality is inconsistent across locations",
      "No in-store butcher",
      "Some products are made in Europe with different standards",
    ],
    bestFor: ["SimplyNature Organic produce", "Organic eggs", "Cage-free eggs", "Organic frozen vegetables", "Nuts and dried fruit"],
    avoidAt: ["Specially Selected premium items (often seed oil heavy)", "Prepared meals", "Conventional packaged snacks"],
    meatNotes: "Aldi has improved meat quality significantly. Their NEVER Antibiotic Free chicken is a genuine commitment. Some stores carry grass-fed beef. The meat is generally better quality than Walmart at similar prices. Check for the 'Certified Humane' or 'NEVER Antibiotic Free' labels.",
    organicNotes: "SimplyNature Organic is one of the best-value organic lines in the US. The organic produce is often the cheapest you'll find anywhere. Quality is consistent and USDA certified.",
    overallVerdict: "Aldi punches well above its weight for quality at this price point. The SimplyNature Organic line is genuinely excellent value. If you're budget-conscious, Aldi's organic section and antibiotic-free meats are hard to beat. Just read labels carefully on packaged goods.",
    storeCount: "2,300+ stores (US)",
    ownership: "Albrecht family (private) — German-owned",
  },
  {
    id: "publix",
    name: "Publix",
    emoji: "🌺",
    logoUrl: "/manus-storage/publix_649a2039.png",
    category: "Conventional",
    tier: "fair",
    overallScore: 58,
    scores: {
      meatQuality: 60,
      organicSelection: 62,
      ingredientTransparency: 55,
      seedOilAvoidance: 45,
      privateLabelQuality: 60,
      valueForQuality: 60,
      sourcingEthics: 58,
    },
    tagline: "Best conventional chain for the Southeast — still conventional at heart",
    pros: [
      "GreenWise Market organic line is solid",
      "Good fresh meat department with knowledgeable butchers",
      "USDA Choice and Prime beef available",
      "Excellent customer service",
      "Some stores carry grass-fed and organic meat",
      "Good wild-caught seafood selection",
    ],
    cons: [
      "Most meat is conventional CAFO",
      "GreenWise products can be expensive",
      "Publix brand products often contain seed oils",
      "Prepared foods section uses seed oils extensively",
      "Limited organic produce compared to natural grocery stores",
    ],
    bestFor: ["GreenWise Organic produce", "Fresh seafood", "USDA Prime beef (for special occasions)", "Organic dairy"],
    avoidAt: ["Publix brand deli meats", "Prepared foods", "Conventional packaged snacks"],
    meatNotes: "Publix has a genuine butcher counter which is rare among conventional chains. They carry USDA Choice and Prime beef, and some stores have GreenWise organic and grass-fed options. Better than Walmart or Kroger for meat quality, but still primarily conventional.",
    organicNotes: "GreenWise is a legitimate organic line with good quality. Pricing is competitive with Whole Foods. The organic produce section is smaller than natural grocery stores but reliable.",
    overallVerdict: "The best conventional chain in the Southeast. Better quality standards than Walmart or Kroger, with a genuine commitment to their GreenWise organic line. If you're in the Southeast and don't have access to Whole Foods or Sprouts, Publix is a solid choice.",
    storeCount: "1,300+ stores (Southeast US)",
    ownership: "Employee-owned (private)",
  },
  {
    id: "heb",
    name: "H-E-B",
    emoji: "🤠",
    logoUrl: "/manus-storage/heb_4c88545f.png",
    category: "Conventional",
    tier: "good",
    overallScore: 68,
    scores: {
      meatQuality: 72,
      organicSelection: 68,
      ingredientTransparency: 65,
      seedOilAvoidance: 55,
      privateLabelQuality: 70,
      valueForQuality: 82,
      sourcingEthics: 70,
    },
    tagline: "Texas institution with genuinely good quality for a conventional chain",
    pros: [
      "Central Market (H-E-B premium) has excellent organic selection",
      "Good meat department with Texas-raised beef options",
      "H-E-B brand products are generally higher quality than national conventional chains",
      "Excellent value — consistently ranked among best grocery stores in the US",
      "Strong local sourcing from Texas farms",
      "Good wild-caught seafood selection",
    ],
    cons: [
      "Primarily Texas — limited geographic availability",
      "H-E-B brand products still contain seed oils",
      "Most conventional meat is CAFO",
      "Prepared foods section uses seed oils",
    ],
    bestFor: ["Central Market organic produce", "Texas-raised beef", "Local produce", "H-E-B Organics line", "Wild-caught seafood"],
    avoidAt: ["H-E-B brand packaged snacks", "Prepared foods", "Conventional deli meats"],
    meatNotes: "H-E-B has a strong meat department with good Texas-raised beef options. Central Market locations carry extensive grass-fed and organic meat. The standard H-E-B meat is better quality than most conventional chains due to their Texas sourcing relationships.",
    organicNotes: "H-E-B Organics is a solid private label. Central Market locations have a Whole Foods-level organic selection at slightly lower prices.",
    overallVerdict: "If you're in Texas, H-E-B is one of the best conventional grocery chains in the country. The Central Market format is excellent for clean eating. Strong local sourcing and good value make it a top choice for Texans.",
    storeCount: "400+ stores (Texas)",
    ownership: "Butt family (private)",
  },
  {
    id: "wegmans",
    name: "Wegmans",
    emoji: "🏆",
    logoUrl: "/manus-storage/wegmans_04bbb9d8.png",
    category: "Premium",
    tier: "excellent",
    overallScore: 80,
    scores: {
      meatQuality: 82,
      organicSelection: 82,
      ingredientTransparency: 78,
      seedOilAvoidance: 68,
      privateLabelQuality: 80,
      valueForQuality: 72,
      sourcingEthics: 80,
    },
    tagline: "Northeast's best grocery chain — strong quality across all departments",
    pros: [
      "Consistently ranked #1 grocery chain in the US for quality",
      "Extensive organic and natural selection",
      "Strong animal welfare standards for meat",
      "Wegmans brand products are high quality",
      "Excellent prepared foods section (better quality than most)",
      "Strong local sourcing relationships",
      "Good transparency on meat sourcing",
    ],
    cons: [
      "Limited to Northeast US",
      "Expensive — comparable to Whole Foods pricing",
      "Some products still contain seed oils",
      "Prepared foods section uses some seed oils",
    ],
    bestFor: ["Organic produce", "Grass-fed beef", "Pasture-raised chicken", "Wegmans brand organic products", "Specialty cheeses"],
    avoidAt: ["Prepared foods (seed oil concern)", "Conventional packaged snacks"],
    meatNotes: "Wegmans has strong animal welfare commitments and carries extensive grass-fed, organic, and pasture-raised options. Their own-brand meat products are high quality. One of the best conventional chain options for quality meat.",
    organicNotes: "Excellent organic selection comparable to Whole Foods. Wegmans brand organic products are high quality and competitively priced.",
    overallVerdict: "If you're in the Northeast, Wegmans is your best conventional grocery option. The quality standards, organic selection, and meat department are all excellent. Consistently outranks Whole Foods in customer satisfaction surveys.",
    storeCount: "110+ stores (Northeast US)",
    ownership: "Wegman family (private)",
  },
  {
    id: "natural-grocers",
    name: "Natural Grocers",
    emoji: "🌾",
    logoUrl: "/manus-storage/natural-grocers_5604e6e0.png",
    category: "Natural/Organic",
    tier: "elite",
    overallScore: 88,
    scores: {
      meatQuality: 90,
      organicSelection: 95,
      ingredientTransparency: 92,
      seedOilAvoidance: 85,
      privateLabelQuality: 88,
      valueForQuality: 78,
      sourcingEthics: 90,
    },
    tagline: "The most principled grocery chain in America",
    pros: [
      "100% USDA certified organic produce — no conventional produce sold",
      "Strictest ingredient standards of any US grocery chain",
      "No products with artificial colors, flavors, preservatives, or sweeteners",
      "No products with hydrogenated oils",
      "All meat is antibiotic-free and humanely raised",
      "Extensive grass-fed, pasture-raised, and regenerative options",
      "No GMO products",
      "Excellent bulk section",
    ],
    cons: [
      "Limited to Mountain West and some other states",
      "Smaller store format — less selection",
      "Can be expensive",
      "Limited prepared foods section",
    ],
    bestFor: ["Everything — this is the gold standard for clean grocery shopping"],
    avoidAt: ["Nothing — their standards prohibit the worst offenders"],
    meatNotes: "Natural Grocers has the strictest meat standards of any mainstream grocery chain. All meat is antibiotic-free, humanely raised, and they carry extensive grass-fed, pasture-raised, and regenerative options. Force of Nature and other premium brands are regularly stocked.",
    organicNotes: "The only major chain that sells 100% organic produce. No conventional produce is sold. This is the gold standard for organic shopping.",
    overallVerdict: "If you have a Natural Grocers near you, it should be your primary grocery store. Their ingredient standards are the strictest in the industry — they've banned ingredients that other 'natural' stores still sell. The 100% organic produce policy is unmatched.",
    storeCount: "165+ stores (Mountain West & other states)",
    ownership: "Isely family (publicly traded, NGVC)",
  },
  {
    id: "fresh-thyme",
    name: "Fresh Thyme Market",
    emoji: "🌿",
    logoUrl: "/manus-storage/fresh-thyme_fbc9417c.png",
    category: "Natural/Organic",
    tier: "excellent",
    overallScore: 78,
    scores: {
      meatQuality: 76,
      organicSelection: 82,
      ingredientTransparency: 76,
      seedOilAvoidance: 70,
      privateLabelQuality: 75,
      valueForQuality: 80,
      sourcingEthics: 76,
    },
    tagline: "Midwest's answer to Sprouts — good value for natural foods",
    pros: [
      "Good organic produce selection at competitive prices",
      "Strong natural and organic product selection",
      "Good bulk section",
      "Competitive pricing compared to Whole Foods",
      "Antibiotic-free meat options",
    ],
    cons: [
      "Limited to Midwest",
      "Some products still contain seed oils",
      "Smaller selection than Whole Foods",
    ],
    bestFor: ["Organic produce", "Natural packaged foods", "Bulk items", "Antibiotic-free meats"],
    avoidAt: ["Conventional packaged snacks", "Prepared foods"],
    meatNotes: "Good selection of antibiotic-free and some grass-fed options. Better than conventional chains but not as strong as Natural Grocers or Whole Foods.",
    organicNotes: "Solid organic produce section at competitive prices. Good alternative to Whole Foods for Midwest shoppers.",
    overallVerdict: "A solid natural grocery option for Midwest shoppers. Good value for organic produce and natural products. Not quite at Whole Foods or Natural Grocers level but significantly better than conventional chains.",
    storeCount: "70+ stores (Midwest)",
    ownership: "Meijer (private)",
  },
];

export const STORE_DB_STATS = {
  total: ALL_STORES.length,
  elite: ALL_STORES.filter(s => s.tier === "elite").length,
  excellent: ALL_STORES.filter(s => s.tier === "excellent").length,
  good: ALL_STORES.filter(s => s.tier === "good").length,
  fair: ALL_STORES.filter(s => s.tier === "fair" || s.tier === "poor").length,
  avoid: ALL_STORES.filter(s => s.tier === "avoid").length,
};

export const SCORE_CATEGORIES = [
  { key: "meatQuality", label: "Meat Quality" },
  { key: "organicSelection", label: "Organic Selection" },
  { key: "ingredientTransparency", label: "Transparency" },
  { key: "seedOilAvoidance", label: "Seed Oil Avoidance" },
  { key: "privateLabelQuality", label: "Store Brand Quality" },
  { key: "valueForQuality", label: "Value for Quality" },
  { key: "sourcingEthics", label: "Sourcing Ethics" },
] as const;
