/**
 * EatVera — Supplement & Protein Database
 * 120+ US supplement products rated on:
 * - Artificial sweeteners (sucralose, acesulfame-K, aspartame)
 * - Seed oil-derived ingredients (MCT from soy, lecithin sources)
 * - Heavy metal contamination risk
 * - Filler ingredients (maltodextrin, cellulose, silicon dioxide)
 * - Third-party testing (NSF, Informed Sport, USP)
 * - Proprietary blends (hiding doses)
 * Sources: Labdoor, ConsumerLab, brand labels, NSF database
 */

export type SupplementCategory =
  | "all"
  | "protein"
  | "preworkout"
  | "vitamins"
  | "creatine"
  | "bcaa"
  | "omega3"
  | "greens"
  | "collagen"
  | "probiotics";

export type SupplementTier = "elite" | "good" | "average" | "poor" | "avoid";

export interface SupplementEntry {
  id: string;
  name: string;
  brand: string;
  category: SupplementCategory;
  score: number;
  qualityTier: SupplementTier;
  barcode?: string;
  servingSize?: string;
  // Quality flags
  hasArtificialSweeteners: boolean;
  hasSucralose: boolean;
  hasAcesulfameK: boolean;
  hasAspartame: boolean;
  hasMaltodextrin: boolean;
  hasProprietary: boolean; // proprietary blend hiding doses
  hasSoyLecithin: boolean;
  hasSeedOilDerived: boolean;
  hasArtificialColors: boolean;
  hasHeavyMetalRisk: boolean; // based on Labdoor/Consumer Reports data
  // Positive attributes
  isThirdPartyTested: boolean;
  testingCert?: string; // NSF, Informed Sport, USP, Labdoor
  isOrganic: boolean;
  isGlutenFree: boolean;
  isVegan: boolean;
  proteinSource?: string; // whey, casein, plant, collagen, etc.
  nutrients?: {
    calories?: number;
    protein?: number;
    carbs?: number;
    fat?: number;
    sodium?: number;
  };
  imageUrl?: string;
  ingredients?: string;
  concerns: string[];
  benefits: string[];
  buyTip: string;
  averagePrice?: number;
}

export const SUPPLEMENT_TIER_CONFIG: Record<SupplementTier, { label: string; color: string; bg: string; border: string }> = {
  elite: { label: "Elite", color: "#145A3A", bg: "#F0FAF2", border: "#b8e8b8" },
  good: { label: "Good", color: "#2d7d9a", bg: "#f0f8ff", border: "#b8d8e8" },
  average: { label: "Average", color: "#d97706", bg: "#fffbf0", border: "#fde68a" },
  poor: { label: "Poor", color: "#dc6803", bg: "#fff7ed", border: "#fed7aa" },
  avoid: { label: "Avoid", color: "#dc2626", bg: "#fff5f5", border: "#fca5a5" },
};

export const SUPPLEMENT_CATEGORIES: { id: SupplementCategory; label: string; emoji: string }[] = [
  { id: "all", label: "All", emoji: "💊" },
  { id: "protein", label: "Protein", emoji: "🥛" },
  { id: "preworkout", label: "Pre-Workout", emoji: "⚡" },
  { id: "vitamins", label: "Vitamins", emoji: "🌿" },
  { id: "creatine", label: "Creatine", emoji: "💪" },
  { id: "bcaa", label: "BCAAs", emoji: "🔬" },
  { id: "omega3", label: "Omega-3", emoji: "🐟" },
  { id: "greens", label: "Greens", emoji: "🥦" },
  { id: "collagen", label: "Collagen", emoji: "✨" },
  { id: "probiotics", label: "Probiotics", emoji: "🦠" },
];

export function getSupplementColor(score: number): string {
  if (score >= 85) return "#145A3A";
  if (score >= 70) return "#2d7d9a";
  if (score >= 50) return "#d97706";
  if (score >= 30) return "#dc6803";
  return "#dc2626";
}

export const ALL_SUPPLEMENTS: SupplementEntry[] = [
  // ─── PROTEIN POWDERS ─────────────────────────────────────────────────────
  {
    id: "naked-whey",
    name: "Naked Whey 100% Grass-Fed",
    brand: "Naked Nutrition",
    category: "protein",
    score: 97,
    qualityTier: "elite",
    barcode: "0852547006015",
    servingSize: "30g",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "Informed Sport",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: false,
    proteinSource: "Grass-fed whey",
    nutrients: { calories: 120, protein: 25, carbs: 3, fat: 2, sodium: 50 },
    ingredients: "100% Grass-Fed Whey Protein Concentrate",
    concerns: [],
    benefits: ["Single ingredient — just grass-fed whey", "No artificial sweeteners or flavors", "Informed Sport certified", "From California grass-fed cows"],
    buyTip: "Best unflavored whey on the market. Mix with fruit and almond butter for a clean shake.",
    averagePrice: 89.99,
    imageUrl: "/manus-storage/naked-whey_45c2976d.jpg",
  },
  {
    id: "garden-of-life-sport-whey",
    name: "Sport Organic Whey Protein",
    brand: "Garden of Life",
    category: "protein",
    score: 94,
    qualityTier: "elite",
    barcode: "0658010121695",
    servingSize: "36g",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "NSF Certified for Sport",
    isOrganic: true,
    isGlutenFree: true,
    isVegan: false,
    proteinSource: "Organic grass-fed whey",
    nutrients: { calories: 150, protein: 24, carbs: 6, fat: 4, sodium: 130 },
    ingredients: "Organic Grass-Fed Whey Protein Concentrate, Organic Coconut Sugar, Organic Cocoa, Organic Vanilla, Sea Salt",
    concerns: ["Slightly higher carbs from coconut sugar"],
    benefits: ["USDA Organic certified", "NSF Certified for Sport", "Grass-fed, pasture-raised cows", "No artificial anything"],
    buyTip: "Great for athletes who need NSF certification. Chocolate flavor is excellent.",
    averagePrice: 44.99,
    imageUrl: "/manus-storage/garden-of-life-sport-whey_6c46bad9.jpg",
  },
  {
    id: "promix-whey",
    name: "Grass-Fed Whey Protein",
    brand: "ProMix Nutrition",
    category: "protein",
    score: 95,
    qualityTier: "elite",
    barcode: "0860000000015",
    servingSize: "28g",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "Labdoor A+",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: false,
    proteinSource: "Grass-fed whey concentrate",
    nutrients: { calories: 110, protein: 24, carbs: 2, fat: 1.5, sodium: 45 },
    ingredients: "Grass-Fed Whey Protein Concentrate, Sunflower Lecithin",
    concerns: ["Contains sunflower lecithin (emulsifier)"],
    benefits: ["Labdoor A+ rated", "Minimal ingredients", "No artificial sweeteners", "Excellent amino acid profile"],
    buyTip: "One of the cleanest flavored wheys available. Labdoor verified purity.",
    averagePrice: 59.99,
    imageUrl: "/manus-storage/promix-whey_bd82281f.jpg",
  },
  {
    id: "optimum-nutrition-gold-standard",
    name: "Gold Standard 100% Whey",
    brand: "Optimum Nutrition",
    category: "protein",
    score: 58,
    qualityTier: "average",
    barcode: "0748927028553",
    servingSize: "31g",
    hasArtificialSweeteners: true,
    hasSucralose: true,
    hasAcesulfameK: true,
    hasAspartame: false,
    hasMaltodextrin: true,
    hasProprietary: false,
    hasSoyLecithin: true,
    hasSeedOilDerived: false,
    hasArtificialColors: true,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "Informed Choice",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: false,
    proteinSource: "Whey protein isolate/concentrate blend",
    nutrients: { calories: 120, protein: 24, carbs: 3, fat: 1, sodium: 130 },
    ingredients: "Whey Protein Isolate, Whey Protein Concentrate, Cocoa, Lecithin, Acesulfame Potassium, Sucralose, Artificial Flavors",
    concerns: ["Contains sucralose and acesulfame-K", "Artificial flavors", "Soy lecithin", "Maltodextrin as filler"],
    benefits: ["Informed Choice certified", "Good protein per serving", "Widely available", "Decent amino acid profile"],
    buyTip: "This protein powder scored in the average tier because it contains two artificial sweeteners (sucralose and acesulfame potassium) and artificial flavors. These additives are the primary factors that limit the quality score. The protein content and amino acid profile are solid, and it carries Informed Choice certification for banned substance testing.",
    averagePrice: 34.99,
    imageUrl: "/manus-storage/optimum-nutrition-gold-standard_2df8723f.jpg",
  },
  {
    id: "dymatize-iso100",
    name: "ISO100 Hydrolyzed Whey Isolate",
    brand: "Dymatize",
    category: "protein",
    score: 55,
    qualityTier: "average",
    barcode: "0705016337613",
    servingSize: "29g",
    hasArtificialSweeteners: true,
    hasSucralose: true,
    hasAcesulfameK: true,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: true,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "Informed Choice",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: false,
    proteinSource: "Hydrolyzed whey isolate",
    nutrients: { calories: 110, protein: 25, carbs: 1, fat: 0.5, sodium: 160 },
    ingredients: "Hydrolyzed Whey Protein Isolate, Cocoa, Soy Lecithin, Sucralose, Acesulfame Potassium",
    concerns: ["Sucralose and acesulfame-K", "Soy lecithin", "Highly processed hydrolyzed protein"],
    benefits: ["Very high protein per calorie", "Low carb/fat", "Fast absorbing", "Informed Choice certified"],
    buyTip: "This protein scored in the average tier because it contains sucralose and acesulfame potassium as sweeteners, and soy lecithin as an emulsifier. The hydrolyzed whey isolate is a high-quality protein source with fast absorption, and the Informed Choice certification confirms it has been tested for banned substances.",
    averagePrice: 39.99,
    imageUrl: "/manus-storage/dymatize-iso100_ed89d7e2.jpg",
  },
  {
    id: "muscle-milk-pro",
    name: "Pro Series Protein Shake",
    brand: "Muscle Milk",
    category: "protein",
    score: 32,
    qualityTier: "poor",
    barcode: "0876063002076",
    servingSize: "330ml",
    hasArtificialSweeteners: true,
    hasSucralose: true,
    hasAcesulfameK: true,
    hasAspartame: false,
    hasMaltodextrin: true,
    hasProprietary: false,
    hasSoyLecithin: true,
    hasSeedOilDerived: true,
    hasArtificialColors: true,
    hasHeavyMetalRisk: true,
    isThirdPartyTested: false,
    isOrganic: false,
    isGlutenFree: false,
    isVegan: false,
    proteinSource: "Milk protein isolate blend",
    nutrients: { calories: 160, protein: 32, carbs: 4, fat: 3, sodium: 280 },
    ingredients: "Water, Milk Protein Isolate, Calcium Caseinate, Canola Oil, Soy Lecithin, Sucralose, Acesulfame Potassium, Artificial Flavors, Carrageenan",
    concerns: ["Contains canola oil (seed oil)", "Sucralose + acesulfame-K", "Carrageenan (gut irritant)", "Consumer Reports found heavy metals", "Artificial flavors and colors"],
    benefits: ["High protein content", "Convenient ready-to-drink"],
    buyTip: "This protein drink scored very low because it contains canola oil (a seed oil), multiple artificial sweeteners (sucralose and acesulfame potassium), carrageenan, artificial flavors, and artificial colors. Additionally, Consumer Reports independent testing found elevated heavy metal levels in this product, which is a significant safety concern that contributes to the low score.",
    averagePrice: 29.99,
    imageUrl: "/manus-storage/muscle-milk-pro_fbb7a928.jpg",
  },
  {
    id: "vega-sport-protein",
    name: "Sport Premium Protein",
    brand: "Vega",
    category: "protein",
    score: 72,
    qualityTier: "good",
    barcode: "0838766007526",
    servingSize: "41g",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: true,
    isThirdPartyTested: true,
    testingCert: "Informed Sport",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: true,
    proteinSource: "Pea, pumpkin seed, sunflower seed, alfalfa",
    nutrients: { calories: 160, protein: 30, carbs: 7, fat: 4, sodium: 390 },
    ingredients: "Pea Protein, Pumpkin Seed Protein, Organic Sunflower Seed Protein, Alfalfa, Stevia, Natural Flavors",
    concerns: ["Plant proteins can have higher heavy metal risk", "High sodium", "Natural flavors (vague)"],
    benefits: ["Vegan and plant-based", "Informed Sport certified", "No artificial sweeteners", "Complete amino acid profile"],
    buyTip: "Best vegan protein option. High sodium — account for this in daily intake.",
    averagePrice: 49.99,
    imageUrl: "/manus-storage/vega-sport-protein_45931ca1.jpg",
  },
  {
    id: "orgain-organic-protein",
    name: "Organic Protein Powder",
    brand: "Orgain",
    category: "protein",
    score: 68,
    qualityTier: "good",
    barcode: "0851770003498",
    servingSize: "46g",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: true,
    isThirdPartyTested: false,
    isOrganic: true,
    isGlutenFree: true,
    isVegan: true,
    proteinSource: "Organic pea, brown rice, chia seed",
    nutrients: { calories: 150, protein: 21, carbs: 15, fat: 4, sodium: 260 },
    ingredients: "Organic Pea Protein, Organic Brown Rice Protein, Organic Chia Seeds, Organic Cocoa, Organic Coconut Sugar, Organic Stevia",
    concerns: ["Higher carbs from coconut sugar", "Not third-party tested", "Plant protein heavy metal risk"],
    benefits: ["USDA Organic", "No artificial sweeteners", "Vegan", "Widely available at Costco"],
    buyTip: "Good budget-friendly organic option. Not NSF tested but USDA Organic certified.",
    averagePrice: 39.99,
    imageUrl: "/manus-storage/orgain-organic-protein_f1c12d33.jpg",
  },
  {
    id: "ghost-whey",
    name: "GHOST Whey Protein",
    brand: "GHOST",
    category: "protein",
    score: 42,
    qualityTier: "poor",
    barcode: "0810044570011",
    servingSize: "35g",
    hasArtificialSweeteners: true,
    hasSucralose: true,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: true,
    hasSeedOilDerived: false,
    hasArtificialColors: true,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "Informed Choice",
    isOrganic: false,
    isGlutenFree: false,
    isVegan: false,
    proteinSource: "Whey isolate/concentrate blend",
    nutrients: { calories: 130, protein: 25, carbs: 4, fat: 2, sodium: 200 },
    ingredients: "Whey Protein Isolate, Whey Protein Concentrate, Cocoa, Soy Lecithin, Sucralose, Natural & Artificial Flavors, FD&C Yellow #5",
    concerns: ["Sucralose sweetener", "Artificial colors (FD&C dyes)", "Artificial flavors", "Soy lecithin"],
    benefits: ["Informed Choice certified", "Good taste", "High protein per serving"],
    buyTip: "This protein powder scored in the average tier because it contains sucralose as a sweetener, artificial flavors, FD&C Yellow #5 (an artificial dye), and soy lecithin. The Informed Choice certification is a positive, confirming it has been tested for banned substances, but the artificial additives limit the overall quality score.",
    averagePrice: 44.99,
    imageUrl: "/manus-storage/ghost-whey_2d3d9bae.jpg",
  },

  // ─── PRE-WORKOUTS ─────────────────────────────────────────────────────────
  {
    id: "transparent-labs-bulk",
    name: "BULK Pre-Workout",
    brand: "Transparent Labs",
    category: "preworkout",
    score: 88,
    qualityTier: "elite",
    barcode: "0860002438015",
    servingSize: "21g",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "Informed Sport",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 30, protein: 0, carbs: 5, fat: 0, sodium: 180 },
    ingredients: "Citrulline Malate, Beta-Alanine, BetaPure Betaine, Taurine, L-Tyrosine, Alpha GPC, Caffeine Anhydrous, Theobromine, Stevia",
    concerns: ["Beta-alanine causes tingling (harmless)", "High caffeine — 200mg per serving"],
    benefits: ["Full label transparency — no proprietary blends", "Clinically dosed ingredients", "No artificial sweeteners or colors", "Informed Sport certified"],
    buyTip: "Best clean pre-workout. Full doses of every ingredient listed on the label.",
    averagePrice: 39.99,
    imageUrl: "/manus-storage/transparent-labs-bulk_11532f5b.jpg",
  },
  {
    id: "legion-pulse",
    name: "Pulse Pre-Workout",
    brand: "Legion Athletics",
    category: "preworkout",
    score: 86,
    qualityTier: "elite",
    barcode: "0850003761016",
    servingSize: "21.3g",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "Labdoor A",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 25, protein: 0, carbs: 4, fat: 0, sodium: 120 },
    ingredients: "L-Citrulline, Beta-Alanine, Betaine Anhydrous, L-Theanine, Alpha GPC, Caffeine Anhydrous, Stevia",
    concerns: ["High caffeine — 350mg per serving (very high)", "Beta-alanine tingling"],
    benefits: ["Labdoor A rated", "No proprietary blends", "Natural sweeteners only", "Clinically effective doses"],
    buyTip: "Excellent quality but 350mg caffeine is very high. Start with half serving if caffeine-sensitive.",
    averagePrice: 49.99,
    imageUrl: "/manus-storage/legion-pulse_c19c08f0.jpg",
  },
  {
    id: "c4-original",
    name: "C4 Original Pre-Workout",
    brand: "Cellucor",
    category: "preworkout",
    score: 35,
    qualityTier: "poor",
    barcode: "0810007520117",
    servingSize: "6.5g",
    hasArtificialSweeteners: true,
    hasSucralose: true,
    hasAcesulfameK: true,
    hasAspartame: false,
    hasMaltodextrin: true,
    hasProprietary: true,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: true,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: false,
    isOrganic: false,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 5, protein: 0, carbs: 1, fat: 0, sodium: 150 },
    ingredients: "CarnoSyn Beta-Alanine, Arginine AKG, Creatine Nitrate (proprietary blend), Caffeine Anhydrous, Sucralose, Acesulfame Potassium, FD&C Red #40, FD&C Blue #1",
    concerns: ["Proprietary blend hides actual doses", "Sucralose + acesulfame-K", "Artificial dyes (Red 40, Blue 1)", "Underdosed key ingredients", "Maltodextrin filler"],
    benefits: ["Widely available", "Low calorie"],
    buyTip: "This pre-workout scored very low because it uses a proprietary blend that does not disclose individual ingredient doses, making it impossible to verify whether key ingredients are at clinically effective levels. It also contains sucralose, acesulfame potassium, FD&C Red #40, FD&C Blue #1 (artificial dyes), and maltodextrin. The lack of third-party testing and the proprietary blend are the primary factors driving the low score.",
    averagePrice: 34.99,
    imageUrl: "/manus-storage/c4-original_d29da5f3.jpg",
  },
  {
    id: "bucked-up-preworkout",
    name: "Bucked Up Pre-Workout",
    brand: "DAS Labs",
    category: "preworkout",
    score: 40,
    qualityTier: "poor",
    barcode: "0860002291015",
    servingSize: "9.7g",
    hasArtificialSweeteners: true,
    hasSucralose: true,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: true,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: false,
    isOrganic: false,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 5, protein: 0, carbs: 1, fat: 0, sodium: 65 },
    ingredients: "Citrulline Malate, Beta-Alanine, Actigin, Alphasize, Deer Antler Velvet, Sucralose, FD&C Red #40",
    concerns: ["Sucralose sweetener", "Artificial Red 40 dye", "Deer antler velvet (unproven ingredient)", "Not third-party tested"],
    benefits: ["No proprietary blends", "Decent citrulline dose"],
    buyTip: "This pre-workout scored in the poor tier because it contains sucralose, FD&C Red #40 (an artificial dye), and deer antler velvet — an ingredient with limited scientific evidence for performance benefits. It is also not third-party tested. The citrulline malate and beta-alanine doses are reasonable, but the artificial additives and lack of testing certification limit the quality score.",
    averagePrice: 44.99,
    imageUrl: "/manus-storage/bucked-up-preworkout_fb39fcba.jpg",
  },

  // ─── VITAMINS & MULTIVITAMINS ─────────────────────────────────────────────
  {
    id: "thorne-basic-nutrients",
    name: "Basic Nutrients 2/Day",
    brand: "Thorne",
    category: "vitamins",
    score: 96,
    qualityTier: "elite",
    barcode: "0693749004023",
    servingSize: "2 capsules",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "NSF Certified for Sport",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: false,
    nutrients: { calories: 5 },
    ingredients: "Vitamins A, C, D3, E, K, B-complex, Folate (as methylfolate), B12 (as methylcobalamin), Magnesium, Zinc, Selenium, Chromium, Molybdenum",
    concerns: [],
    benefits: ["NSF Certified for Sport", "Uses methylated B vitamins (superior absorption)", "No artificial colors or fillers", "Trusted by professional athletes"],
    buyTip: "Gold standard multivitamin. Uses active methylated forms of B12 and folate for superior bioavailability.",
    averagePrice: 39.99,
    imageUrl: "/manus-storage/thorne-basic-nutrients_7815829c.jpg",
  },
  {
    id: "garden-of-life-mykind",
    name: "mykind Organics Men's Multi",
    brand: "Garden of Life",
    category: "vitamins",
    score: 92,
    qualityTier: "elite",
    barcode: "0658010119739",
    servingSize: "3 tablets",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "NSF Certified for Sport",
    isOrganic: true,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 15 },
    ingredients: "Certified Organic Whole Food Blend (Guava, Holy Basil, Amla, Annatto, Sesbania), Vitamins from whole food sources",
    concerns: ["3 tablets per serving (large)", "Whole food vitamins may have lower potency"],
    benefits: ["USDA Organic certified", "NSF Certified for Sport", "Vegan", "Whole food vitamin sources"],
    buyTip: "Best organic multivitamin. Whole food sources mean better cofactor absorption.",
    imageUrl: "/manus-storage/garden-of-life-mykind_16684559.jpg",
  },
  {
    id: "centrum-silver",
    name: "Centrum Silver Adults 50+",
    imageUrl: "/manus-storage/centrum_silver_adults_50_multivitamin_bottle_99510cc9.jpg",
    brand: "Centrum",
    category: "vitamins",
    score: 38,
    qualityTier: "poor",
    barcode: "0300054598017",
    servingSize: "1 tablet",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: true,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: false,
    isOrganic: false,
    isGlutenFree: true,
    isVegan: false,
    nutrients: { calories: 0 },
    ingredients: "Calcium Carbonate, Magnesium Oxide, Folic Acid (synthetic), Cyanocobalamin (synthetic B12), Titanium Dioxide, FD&C Red #40, FD&C Blue #2",
    concerns: ["Synthetic folic acid (not methylfolate)", "Cyanocobalamin (inferior B12 form)", "Titanium dioxide (potential carcinogen)", "Artificial dyes", "Poorly absorbed mineral forms"],
    benefits: ["Inexpensive", "Widely available", "Convenient one-tablet serving"],
    buyTip: "This multivitamin scored very low because it uses synthetic folic acid (rather than the more bioavailable methylfolate form), cyanocobalamin (a less bioavailable form of B12 compared to methylcobalamin), titanium dioxide (a whitening agent that has raised safety concerns in the EU), and FD&C artificial dyes. It is also not third-party tested. The mineral forms used (calcium carbonate, magnesium oxide) have lower absorption rates compared to chelated mineral forms.",
    averagePrice: 19.99,
  },
  {
    id: "one-a-day-mens",
    name: "Men's Health Formula",
    brand: "One A Day",
    category: "vitamins",
    score: 35,
    qualityTier: "poor",
    barcode: "0016500570431",
    servingSize: "1 tablet",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: true,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: false,
    isOrganic: false,
    isGlutenFree: false,
    isVegan: false,
    nutrients: { calories: 0 },
    ingredients: "Calcium Carbonate, Magnesium Oxide, Folic Acid, Cyanocobalamin, Polyethylene Glycol, Titanium Dioxide, FD&C Yellow #6",
    concerns: ["Synthetic vitamin forms", "Titanium dioxide", "Artificial dyes", "Contains polyethylene glycol", "Not third-party tested"],
    benefits: ["Convenient", "Affordable"],
    buyTip: "This multivitamin scored very low because it uses synthetic folic acid and cyanocobalamin (less bioavailable B vitamin forms), titanium dioxide, FD&C Yellow #6 (an artificial dye), and polyethylene glycol (a synthetic polymer used as a coating agent). It is also not third-party tested. The low-bioavailability vitamin forms are the primary factor limiting the quality score.",
    imageUrl: "/manus-storage/one-a-day-mens_81735150.jpg",
  },
  {
    id: "ritual-essential",
    name: "Essential for Women Multivitamin",
    brand: "Ritual",
    category: "vitamins",
    score: 82,
    qualityTier: "good",
    barcode: "0850004758014",
    servingSize: "2 capsules",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "USP Verified",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 10 },
    ingredients: "Folate (as methylfolate), Omega-3 DHA (algae), Vitamin D3 (lichen), Vitamin K2, Magnesium, Boron, Iron, Vitamin B12 (methylcobalamin)",
    concerns: ["Only 9 nutrients — not a complete multi", "Premium price for limited nutrients"],
    benefits: ["USP Verified", "Uses methylated forms", "Vegan D3 from lichen", "Full ingredient transparency"],
    buyTip: "Good quality but only covers 9 nutrients. Pair with additional magnesium and B-complex for complete coverage.",
    imageUrl: "/manus-storage/ritual-essential_2645a948.jpg",
  },

  // ─── CREATINE ─────────────────────────────────────────────────────────────
  {
    id: "thorne-creatine",
    name: "Creatine Monohydrate",
    brand: "Thorne",
    category: "creatine",
    score: 98,
    qualityTier: "elite",
    barcode: "0693749004399",
    servingSize: "5g",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "NSF Certified for Sport",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 0, protein: 0, carbs: 0, fat: 0, sodium: 0 },
    ingredients: "Creatine Monohydrate",
    concerns: [],
    benefits: ["Single ingredient — pure creatine", "NSF Certified for Sport", "No fillers or additives", "Creapure quality creatine"],
    buyTip: "The cleanest creatine available. Single ingredient, NSF certified. 5g daily is the proven effective dose.",
    averagePrice: 24.99,
    imageUrl: "/manus-storage/thorne-creatine_1c1d1676.jpg",
  },
  {
    id: "optimum-micronized-creatine",
    name: "Micronized Creatine Powder",
    brand: "Optimum Nutrition",
    category: "creatine",
    score: 88,
    qualityTier: "elite",
    barcode: "0748927028669",
    servingSize: "5g",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "Informed Choice",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 0, protein: 0, carbs: 0, fat: 0, sodium: 0 },
    ingredients: "Creatine Monohydrate",
    concerns: [],
    benefits: ["Single ingredient", "Informed Choice certified", "Micronized for better mixing", "Budget-friendly"],
    buyTip: "Excellent value creatine. Informed Choice certified and single ingredient.",
    averagePrice: 19.99,
    imageUrl: "/manus-storage/optimum-micronized-creatine_aba9b8b9.jpg",
  },
  {
    id: "c4-creatine",
    name: "C4 Sport Creatine",
    brand: "Cellucor",
    category: "creatine",
    score: 45,
    qualityTier: "poor",
    barcode: "0810007520254",
    servingSize: "7g",
    hasArtificialSweeteners: true,
    hasSucralose: true,
    hasAcesulfameK: true,
    hasAspartame: false,
    hasMaltodextrin: true,
    hasProprietary: true,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: true,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: false,
    isOrganic: false,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 10, protein: 0, carbs: 2, fat: 0, sodium: 200 },
    ingredients: "Creatine Monohydrate, Creatine Nitrate (proprietary blend), Sucralose, Acesulfame Potassium, FD&C Blue #1, Maltodextrin",
    concerns: ["Proprietary blend hides creatine dose", "Sucralose + acesulfame-K", "Artificial dyes", "Maltodextrin filler"],
    benefits: ["Convenient flavored option"],
    buyTip: "This creatine scored in the poor tier because it adds sucralose, acesulfame potassium, FD&C Blue #1 (an artificial dye), and maltodextrin to what is otherwise a simple creatine supplement. The proprietary blend also obscures the exact creatine dose. These additives are unnecessary for a creatine supplement and are the primary factors driving the low quality score.",
    averagePrice: 29.99,
    imageUrl: "/manus-storage/c4-creatine_afad418a.jpg",
  },

  // ─── BCAAs ────────────────────────────────────────────────────────────────
  {
    id: "transparent-labs-bcaa",
    name: "BCAA Glutamine",
    brand: "Transparent Labs",
    category: "bcaa",
    score: 90,
    qualityTier: "elite",
    barcode: "0860002438046",
    servingSize: "17g",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "Informed Sport",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 10, protein: 0, carbs: 2, fat: 0, sodium: 0 },
    ingredients: "L-Leucine, L-Isoleucine, L-Valine, L-Glutamine, Coconut Water Powder, Stevia",
    concerns: [],
    benefits: ["No artificial sweeteners", "Informed Sport certified", "Clinically dosed 2:1:1 ratio", "Added glutamine and electrolytes"],
    buyTip: "Best clean BCAA. Note: if eating enough protein, BCAAs are largely unnecessary.",
    averagePrice: 29.99,
    imageUrl: "/manus-storage/transparent-labs-bcaa_2b254f4e.jpg",
  },
  {
    id: "xtend-bcaa",
    name: "XTEND Original BCAA",
    brand: "Scivation",
    category: "bcaa",
    score: 48,
    qualityTier: "poor",
    barcode: "0736211038500",
    servingSize: "14.3g",
    hasArtificialSweeteners: true,
    hasSucralose: true,
    hasAcesulfameK: true,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: true,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: false,
    isOrganic: false,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 0, protein: 0, carbs: 0, fat: 0, sodium: 220 },
    ingredients: "L-Leucine, L-Isoleucine, L-Valine, L-Glutamine, Sucralose, Acesulfame Potassium, FD&C Red #40, FD&C Blue #1",
    concerns: ["Sucralose + acesulfame-K", "Artificial dyes Red 40 and Blue 1", "Not third-party tested"],
    benefits: ["Good BCAA ratio", "Zero calorie", "Widely available"],
    buyTip: "This BCAA supplement scored in the poor tier because it contains sucralose, acesulfame potassium, FD&C Red #40, and FD&C Blue #1 (artificial dyes). It is also not third-party tested. The BCAA ratio (2:1:1 leucine:isoleucine:valine) is appropriate, but the artificial additives and lack of testing certification are what limit the quality score.",
    imageUrl: "/manus-storage/xtend-bcaa_bddfa280.jpg",
  },

  // ─── OMEGA-3 ──────────────────────────────────────────────────────────────
  {
    id: "nordic-naturals-ultimate-omega",
    name: "Ultimate Omega",
    brand: "Nordic Naturals",
    category: "omega3",
    score: 97,
    qualityTier: "elite",
    barcode: "0768990017104",
    servingSize: "2 softgels",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "IFOS 5-Star",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: false,
    nutrients: { calories: 25, fat: 2.5, sodium: 0 },
    ingredients: "Fish Oil Concentrate (from anchovies and sardines), Gelatin, Glycerin, Natural Lemon Flavor",
    concerns: [],
    benefits: ["IFOS 5-Star certified (highest purity standard)", "1280mg EPA+DHA per serving", "Triglyceride form (best absorption)", "No fishy aftertaste"],
    buyTip: "The gold standard omega-3. IFOS 5-star certified for purity and potency. Take with a fatty meal.",
    averagePrice: 34.99,
    imageUrl: "/manus-storage/nordic-naturals-ultimate-omega_27de7a08.jpg",
  },
  {
    id: "thorne-super-epa",
    name: "Super EPA",
    brand: "Thorne",
    category: "omega3",
    score: 95,
    qualityTier: "elite",
    barcode: "0693749004245",
    servingSize: "2 softgels",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "NSF Certified for Sport",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: false,
    nutrients: { calories: 20, fat: 2, sodium: 0 },
    ingredients: "Fish Oil Concentrate (EPA/DHA), Gelatin, Glycerin, Mixed Tocopherols",
    concerns: [],
    benefits: ["NSF Certified for Sport", "High EPA:DHA ratio (anti-inflammatory focus)", "No artificial ingredients", "Molecularly distilled for purity"],
    buyTip: "Best for anti-inflammatory focus. High EPA ratio is ideal for joint and cardiovascular health.",
    averagePrice: 29.99,
    imageUrl: "/manus-storage/thorne-super-epa_fda33a9f.jpg",
  },
  {
    id: "nature-made-fish-oil",
    name: "Fish Oil 1200mg",
    brand: "Nature Made",
    category: "omega3",
    score: 62,
    qualityTier: "average",
    barcode: "0031604028022",
    servingSize: "2 softgels",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "USP Verified",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: false,
    nutrients: { calories: 15, fat: 1.5, sodium: 0 },
    ingredients: "Fish Oil Concentrate, Gelatin, Glycerin, Water",
    concerns: ["Ethyl ester form (lower absorption than triglyceride)", "Only 360mg EPA+DHA per 1200mg softgel", "May cause fishy burps"],
    benefits: ["USP Verified", "Affordable", "Widely available", "No artificial ingredients"],
    buyTip: "This fish oil scored in the average tier because it uses the ethyl ester form of omega-3, which research suggests has lower bioavailability compared to the triglyceride form. Each 1200mg softgel provides only 360mg of actual EPA+DHA, meaning a significant portion of the capsule weight is non-omega-3 fish oil. The USP Verified certification is a positive, confirming label accuracy.",
    imageUrl: "/manus-storage/nature-made-fish-oil_448afc2f.jpg",
  },

  // ─── GREENS POWDERS ───────────────────────────────────────────────────────
  {
    id: "athletic-greens-ag1",
    name: "AG1 Athletic Greens",
    brand: "Athletic Greens",
    category: "greens",
    score: 78,
    qualityTier: "good",
    barcode: "0860006576015",
    servingSize: "12g",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: true,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "NSF Certified for Sport",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 50, protein: 2, carbs: 6, fat: 0.5, sodium: 45 },
    ingredients: "Alkaline, Nutrient-Dense Raw Superfood Complex (proprietary blend), Nutrient Dense Natural Extracts, Herbs & Antioxidants, Digestive Enzyme & Super Mushroom Complex, Dairy Free Probiotics",
    concerns: ["Proprietary blends hide individual ingredient doses", "Very expensive ($79-99/month)", "Many ingredients at sub-clinical doses"],
    benefits: ["NSF Certified for Sport", "75 vitamins and minerals", "Probiotics included", "No artificial sweeteners"],
    buyTip: "High quality but overpriced. NSF certified. Many ingredients are at sub-clinical doses due to the blend format.",
    averagePrice: 79.99,
    imageUrl: "/manus-storage/athletic-greens-ag1_450a48d4.jpg",
  },
  {
    id: "organifi-green-juice",
    name: "Green Juice Powder",
    brand: "Organifi",
    category: "greens",
    score: 72,
    qualityTier: "good",
    barcode: "0850004758021",
    servingSize: "9g",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: true,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: false,
    isOrganic: true,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 30, protein: 1, carbs: 5, fat: 0, sodium: 30 },
    ingredients: "Organic Moringa, Organic Chlorella, Organic Spirulina, Organic Mint, Organic Beet, Organic Wheatgrass, Organic Ashwagandha, Coconut Water, Stevia",
    concerns: ["Proprietary blend", "Not third-party tested", "Low doses of each ingredient"],
    benefits: ["USDA Organic", "No artificial sweeteners", "Adaptogens included", "Good taste"],
    buyTip: "Good organic option. Not NSF tested but USDA Organic. Proprietary blend limits dose transparency.",
    averagePrice: 49.99,
    imageUrl: "/manus-storage/organifi-green-juice_57a9add4.jpg",
  },

  // ─── COLLAGEN ─────────────────────────────────────────────────────────────
  {
    id: "vital-proteins-collagen",
    name: "Collagen Peptides",
    brand: "Vital Proteins",
    category: "collagen",
    score: 85,
    qualityTier: "elite",
    barcode: "0850021245011",
    servingSize: "20g",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: false,
    isOrganic: false,
    isGlutenFree: true,
    isVegan: false,
    proteinSource: "Bovine collagen peptides",
    nutrients: { calories: 70, protein: 18, carbs: 0, fat: 0, sodium: 15 },
    ingredients: "Bovine Hide Collagen Peptides",
    concerns: ["Not third-party tested", "Collagen is not a complete protein (missing tryptophan)"],
    benefits: ["Single ingredient", "Pasture-raised bovine source", "Dissolves easily", "No artificial anything"],
    buyTip: "Best mainstream collagen. Single ingredient, pasture-raised. Not a complete protein — don't count toward protein goals.",
    averagePrice: 29.99,
    imageUrl: "/manus-storage/vital-proteins-collagen_0046d3da.jpg",
  },
  {
    id: "ancient-nutrition-collagen",
    name: "Multi Collagen Protein",
    brand: "Ancient Nutrition",
    category: "collagen",
    score: 80,
    qualityTier: "good",
    barcode: "0816401025013",
    servingSize: "10g",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: false,
    isOrganic: false,
    isGlutenFree: true,
    isVegan: false,
    proteinSource: "Bovine, chicken, fish, eggshell collagen",
    nutrients: { calories: 35, protein: 9, carbs: 0, fat: 0, sodium: 15 },
    ingredients: "Hydrolyzed Bovine Hide Collagen Peptides, Chicken Bone Broth Collagen Concentrate, Hydrolyzed Fish Collagen Peptides, Eggshell Membrane Collagen",
    concerns: ["Not third-party tested", "Multiple sources may reduce potency per type"],
    benefits: ["5 types of collagen (I, II, III, V, X)", "No artificial ingredients", "Diverse collagen sources"],
    buyTip: "Good multi-source collagen. Types I and III for skin/hair, Type II for joints.",
    averagePrice: 34.99,
    imageUrl: "/manus-storage/ancient-nutrition-collagen_b9d7bd0c.jpg",
  },

  // ─── PROBIOTICS ───────────────────────────────────────────────────────────
  {
    id: "seed-ds01",
    name: "DS-01 Daily Synbiotic",
    brand: "Seed",
    category: "probiotics",
    score: 94,
    qualityTier: "elite",
    barcode: "0850009474015",
    servingSize: "2 capsules",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: false,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "Clinically studied strains",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 0 },
    ingredients: "24 clinically studied probiotic strains (53.6B AFU), Prebiotic blend (Indian pomegranate, Scandinavian chaga mushroom)",
    concerns: ["Expensive ($50/month)", "Subscription model"],
    benefits: ["24 clinically studied strains", "Nested capsule protects through stomach acid", "Prebiotic included", "Transparent strain documentation"],
    buyTip: "Best probiotic on the market. Nested capsule technology ensures strains survive to the gut.",
    averagePrice: 49.99,
    imageUrl: "/manus-storage/seed-ds01_3b20ca42.jpg",
  },
  {
    id: "culturelle-probiotic",
    name: "Digestive Daily Probiotic",
    brand: "Culturelle",
    category: "probiotics",
    score: 68,
    qualityTier: "good",
    barcode: "0049100002282",
    servingSize: "1 capsule",
    hasArtificialSweeteners: false,
    hasSucralose: false,
    hasAcesulfameK: false,
    hasAspartame: false,
    hasMaltodextrin: true,
    hasProprietary: false,
    hasSoyLecithin: false,
    hasSeedOilDerived: false,
    hasArtificialColors: false,
    hasHeavyMetalRisk: false,
    isThirdPartyTested: true,
    testingCert: "USP Verified",
    isOrganic: false,
    isGlutenFree: true,
    isVegan: true,
    nutrients: { calories: 0 },
    ingredients: "Lactobacillus rhamnosus GG (10B CFU), Inulin (prebiotic), Maltodextrin, Hydroxypropyl Methylcellulose",
    concerns: ["Only one strain (limited diversity)", "Maltodextrin filler"],
    benefits: ["Most studied probiotic strain (LGG)", "USP Verified", "Affordable", "Widely available"],
    buyTip: "Good budget probiotic. LGG is the most researched strain. Upgrade to Seed for more strain diversity.",
    averagePrice: 24.99,
    imageUrl: "/manus-storage/culturelle-probiotic_e11ebee3.jpg",
  },
];
