/**
 * EatVera — Comprehensive US Vegetable Database
 * Scores based on: EWG Dirty Dozen/Clean Fifteen, pesticide residue data,
 * nutritional density, USDA organic availability, and farming practices.
 */

export type VegetableQualityTier = "elite" | "excellent" | "good" | "fair" | "caution" | "avoid";
export type EWGStatus = "dirty-dozen" | "clean-fifteen" | "moderate" | "clean";

export interface VegetableEntry {
  id: string;
  name: string;
  imageUrl?: string;
  emoji: string;
  category: VegCategory;
  ewgStatus: EWGStatus;
  conventionalScore: number;
  organicScore: number;
  tier: VegetableQualityTier;
  pesticidesFound?: number;      // number of different pesticides detected by EWG
  pesticideRisk: "very-high" | "high" | "moderate" | "low" | "very-low";
  nutritionHighlights: string[];
  concerns: string[];
  buyTip: string;
  averagePrice?: number;
  benefits: string[];
  servingIdea: string;
  calories100g: number;
  keyNutrients: string[];
  /** IFPS PLU codes used at US grocery store checkouts */
  pluCodes: string[];
}

export type VegCategory =
  | "Leafy Greens"
  | "Cruciferous"
  | "Root Vegetables"
  | "Nightshades"
  | "Alliums"
  | "Legumes"
  | "Squash & Gourds"
  | "Stalks & Stems"
  | "Mushrooms"
  | "Sea Vegetables"
  | "Frozen & Canned"
  | "Herbs";

export const VEG_CATEGORIES: VegCategory[] = [
  "Leafy Greens", "Cruciferous", "Root Vegetables", "Nightshades",
  "Alliums", "Legumes", "Squash & Gourds", "Stalks & Stems",
  "Mushrooms", "Sea Vegetables", "Frozen & Canned", "Herbs"
];

export const VEG_QUALITY_TIER_CONFIG: Record<VegetableQualityTier, { label: string; color: string; bg: string; description: string }> = {
  elite:     { label: "Elite",     color: "#145A3A", bg: "#F0FAF2", description: "Exceptional nutrition, very low pesticide risk" },
  excellent: { label: "Excellent", color: "#3FA34D", bg: "#DCF4DF", description: "High nutrition, low pesticide exposure" },
  good:      { label: "Good",      color: "#4ade80", bg: "#f0fdf4", description: "Good nutrition, moderate pesticide risk" },
  fair:      { label: "Fair",      color: "#d97706", bg: "#fffbf0", description: "Decent nutrition but notable pesticide concerns" },
  caution:   { label: "Caution",   color: "#ea580c", bg: "#fff7ed", description: "High pesticide residues — buy organic when possible" },
  avoid:     { label: "Avoid",     color: "#dc2626", bg: "#fff5f5", description: "Very high pesticide load — always buy organic" },
};

export const ALL_VEGETABLES: VegetableEntry[] = [
  // ── LEAFY GREENS ─────────────────────────────────────────────────────────
  {
    id: "spinach",
    name: "Spinach",
    imageUrl: "/manus-storage/spinach_8393c16b.png",
    emoji: "🥬",
    category: "Leafy Greens",
    ewgStatus: "dirty-dozen",
    conventionalScore: 28,
    organicScore: 91,
    tier: "avoid",
    pesticidesFound: 103,
    pesticideRisk: "very-high",
    nutritionHighlights: ["Iron", "Folate", "Vitamin K", "Magnesium", "Lutein"],
    concerns: ["#1 on EWG Dirty Dozen 2024", "103 different pesticides detected", "Permethrin (neurotoxin) commonly found"],
    buyTip: "Always buy organic — spinach absorbs pesticides deeply into its leaves and cannot be washed off.",
    benefits: ["Powerful antioxidants", "Bone health (Vitamin K)", "Anti-inflammatory", "Eye health (lutein/zeaxanthin)"],
    servingIdea: "Sauté with garlic and olive oil, or blend into smoothies",
    calories100g: 23,
    keyNutrients: ["Vitamin K", "Folate", "Iron", "Vitamin A", "Manganese"],
    pluCodes: ["3083", "4083", "94083"],
  },
  {
    id: "kale",
    name: "Kale",
    imageUrl: "/manus-storage/kale_8a6b2444.jpg",
    emoji: "🥬",
    category: "Leafy Greens",
    ewgStatus: "dirty-dozen",
    conventionalScore: 32,
    organicScore: 93,
    tier: "avoid",
    pesticidesFound: 92,
    pesticideRisk: "very-high",
    nutritionHighlights: ["Vitamin K", "Vitamin C", "Calcium", "Antioxidants"],
    concerns: ["Top 3 on EWG Dirty Dozen", "92 pesticides detected", "DCPA (potential carcinogen) found in 75% of samples"],
    buyTip: "One of the most pesticide-contaminated vegetables — always buy organic or grow your own.",
    benefits: ["Highest Vitamin K of any vegetable", "Cancer-fighting glucosinolates", "Bone density support", "Powerful antioxidants"],
    servingIdea: "Massage with olive oil and lemon for a raw salad, or roast into chips",
    calories100g: 35,
    keyNutrients: ["Vitamin K", "Vitamin C", "Vitamin A", "Calcium", "Manganese"],
    pluCodes: ["3627", "4627", "94627"],
  },
  {
    id: "collard-greens",
    name: "Collard Greens",
    imageUrl: "/manus-storage/collard_greens_a1c58688.jpg",
    emoji: "🥬",
    category: "Leafy Greens",
    ewgStatus: "dirty-dozen",
    conventionalScore: 33,
    organicScore: 92,
    tier: "avoid",
    pesticidesFound: 85,
    pesticideRisk: "very-high",
    nutritionHighlights: ["Vitamin K", "Vitamin C", "Folate", "Calcium"],
    concerns: ["On EWG Dirty Dozen 2024", "Organophosphate insecticides commonly detected"],
    buyTip: "Buy organic — collards are heavily sprayed. Frozen organic is a great budget option.",
    benefits: ["Exceptional Vitamin K", "Cholesterol-lowering fiber", "Anti-cancer compounds", "High calcium for a vegetable"],
    servingIdea: "Slow-braise with pastured bacon and apple cider vinegar",
    calories100g: 32,
    keyNutrients: ["Vitamin K", "Vitamin C", "Folate", "Calcium", "Vitamin A"],
    pluCodes: ["3158", "4158"],
  },
  {
    id: "mustard-greens",
    name: "Mustard Greens",
    imageUrl: "/manus-storage/mustard_greens_e5e8dc64.jpg",
    emoji: "🥬",
    category: "Leafy Greens",
    ewgStatus: "dirty-dozen",
    conventionalScore: 34,
    organicScore: 91,
    tier: "avoid",
    pesticidesFound: 80,
    pesticideRisk: "very-high",
    nutritionHighlights: ["Vitamin K", "Vitamin C", "Folate"],
    concerns: ["On EWG Dirty Dozen 2024", "High pesticide residue levels"],
    buyTip: "Buy organic. Mustard greens are in the same high-risk category as kale and collards.",
    benefits: ["Detoxification support", "Anti-inflammatory glucosinolates", "High antioxidant capacity"],
    servingIdea: "Sauté with garlic, ginger, and sesame oil",
    calories100g: 27,
    keyNutrients: ["Vitamin K", "Vitamin C", "Vitamin A", "Folate"],
    pluCodes: ["3168", "4168"],
  },
  {
    id: "romaine-lettuce",
    name: "Romaine Lettuce",
    imageUrl: "/manus-storage/romaine_lettuce_8be1bc37.jpg",
    emoji: "🥗",
    category: "Leafy Greens",
    ewgStatus: "moderate",
    conventionalScore: 55,
    organicScore: 88,
    tier: "fair",
    pesticidesFound: 45,
    pesticideRisk: "moderate",
    nutritionHighlights: ["Vitamin K", "Folate", "Vitamin A", "Vitamin C"],
    concerns: ["Moderate pesticide residues", "E. coli contamination risk if not washed"],
    buyTip: "Organic preferred but conventional is acceptable if washed thoroughly.",
    benefits: ["High water content for hydration", "Good source of folate", "Low calorie, high volume"],
    servingIdea: "Caesar salad with homemade dressing, or as taco wraps",
    calories100g: 17,
    keyNutrients: ["Vitamin K", "Folate", "Vitamin A", "Vitamin C"],
    pluCodes: ["3055", "4055", "94055"],
  },
  {
    id: "arugula",
    name: "Arugula",
    imageUrl: "/manus-storage/arugula_7dcb3f94.png",
    emoji: "🥗",
    category: "Leafy Greens",
    ewgStatus: "clean",
    conventionalScore: 72,
    organicScore: 94,
    tier: "good",
    pesticidesFound: 18,
    pesticideRisk: "low",
    nutritionHighlights: ["Vitamin K", "Folate", "Calcium", "Nitrates (good)"],
    concerns: ["Moderate pesticide residues on some samples"],
    buyTip: "Conventional is generally acceptable. Organic preferred for frequent use.",
    benefits: ["High nitrate content supports athletic performance", "Peppery flavor from glucosinolates", "Digestive support"],
    servingIdea: "Top pizzas, pasta, or pair with prosciutto and parmesan",
    calories100g: 25,
    keyNutrients: ["Vitamin K", "Folate", "Calcium", "Vitamin A"],
    pluCodes: ["3632", "4632"],
  },
  {
    id: "swiss-chard",
    name: "Swiss Chard",
    imageUrl: "/manus-storage/swiss_chard_fa5a671a.jpg",
    emoji: "🥬",
    category: "Leafy Greens",
    ewgStatus: "moderate",
    conventionalScore: 60,
    organicScore: 90,
    tier: "fair",
    pesticidesFound: 35,
    pesticideRisk: "moderate",
    nutritionHighlights: ["Vitamin K", "Magnesium", "Potassium", "Iron"],
    concerns: ["Moderate pesticide residues", "High oxalate content (kidney stone risk if eaten in excess)"],
    buyTip: "Organic preferred. Rotate with other greens to avoid oxalate buildup.",
    benefits: ["Blood sugar regulation", "Bone health", "Excellent magnesium source"],
    servingIdea: "Sauté the stems first, then add leaves with garlic and olive oil",
    calories100g: 19,
    keyNutrients: ["Vitamin K", "Vitamin A", "Vitamin C", "Magnesium", "Iron"],
    pluCodes: ["3093", "4093"],
  },
  {
    id: "watercress",
    name: "Watercress",
    imageUrl: "/manus-storage/watercress_9847b3ae.jpg",
    emoji: "🌿",
    category: "Leafy Greens",
    ewgStatus: "clean",
    conventionalScore: 78,
    organicScore: 95,
    tier: "excellent",
    pesticidesFound: 12,
    pesticideRisk: "low",
    nutritionHighlights: ["Vitamin K", "Vitamin C", "Calcium", "PEITC (anti-cancer)"],
    concerns: ["Grows in water — potential contamination if not from clean source"],
    buyTip: "Buy from reputable sources. Watercress is generally low in pesticides.",
    benefits: ["Highest nutrient density of any vegetable (CDC)", "PEITC compound fights cancer", "Bone health"],
    servingIdea: "Add to salads, sandwiches, or blend into green soups",
    calories100g: 11,
    keyNutrients: ["Vitamin K", "Vitamin C", "Calcium", "Vitamin A"],
    pluCodes: ["3092", "4092"],
  },

  // ── CRUCIFEROUS ──────────────────────────────────────────────────────────
  {
    id: "broccoli",
    name: "Broccoli",
    imageUrl: "/manus-storage/broccoli_c8af67fc.jpg",
    emoji: "🥦",
    category: "Cruciferous",
    ewgStatus: "clean-fifteen",
    conventionalScore: 82,
    organicScore: 96,
    tier: "excellent",
    pesticidesFound: 8,
    pesticideRisk: "low",
    nutritionHighlights: ["Sulforaphane", "Vitamin C", "Vitamin K", "Folate", "Fiber"],
    concerns: ["Very low pesticide risk", "Wash thoroughly to remove any surface residues"],
    buyTip: "Conventional broccoli is safe. Organic is a bonus but not necessary.",
    benefits: ["Sulforaphane is one of the most studied anti-cancer compounds", "Supports detoxification", "Excellent Vitamin C source"],
    servingIdea: "Roast at 425°F with olive oil and garlic until crispy",
    calories100g: 34,
    keyNutrients: ["Vitamin C", "Vitamin K", "Folate", "Sulforaphane", "Fiber"],
    pluCodes: ["3082", "4082", "94082"],
  },
  {
    id: "cauliflower",
    name: "Cauliflower",
    imageUrl: "/manus-storage/cauliflower_8b5a7f7b.jpg",
    emoji: "🥦",
    category: "Cruciferous",
    ewgStatus: "clean-fifteen",
    conventionalScore: 80,
    organicScore: 94,
    tier: "excellent",
    pesticidesFound: 7,
    pesticideRisk: "low",
    nutritionHighlights: ["Vitamin C", "Vitamin K", "Choline", "Fiber"],
    concerns: ["Very low pesticide risk"],
    buyTip: "Conventional is fine. One of the safest vegetables to buy non-organic.",
    benefits: ["Versatile low-carb substitute (rice, pizza crust)", "Choline for brain health", "Anti-inflammatory"],
    servingIdea: "Roast whole with turmeric and olive oil, or rice it as a grain substitute",
    calories100g: 25,
    keyNutrients: ["Vitamin C", "Vitamin K", "Choline", "Folate"],
    pluCodes: ["3149", "4149", "94149"],
  },
  {
    id: "brussels-sprouts",
    name: "Brussels Sprouts",
    imageUrl: "/manus-storage/brussels_sprouts_450f1536.jpg",
    emoji: "🥦",
    category: "Cruciferous",
    ewgStatus: "clean",
    conventionalScore: 78,
    organicScore: 93,
    tier: "excellent",
    pesticidesFound: 10,
    pesticideRisk: "low",
    nutritionHighlights: ["Vitamin K", "Vitamin C", "Folate", "Glucosinolates"],
    concerns: ["Low pesticide risk", "Can cause gas if eaten in large amounts"],
    buyTip: "Conventional is generally safe. Organic preferred for regular consumption.",
    benefits: ["Cancer-fighting glucosinolates", "Excellent Vitamin K", "Gut health fiber"],
    servingIdea: "Halve and roast at 425°F with balsamic glaze and bacon",
    calories100g: 43,
    keyNutrients: ["Vitamin K", "Vitamin C", "Folate", "Manganese"],
    pluCodes: ["3310", "4310", "94310"],
  },
  {
    id: "cabbage",
    name: "Cabbage",
    imageUrl: "/manus-storage/cabbage_a5f9450d.jpg",
    emoji: "🥬",
    category: "Cruciferous",
    ewgStatus: "clean-fifteen",
    conventionalScore: 85,
    organicScore: 96,
    tier: "excellent",
    pesticidesFound: 5,
    pesticideRisk: "very-low",
    nutritionHighlights: ["Vitamin K", "Vitamin C", "Fiber", "Glutamine"],
    concerns: ["Very low pesticide risk — outer leaves protect inner leaves"],
    buyTip: "Conventional cabbage is very safe. One of the best budget vegetables.",
    benefits: ["Gut healing (glutamine)", "Ferments into probiotic-rich sauerkraut/kimchi", "Anti-ulcer properties"],
    servingIdea: "Ferment into sauerkraut or shred for coleslaw with apple cider vinegar",
    calories100g: 25,
    keyNutrients: ["Vitamin K", "Vitamin C", "Folate", "Fiber"],
    pluCodes: ["3089", "4089"],
  },
  {
    id: "bok-choy",
    name: "Bok Choy",
    imageUrl: "/manus-storage/bok_choy_6dc7a14a.jpg",
    emoji: "🥬",
    category: "Cruciferous",
    ewgStatus: "clean",
    conventionalScore: 75,
    organicScore: 92,
    tier: "excellent",
    pesticidesFound: 14,
    pesticideRisk: "low",
    nutritionHighlights: ["Vitamin A", "Vitamin C", "Vitamin K", "Calcium"],
    concerns: ["Low pesticide risk", "Contains goitrogens (thyroid concern if eaten raw in excess)"],
    buyTip: "Conventional is acceptable. Cook to reduce goitrogen content.",
    benefits: ["Excellent calcium source for a vegetable", "Anti-cancer glucosinolates", "Eye health"],
    servingIdea: "Stir-fry with ginger, garlic, and coconut aminos",
    calories100g: 13,
    keyNutrients: ["Vitamin A", "Vitamin C", "Vitamin K", "Calcium"],
    pluCodes: ["3170", "4170"],
  },
  {
    id: "radishes",
    name: "Radishes",
    imageUrl: "/manus-storage/radishes_2bc17f48.jpg",
    emoji: "🌶️",
    category: "Cruciferous",
    ewgStatus: "clean",
    conventionalScore: 80,
    organicScore: 93,
    tier: "excellent",
    pesticidesFound: 9,
    pesticideRisk: "low",
    nutritionHighlights: ["Vitamin C", "Folate", "Fiber", "Potassium"],
    concerns: ["Low pesticide risk"],
    buyTip: "Conventional radishes are safe and affordable.",
    benefits: ["Liver detoxification support", "Digestive enzyme stimulation", "Anti-fungal properties"],
    servingIdea: "Slice thin for tacos, pickle in apple cider vinegar, or roast",
    calories100g: 16,
    keyNutrients: ["Vitamin C", "Folate", "Potassium", "Fiber"],
    pluCodes: ["3085", "4085"],
  },

  // ── ROOT VEGETABLES ──────────────────────────────────────────────────────
  {
    id: "sweet-potato",
    name: "Sweet Potato",
    imageUrl: "/manus-storage/sweet_potato_8a30331f.jpg",
    emoji: "🍠",
    category: "Root Vegetables",
    ewgStatus: "clean-fifteen",
    conventionalScore: 84,
    organicScore: 95,
    tier: "excellent",
    pesticidesFound: 6,
    pesticideRisk: "very-low",
    nutritionHighlights: ["Beta-carotene", "Vitamin A", "Potassium", "Fiber", "Vitamin B6"],
    concerns: ["Very low pesticide risk", "High glycemic index — portion control for diabetics"],
    buyTip: "Conventional sweet potatoes are very safe. One of the best value vegetables.",
    benefits: ["Exceptional beta-carotene (Vitamin A precursor)", "Blood sugar stabilization (resistant starch)", "Anti-inflammatory"],
    servingIdea: "Bake whole, or cube and roast with cinnamon and coconut oil",
    calories100g: 86,
    keyNutrients: ["Vitamin A", "Potassium", "Vitamin B6", "Fiber", "Manganese"],
    pluCodes: ["3033", "4033", "94033"],
  },
  {
    id: "carrots",
    name: "Carrots",
    imageUrl: "/manus-storage/carrots_1c59b830.jpg",
    emoji: "🥕",
    category: "Root Vegetables",
    ewgStatus: "moderate",
    conventionalScore: 65,
    organicScore: 90,
    tier: "good",
    pesticidesFound: 28,
    pesticideRisk: "moderate",
    nutritionHighlights: ["Beta-carotene", "Vitamin K", "Potassium", "Fiber"],
    concerns: ["Moderate pesticide residues", "Absorb pesticides from soil"],
    buyTip: "Organic preferred since carrots grow in soil and absorb pesticides. Baby carrots especially.",
    benefits: ["Highest beta-carotene of common vegetables", "Eye health (lutein)", "Gut health fiber"],
    servingIdea: "Roast with honey and thyme, or eat raw with hummus",
    calories100g: 41,
    keyNutrients: ["Vitamin A", "Vitamin K", "Potassium", "Fiber", "Biotin"],
    pluCodes: ["3058", "4058", "94058"],
  },
  {
    id: "beets",
    name: "Beets",
    imageUrl: "/manus-storage/beets_cfa18774.jpg",
    emoji: "🫐",
    category: "Root Vegetables",
    ewgStatus: "moderate",
    conventionalScore: 62,
    organicScore: 88,
    tier: "fair",
    pesticidesFound: 30,
    pesticideRisk: "moderate",
    nutritionHighlights: ["Nitrates", "Folate", "Manganese", "Betalains"],
    concerns: ["Moderate pesticide residues", "High sugar content — limit for diabetics"],
    buyTip: "Organic preferred. Beets absorb soil pesticides like carrots.",
    benefits: ["Nitrates boost athletic endurance", "Betalains are powerful antioxidants", "Liver detox support"],
    servingIdea: "Roast and pair with goat cheese and walnuts, or juice with ginger",
    calories100g: 43,
    keyNutrients: ["Folate", "Manganese", "Potassium", "Nitrates", "Betalains"],
    pluCodes: ["3082", "4082"],
  },
  {
    id: "turnips",
    name: "Turnips",
    imageUrl: "/manus-storage/turnips_755ddd4b.jpg",
    emoji: "🫚",
    category: "Root Vegetables",
    ewgStatus: "clean",
    conventionalScore: 78,
    organicScore: 92,
    tier: "excellent",
    pesticidesFound: 10,
    pesticideRisk: "low",
    nutritionHighlights: ["Vitamin C", "Fiber", "Potassium", "Glucosinolates"],
    concerns: ["Low pesticide risk"],
    buyTip: "Conventional turnips are safe and very affordable.",
    benefits: ["Low calorie root vegetable", "Anti-cancer glucosinolates", "Good fiber source"],
    servingIdea: "Mash with butter as a low-carb potato substitute",
    calories100g: 28,
    keyNutrients: ["Vitamin C", "Fiber", "Potassium", "Folate"],
    pluCodes: ["3088", "4088"],
  },
  {
    id: "parsnips",
    name: "Parsnips",
    imageUrl: "/manus-storage/parsnips_dbfa6db3.jpg",
    emoji: "🌽",
    category: "Root Vegetables",
    ewgStatus: "clean",
    conventionalScore: 76,
    organicScore: 91,
    tier: "excellent",
    pesticidesFound: 11,
    pesticideRisk: "low",
    nutritionHighlights: ["Fiber", "Folate", "Vitamin C", "Potassium"],
    concerns: ["Low pesticide risk", "Higher carb content than other root vegetables"],
    buyTip: "Conventional parsnips are generally safe.",
    benefits: ["High fiber for gut health", "Prebiotic fiber feeds good bacteria", "Immune support"],
    servingIdea: "Roast with olive oil and rosemary, or add to soups",
    calories100g: 75,
    keyNutrients: ["Fiber", "Folate", "Vitamin C", "Potassium", "Manganese"],
    pluCodes: ["3088", "4088"],
  },
  {
    id: "potatoes",
    name: "Potatoes",
    imageUrl: "/manus-storage/potatoes_6d39772b.jpg",
    emoji: "🥔",
    category: "Root Vegetables",
    ewgStatus: "dirty-dozen",
    conventionalScore: 38,
    organicScore: 82,
    tier: "caution",
    pesticidesFound: 35,
    pesticideRisk: "high",
    nutritionHighlights: ["Potassium", "Vitamin B6", "Vitamin C", "Resistant Starch"],
    concerns: ["On EWG Dirty Dozen", "Chlorpropham (sprout inhibitor) commonly found", "High glycemic index"],
    buyTip: "Buy organic or peel conventional potatoes — most pesticides are in the skin.",
    benefits: ["Highest potassium of common vegetables", "Resistant starch (when cooled) feeds gut bacteria", "Vitamin B6 for brain health"],
    servingIdea: "Boil, cool overnight for resistant starch, then reheat and eat",
    calories100g: 77,
    keyNutrients: ["Potassium", "Vitamin B6", "Vitamin C", "Resistant Starch"],
    pluCodes: ["4072", "3072", "4073", "3073"],
  },

  // ── NIGHTSHADES ──────────────────────────────────────────────────────────
  {
    id: "bell-peppers",
    name: "Bell Peppers",
    imageUrl: "/manus-storage/bell_peppers_f447d1bc.jpg",
    emoji: "🫑",
    category: "Nightshades",
    ewgStatus: "dirty-dozen",
    conventionalScore: 30,
    organicScore: 90,
    tier: "avoid",
    pesticidesFound: 101,
    pesticideRisk: "very-high",
    nutritionHighlights: ["Vitamin C", "Vitamin A", "Vitamin B6", "Antioxidants"],
    concerns: ["#2 on EWG Dirty Dozen 2024", "101 different pesticides detected", "Acephate (neurotoxin) commonly found"],
    buyTip: "Always buy organic bell peppers — they are the second most contaminated vegetable.",
    benefits: ["Highest Vitamin C of any vegetable (red peppers)", "Capsanthin antioxidant", "Eye health"],
    servingIdea: "Roast and stuff with ground beef and cauliflower rice",
    calories100g: 31,
    keyNutrients: ["Vitamin C", "Vitamin A", "Vitamin B6", "Folate"],
    pluCodes: ["3101", "4101", "94101"],
  },
  {
    id: "tomatoes",
    name: "Tomatoes",
    imageUrl: "/manus-storage/tomatoes_9d26e336.jpg",
    emoji: "🍅",
    category: "Nightshades",
    ewgStatus: "moderate",
    conventionalScore: 55,
    organicScore: 87,
    tier: "fair",
    pesticidesFound: 40,
    pesticideRisk: "moderate",
    nutritionHighlights: ["Lycopene", "Vitamin C", "Potassium", "Folate"],
    concerns: ["Moderate pesticide residues", "Cherry tomatoes have higher residue than large tomatoes"],
    buyTip: "Organic preferred, especially for cherry tomatoes. Cooking increases lycopene absorption.",
    benefits: ["Lycopene is a powerful anti-cancer antioxidant", "Heart health", "Skin protection from UV"],
    servingIdea: "Slow-roast with olive oil and herbs to concentrate lycopene",
    calories100g: 18,
    keyNutrients: ["Lycopene", "Vitamin C", "Potassium", "Folate", "Vitamin K"],
    pluCodes: ["3664", "4664", "94664"],
  },
  {
    id: "eggplant",
    name: "Eggplant",
    imageUrl: "/manus-storage/eggplant_f33feb81.jpg",
    emoji: "🍆",
    category: "Nightshades",
    ewgStatus: "clean",
    conventionalScore: 72,
    organicScore: 90,
    tier: "good",
    pesticidesFound: 16,
    pesticideRisk: "low",
    nutritionHighlights: ["Nasunin (antioxidant)", "Fiber", "Manganese", "Folate"],
    concerns: ["Low pesticide risk", "Nightshade — some people with autoimmune issues are sensitive"],
    buyTip: "Conventional eggplant is generally safe.",
    benefits: ["Nasunin protects brain cell membranes", "High fiber for gut health", "Low calorie"],
    servingIdea: "Grill with olive oil and za'atar, or make baba ganoush",
    calories100g: 25,
    keyNutrients: ["Fiber", "Manganese", "Folate", "Nasunin"],
    pluCodes: ["3087", "4087"],
  },
  {
    id: "hot-peppers",
    name: "Hot Peppers (Jalapeño/Chili)",
    imageUrl: "/manus-storage/hot_peppers_jalape_o_chili_10f9c39f.jpg",
    emoji: "🌶️",
    category: "Nightshades",
    ewgStatus: "dirty-dozen",
    conventionalScore: 35,
    organicScore: 88,
    tier: "caution",
    pesticidesFound: 65,
    pesticideRisk: "high",
    nutritionHighlights: ["Capsaicin", "Vitamin C", "Vitamin A"],
    concerns: ["On EWG Dirty Dozen 2024", "High pesticide residues similar to bell peppers"],
    buyTip: "Buy organic hot peppers when possible, especially if eating the skin.",
    benefits: ["Capsaicin boosts metabolism", "Pain relief (topical)", "Anti-inflammatory"],
    servingIdea: "Ferment into hot sauce or add to salsas",
    calories100g: 40,
    keyNutrients: ["Vitamin C", "Vitamin A", "Capsaicin"],
    pluCodes: ["3101", "4101"],
  },

  // ── ALLIUMS ──────────────────────────────────────────────────────────────
  {
    id: "garlic",
    name: "Garlic",
    imageUrl: "/manus-storage/garlic_0f128135.jpg",
    emoji: "🧄",
    category: "Alliums",
    ewgStatus: "clean-fifteen",
    conventionalScore: 90,
    organicScore: 97,
    tier: "elite",
    pesticidesFound: 2,
    pesticideRisk: "very-low",
    nutritionHighlights: ["Allicin", "Manganese", "Vitamin B6", "Selenium"],
    concerns: ["Very low pesticide risk — papery skin protects cloves"],
    buyTip: "Conventional garlic is very safe. One of the best foods you can eat.",
    benefits: ["Allicin is a powerful antibiotic and antiviral", "Cardiovascular protection", "Immune system booster", "Anti-cancer properties"],
    servingIdea: "Crush and let sit 10 minutes before cooking to maximize allicin",
    calories100g: 149,
    keyNutrients: ["Allicin", "Manganese", "Vitamin B6", "Selenium", "Vitamin C"],
    pluCodes: ["3059", "4059", "94059"],
  },
  {
    id: "onions",
    name: "Onions",
    imageUrl: "/manus-storage/onions_0faf062e.jpg",
    emoji: "🧅",
    category: "Alliums",
    ewgStatus: "clean-fifteen",
    conventionalScore: 88,
    organicScore: 96,
    tier: "elite",
    pesticidesFound: 3,
    pesticideRisk: "very-low",
    nutritionHighlights: ["Quercetin", "Fiber", "Vitamin C", "Folate"],
    concerns: ["Very low pesticide risk — papery skin provides protection"],
    buyTip: "Conventional onions are very safe. One of the Clean Fifteen.",
    benefits: ["Quercetin is a powerful anti-inflammatory and antihistamine", "Prebiotic fiber", "Heart health", "Anti-cancer"],
    servingIdea: "Caramelize slowly for 45 minutes to develop natural sweetness",
    calories100g: 40,
    keyNutrients: ["Quercetin", "Fiber", "Vitamin C", "Folate", "Potassium"],
    pluCodes: ["3084", "4084", "94084"],
  },
  {
    id: "leeks",
    name: "Leeks",
    imageUrl: "/manus-storage/leeks_df08b036.jpg",
    emoji: "🌿",
    category: "Alliums",
    ewgStatus: "moderate",
    conventionalScore: 65,
    organicScore: 88,
    tier: "good",
    pesticidesFound: 25,
    pesticideRisk: "moderate",
    nutritionHighlights: ["Vitamin K", "Folate", "Manganese", "Prebiotic fiber"],
    concerns: ["Moderate pesticide residues in the green tops"],
    buyTip: "Organic preferred. Wash thoroughly between layers.",
    benefits: ["Excellent prebiotic fiber (inulin)", "Folate for heart health", "Kaempferol antioxidant"],
    servingIdea: "Braise in butter and white wine, or add to potato soup",
    calories100g: 61,
    keyNutrients: ["Vitamin K", "Folate", "Manganese", "Vitamin A"],
    pluCodes: ["3169", "4169"],
  },
  {
    id: "shallots",
    name: "Shallots",
    imageUrl: "/manus-storage/shallots_2929bb44.jpg",
    emoji: "🧅",
    category: "Alliums",
    ewgStatus: "clean",
    conventionalScore: 82,
    organicScore: 94,
    tier: "excellent",
    pesticidesFound: 8,
    pesticideRisk: "low",
    nutritionHighlights: ["Quercetin", "Allicin", "Vitamin B6", "Potassium"],
    concerns: ["Low pesticide risk"],
    buyTip: "Conventional shallots are generally safe.",
    benefits: ["Higher quercetin than onions", "Antimicrobial properties", "Cardiovascular support"],
    servingIdea: "Mince and use as a base for vinaigrettes and pan sauces",
    calories100g: 72,
    keyNutrients: ["Quercetin", "Allicin", "Vitamin B6", "Potassium"],
    pluCodes: ["3169", "4169"],
  },
  {
    id: "scallions",
    name: "Scallions (Green Onions)",
    imageUrl: "/manus-storage/scallions_green_onions_d95423bc.jpg",
    emoji: "🌿",
    category: "Alliums",
    ewgStatus: "moderate",
    conventionalScore: 62,
    organicScore: 87,
    tier: "fair",
    pesticidesFound: 32,
    pesticideRisk: "moderate",
    nutritionHighlights: ["Vitamin K", "Vitamin C", "Folate"],
    concerns: ["Moderate pesticide residues"],
    buyTip: "Organic preferred for raw use. Conventional acceptable if cooked.",
    benefits: ["Vitamin K for bone health", "Allicin antimicrobial", "Low calorie flavor booster"],
    servingIdea: "Garnish soups, stir-fries, and egg dishes",
    calories100g: 32,
    keyNutrients: ["Vitamin K", "Vitamin C", "Folate"],
    pluCodes: ["3169", "4169"],
  },

  // ── LEGUMES ──────────────────────────────────────────────────────────────
  {
    id: "green-beans",
    name: "Green Beans (String Beans)",
    imageUrl: "/manus-storage/green_beans_string_beans_45af9e4d.jpg",
    emoji: "🫘",
    category: "Legumes",
    ewgStatus: "dirty-dozen",
    conventionalScore: 36,
    organicScore: 88,
    tier: "caution",
    pesticidesFound: 84,
    pesticideRisk: "high",
    nutritionHighlights: ["Vitamin K", "Vitamin C", "Folate", "Fiber"],
    concerns: ["On EWG Dirty Dozen 2024", "Acephate and methamidophos (neurotoxins) commonly found"],
    buyTip: "Buy organic green beans — they are heavily sprayed with neurotoxic pesticides.",
    benefits: ["Good Vitamin K source", "Fiber for gut health", "Chlorophyll antioxidants"],
    servingIdea: "Blanch and sauté with almonds and lemon butter",
    calories100g: 31,
    keyNutrients: ["Vitamin K", "Vitamin C", "Folate", "Fiber", "Manganese"],
    pluCodes: ["3086", "4086", "94086"],
  },
  {
    id: "peas",
    name: "Peas (Fresh/Frozen)",
    imageUrl: "/manus-storage/peas_fresh_frozen_c798f09f.jpg",
    emoji: "🫛",
    category: "Legumes",
    ewgStatus: "clean",
    conventionalScore: 78,
    organicScore: 92,
    tier: "excellent",
    pesticidesFound: 12,
    pesticideRisk: "low",
    nutritionHighlights: ["Protein", "Fiber", "Vitamin K", "Folate", "Thiamine"],
    concerns: ["Low pesticide risk", "Frozen peas are often as nutritious as fresh"],
    buyTip: "Conventional peas are safe. Frozen organic is an excellent budget option.",
    benefits: ["Plant protein source", "Prebiotic fiber", "Lutein for eye health", "Thiamine for energy"],
    servingIdea: "Add to risottos, pasta, or blend into a vibrant green soup",
    calories100g: 81,
    keyNutrients: ["Protein", "Fiber", "Vitamin K", "Folate", "Thiamine"],
    pluCodes: ["3086", "4086"],
  },
  {
    id: "edamame",
    name: "Edamame (Soybeans)",
    imageUrl: "/manus-storage/edamame_soybeans_23851da3.jpg",
    emoji: "🫘",
    category: "Legumes",
    ewgStatus: "moderate",
    conventionalScore: 52,
    organicScore: 80,
    tier: "fair",
    pesticidesFound: 22,
    pesticideRisk: "moderate",
    nutritionHighlights: ["Complete Protein", "Fiber", "Iron", "Calcium", "Isoflavones"],
    concerns: ["Most US soybeans are GMO", "Phytoestrogens (isoflavones) — controversial for hormone-sensitive conditions", "Moderate pesticide residues"],
    buyTip: "Buy organic and non-GMO edamame. Avoid if you have thyroid or hormone issues.",
    benefits: ["Complete plant protein", "High fiber", "Iron for energy"],
    servingIdea: "Steam and sprinkle with sea salt as a snack",
    calories100g: 121,
    keyNutrients: ["Protein", "Fiber", "Iron", "Calcium", "Folate"],
    pluCodes: ["3316", "4316"],
  },

  // ── SQUASH & GOURDS ──────────────────────────────────────────────────────
  {
    id: "zucchini",
    name: "Zucchini (Summer Squash)",
    imageUrl: "/manus-storage/zucchini_summer_squash_875f1b89.jpg",
    emoji: "🥒",
    category: "Squash & Gourds",
    ewgStatus: "moderate",
    conventionalScore: 60,
    organicScore: 87,
    tier: "fair",
    pesticidesFound: 30,
    pesticideRisk: "moderate",
    nutritionHighlights: ["Vitamin C", "Potassium", "Manganese", "Folate"],
    concerns: ["Moderate pesticide residues", "Imidacloprid (bee-killing neonicotinoid) commonly found"],
    buyTip: "Organic preferred, especially for the skin. Conventional is acceptable if peeled.",
    benefits: ["Low calorie, high volume", "Lutein for eye health", "Potassium for blood pressure"],
    servingIdea: "Spiralize into zoodles, grill, or stuff with meat and cheese",
    calories100g: 17,
    keyNutrients: ["Vitamin C", "Potassium", "Manganese", "Folate"],
    pluCodes: ["3099", "4099", "94099"],
  },
  {
    id: "butternut-squash",
    name: "Butternut Squash",
    imageUrl: "/manus-storage/butternut_squash_37c19fb3.jpg",
    emoji: "🎃",
    category: "Squash & Gourds",
    ewgStatus: "clean",
    conventionalScore: 80,
    organicScore: 93,
    tier: "excellent",
    pesticidesFound: 8,
    pesticideRisk: "low",
    nutritionHighlights: ["Beta-carotene", "Vitamin A", "Vitamin C", "Potassium", "Fiber"],
    concerns: ["Low pesticide risk — thick skin protects flesh"],
    buyTip: "Conventional butternut squash is safe. Thick skin protects the flesh.",
    benefits: ["Exceptional beta-carotene", "Anti-inflammatory", "Blood sugar stabilization"],
    servingIdea: "Roast cubed with sage and brown butter, or blend into soup",
    calories100g: 45,
    keyNutrients: ["Vitamin A", "Vitamin C", "Potassium", "Fiber", "Manganese"],
    pluCodes: ["3100", "4100"],
  },
  {
    id: "acorn-squash",
    name: "Acorn Squash",
    imageUrl: "/manus-storage/acorn_squash_13613148.png",
    emoji: "🎃",
    category: "Squash & Gourds",
    ewgStatus: "clean",
    conventionalScore: 79,
    organicScore: 92,
    tier: "excellent",
    pesticidesFound: 7,
    pesticideRisk: "low",
    nutritionHighlights: ["Vitamin C", "Potassium", "Fiber", "Magnesium"],
    concerns: ["Low pesticide risk"],
    buyTip: "Conventional acorn squash is safe.",
    benefits: ["High fiber for gut health", "Potassium for heart health", "Antioxidant-rich"],
    servingIdea: "Halve, brush with butter and maple syrup, roast at 400°F",
    calories100g: 40,
    keyNutrients: ["Vitamin C", "Potassium", "Fiber", "Magnesium"],
    pluCodes: ["3100", "4100"],
  },
  {
    id: "cucumber",
    name: "Cucumber",
    imageUrl: "/manus-storage/cucumber_70e5798a.jpg",
    emoji: "🥒",
    category: "Squash & Gourds",
    ewgStatus: "dirty-dozen",
    conventionalScore: 38,
    organicScore: 86,
    tier: "caution",
    pesticidesFound: 68,
    pesticideRisk: "high",
    nutritionHighlights: ["Vitamin K", "Hydration", "Silica", "Antioxidants"],
    concerns: ["On EWG Dirty Dozen", "Wax coating on conventional cucumbers traps pesticides"],
    buyTip: "Buy organic or peel conventional cucumbers — the wax coating traps pesticides.",
    benefits: ["96% water for hydration", "Silica for skin and joint health", "Cooling anti-inflammatory"],
    servingIdea: "Slice with sea salt and apple cider vinegar, or blend into gazpacho",
    calories100g: 15,
    keyNutrients: ["Vitamin K", "Potassium", "Magnesium", "Silica"],
    pluCodes: ["3097", "4097", "94097"],
  },

  // ── STALKS & STEMS ───────────────────────────────────────────────────────
  {
    id: "celery",
    name: "Celery",
    imageUrl: "/manus-storage/celery_26260031.jpg",
    emoji: "🥬",
    category: "Stalks & Stems",
    ewgStatus: "dirty-dozen",
    conventionalScore: 30,
    organicScore: 89,
    tier: "avoid",
    pesticidesFound: 67,
    pesticideRisk: "very-high",
    nutritionHighlights: ["Vitamin K", "Folate", "Potassium", "Apigenin"],
    concerns: ["Consistently on EWG Dirty Dozen", "67 pesticides detected", "No protective skin — absorbs pesticides directly"],
    buyTip: "Always buy organic celery — it has no protective skin and absorbs pesticides directly.",
    benefits: ["Apigenin has anti-cancer and anti-anxiety properties", "Hydration", "Digestive support"],
    servingIdea: "Eat with almond butter, add to bone broth, or juice with apple and ginger",
    calories100g: 16,
    keyNutrients: ["Vitamin K", "Folate", "Potassium", "Apigenin"],
    pluCodes: ["3083", "4083", "94083"],
  },
  {
    id: "asparagus",
    name: "Asparagus",
    imageUrl: "/manus-storage/asparagus_bd129f66.png",
    emoji: "🌿",
    category: "Stalks & Stems",
    ewgStatus: "clean-fifteen",
    conventionalScore: 85,
    organicScore: 95,
    tier: "excellent",
    pesticidesFound: 5,
    pesticideRisk: "very-low",
    nutritionHighlights: ["Folate", "Vitamin K", "Vitamin E", "Glutathione", "Prebiotic fiber"],
    concerns: ["Very low pesticide risk"],
    buyTip: "Conventional asparagus is very safe. One of the Clean Fifteen.",
    benefits: ["Glutathione — the body's master antioxidant", "Prebiotic inulin fiber", "Folate for DNA repair", "Diuretic for kidney health"],
    servingIdea: "Roast with olive oil and parmesan, or grill and top with a poached egg",
    calories100g: 20,
    keyNutrients: ["Folate", "Vitamin K", "Vitamin E", "Glutathione", "Inulin"],
    pluCodes: ["3080", "4080", "94080"],
  },
  {
    id: "artichokes",
    name: "Artichokes",
    imageUrl: "/manus-storage/artichokes_96f50d21.jpg",
    emoji: "🌿",
    category: "Stalks & Stems",
    ewgStatus: "clean-fifteen",
    conventionalScore: 86,
    organicScore: 95,
    tier: "elite",
    pesticidesFound: 4,
    pesticideRisk: "very-low",
    nutritionHighlights: ["Fiber", "Cynarin", "Silymarin", "Folate", "Magnesium"],
    concerns: ["Very low pesticide risk"],
    buyTip: "Conventional artichokes are very safe. One of the Clean Fifteen.",
    benefits: ["Cynarin and silymarin are the most powerful liver-protective compounds in food", "Highest antioxidant capacity of any vegetable", "Prebiotic fiber"],
    servingIdea: "Steam and dip in garlic aioli, or stuff with breadcrumbs and herbs",
    calories100g: 47,
    keyNutrients: ["Fiber", "Cynarin", "Folate", "Magnesium", "Vitamin C"],
    pluCodes: ["3080", "4080"],
  },
  {
    id: "fennel",
    name: "Fennel",
    imageUrl: "/manus-storage/fennel_4438d330.jpg",
    emoji: "🌿",
    category: "Stalks & Stems",
    ewgStatus: "clean",
    conventionalScore: 76,
    organicScore: 91,
    tier: "excellent",
    pesticidesFound: 12,
    pesticideRisk: "low",
    nutritionHighlights: ["Vitamin C", "Fiber", "Potassium", "Anethole"],
    concerns: ["Low pesticide risk"],
    buyTip: "Conventional fennel is generally safe.",
    benefits: ["Anethole is anti-inflammatory and anti-cancer", "Digestive support", "Estrogen-balancing"],
    servingIdea: "Shave raw into salads with citrus, or roast until caramelized",
    calories100g: 31,
    keyNutrients: ["Vitamin C", "Fiber", "Potassium", "Folate"],
    pluCodes: ["3169", "4169"],
  },

  // ── MUSHROOMS ────────────────────────────────────────────────────────────
  {
    id: "shiitake",
    name: "Shiitake Mushrooms",
    imageUrl: "/manus-storage/shiitake_mushrooms_f0b0c518.jpg",
    emoji: "🍄",
    category: "Mushrooms",
    ewgStatus: "clean",
    conventionalScore: 85,
    organicScore: 95,
    tier: "elite",
    pesticidesFound: 3,
    pesticideRisk: "very-low",
    nutritionHighlights: ["Lentinan (immune)", "Eritadenine (cholesterol)", "Vitamin D", "B vitamins", "Zinc"],
    concerns: ["Very low pesticide risk", "Avoid if on blood thinners (high Vitamin K)"],
    buyTip: "Conventional shiitake is safe. Dried shiitake has concentrated nutrients.",
    benefits: ["Lentinan is a clinically proven immune modulator", "Eritadenine lowers LDL cholesterol", "Vitamin D when sun-dried", "Antiviral properties"],
    servingIdea: "Sauté in butter and thyme, or add to bone broth for immune support",
    calories100g: 34,
    keyNutrients: ["Lentinan", "Eritadenine", "Vitamin D", "Zinc", "B vitamins"],
    pluCodes: ["3281", "4281"],
  },
  {
    id: "portobello",
    name: "Portobello Mushrooms",
    imageUrl: "/manus-storage/portobello_mushrooms_7cfb1662.jpg",
    emoji: "🍄",
    category: "Mushrooms",
    ewgStatus: "clean",
    conventionalScore: 80,
    organicScore: 92,
    tier: "excellent",
    pesticidesFound: 4,
    pesticideRisk: "very-low",
    nutritionHighlights: ["Protein", "Selenium", "Potassium", "B vitamins", "Beta-glucans"],
    concerns: ["Very low pesticide risk", "Grown on substrate — quality varies by producer"],
    buyTip: "Conventional portobello is safe. Look for firm caps without dark spots.",
    benefits: ["Beta-glucans boost immune function", "Selenium for thyroid health", "Meaty texture — great meat substitute"],
    servingIdea: "Grill as a burger patty or stuff with spinach and cheese",
    calories100g: 22,
    keyNutrients: ["Selenium", "Potassium", "B vitamins", "Beta-glucans", "Copper"],
    pluCodes: ["3281", "4281"],
  },
  {
    id: "white-button-mushrooms",
    name: "White Button Mushrooms",
    imageUrl: "/manus-storage/white_button_mushrooms_24d24a7c.jpg",
    emoji: "🍄",
    category: "Mushrooms",
    ewgStatus: "clean",
    conventionalScore: 75,
    organicScore: 89,
    tier: "excellent",
    pesticidesFound: 5,
    pesticideRisk: "very-low",
    nutritionHighlights: ["Selenium", "B vitamins", "Potassium", "Beta-glucans"],
    concerns: ["Very low pesticide risk", "Cook before eating — raw mushrooms contain agaritine (mildly toxic)"],
    buyTip: "Conventional white mushrooms are safe. Always cook before eating.",
    benefits: ["Beta-glucans for immune function", "Selenium for antioxidant defense", "Low calorie, high satiety"],
    servingIdea: "Sauté with garlic and herbs as a side, or add to omelets",
    calories100g: 22,
    keyNutrients: ["Selenium", "B vitamins", "Potassium", "Beta-glucans"],
    pluCodes: ["3281", "4281", "94281"],
  },

  // ── HERBS ────────────────────────────────────────────────────────────────
  {
    id: "cilantro",
    name: "Cilantro",
    imageUrl: "/manus-storage/cilantro_3c1ba2ba.jpg",
    emoji: "🌿",
    category: "Herbs",
    ewgStatus: "dirty-dozen",
    conventionalScore: 28,
    organicScore: 90,
    tier: "avoid",
    pesticidesFound: 72,
    pesticideRisk: "very-high",
    nutritionHighlights: ["Vitamin K", "Vitamin A", "Antioxidants", "Heavy metal chelation"],
    concerns: ["On EWG Dirty Dozen 2024", "72 pesticides detected", "Organophosphates commonly found"],
    buyTip: "Always buy organic cilantro or grow your own. Used in large amounts in cooking.",
    benefits: ["Chelates heavy metals (mercury, lead)", "Antibacterial", "Anti-anxiety compounds"],
    servingIdea: "Add fresh to salsas, curries, and tacos — never cook (destroys flavor)",
    calories100g: 23,
    keyNutrients: ["Vitamin K", "Vitamin A", "Vitamin C"],
    pluCodes: ["3169", "4169"],
  },
  {
    id: "parsley",
    name: "Parsley",
    imageUrl: "/manus-storage/parsley_67c68023.jpg",
    emoji: "🌿",
    category: "Herbs",
    ewgStatus: "moderate",
    conventionalScore: 50,
    organicScore: 88,
    tier: "fair",
    pesticidesFound: 38,
    pesticideRisk: "moderate",
    nutritionHighlights: ["Vitamin K", "Vitamin C", "Apigenin", "Folate"],
    concerns: ["Moderate pesticide residues", "Avoid in large amounts during pregnancy (uterine stimulant)"],
    buyTip: "Organic preferred, especially for fresh use in large quantities.",
    benefits: ["Apigenin is anti-cancer and anti-inflammatory", "Freshens breath", "Diuretic for kidney health"],
    servingIdea: "Make chimichurri with olive oil, garlic, and red wine vinegar",
    calories100g: 36,
    keyNutrients: ["Vitamin K", "Vitamin C", "Folate", "Apigenin"],
    pluCodes: ["3169", "4169"],
  },
  {
    id: "basil",
    name: "Basil",
    imageUrl: "/manus-storage/basil_7d0052f6.jpg",
    emoji: "🌿",
    category: "Herbs",
    ewgStatus: "moderate",
    conventionalScore: 55,
    organicScore: 89,
    tier: "fair",
    pesticidesFound: 30,
    pesticideRisk: "moderate",
    nutritionHighlights: ["Eugenol", "Vitamin K", "Antioxidants", "Anti-inflammatory"],
    concerns: ["Moderate pesticide residues on some samples"],
    buyTip: "Organic preferred for fresh use. Grow your own for best quality.",
    benefits: ["Eugenol is anti-inflammatory and antibacterial", "Adaptogenic properties", "Stress reduction"],
    servingIdea: "Make fresh pesto with olive oil, pine nuts, and parmesan",
    calories100g: 23,
    keyNutrients: ["Vitamin K", "Vitamin A", "Eugenol", "Manganese"],
    pluCodes: ["3169", "4169"],
  },

  // ── FROZEN & CANNED ──────────────────────────────────────────────────────
  {
    id: "frozen-broccoli",
    name: "Frozen Broccoli (Organic)",
    imageUrl: "/manus-storage/frozen_broccoli_organic_57073f77.png",
    emoji: "🥦",
    category: "Frozen & Canned",
    ewgStatus: "clean-fifteen",
    conventionalScore: 80,
    organicScore: 93,
    tier: "excellent",
    pesticidesFound: 3,
    pesticideRisk: "very-low",
    nutritionHighlights: ["Sulforaphane", "Vitamin C", "Vitamin K", "Fiber"],
    concerns: ["Blanching before freezing reduces some water-soluble vitamins by ~10%"],
    buyTip: "Frozen organic broccoli is an excellent value — often more nutritious than fresh that's been stored for days.",
    benefits: ["Flash-frozen at peak nutrition", "Year-round availability", "No waste", "Sulforaphane preserved"],
    servingIdea: "Steam from frozen and toss with olive oil and lemon",
    calories100g: 35,
    keyNutrients: ["Vitamin C", "Vitamin K", "Sulforaphane", "Fiber"],
    pluCodes: ["3082", "4082"],
  },
  {
    id: "canned-tomatoes",
    name: "Canned Tomatoes (BPA-free)",
    imageUrl: "/manus-storage/canned_tomatoes_bpa_free_6dbed65b.jpg",
    emoji: "🍅",
    category: "Frozen & Canned",
    ewgStatus: "moderate",
    conventionalScore: 68,
    organicScore: 85,
    tier: "good",
    pesticidesFound: 15,
    pesticideRisk: "low",
    nutritionHighlights: ["Lycopene", "Vitamin C", "Potassium"],
    concerns: ["BPA in can lining (choose BPA-free brands)", "Cooking concentrates lycopene — actually more bioavailable than fresh"],
    buyTip: "Choose BPA-free canned tomatoes (Muir Glen, Pomi, Eden Organics). Cooking increases lycopene.",
    benefits: ["Higher lycopene than fresh tomatoes", "Convenient year-round", "Budget-friendly"],
    servingIdea: "Use as the base for sauces, soups, and stews",
    calories100g: 20,
    keyNutrients: ["Lycopene", "Vitamin C", "Potassium", "Folate"],
    pluCodes: ["3664", "4664"],
  },
  {
    id: "frozen-peas",
    name: "Frozen Peas",
    imageUrl: "/manus-storage/frozen_peas_eae75d54.jpg",
    emoji: "🫛",
    category: "Frozen & Canned",
    ewgStatus: "clean",
    conventionalScore: 76,
    organicScore: 90,
    tier: "excellent",
    pesticidesFound: 8,
    pesticideRisk: "low",
    nutritionHighlights: ["Protein", "Fiber", "Vitamin K", "Folate"],
    concerns: ["Low pesticide risk", "Blanching reduces some vitamins slightly"],
    buyTip: "Frozen peas are an excellent budget vegetable — nutritionally comparable to fresh.",
    benefits: ["Plant protein", "Prebiotic fiber", "Lutein for eye health"],
    servingIdea: "Add to pasta, rice dishes, or blend into a vibrant pea soup",
    calories100g: 81,
    keyNutrients: ["Protein", "Fiber", "Vitamin K", "Folate", "Thiamine"],
    pluCodes: ["3086", "4086"],
  },

  // ── SEA VEGETABLES ───────────────────────────────────────────────────────
  {
    id: "nori",
    name: "Nori (Seaweed)",
    imageUrl: "/manus-storage/nori_seaweed_faaf2988.png",
    emoji: "🌊",
    category: "Sea Vegetables",
    ewgStatus: "clean",
    conventionalScore: 88,
    organicScore: 95,
    tier: "elite",
    pesticidesFound: 1,
    pesticideRisk: "very-low",
    nutritionHighlights: ["Iodine", "DHA/EPA", "Vitamin B12", "Minerals", "Fucoxanthin"],
    concerns: ["Very low pesticide risk", "Can be high in heavy metals if from polluted waters — buy from Japan/Korea"],
    buyTip: "Buy from reputable Japanese or Korean brands. Avoid cheap generic brands from unknown sources.",
    benefits: ["Rare plant source of Vitamin B12", "Iodine for thyroid health", "Fucoxanthin burns fat", "Omega-3 fatty acids"],
    servingIdea: "Wrap sushi, use as a chip alternative, or crumble over rice bowls",
    calories100g: 35,
    keyNutrients: ["Iodine", "Vitamin B12", "DHA", "Iron", "Fucoxanthin"],
    pluCodes: ["3316", "4316"],
  },
  {
    id: "kelp",
    name: "Kelp",
    imageUrl: "/manus-storage/kelp_9d3b74cf.jpg",
    emoji: "🌊",
    category: "Sea Vegetables",
    ewgStatus: "clean",
    conventionalScore: 82,
    organicScore: 93,
    tier: "excellent",
    pesticidesFound: 1,
    pesticideRisk: "very-low",
    nutritionHighlights: ["Iodine", "Fucoidan", "Calcium", "Magnesium", "Vanadium"],
    concerns: ["Can be very high in iodine — excess can harm thyroid", "Heavy metal risk from polluted waters"],
    buyTip: "Use in small amounts. Buy from certified clean-water sources.",
    benefits: ["Fucoidan is anti-cancer and antiviral", "Iodine supports thyroid function", "Alkalizing minerals"],
    servingIdea: "Add dried kelp to soups and broths for umami and minerals",
    calories100g: 43,
    keyNutrients: ["Iodine", "Fucoidan", "Calcium", "Magnesium"],
    pluCodes: ["3316", "4316"],
  },
];

// ── Stats ─────────────────────────────────────────────────────────────────
export const VEG_DB_STATS = {
  total: ALL_VEGETABLES.length,
  categories: VEG_CATEGORIES.length,
  dirtyDozen: ALL_VEGETABLES.filter(v => v.ewgStatus === "dirty-dozen").length,
  cleanFifteen: ALL_VEGETABLES.filter(v => v.ewgStatus === "clean-fifteen").length,
};

export function getVegColor(tier: VegetableQualityTier): string {
  return VEG_QUALITY_TIER_CONFIG[tier].color;
}

export function getVegDisplayScore(entry: VegetableEntry, organic: boolean): number {
  return organic ? entry.organicScore : entry.conventionalScore;
}
