/**
 * EatVera Water Database
 *
 * Comprehensive ratings for bottled waters, water filters, and tap water sources.
 * Each entry includes pH, TDS (Total Dissolved Solids), mineral content, contaminants,
 * and a 1–100 quality score based on purity, mineral balance, and sourcing.
 */

export type WaterType = "bottled" | "filtered" | "tap" | "sparkling";

export interface WaterProduct {
  id: string;
  name: string;
  brand: string;
  type: WaterType;
  imageUrl?: string;
  category: string;
  qualityScore: number;
  scoreLabel: string;
  ph: number;
  tds: number; // Total Dissolved Solids (ppm)
  source: string;
  minerals: {
    calcium?: number;   // mg/L
    magnesium?: number; // mg/L
    sodium?: number;    // mg/L
    potassium?: number; // mg/L
    bicarbonate?: number; // mg/L
    silica?: number;    // mg/L
    fluoride?: number;  // mg/L
  };
  contaminants: string[];
  certifications: string[];
  healthNotes: string;
  averagePrice?: number;
  warnings: string[];
  plasticType?: string; // BPA-free, PET, glass, etc.
  country: string;
}

function score(s: number): string {
  if (s >= 85) return "Excellent";
  if (s >= 70) return "Good";
  if (s >= 50) return "Fair";
  return "Poor";
}

export const ALL_WATERS: WaterProduct[] = [
  // ─── PREMIUM BOTTLED WATERS ───────────────────────────────────────────────
  {
    id: "evian",
    name: "Evian Natural Spring Water",
    brand: "Evian",
    type: "bottled",
    imageUrl: "/manus-storage/water-evian-natural-spring-water-bottle_5fa6480c.jpg",
    category: "Natural Spring",
    qualityScore: 92,
    scoreLabel: score(92),
    ph: 7.2,
    tds: 309,
    source: "French Alps glacial springs, Évian-les-Bains",
    minerals: { calcium: 80, magnesium: 26, sodium: 5, potassium: 1, bicarbonate: 360, silica: 15 },
    contaminants: [],
    certifications: ["NSF Certified", "ISO 22000"],
    healthNotes: "Well-balanced mineral profile with naturally occurring electrolytes. High bicarbonate supports alkalinity. One of the most studied natural spring waters globally.",
    warnings: [],
    plasticType: "BPA-free PET",
    country: "France",
  },
  {
    id: "fiji",
    name: "FIJI Natural Artesian Water",
    brand: "FIJI Water",
    type: "bottled",
    imageUrl: "/manus-storage/water-fiji_76ab2bf5.jpg",
    category: "Artesian",
    qualityScore: 90,
    scoreLabel: score(90),
    ph: 7.7,
    tds: 222,
    source: "Artesian aquifer, Viti Levu island, Fiji",
    minerals: { calcium: 18, magnesium: 15, sodium: 18, potassium: 5, bicarbonate: 140, silica: 93 },
    contaminants: [],
    certifications: ["NSF Certified"],
    healthNotes: "Exceptionally high silica content (93 mg/L) supports skin, hair, and nail health. Naturally filtered through volcanic rock. Slightly alkaline pH.",
    warnings: [],
    plasticType: "BPA-free PET",
    country: "Fiji",
  },
  {
    id: "volvic",
    name: "Volvic Natural Spring Water",
    brand: "Volvic",
    type: "bottled",
    imageUrl: "/manus-storage/water-volvic-natural-spring-water-bottle_4d2ccb17.jpg",
    category: "Natural Spring",
    qualityScore: 88,
    scoreLabel: score(88),
    ph: 7.0,
    tds: 130,
    source: "Auvergne volcanic region, France",
    minerals: { calcium: 12, magnesium: 8, sodium: 12, potassium: 6, bicarbonate: 74, silica: 32 },
    contaminants: [],
    certifications: ["ISO 22000"],
    healthNotes: "Low mineral content makes it ideal for daily hydration and infant formula. Filtered through layers of volcanic rock over years. Neutral pH.",
    warnings: [],
    plasticType: "BPA-free PET",
    country: "France",
  },
  {
    id: "san-pellegrino",
    name: "S.Pellegrino Sparkling Natural Mineral Water",
    brand: "San Pellegrino",
    type: "sparkling",
    imageUrl: "/manus-storage/water-s-pellegrino-sparkling-natural-mineral-water-bottl_11cca7b9.jpg",
    category: "Sparkling Mineral",
    qualityScore: 87,
    scoreLabel: score(87),
    ph: 5.6,
    tds: 1109,
    source: "San Pellegrino Terme, Lombardy, Italy",
    minerals: { calcium: 174, magnesium: 54, sodium: 36, potassium: 3, bicarbonate: 243, silica: 7 },
    contaminants: [],
    certifications: ["ISO 22000"],
    healthNotes: "High mineral content, particularly calcium and magnesium. CO₂ added after source. Lower pH due to carbonation. Rich, complex mineral taste.",
    warnings: ["Lower pH (5.6) may affect tooth enamel with excessive consumption"],
    plasticType: "Glass bottle available",
    country: "Italy",
  },
  {
    id: "perrier",
    name: "Perrier Sparkling Natural Mineral Water",
    brand: "Perrier",
    type: "sparkling",
    imageUrl: "/manus-storage/water-perrier-sparkling-natural-mineral-water-bottle_a04b16f5.jpg",
    category: "Sparkling Mineral",
    qualityScore: 84,
    scoreLabel: score(84),
    ph: 5.5,
    tds: 475,
    source: "Vergèze spring, Gard, France",
    minerals: { calcium: 147, magnesium: 3, sodium: 9, potassium: 1, bicarbonate: 390 },
    contaminants: [],
    certifications: ["ISO 22000"],
    healthNotes: "Naturally carbonated at source. High calcium content. Low magnesium. The CO₂ is captured, purified, and re-added.",
    warnings: ["Lower pH (5.5) due to carbonation — limit if you have acid reflux"],
    plasticType: "Glass bottle available",
    country: "France",
  },
  {
    id: "smartwater",
    name: "smartwater Vapor Distilled Water",
    brand: "smartwater (Coca-Cola)",
    type: "bottled",
    imageUrl: "/manus-storage/water-smartwater-vapor-distilled-water-bottle_bc32963c.jpg",
    category: "Vapor Distilled",
    qualityScore: 72,
    scoreLabel: score(72),
    ph: 7.0,
    tds: 20,
    source: "Municipal water, vapor distilled and electrolytes added",
    minerals: { calcium: 0, magnesium: 0, sodium: 10, potassium: 0 },
    contaminants: [],
    certifications: ["NSF Certified"],
    healthNotes: "Purified via vapor distillation then electrolytes (calcium chloride, magnesium chloride, potassium bicarbonate) added back. Very low TDS. Owned by Coca-Cola.",
    warnings: ["Owned by Coca-Cola — corporate water brand", "Minimal natural minerals"],
    plasticType: "BPA-free PET",
    country: "USA",
  },
  {
    id: "voss",
    name: "VOSS Artesian Still Water",
    brand: "VOSS",
    type: "bottled",
    imageUrl: "/manus-storage/water-voss-artesian-still-water-bottle_f386512b.jpg",
    category: "Artesian",
    qualityScore: 89,
    scoreLabel: score(89),
    ph: 6.0,
    tds: 44,
    source: "Artesian aquifer, Iveland, Norway",
    minerals: { calcium: 5, magnesium: 1, sodium: 6, potassium: 0, bicarbonate: 13, silica: 16 },
    contaminants: [],
    certifications: ["NSF Certified"],
    healthNotes: "Exceptionally low TDS (44 ppm) — one of the purest natural waters. Filtered through ancient rock for hundreds of years. Slightly acidic pH.",
    warnings: [],
    plasticType: "Glass bottle available",
    country: "Norway",
  },
  {
    id: "gerolsteiner",
    name: "Gerolsteiner Sparkling Mineral Water",
    brand: "Gerolsteiner",
    type: "sparkling",
    imageUrl: "/manus-storage/water-gerolsteiner-sparkling-mineral-water-bottle_13bce364.jpg",
    category: "Sparkling Mineral",
    qualityScore: 91,
    scoreLabel: score(91),
    ph: 5.9,
    tds: 2527,
    source: "Volcanic Eifel region, Germany",
    minerals: { calcium: 348, magnesium: 108, sodium: 118, potassium: 11, bicarbonate: 1816 },
    contaminants: [],
    certifications: ["DIN EN ISO 22000"],
    healthNotes: "One of the highest mineral content waters available. Exceptional calcium (348 mg/L) and magnesium (108 mg/L) — supports bone health and muscle function. Naturally carbonated.",
    warnings: ["High sodium (118 mg/L) — those on low-sodium diets should limit intake"],
    plasticType: "Glass bottle available",
    country: "Germany",
  },
  {
    id: "acqua-panna",
    name: "Acqua Panna Natural Spring Water",
    brand: "Acqua Panna",
    type: "bottled",
    imageUrl: "/manus-storage/water-acqua-panna-natural-spring-water-bottle_a6fc6fb6.jpg",
    category: "Natural Spring",
    qualityScore: 88,
    scoreLabel: score(88),
    ph: 8.0,
    tds: 199,
    source: "Tuscan hills, Scarperia, Italy",
    minerals: { calcium: 32, magnesium: 7, sodium: 7, potassium: 1, bicarbonate: 109, silica: 7 },
    contaminants: [],
    certifications: ["ISO 22000"],
    healthNotes: "Naturally alkaline (pH 8.0) with a smooth, soft taste. Filtered through Tuscan sandstone. Balanced mineral profile. Owned by Nestlé.",
    warnings: [],
    plasticType: "Glass bottle available",
    country: "Italy",
  },
  {
    id: "mountain-valley",
    name: "Mountain Valley Spring Water",
    brand: "Mountain Valley",
    type: "bottled",
    imageUrl: "/manus-storage/water-mountain-valley-spring-water-glass-bottle_06f71764.jpg",
    category: "Natural Spring",
    qualityScore: 93,
    scoreLabel: score(93),
    ph: 7.8,
    tds: 220,
    source: "Ouachita Mountains, Hot Springs, Arkansas",
    minerals: { calcium: 68, magnesium: 7, sodium: 3, potassium: 1, bicarbonate: 210, silica: 14 },
    contaminants: [],
    certifications: ["NSF Certified", "Certified B Corp"],
    healthNotes: "Naturally alkaline spring water in glass bottles. Consistently high quality since 1871. Low sodium, good calcium. Preferred by many health professionals.",
    warnings: [],
    plasticType: "Glass bottle",
    country: "USA",
  },
  {
    id: "icelandic-glacial",
    name: "Icelandic Glacial Natural Spring Water",
    brand: "Icelandic Glacial",
    type: "bottled",
    imageUrl: "/manus-storage/water-icelandic-glacial-natural-spring-water-bottle_568dbf2a.jpg",
    category: "Natural Spring",
    qualityScore: 91,
    scoreLabel: score(91),
    ph: 8.4,
    tds: 62,
    source: "Ölfus Spring, Iceland (4,500-year-old lava rock aquifer)",
    minerals: { calcium: 6, magnesium: 1, sodium: 7, potassium: 1, bicarbonate: 40, silica: 15 },
    contaminants: [],
    certifications: ["CarbonNeutral Certified", "NSF Certified"],
    healthNotes: "Highly alkaline (pH 8.4) with very low TDS. Filtered through ancient lava rock. Carbon neutral certified. Excellent for those seeking alkaline water.",
    warnings: [],
    plasticType: "BPA-free PET",
    country: "Iceland",
  },
  {
    id: "waiakea",
    name: "Waiakea Hawaiian Volcanic Water",
    brand: "Waiakea",
    type: "bottled",
    imageUrl: "/manus-storage/water-waiakea_22937ce8.png",
    category: "Volcanic Spring",
    qualityScore: 90,
    scoreLabel: score(90),
    ph: 8.2,
    tds: 120,
    source: "Mauna Loa volcano, Big Island, Hawaii",
    minerals: { calcium: 14, magnesium: 9, sodium: 11, potassium: 2, bicarbonate: 90, silica: 36 },
    contaminants: [],
    certifications: ["CarbonNeutral Certified", "NSF Certified"],
    healthNotes: "Naturally alkaline water filtered through 14,000 feet of porous volcanic rock. High silica content. Sustainably sourced from rainwater and snowmelt.",
    warnings: [],
    plasticType: "BPA-free PET",
    country: "USA",
  },
  {
    id: "deer-park",
    name: "Deer Park Natural Spring Water",
    brand: "Deer Park (Nestlé)",
    type: "bottled",
    imageUrl: "/manus-storage/water-deer-park-natural-spring-water-bottle_f6acf581.jpg",
    category: "Natural Spring",
    qualityScore: 65,
    scoreLabel: score(65),
    ph: 6.8,
    tds: 60,
    source: "Various springs in the Eastern US",
    minerals: { calcium: 10, magnesium: 3, sodium: 3, potassium: 0 },
    contaminants: [],
    certifications: ["NSF Certified"],
    healthNotes: "Budget-friendly spring water. Owned by Nestlé (now BlueTriton Brands). Moderate quality with low mineral content. Consistent but unremarkable.",
    warnings: ["Owned by large corporation — sustainability concerns"],
    plasticType: "BPA-free PET",
    country: "USA",
  },
  {
    id: "dasani",
    name: "Dasani Purified Water",
    brand: "Dasani (Coca-Cola)",
    type: "bottled",
    imageUrl: "/manus-storage/water-dasani-purified-water-bottle_23cd1aa9.jpg",
    category: "Purified",
    qualityScore: 55,
    scoreLabel: score(55),
    ph: 5.6,
    tds: 30,
    source: "Municipal tap water, purified via reverse osmosis",
    minerals: { magnesium: 0, sodium: 10, potassium: 0 },
    contaminants: [],
    certifications: ["NSF Certified"],
    healthNotes: "Purified municipal water with added magnesium sulfate, potassium chloride, and salt. Slightly acidic. Owned by Coca-Cola. Essentially treated tap water in a bottle.",
    warnings: ["Acidic pH (5.6)", "Owned by Coca-Cola", "Added salt (sodium chloride)"],
    plasticType: "BPA-free PET",
    country: "USA",
  },
  {
    id: "aquafina",
    name: "Aquafina Purified Drinking Water",
    brand: "Aquafina (PepsiCo)",
    type: "bottled",
    imageUrl: "/manus-storage/water-aquafina-purified-drinking-water-bottle_5449489f.jpg",
    category: "Purified",
    qualityScore: 52,
    scoreLabel: score(52),
    ph: 6.0,
    tds: 10,
    source: "Municipal tap water, 7-step HydRO-7 purification",
    minerals: {},
    contaminants: [],
    certifications: ["NSF Certified"],
    healthNotes: "Highly purified municipal water. Very low TDS (10 ppm) — essentially stripped of all minerals. Owned by PepsiCo. No added minerals.",
    warnings: ["Owned by PepsiCo", "No minerals — not ideal as primary hydration source", "Very low TDS may leach minerals from body over time"],
    plasticType: "BPA-free PET",
    country: "USA",
  },
  {
    id: "poland-spring",
    name: "Poland Spring Natural Spring Water",
    brand: "Poland Spring (BlueTriton)",
    type: "bottled",
    imageUrl: "/manus-storage/water-poland-spring-natural-spring-water-bottle_d0fcbd9d.jpg",
    category: "Natural Spring",
    qualityScore: 63,
    scoreLabel: score(63),
    ph: 6.8,
    tds: 70,
    source: "Multiple springs in Maine, USA",
    minerals: { calcium: 7, magnesium: 1, sodium: 3, potassium: 0 },
    contaminants: [],
    certifications: ["NSF Certified"],
    healthNotes: "Classic American spring water. Owned by BlueTriton (formerly Nestlé). Faced legal challenges over 'spring water' labeling. Low mineral content.",
    warnings: ["Past labeling controversy regarding spring source authenticity"],
    plasticType: "BPA-free PET",
    country: "USA",
  },
  {
    id: "core-water",
    name: "CORE Hydration Nutrient Enhanced Water",
    brand: "CORE",
    type: "bottled",
    imageUrl: "/manus-storage/water-core-hydration-nutrient-enhanced-water-bottle_aa7c6daa.jpg",
    category: "Enhanced",
    qualityScore: 74,
    scoreLabel: score(74),
    ph: 7.4,
    tds: 25,
    source: "Purified water with added electrolytes",
    minerals: { calcium: 0, magnesium: 0, sodium: 10, potassium: 0 },
    contaminants: [],
    certifications: ["NSF Certified"],
    healthNotes: "pH-balanced at 7.4 (matching the body's natural pH). Purified via reverse osmosis with electrolytes added. Clean taste, good for hydration.",
    warnings: [],
    plasticType: "BPA-free PET",
    country: "USA",
  },

  // ─── WATER FILTERS ────────────────────────────────────────────────────────
  {
    id: "brita-longlast",
    name: "Brita Longlast+ Filter",
    brand: "Brita",
    type: "filtered",
    imageUrl: "/manus-storage/water-brita-longlast-water-filter-pitcher_94925c19.webp",
    category: "Pitcher Filter",
    qualityScore: 75,
    scoreLabel: score(75),
    ph: 7.0,
    tds: 150,
    source: "Tap water filtered through activated carbon + ion exchange",
    minerals: { calcium: 30, magnesium: 10, sodium: 5 },
    contaminants: ["Lead (99% reduction)", "Chlorine (99% reduction)", "Asbestos", "Benzene", "Cadmium"],
    certifications: ["NSF/ANSI 53", "NSF/ANSI 42"],
    healthNotes: "Reduces lead, chlorine, and many contaminants. Does not remove fluoride or TDS significantly. Convenient and affordable. Filter lasts ~120 gallons.",
    warnings: ["Does not remove fluoride", "Does not remove nitrates", "Filter must be replaced regularly"],
    country: "USA",
  },
  {
    id: "zerowater",
    name: "ZeroWater 5-Stage Filter",
    brand: "ZeroWater",
    type: "filtered",
    imageUrl: "/manus-storage/water-zerowater-5-stage-water-filter-pitcher_ee4179c3.jpg",
    category: "Pitcher Filter",
    qualityScore: 80,
    scoreLabel: score(80),
    ph: 6.5,
    tds: 0,
    source: "Tap water through 5-stage ion exchange + activated carbon",
    minerals: {},
    contaminants: ["Lead (99.9% reduction)", "Chromium", "Chlorine", "Fluoride (partial)", "PFAS (partial)", "Mercury"],
    certifications: ["NSF/ANSI 53", "NSF/ANSI 42", "NSF/ANSI 58"],
    healthNotes: "Removes virtually all dissolved solids (TDS = 0). Includes a TDS meter. Removes more contaminants than Brita. However, zero minerals may not be ideal for daily use.",
    warnings: ["TDS of 0 means no beneficial minerals", "Slightly acidic pH (6.5)", "Filters need frequent replacement with high-TDS tap water"],
    country: "USA",
  },
  {
    id: "berkey",
    name: "Big Berkey Gravity Filter",
    brand: "Berkey",
    type: "filtered",
    imageUrl: "/manus-storage/water-big-berkey-gravity-water-filter_882373e2.jpg",
    category: "Gravity Filter",
    qualityScore: 88,
    scoreLabel: score(88),
    ph: 7.2,
    tds: 80,
    source: "Tap water through Black Berkey purification elements",
    minerals: { calcium: 20, magnesium: 8, sodium: 3 },
    contaminants: ["Lead (99.9%)", "Chlorine (99.9%)", "Fluoride (95% with PF-2 filters)", "Bacteria (99.9999%)", "Viruses (99.999%)", "PFAS", "Pharmaceuticals", "Heavy metals"],
    certifications: ["EPA-approved testing labs"],
    healthNotes: "One of the most comprehensive gravity filters available. Removes bacteria, viruses, and most contaminants while retaining beneficial minerals. Excellent for emergency preparedness.",
    warnings: ["Not NSF certified (tests done by EPA-approved labs)", "Fluoride removal requires additional PF-2 filters"],
    country: "USA",
  },
  {
    id: "alexapure-pro",
    name: "Alexapure Pro Gravity Filter",
    brand: "Alexapure",
    type: "filtered",
    imageUrl: "/manus-storage/water-alexapure_386ecb1a.jpg",
    category: "Gravity Filter",
    qualityScore: 86,
    scoreLabel: score(86),
    ph: 7.1,
    tds: 90,
    source: "Tap water through hybrid ceramic/carbon filter",
    minerals: { calcium: 18, magnesium: 7, sodium: 4 },
    contaminants: ["Lead (99.9%)", "Chlorine (99.9%)", "Bacteria (99.9999%)", "Viruses (99.999%)", "Fluoride (partial)", "Arsenic", "Heavy metals"],
    certifications: ["NSF/ANSI 42"],
    healthNotes: "Gravity-fed filter with high contaminant removal. Retains beneficial minerals. Good alternative to Berkey at a lower price point.",
    warnings: ["Partial fluoride removal only"],
    country: "USA",
  },
  {
    id: "aquasana-whole-house",
    name: "Aquasana Whole House Filter",
    brand: "Aquasana",
    type: "filtered",
    imageUrl: "/manus-storage/water-aquasana-whole-house-water-filter-system_83267e6c.jpg",
    category: "Whole House",
    qualityScore: 87,
    scoreLabel: score(87),
    ph: 7.2,
    tds: 120,
    source: "Municipal water through multi-stage carbon + KDF filter",
    minerals: { calcium: 25, magnesium: 10, sodium: 5 },
    contaminants: ["Chlorine (97%)", "Chloramines (97%)", "Lead (99%)", "PFAS", "Herbicides", "Pesticides"],
    certifications: ["NSF/ANSI 42", "NSF/ANSI 53"],
    healthNotes: "Filters water at the point of entry for the entire home. Protects appliances and skin during showering. Does not remove fluoride or TDS significantly.",
    warnings: ["Does not remove fluoride", "Requires professional installation"],
    country: "USA",
  },
  {
    id: "ro-reverse-osmosis",
    name: "APEC Top Tier Reverse Osmosis System",
    brand: "APEC Water Systems",
    type: "filtered",
    imageUrl: "/manus-storage/water-apec-top-tier-reverse-osmosis-water-system_8bf5543b.jpg",
    category: "Reverse Osmosis",
    qualityScore: 85,
    scoreLabel: score(85),
    ph: 6.5,
    tds: 5,
    source: "Tap water through 5-stage RO membrane",
    minerals: {},
    contaminants: ["Fluoride (95%)", "Lead (99%)", "Arsenic (99%)", "Chlorine (99%)", "Bacteria", "Nitrates", "PFAS", "Pharmaceuticals"],
    certifications: ["NSF/ANSI 58", "WQA Gold Seal"],
    healthNotes: "Removes up to 99% of all contaminants including fluoride and nitrates. Very low TDS. Consider adding a remineralization filter to restore beneficial minerals.",
    warnings: ["Removes all minerals — add remineralization stage for optimal health", "Slightly acidic pH", "Wastes 3–4 gallons per gallon filtered"],
    country: "USA",
  },
  {
    id: "clearly-filtered",
    name: "Clearly Filtered Water Pitcher",
    brand: "Clearly Filtered",
    type: "filtered",
    imageUrl: "/manus-storage/water-clearly-filtered-water-pitcher_b25ab86d.png",
    category: "Pitcher Filter",
    qualityScore: 83,
    scoreLabel: score(83),
    ph: 7.0,
    tds: 100,
    source: "Tap water through Affinity Filtration Technology",
    minerals: { calcium: 20, magnesium: 8, sodium: 4 },
    contaminants: ["Fluoride (99.5%)", "Lead (99.5%)", "PFAS (99.9%)", "Chlorine (99.5%)", "Chromium-6", "Pharmaceuticals", "Herbicides"],
    certifications: ["NSF/ANSI 42", "NSF/ANSI 53", "NSF/ANSI 244", "NSF/ANSI 401"],
    healthNotes: "One of the best pitcher filters for fluoride removal. Removes 365+ contaminants. Retains beneficial minerals. More expensive than Brita but significantly more effective.",
    warnings: ["Higher cost per filter than standard pitchers"],
    country: "USA",
  },

  // ─── TAP WATER (CITY RATINGS) ─────────────────────────────────────────────
  {
    id: "tap-nyc",
    name: "New York City Tap Water",
    brand: "NYC DEP",
    type: "tap",
    imageUrl: "/manus-storage/water-new-york-city-tap-pure-natural-water_bbc5ddca.png",
    category: "Municipal Tap",
    qualityScore: 78,
    scoreLabel: score(78),
    ph: 7.2,
    tds: 50,
    source: "Catskill/Delaware and Croton watersheds",
    minerals: { calcium: 10, magnesium: 2, sodium: 8, potassium: 1 },
    contaminants: ["Chlorine (added for disinfection)", "Chloramines", "Trace lead (from old pipes)", "PFAS (trace)"],
    certifications: ["EPA Safe Drinking Water Act compliant"],
    healthNotes: "Widely regarded as some of the best tap water in the US. Unfiltered surface water from protected upstate reservoirs. Soft water with low mineral content. Fluoride added (0.7 mg/L).",
    warnings: ["Fluoride added", "Old building pipes may leach lead — filter recommended in pre-1986 buildings"],
    country: "USA",
  },
  {
    id: "tap-sf",
    name: "San Francisco Tap Water",
    brand: "SFPUC",
    type: "tap",
    imageUrl: "/manus-storage/water-better-home-products-san-francisco-kitchen-faucet_f0e3dec3.jpg",
    category: "Municipal Tap",
    qualityScore: 80,
    scoreLabel: score(80),
    ph: 8.0,
    tds: 55,
    source: "Hetch Hetchy Reservoir, Yosemite National Park",
    minerals: { calcium: 8, magnesium: 2, sodium: 10, potassium: 1 },
    contaminants: ["Chloramine (added)", "Trace PFAS"],
    certifications: ["EPA Safe Drinking Water Act compliant"],
    healthNotes: "High-quality tap water sourced from protected Yosemite watershed. Slightly alkaline. Very low TDS. Chloramines used instead of chlorine — filtered water recommended.",
    warnings: ["Chloramines added — harder to remove than chlorine (requires catalytic carbon filter)", "Fluoride added"],
    country: "USA",
  },
  {
    id: "tap-chicago",
    name: "Chicago Tap Water",
    brand: "Chicago DWM",
    type: "tap",
    imageUrl: "/manus-storage/water-chicago-tap-water-faucet_83b5de10.jpg",
    category: "Municipal Tap",
    qualityScore: 68,
    scoreLabel: score(68),
    ph: 7.6,
    tds: 170,
    source: "Lake Michigan",
    minerals: { calcium: 40, magnesium: 12, sodium: 8, potassium: 2 },
    contaminants: ["Chlorine", "Lead (from service lines)", "Chromium-6 (trace)", "PFAS (trace)"],
    certifications: ["EPA Safe Drinking Water Act compliant"],
    healthNotes: "Lake Michigan is a clean source but Chicago has aging lead service lines. Higher TDS than coastal cities. Good mineral content. Filtering strongly recommended.",
    warnings: ["Lead service lines — filter strongly recommended", "Fluoride added", "Chromium-6 detected at trace levels"],
    country: "USA",
  },
  {
    id: "tap-houston",
    name: "Houston Tap Water",
    brand: "Houston Water",
    type: "tap",
    imageUrl: "/manus-storage/water-juno-showers-houston-classic-bathroom-faucet_d5bb640f.jpg",
    category: "Municipal Tap",
    qualityScore: 58,
    scoreLabel: score(58),
    ph: 8.2,
    tds: 300,
    source: "Lake Houston, Lake Conroe, Lake Livingston",
    minerals: { calcium: 55, magnesium: 18, sodium: 40, potassium: 4 },
    contaminants: ["Chloramine", "Trihalomethanes (THMs)", "Haloacetic acids", "PFAS", "Arsenic (trace)"],
    certifications: ["EPA Safe Drinking Water Act compliant"],
    healthNotes: "Higher TDS and mineral content due to Texas geology. Disinfection byproducts (THMs) detected above EWG health guidelines. Filtering strongly recommended.",
    warnings: ["High THMs and haloacetic acids", "PFAS detected", "Fluoride added", "Higher sodium content"],
    country: "USA",
  },
  {
    id: "tap-los-angeles",
    name: "Los Angeles Tap Water",
    brand: "LADWP",
    type: "tap",
    imageUrl: "/manus-storage/water-los-angeles-tap-water-faucet_ddf04d98.jpg",
    category: "Municipal Tap",
    qualityScore: 62,
    scoreLabel: score(62),
    ph: 8.0,
    tds: 400,
    source: "Colorado River, Northern California via aqueducts, local groundwater",
    minerals: { calcium: 60, magnesium: 20, sodium: 60, potassium: 5 },
    contaminants: ["Chloramine", "Chromium-6", "Arsenic (trace)", "Perchlorate", "PFAS (trace)", "Trihalomethanes"],
    certifications: ["EPA Safe Drinking Water Act compliant"],
    healthNotes: "Hard water with high TDS from multiple sources. Chromium-6 detected above EWG health guidelines. Filtering recommended. Tastes noticeably different from bottled water.",
    warnings: ["Chromium-6 detected", "High TDS — hard water", "Fluoride added", "Multiple contaminants above EWG health guidelines"],
    country: "USA",
  },
  {
    id: "tap-london",
    name: "London Tap Water",
    brand: "Thames Water",
    type: "tap",
    imageUrl: "/manus-storage/water-london-sunshine-1440-swivel-faucet-extender_573f00a4.jpg",
    category: "Municipal Tap",
    qualityScore: 72,
    scoreLabel: score(72),
    ph: 7.8,
    tds: 260,
    source: "River Thames and River Lee reservoirs",
    minerals: { calcium: 70, magnesium: 5, sodium: 20, potassium: 4 },
    contaminants: ["Chlorine", "Trace pharmaceuticals", "Microplastics (trace)"],
    certifications: ["UK Drinking Water Regulations compliant"],
    healthNotes: "Hard water with high calcium content. Meets all UK safety standards. Trace pharmaceuticals detected but at very low levels. Limescale buildup common in appliances.",
    warnings: ["Very hard water — limescale buildup", "Trace pharmaceuticals detected", "Fluoride not added (unlike US)"],
    country: "UK",
  },
  {
    id: "tap-tokyo",
    name: "Tokyo Tap Water",
    brand: "Tokyo Waterworks",
    type: "tap",
    imageUrl: "/manus-storage/water-tokyo-tap_52c70ca7.jpg",
    category: "Municipal Tap",
    qualityScore: 85,
    scoreLabel: score(85),
    ph: 7.5,
    tds: 60,
    source: "Tama River and Tone River watersheds",
    minerals: { calcium: 15, magnesium: 3, sodium: 8, potassium: 1 },
    contaminants: ["Chlorine (minimal)"],
    certifications: ["WHO Guidelines compliant", "Japan Water Quality Standards"],
    healthNotes: "Among the highest quality tap water in the world. Very low TDS, soft water, minimal chlorine. Tokyo invests heavily in water treatment. Safe to drink directly from tap.",
    warnings: [],
    country: "Japan",
  },
];

// ─── HELPER FUNCTIONS ─────────────────────────────────────────────────────────

export const ALL_BOTTLED = ALL_WATERS.filter(w => w.type === "bottled");
export const ALL_SPARKLING = ALL_WATERS.filter(w => w.type === "sparkling");
export const ALL_FILTERED = ALL_WATERS.filter(w => w.type === "filtered");
export const ALL_TAP = ALL_WATERS.filter(w => w.type === "tap");

export function searchWater(query: string): WaterProduct[] {
  const q = query.toLowerCase();
  return ALL_WATERS.filter(
    w =>
      w.name.toLowerCase().includes(q) ||
      w.brand.toLowerCase().includes(q) ||
      w.source.toLowerCase().includes(q) ||
      w.category.toLowerCase().includes(q) ||
      w.country.toLowerCase().includes(q)
  );
}

export function filterByWaterType(type: WaterType | null): WaterProduct[] {
  if (!type) return ALL_WATERS;
  return ALL_WATERS.filter(w => w.type === type);
}

export function getScoreColor(score: number): string {
  if (score >= 85) return "#0B3D2E";
  if (score >= 70) return "#eab308";
  if (score >= 50) return "#f97316";
  return "#dc2626";
}
